### PR TITLE
VACMS-6604: Add css for action links in editor/proofing.

### PR DESCRIPTION
**Pull request by msbtterswrth**
## Description

Closes to #6604

## Testing done
Edited a page to add an action link class, viewed new styles in editor and node view. 

## Screenshots
image

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As a cms editor; 
1. Edit a page (`node/33339/edit`)
2. Then change the class on register button to use an action link class
   - [x] Validate that the css for action links loads in node view (`/centralized-content/vamc-system-register-for-care-page-content`)
3. Then validate Acceptance Criteria from issue
   - [x] On a selected link in the ckeditor can select "Primary action link" and have it assign class="vads-c-action-link--green"
   - [x] On a selected link in the ckeditor can select "Secondary action link" and have it assign class="vads-c-action-link--blue"
   - [x] CSS in ckeditor makes them look like https://design.va.gov/experimental-design/action_links
   - [x] CSS on page makes node view (proofing) look like https://design.va.gov/experimental-design/action_links
   - [x] must allow for adding hreflang and lang properties in the source mode and not eat them on save or re-edit.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by swirtSJW — CHANGES_REQUESTED** [review]
This is not satisfying the ACs or passing QA steps
image
Then validate Acceptance Criteria from issue
 - [ ] On a selected link in the ckeditor can select "Primary action link" and have it assign class="vads-c-action-link--green"
 - [ ] On a selected link in the ckeditor can select "Secondary action link" and have it assign class="vads-c-action-link--blue"

**Comment by msbtterswrth** [comment]
@swirtSJW good catch, we had originally included the config in the earlier PR, so this one assumed it would already be present. I have added it back in.

**Review by swirtSJW — APPROVED** [review]
Nice work @msbtterswrth 
QA pass 
Works on page
image

Shows in editor
image


Supports hreflang and lang 
image

image

**Comment by swirtSJW** [comment]
I just noticed these ACs shifted with no record of the change or why.
image

The name change is subtle.   The original intent was so they would be clustered by type (when alpha sorted).  I am assuming the ACs were changed intentionally, and not just to fit the code, but I don't see any explanation.

**Pull request merged**
