### PR TITLE
Revert "VACMS-4923: Add limiting logic to service dropdowns."

### PR DESCRIPTION
**Pull request by swirtSJW**
Reverts department-of-veterans-affairs/va.gov-cms#5328

### CODE REVIEW

**Comment by swirtSJW** [comment]
Reverting this because editing a covid vaccine facility health service causes the service to get misapplied.

**Comment by ElijahLynn** [comment]
```
Running:  entity_reference_validation.feature                                             (2 of 6)


  Entity Reference Validation
    1) Duplicate Benefit Hub references should not be allowed

  0 passing (46s)

  1) Entity Reference Validation
       Duplicate Benefit Hub references should not be allowed:
     AssertionError: Timed out retrying after 10000ms: Expected to find content: '1 error has been found' but never did.
      at Context.eval (https://pr5363-wzzeapb2fhjgbyb7dsiyua0xtvokozhg.ci.cms.va.gov/__cypress/tests?p=cypress/integration/entity_reference_validation.feature:174838:28)
      at Context.resolveAndRunStepDefinition (https://pr5363-wzzeapb2fhjgbyb7dsiyua0xtvokozhg.ci.cms.va.gov/__cypress/tests?p=cypress/integration/entity_reference_validation.feature:23780:9)
      at Context.eval (https://pr5363-wzzeapb2fhjgbyb7dsiyua0xtvokozhg.ci.cms.va.gov/__cypress/tests?p=cypress/integration/entity_reference_validation.feature:23121:35)
```

**Comment by ElijahLynn** [comment]
>   Entity Reference Validation
>     1) Duplicate Benefit Hub references should not be allowed



>  Entity Reference Validation
>     1) Duplicate Benefit Hub references should not be allowed

@ndouglas re-created this on #5226 and we need to fix that first in a different PR.

**Comment by ElijahLynn** [comment]
Sure _ _ _ _, passed on a replay of tests!

**Review by ElijahLynn — APPROVED** [review]

**Pull request merged**
