### PR TITLE
VAGOV-5415: Reorder breadcrumb menus.

### PR DESCRIPTION
**Pull request by kevwalsh**
QA. 
Compare [menu breadcrumbs on the prod site](http://prod.cms.va.gov/admin/config/user-interface/menu-breadcrumb), which were configured on prod to the a menu breadcrumbs, to the same config page in the PR environment. They should be the same.

### CODE REVIEW

**Comment by kevwalsh** [comment]
@ethanteague do you mind reviewing this? 5 min QA. http://pr504.ci.cms.va.gov 
The deploy succeeded but devshop isn't talking to github right now.

**Comment by swirtSJW** [comment]
@kevwalsh @ethanteague  is the lack of consistent weights a show stopper?

**Comment by ethanteague** [comment]
> @kevwalsh @ethanteague is the lack of consistent weights a show stopper?

It's my understanding that breadcrumb weights are important, b/c it can result in the wrong breacdcrumb pattern being applied in some situations.

**Comment by swirtSJW** [comment]
@ethanteague  @kevwalsh They are important, but wondering if it is a question of them just being relative same relative order as the PR defines, or is the order of them wrong?

**Comment by ethanteague** [comment]
> @ethanteague @kevwalsh They are important, but wondering if it is a question of them just being relative same relative order as the PR defines, or is the order of them wrong?

I'll defer to @kevwalsh on this, but the ordering was totally different between environments, @swirtSJW

**Comment by kevwalsh** [comment]
Menu_Breadcrumb___Veterans_Affairs_and_Menu_Breadcrumb___Veterans_Affairs

Looks identical to me... 

i've rebased and pushed again.

**Comment by ethanteague** [comment]
> Menu_Breadcrumb___Veterans_Affairs_and_Menu_Breadcrumb___Veterans_Affairs
> 
> Looks identical to me...
> 
> i've rebased and pushed again.

Yep. Looks good, @kevwalsh

**Pull request merged**
