### PR TITLE
VACMS-8871: Re-roll patch to allow pathauto to update.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
closes #8871

## Testing done
`ddev composer install`

## QA steps
 - N/A - rerolls patch.

### CODE REVIEW

**Review by ndouglas — APPROVED** [review]

**Review by swirtSJW — APPROVED** [review]
nice work

**Comment by swirtSJW** [comment]
looks we got a conflict

**Comment by ethanteague** [comment]
> looks we got a conflict

Resolved, @swirtSJW :+1:

**Review by swirtSJW — APPROVED** [review]

**Comment by swirtSJW** [comment]
image

**Pull request merged**
