### PR TITLE
VACMS-6860: Update media view to include alt text.

### LINKED ISSUE #6860: Create audit tool for alt text on images
## User Story or Problem Statement

As an accessibility advocate for www.va.gov (member of CMS team, or Platform accessibility team, product owner, etc), i want a tool to review alt text in VA.gov CMS to identify and prioritize opportunities for improvement, training, automated tools, and other TBD actions in the name of ensuring accessible content at VA. 

See epic for more info. 

## Acceptance Criteria
- [ ] View display:  /admin/content/audit/media/alt-text 
   - [x] Child of core Media view?
- [x] Menu: Child of core admin/media view
- [ ] Fields
  - [x] image thumbnails (original aspect ratio, but reduced in size to small)
  - [x] What section they belong to
  - [ ] ~What product that section relates to~
  - [x] Which user uploaded them 
  - [x] Alt text 
  - [ ] Stretch: What content uses references it?
- [ ] Access: CMS editor
- [x] 50 pages at a time
- [x] Filters
  - [x] Section
  - [x] Title contains

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

### LINKED ISSUE #8103: media alt search
## User Story or Problem Statement

As a media manager I would like the ability to search for strings in alt so that I may easily find things like '.jpg'  for repairs.
image

## Acceptance Criteria
- [x] Media audit at admin/content/media/images  has text field  filter for searching alt.
- [x] Filter should be labelled "Alt contains" and appear between the "reuseable" and "alt text" filters

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by msbtterswrth**
## Description

Closes #8103
Closes #6860 .  Kev and I refined this in a slightly different way the the original ticket's ACs. I created a copy of the media view, filtered it by images and added the alt text field, filter and export. We may add additional functionality to this audit at a later date. 

## Testing done
Views the media page and saw the alt text appearing.

## Screenshots
image

## QA steps

As a cms editor, I can
1. view the new media images page (`admin/content/media/images`) 
2. Then validate Acceptance Criteria from issue
- [x] View Alt text in the report

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by swirtSJW — COMMENTED** [review]
Looks good overall.  
From the summary at the top of the PR I gather the AC's changed... but I don't know how they changed.  Ideally the AC's would be edited to reflect the change (maybe they have been?).

Here are differences I found but am not sure if they are intended it or not:
Access:  AC address role, this addresses perm.
image

Path:  I think this one makes sense for the changes described at the top of the PR
image

Product: not covered
image

**Comment by msbtterswrth** [comment]
@swirtSJW, ah the AC's didn't get updated but they're pretty close. I updated the perms just now to be 'CMS editors'. We decided to basically clone the existing media view (I was just going to add the alt text field into it, but there's more than just images in that) so the permissions should be the same with that. 

As for the AC about products I'm not sure we talked about that, nor do I think I've seen any other views have a similar field. How should I go about adding that?

**Comment by swirtSJW** [comment]
@msbtterswrth I think adding the product would be  done using a relationship to the section term as that is where product is set... but that is an entity reference to another vocabulary so it might need two relationships.   It is worth clarifying if that is the desired behavior or if it is still part  of the AC's.

**Review by swirtSJW — APPROVED** [review]
Looks great.  Well done.

image

**Comment by swirtSJW** [comment]
Rebased to re-trigger tests and hopefully unclogging cypress.

**Comment by swirtSJW** [comment]
Here's the spectool behat failure.
```
--- Missing views displays (present in specification, absent from Drupal)
      | Media - images        | Default     | default       | Default     |
      | Media - images        | Media       | media_images  | Page        |
      | Media - images export | Data export | images_export | Data export |
      +++ Unexpected views displays (present in Drupal, absent from specification)
      | Facility Services | Master                                     | default                                    | Default     |
      | Facility Services | VAMC facility health services              | vamc_facility_health_services_page         | Page        |
      | Facility Services | VAMC facility health services export       | vamc_facility_health_services_export       | Data export |
      | Facility Services | VAMC facility non-clinical services        | vamc_facility_non_clinical_services_page   | Page        |
      | Facility Services | VAMC facility non-clinical services export | vamc_facility_non_clinical_services_export | Data export |
      | Facility Services | Vet Center services                        | vet_center_services_page                   | Page        |
      | Facility Services | Vet Center services export                 | vet_center_services_export                 | Data export |
      | Media Images      | Data export                                | images_export                              | Data export |
      | Media Images      | Master                                     | default                                    | Default     |
      | Media Images      | Media                                      | media_images                               | Page        | 
```

I'll fix these.
Looks like some misaligment with D9.3 changes

**Review by swirtSJW — APPROVED** [review]

**Pull request merged**
