### PR TITLE
VACMS-5911: Add vamc custom module and op status ief banner auto governance

### LINKED ISSUE #5911: VAMC banner alerts created on IEF pages are always associated with Pittsburgh Health Care
**Describe the defect**

When a PAO creates a banner alert from within the Operating Status page, it gets associated with Pittsburgh Health Care section.

**To Reproduce**

As user 1625
1. Go node/2370/edit
2. Create a banner alert with IEF
3. Save.
4. Find the node from /admin/content 
5. See that it's assigned to Pittsburgh Health Care section via field_administration

**Expected behavior**

I should be asked what section to assign to OR it should just figure it out from the context i'm in. 

**ACs**

- [ ] Section (`field_administration`) is either filled (and hidden) or filled (and visible) to editors in th eIEF
- [ ] While we're in here: "add existing banner alert" option is removed.

Edit_VAMC_System_Operating_Status_Operating_status_-_VA_Wilmington_health_care___VA_gov_CMS

### PR DESCRIPTION
**Pull request by ethanteague**
## Description

Closes #5911

## Testing done
Visual / behat

## QA steps
1. Go node/2370/edit
2. Create a banner alert with IEF
3. Save.
4. Find the node from /admin/content
5. See that it's assigned to Wilmington section via field_administration

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by kevwalsh — CHANGES_REQUESTED** [review]
This worked as admin, but it didn't work when logged in as jacob.dillon@va.gov

First, after completing the IEF form, i saw 

Edit_VAMC_System_Operating_Status_Operating_status_-_VA_Wilmington_health_care___VA_gov_CMS

Then after saving i see this

Edit_VAMC_System_Operating_Status_Operating_status_-_VA_Wilmington_health_care___VA_gov_CMS

looks like field_office is not getting populated, and/or CER is not working during save.

**Comment by kevwalsh** [comment]
Edit_VAMC_System_Operating_Status_Operating_status_-_VA_Wilmington_health_care___VA_gov_CMS

Just noticed this too, missing Section field on  node/2370/edit

**Review by kevwalsh — APPROVED** [review]
QA Pass!

**Review by swirtSJW — COMMENTED** [review]
Admin passes ief creation
image

Adding an alert as a section editor (jacob.dillon@va.gov) throws some notices and encounters a form error
image

The error prevents form save.
image

**Review by swirtSJW — CHANGES_REQUESTED** [review]
See comments above for problems found.

**Comment by ethanteague** [comment]
> See comments above for problems found.

It works if you set it to published / issue that is going to be addressed in this task, @swirtSJW : 
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5942

See slack thread: https://dsva.slack.com/archives/CT4GZBM8F/p1626982580484300

**Review by swirtSJW — APPROVED** [review]

**Comment by swirtSJW** [comment]
image

**Pull request merged**
