### PR TITLE
VACMS-8495 Resolve failing file upload from office_hours logic.

### LINKED ISSUE #8495: File uploads not working.
## Describe the defect
image

Dropzone added a new permission, but even when that is set correctly, dropzone prevents adding files.   Drag and drop of file selection happens but then file disappears with no error or message... just vanishes.

The decision was made to no longer use dropzone.

## Implementations Steps

 - [x] uninstall dropzone on prod
 - [ ] pr for keeping dropzone disabled -> https://github.com/department-of-veterans-affairs/va.gov-cms/pull/8498
 - [ ] PR for removing dropzone from composer

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by swirtSJW**
## Description
Closes #8495

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As user _uid_ with _user_role_

As samuel.house2@va.gov , 

#### Test file upload
- Go to https://pr8503-3yr77xidr7cbiyrlqdpebgbcxqnrgkvr.ci.cms.va.gov/node/add/event
- [ ] validate that you can add an image using the select file button  and make sure the node saves with the file.
- [ ] validate that you repeat that step using drag and drop onto the dropzone to add a file.

#### Test field office hour editing 
- Go to https://pr8503-3yr77xidr7cbiyrlqdpebgbcxqnrgkvr.ci.cms.va.gov/node/42066/edit
- [x] validate you can edit the service hours in field_office_hours.
- [x] validate you don't see the tablefield version of the hours.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by ethanteague** [comment]
You saved the day, @swirtSJW

**Review by ndouglas — APPROVED** [review]
Changes make sense.

**Comment by JayDarnell** [comment]
Permission change is missing to allow Dropzone for authenticated users. QA will not pass without this change.

**Comment by swirtSJW** [comment]
Looking into the phpunit fail

**Comment by swirtSJW** [comment]
PHP unity failure was due to someone changing the perms on the PR environment while tests were still running.  Not due to an actual failure.   Going to merge.

**Pull request merged**
