### PR TITLE
VACMS-3563: Populates og:image:alt and twitter:image:alt.

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

See #3563. 

## Testing done
Manually checked to ensure meta tags are populated appropriately.

## Screenshots
Screen Shot 2021-01-11 at 8 41 56 AM
Screen Shot 2021-01-11 at 8 42 09 AM

## QA steps

As a user with permission to view published nodes:
1. View [a node with an image set](http://va-gov-cms.lndo.site/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/)
1. Then validate Acceptance Criteria from issue #3563:
    - [ ] A meta tag `og:image:alt` is set
    - [ ] A meta tag `twitter:image:alt` is set

### Definition of Done
- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by acrollet** [comment]
Confirmed that the new tags are shown on https://web-0mlv9jxztpi3whms3twzugiut42d5wpi.ci.cms.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/:

Screen Shot 2021-01-11 at 7 58 10 AM

**Review by acrollet — CHANGES_REQUESTED** [review]
The code looks good to me, I think it would make sense to have a test inspect at least the drupal output to ensure we don't have a regression.

**Comment by ndouglas** [comment]
Fair 'nuff.

**Comment by ndouglas** [comment]
Oops, Monday morning and I apparently wasn't yet fully awake.  Misunderstood the issue, need to approach it differently.

**Comment by ndouglas** [comment]
Screen Shot 2021-01-11 at 11 58 10 AM

No, this was still right, but [I guess this needs to be done in the frontend too](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/process-cms-exports/transformers/helpers.js).

**Review by acrollet — APPROVED** [review]
Approved pending tests. I like the test MO.

**Pull request merged**
