### PR TITLE
WIP: VAGOV-1729: Moving socials from facility to regional landing page.

### PR DESCRIPTION
**Pull request by ethanteague**

### CODE REVIEW

**Comment by andyhawks** [comment]
Merge after Sprint Demo on 3/13.

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-201<br><br> [button_visit-site](http://pr-201.va.agile6.com)

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-201<br><br> [button_visit-site](http://pr-201.va.agile6.com)

**Comment by andyhawks** [comment]
rebuild

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-201<br><br> [button_visit-site](http://pr-201.va.agile6.com)

**Comment by andyhawks** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/pull/203

**Pull request closed without merging**
