### PR TITLE
VACMS-11010: Assure Claro theme compatibility with Drupal 10.

### LINKED ISSUE #11010: Update `vagovclaro` theme for compatibility with Drupal 10.
## Description
```

--------------------------------------------------------------------------------
VA.gov Claro Admin Theme
Scanned on Fri, 09/30/2022 - 11:56 am.

10 warnings found.

vagovclaro.info.yml:
┌──────────┬──────┬─────────────────────────────────────────────────────────────┐
│  STATUS  │ LINE │                           MESSAGE                           │
├──────────┼──────┼─────────────────────────────────────────────────────────────┤
│ Check    │ 0    │ The 'tour/tour-styling' library is not defined because the  │
│ manually │      │ defining extension is not installed. Cannot decide if it is │
│          │      │ deprecated or not.                                          │
│          │      │                                                             │
│ Check    │ 0    │ The 'shortcut/drupal.shortcut' library is not defined       │
│ manually │      │ because the defining extension is not installed. Cannot     │
│          │      │ decide if it is deprecated or not.                          │
│          │      │                                                             │
└──────────┴──────┴─────────────────────────────────────────────────────────────┘

themes/custom/vagovclaro/templates/node/node--full.html.twig:
┌──────────┬──────┬─────────────────────────────────────────────────────────────┐
│  STATUS  │ LINE │                           MESSAGE                           │
├──────────┼──────┼─────────────────────────────────────────────────────────────┤
│ Check    │ 83   │ The 'classy/node' library is not defined because the        │
│ manually │      │ defining extension is not installed. Cannot decide if it is │
│          │      │ deprecated or not.                                          │
│          │      │                                                             │
└──────────┴──────┴─────────────────────────────────────────────────────────────┘

themes/custom/vagovclaro/templates/node/node--landing-page--support-services-lis
ting.html.twig:
┌──────────┬──────┬─────────────────────────────────────────────────────────────┐
│  STATUS  │ LINE │                           MESSAGE                           │
├──────────┼──────┼─────────────────────────────────────────────────────────────┤
│ Check    │ 83   │ The 'classy/node' library is not defined because the        │
│ manually │      │ defining extension is not installed. Cannot decide if it is │
│          │      │ deprecated or not.                                          │
│          │      │                                                             │
└──────────┴──────┴─────────────────────────────────────────────────────────────┘

themes/custom/vagovclaro/templates/node/node--landing-page--teaser.html.twig:
┌──────────┬──────┬─────────────────────────────────────────────────────────────┐
│  STATUS  │ LINE │                           MESSAGE                           │
├──────────┼──────┼─────────────────────────────────────────────────────────────┤
│ Check    │ 83   │ The 'classy/node' library is not defined because the        │
│ manually │      │ defining extension is not installed. Cannot decide if it is │
│          │      │ deprecated or not.                                          │
│          │      │                                                             │
└──────────┴──────┴─────────────────────────────────────────────────────────────┘

themes/custom/vagovclaro/templates/node/node--office--connect-with-us.html.twig:
┌──────────┬──────┬─────────────────────────────────────────────────────────────┐
│  STATUS  │ LINE │                           MESSAGE                           │
├──────────┼──────┼─────────────────────────────────────────────────────────────┤
│ Check    │ 85   │ The 'classy/node' library is not defined because the        │
│ manually │      │ defining extension is not installed. Cannot decide if it is │
│          │      │ deprecated or not.                                          │
│          │      │                                                             │
└──────────┴──────┴─────────────────────────────────────────────────────────────┘

themes/custom/vagovclaro/templates/node/node--page.html.twig:
┌──────────┬──────┬─────────────────────────────────────────────────────────────┐
│  STATUS  │ LINE │                           MESSAGE                           │
├──────────┼──────┼─────────────────────────────────────────────────────────────┤
│ Check    │ 83   │ The 'classy/node' library is not defined because the        │
│ manually │      │ defining extension is not installed. Cannot decide if it is │
│          │      │ deprecated or not.                                          │
│          │      │                                                             │
└──────────┴──────┴─────────────────────────────────────────────────────────────┘

themes/custom/vagovclaro/templates/node/node--support-service--support-services-
listing.html.twig:
┌──────────┬──────┬─────────────────────────────────────────────────────────────┐
│  STATUS  │ LINE │                           MESSAGE                           │
├──────────┼──────┼─────────────────────────────────────────────────────────────┤
│ Check    │ 83   │ The 'classy/node' library is not defined because the        │
│ manually │      │ defining extension is not installed. Cannot decide if it is │
│          │      │ deprecated or not.                                          │
│          │      │                                                             │
└──────────┴──────┴─────────────────────────────────────────────────────────────┘

themes/custom/vagovclaro/templates/node/node--va-form--full.html.twig:
┌──────────┬──────┬─────────────────────────────────────────────────────────────┐
│  STATUS  │ LINE │                           MESSAGE                           │
├──────────┼──────┼─────────────────────────────────────────────────────────────┤
│ Check    │ 83   │ The 'classy/node' library is not defined because the        │
│ manually │      │ defining extension is not installed. Cannot decide if it is │
│          │      │ deprecated or not.                                          │
│          │      │                                                             │
└──────────┴──────┴─────────────────────────────────────────────────────────────┘

themes/custom/vagovclaro/vagovclaro.info.yml:
┌──────────┬──────┬────────────────────────────────────────────────────────────┐
│  STATUS  │ LINE │                          MESSAGE                           │
├──────────┼──────┼────────────────────────────────────────────────────────────┤
│ Check    │ 0    │ Value of core_version_requirement: ^8 || ^9 is not         │
│ manually │      │ compatible with the next major version of Drupal core. See │
│          │      │ https://drupal.org/node/3070687.                           │
│          │      │                                                            │
└──────────┴──────┴────────────────────────────────────────────────────────────┘
```

## Acceptance Criteria
- [x] The theme has been updated and verified to be compatible with Drupal 10.

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

Closes #11010.

I'm looking for confirmation, but it appears that everything here is working correctly; Upgrade Status just can't confirm that.

Consequently, the only change at this time is to openly state that we're compatible with Drupal 10.

### CODE REVIEW

**Comment by ndouglas** [comment]
We might get a clearer picture of how accurate this is after #11529 .

**Comment by ndouglas** [comment]
PHPUnit failure is spurious.

**Review by swirtSJW — APPROVED** [review]
I am not seeing a risk of merging this now (as opposed to blocking it on https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11529)  The biggest risk is that the theme is not actually fully compatible with D10, but I am not sure we are going to know that for sure until we have a build that is upgraded to D10.

@ndouglas I am approving this.   If you think I am missing something with my loose argument above, let me know.    Otherwise you are free to merge.

**Comment by ndouglas** [comment]
Yeah, there are no code-level compatibility issues with Drupal 10; that much I'm sure of.  There are some complaints thrown by the Upgrade Status module, but I think they're tied to the issues we're seeing in #11529 and not actually compatibility issues.

**Pull request merged**
