### PR TITLE
VACMS-3925: Update browser to show r&s hub description info.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #3925 

## Testing done
Visual / behat

## Screenshots
image
image

## QA steps
- As an administrator, go to `node/15068/edit`, open up the VA benefits panel, and click Select Benefit hubs button
- Visually verify that all items in browser have a description
- Close browser, and visually verify that selected items are in a sortable table.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by swirtSJW** [comment]
Conflictified :(

**Comment by ethanteague** [comment]
> Conflictified :(

Resolved, @swirtSJW :+1:

**Review by swirtSJW — APPROVED** [review]

**Review by kevwalsh — APPROVED** [review]
Nice, looks good @ethanteague!

**Comment by swirtSJW** [comment]
Sorry, conflicted again.   I promise this one goes next.

**Comment by ethanteague** [comment]
> Sorry, conflicted again. I promise this one goes next.

Np a'tall, @swirtSJW - thanks for herding all the pr cats.
Updated.

**Comment by swirtSJW** [comment]
Sorry somebody else merged something.   another coflict.   And a failing behat.

**Comment by ethanteague** [comment]
> Sorry somebody else merged something. another coflict. And a failing behat.

ok. will look at this tomorrow.

**Review by swirtSJW — APPROVED** [review]

**Pull request merged**
