### PR TITLE
1585 facility content structure and other AX improvements.

### PR DESCRIPTION
**Pull request by kevwalsh**

### CODE REVIEW

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-144<br><br> [button_visit-site](http://pr-144.va.agile6.com)

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-144<br><br> [button_visit-site](http://pr-144.va.agile6.com)

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-144<br><br> [button_visit-site](http://pr-144.va.agile6.com)

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-144<br><br> [button_visit-site](http://pr-144.va.agile6.com)

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-144<br><br> [button_visit-site](http://pr-144.va.agile6.com)

**Comment by andyhawks** [comment]
rebuild

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-144<br><br> [button_visit-site](http://pr-144.va.agile6.com)

**Comment by ElijahLynn** [comment]
FYI, Jira won't pickup branches or PRs without the "VAGOV-" prefix.

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-144<br><br> [button_visit-site](http://pr-144.va.agile6.com)

**Pull request merged**
