### PR TITLE
VACMS-11655:  removed max-width from node edit forms

### LINKED ISSUE #11655: Make edit form responsive, removed fixed max-width
## Description
The edit form currently is set to a max-width of 52rem. We can remove that line and make it responsive within the grid property. 

## Acceptance Criteria
- [ ] Make Edit forms fully responsive.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by edmund-dunn**
## Description

Closes #11655.

## Testing done
Tested Locally.

## Screenshots
CleanShot 2022-11-28 at 09 15 01
CleanShot 2022-11-28 at 09 04 56

## QA steps

As any user:
1. Edit an existing node
   - [ ] Validate that node form is now full width (see screen shots)
2. Then add a new node
   - [ ] Validate that node form is now full width (see screen shots)

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by swirtSJW** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11655#issuecomment-1329807856

**Comment by swirtSJW** [comment]
i don't think node 44718 identified in Tanner's QA steps can be used here to validate this because that node no longer contains paragraph tables.

Also this change impacts every single content type in the system.  We need a more intentional set of QA steps than simply editing any old node and creating a new node from any content type.  We have 51 content types in the CMS.  We can not make a sweeping change and QA only one of them.

**Comment by edmund-dunn** [comment]
> Sorry, this seems to be undoing work without looking to see what issue it is undoing That limit to 52rem was added by #8571 in response to user feedback and specific issues that the QA steps on this PR are not looking for.
> 
> At minimum we should be carrying forward the QA steps that were in the PR that added the limit for 52 rem
> 
> * [ ]  Visit /node/18161/edit and scroll down to the media contacts field. See that it is inside the container at all screen sizes.
> * [ ]  Visit /node/44718/edit and resize screen size. See that paragraphs tables with multiple values don't break out of the container at all screen sizes. Link teaser paragraph ("Related Information") was the main offender here.

This is very helpful. I will consult and readdress the work done.

**Comment by edmund-dunn** [comment]
> i don't think node 44718 identified in Tanner's QA steps can be used here to validate this because that node no longer contains paragraph tables.
> 
> Also this change impacts every single content type in the system. We need a more intentional set of QA steps than simply editing any old node and creating a new node from any content type. We have 51 content types in the CMS. We can not make a sweeping change and QA only one of them.

@swirtSJW while I understand what you are saying here and do not disagree it needs to be clarified to be actionable.

**Comment by swirtSJW** [comment]
> @swirtSJW while I understand what you are saying here and do not disagree it needs to be clarified to be actionable.

As the creator of this PR, what do you propose as QA steps to better insure that our 51 content types are not adversely impacted by the change you are making?  You have proposed checking one node.  I am suggesting that 1/51 is not enough.

**Pull request closed without merging**
