### PR TITLE
VACMS-10111: Adds configurable heading functionality to views pagers

### PR DESCRIPTION
**Pull request by tonytaylor**
## Description

Patch allows for per-view pager heading configuration.

Relates to #10111 

## Testing done

This patch has been tested against core.  It is currently failing the test @ core/modules/datetime/tests/src/Functional/Views/FilterDateTest.php with the following error:

`Drupal\Core\Config\Schema\SchemaIncompleteException: Schema errors for views.view.test_filter_datetime with the following errors: views.view.test_filter_datetime:display.default.display_options.pager.options.pagination_heading_level missing schema in Drupal\Core\Config\Development\ConfigSchemaChecker->onConfigSave() (line 94 of core/lib/Drupal/Core/Config/Development/ConfigSchemaChecker.php).`

## Screenshots

image

## QA steps

What needs to be checked to prove this works?

- Go to https://pr14841-zocaqptxdmttlxhdgak9onnf5s3didgh.ci.cms.va.gov/admin/structure/views/view/content
- Click on the Pager Options Configuration link image
- The _Heading Level_ configuration option should be present image
- Choose a heading level, click `Apply`, and then click `Save`
- Either scroll down to verify via Preview pager area, or navigate back to https://pr14841-zocaqptxdmttlxhdgak9onnf5s3didgh.ci.cms.va.gov/admin/content and locate the pager near the bottom of the page
- Right-click on or near the first link in the pager and select Inspect. The invisible header that contains the pager--its element should have been updated to reflect your selection. image

### Select Team for PR review

- [x] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### CODE REVIEW

**Review by ndouglas — DISMISSED** [review]

**Comment by ndouglas** [comment]
This looks good to me, if it works for @laflannery.

**Comment by laflannery** [comment]
This looks pretty good to me but I do have one question and I think it's just my lack of Drupal knowledge.  

I was checking multiple views (Media, people, etc.) because I wanted to make sure that they kept the default H4 and for the most part they did. However, the [Outdated Content view](https://pr14841-zocaqptxdmttlxhdgak9onnf5s3didgh.ci.cms.va.gov/admin/content/outdated_content) now has an H2 pager heading, like the Main content view does. Is that just because of how we built it (maybe a child of the content view or something?) Other content views, like [Facilities](https://pr14841-zocaqptxdmttlxhdgak9onnf5s3didgh.ci.cms.va.gov/admin/content/facilities) did not get the H2 header so I just want to make sure that this is more of a specific VA thing with our set up.

**Comment by laflannery** [comment]
This looks pretty good to me but I do have one question and I think it's just my lack of Drupal knowledge.  

I was checking multiple views (Media, people, etc.) because I wanted to make sure that they kept the default H4 and for the most part they did. However, the [Outdated Content view](https://pr14841-zocaqptxdmttlxhdgak9onnf5s3didgh.ci.cms.va.gov/admin/content/outdated_content) now has an H2 pager heading, like the Main content view does. Is that just because of how we built it (maybe a child of the content view or something?) Other content views, like [Facilities](https://pr14841-zocaqptxdmttlxhdgak9onnf5s3didgh.ci.cms.va.gov/admin/content/facilities) did not get the H2 header so I just want to make sure that this is more of a specific VA thing with our set up.

**Comment by tonytaylor** [comment]
Hmmm that's strange--just checked those views and they have an H4 pager heading ([Main Content](https://pr14841-zocaqptxdmttlxhdgak9onnf5s3didgh.ci.cms.va.gov/admin/content) and [Outdated View Content](https://pr14841-zocaqptxdmttlxhdgak9onnf5s3didgh.ci.cms.va.gov/admin/content/outdated_content)).  

This patch should not modify any existing view's pager configuration.

**Comment by laflannery** [comment]
@tonytaylor It's not modifying existing views - I had made the Main content view pager an H2 on purpose. But I think somehow the Main content view and the Outdated content view are connected because whenever I change the pager header level for the Main content view, the pager level for outdated content changes as well.  Is that expected? (I just changed main content to an h3 just now and Outdated content is also H3)

**Comment by tonytaylor** [comment]
Thanks for clarifying.  AFAICT changing the primary view pager config shouldn't affect derivative view configs.

I'll look further into this.

**Comment by tonytaylor** [comment]
You'll have to select whether you want to affect all child views or just the current view. A bit counter-intuitive, but you can click on the Pager Type link (Full/Mini) to select whether to update the configuration on all views or just the current one.



Pardon the senior moment.

**Comment by tonytaylor** [comment]
Yes, precisely!

Main content and Outdated content reuse the same configuration except for the filter component (and probably other stuff too)--this was overridden in a similar fashion.

**Comment by laflannery** [comment]
Got it, thanks for explaining! This is approved by me then!

**Review by ndouglas — APPROVED** [review]
Verified this functions as intended. Thank you for the excellent QA steps, @tonytaylor!

**Pull request merged**
