### PR TITLE
VACMS-9510 add drush command patch, export config for sitewide alerts

### LINKED ISSUE #9510: Add drush commands for create and delete
**Background**
We use drush to automatically manage site alerts & shields around deployment messaging.

- [pre-deploy alert](https://github.com/department-of-veterans-affairs/devops/blob/793326c6d6a6075ecaee746a129203da6f0a2dfe/ansible/cms-test/cms-site-alert.yml#L33)
- [site shield during deployment](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/cms-test/tasks/pre-deploy-tasks.yml#L17)
- [post-deploy alert](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/cms/cms-deploy-live.yml#L28)

Before we can use the Sitewide Alert module instead of Site Alert, we need feature parity on the drush commands.

Upstream issue on D.o [created here](https://www.drupal.org/project/sitewide_alert/issues/3290964). 

**ACs**
- [ ] Patch available on the issue above that adds drush commands to create & delete, enable and disable sitewide alerts.

### PR DESCRIPTION
**Pull request by tjheffner**
## Description
Closes #9510. Adds drush commands for ability to create / enable / disable / delete sitewide alerts. 

TODO: clean up menu placement for sitewide alert... right now it places itself in the tab list on `/admin/content` in the second spot and throws everything off. gross.

## Testing done

Same syntax as site alert drush commands: `"label"`, `"message"`, `--option` flags. Adjust quotes as needed for passing into ddev properly, see below:

**create alert:**
`ddev drush sitewide-alert:create "'test-alert 7' 'testing my new alert' --style=warning --dismissible"`

`ddev drush sitewide-alert:create "'schedule-end' 'a brand new world' --style=shield --end='20 minutes'"`
 
`ddev drush sitewide-alert:create "'test-alert 4' 'testing my new alert' --style=warning --status=0 --dismissible=0"`

**enable alert:**
`ddev drush sitewide-alert:enable "'test-alert 4'" -y`

**delete alert:**
`ddev drush sitewide-alert:delete "'test-alert 4'" -y`

**disable alert:**
`ddev drush sitewide-alert:disable "'test-alert 7'" -y`

## Screenshots
Screen Shot 2022-06-24 at 1 04 15 PM

## QA steps

pull branch locally, verify that the above drush commands return successfully for you. malformed commands should throw proper error messages or normalize to allowed values (in the case of the `--style` option)

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### CODE REVIEW

**Comment by swirtSJW** [comment]
This is looking really good.  After I test this a bit more I will RTBC upstream.

**Comment by swirtSJW** [comment]
I just rebased this on main and resolved the composer conflicts.  You'll need to reset hard to head if you need to pull this down again.

**Comment by swirtSJW** [comment]
RTBC'd this on the https://www.drupal.org/project/sitewide_alert/issues/3290964

**Comment by swirtSJW** [comment]
I think it makes sense to merge this to make it easier to do all the additional things to do, but we can discuss tomorrow in case we want to wait, and treat this as an integration branch.

**Comment by tjheffner** [comment]
> I think it makes sense to merge this to make it easier to do all the additional things to do, but we can discuss tomorrow in case we want to wait, and treat this as an integration branch.

I agree -- would be nice to have this in as a base, keep future PRs a bit easier with the composer shenanigans (as long as people aren't annoyed by the new tab... i think we can theme alter that out in the future if needed)

**Review by swirtSJW — APPROVED** [review]

**Pull request merged**
