### PR TITLE
VACMS-2767: Update list styles to show numbers and improve consistency

### PR DESCRIPTION
**Pull request by acrollet**
## Description

See #2767 

## Testing done

Tested editing and viewing on 'page' and 'health_care_region_detail_page' content types.

## Screenshots

Screen Shot 2020-11-02 at 8 05 45 AM

Screen Shot 2020-11-02 at 8 06 20 AM

## QA steps

As a user with the content admin role:
1. Create or edit pages from multiple content types
1. Add ordered and unordered lists in a rich text block
1. Then validate Acceptance Criteria from issue:
- [ ] Ordered lists are shown with numbered bullets
- [ ] List margins and padding are consistent

## Definition of done 

- [ ] defect resolution is validated w/ Randi after deployment including #3327

### CMS user-facing release note

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication.
- [ ] Yes, but it hasn't yet been written (this code is not ready to merge!).
- [x] No announcement is needed for this code change.

### CODE REVIEW

**Comment by oksana-c** [comment]
@acrollet #2767 and https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3327 are related in that the styling using `revert` values may need to be reviewed/updated. 
You may have already seen 3327, but if not, please confirm that the solution here will cover both.

**Comment by acrollet** [comment]
@oksana-c thanks for the heads-up, I hadn't seen #3327 - however this PR removes the revert values so I believe it should address the issue - will work on repro-ing and confirming.

**Comment by acrollet** [comment]
@kevwalsh just pinging for a review if you're able :-)

**Review by ndouglas — APPROVED** [review]
Seems legit and works in practice.  Appears to resolve #3327 as well.

**Pull request merged**
