### PR TITLE
VACMS-15893 Add setup for CM Document export/import.

### LINKED ISSUE #15893: Lay prep work for importing Content Model Documentation.
## User Story or Problem Statement
Content model documenation now supports exporting from Sandbox and importing to prod.  This created the needed ability to have code ship with its documentation.

There is a slight bit of prep that is need to pave the way for this.  That is what this issue is about.

## Acceptance Criteria
- [ ] Config sets va_gov_migration as the location for export files
- [ ] Sets an import pattern in va_gov_migrate.install
- [ ] Add a README to the export file directory.

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

### PR DESCRIPTION
**Pull request by swirtSJW**
## Description

Closes #15893

This PR includes both the initial setup for import and export, AND a sample Content Model Document import  about Import / Export (inception much?).

## Screenshots
See my comment.

## QA steps

What needs to be checked to prove this works?
What needs to be checked to prove it didn't break any related things?
What variations of circumstances (users, actions, values) need to be checked?
- [x] View the build log and validate the update section shows no errors
image

As an admin
1. Go to where the [newly imported doc should be](https://pr15894-ecrdwq9diwefb6d0awbeaa9qe71uz8h1.ci.cms.va.gov//admin/structure/cm_document/process/125/importing-site-documentation)
   - [x] Validate that the doc has content, a diagram, and a link.
2. Click on the revisions tab
   - [x] Validate that it has a revision showing the import and that it indicates it was an import. 
3. Go to the [recent log messages](https://pr15894-ecrdwq9diwefb6d0awbeaa9qe71uz8h1.ci.cms.va.gov/admin/reports/dblog?type%5B%5D=cm_document) 
   - [x] Validate that there is one entry for the summary of files imported
   - [x] Validate there is one entry for the import of the specific content model document.
  

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.
- [ ] If there are field changes, front end output has been thoroughly checked.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by swirtSJW** [comment]
Build log output
image

**Review by omahane — APPROVED** [review]
Does what it says on the tin!

I didn't understand the line breaks in this document. It might be worth looking into. NBD, though.
Screenshot 2023-10-30 at 7 42 42 AM

**Comment by swirtSJW** [comment]
@omahane Those linebreaks are in the original.   One was intentional the other was not, but both of them were created by the person in the chair, not the export import process.

**Comment by swirtSJW** [comment]
image

**Pull request merged**
