### PR TITLE
VACMS-5086: Add redirect on login for one section users.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #5086

## Testing done
Visual

## Screenshots
image

## QA steps
Login as `vanessa.luxen@va.gov` and visually verify you are redirected to Butler section page.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by ndouglas — COMMENTED** [review]
If I'm on a page within my section, like [this one](https://cms-nlarf7kaxljdmdhbwhbvkrwqklqhsjgf.ci.cms.va.gov/butler-health-care/locations/armstrong-county-va-clinic/addiction-and-substance-abuse-care), and then log in, I'm redirected to Butler health care rather than the page I was on previously.  Is this intended?

**Comment by ethanteague** [comment]
> If I'm on a page within my section, like [this one](https://cms-nlarf7kaxljdmdhbwhbvkrwqklqhsjgf.ci.cms.va.gov/butler-health-care/locations/armstrong-county-va-clinic/addiction-and-substance-abuse-care), and then log in, I'm redirected to Butler health care rather than the page I was on previously. Is this intended?

Good thinking, @ndouglas - I added a check to only do the redirect if the route is `user.login`

**Review by ndouglas — APPROVED** [review]
❤️

**Review by kevwalsh — APPROVED** [review]
Amazing. Can't believe we waited to do this for so long when it was this simple. 

This is a particular great experience for members of Vet Centers, who actually get a designed dashboard.

**Comment by kevwalsh** [comment]
VACMS-5086__Add_redirect_on_login_for_one_section_users__by_ethanteague_·_Pull_Request__5752_·_department-of-veterans-affairs_va_gov-cms

**Pull request merged**
