### PR TITLE
VACMS-11726: make VAMC alert checkbox list alpha sort and cleanup

### LINKED ISSUE #11726: CMS: VAMC System Banner Alert with Situation Updates do not work for Lovell systems
## Describe the defect
The existing logic to handle the placement of Banner Alerts with Situation Updates does not work with Lovell. When we attempt to create one of these nodes we do not have the option to display the Banner on the Lovell - VA or Lovell - TRICARE subsystems. These systems are not listed as options ( see comments on #11636 )

## To Reproduce
1. Create a new VAMC System Banner Alert with Situation Updates node
2. For the field **Pages for the following VAMC systems** select **Lovell Federal health care**
3. For the section select **Lovell Federal health care**
4. Be sure to supply values for all additional required fields
5. Save the node
6. Trigger a content release: /admin/content/deploy
7. When the content release has finished, check the following pages on the front end: **/lovell-federal-tricare-health-care/** and **/lovell-federal-va-health-care/**
8. The Banner alert with situation updates is not present

## AC / Expected behavior
CMS:
- Editors should have the option to add one of these banners to Lovell Federal VA health care
- Editors should have the option to add one of these banners to Lovell Federal TRICARE health care
- The list of systems to choose from should be alpha sorted to make the selection process easier
Front End:
- A banner added to Lovell VA should show up on Lovell VA
- A banner added to Lovell TRICARE should show up on Lovell TRICARE

I suspect adding Lovell VA and Lovell TRICARE to the list of available systems will fix the issue with these not showing for those individual systems on the front end. 

## Screenshots
Screen Shot 2022-11-23 at 4 24 44 PM

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by JayDarnell**
## Description

Relates to #11726 

## Testing done

Visual/manual

## Screenshots

Previous checkbox presentation:
204313312-32a8e866-ac92-4c16-b917-e610421d9429

Updated checkbox presentation:
Screen Shot 2022-11-30 at 3 06 33 PM

Previous view definition:
Screen Shot 2022-11-30 at 1 40 52 PM

New view definition:
Screen Shot 2022-11-30 at 3 12 08 PM

## QA steps

As an admin user:

- [x] Visit /admin/content/bulk and filter by Section = **Lovell Federal health care**
- [x] Select all results and publish latest revision
- [x] Visit /node/add/full_width_banner_alert and select **Lovell Federal TRICARE** health care for the field **Pages for the following VAMC systems** and select Lovell - TRICARE for the Section field
- [x] Supply all remaining required fields and check the Published checkbox and save
- [x] Visit /admin/content/deploy and trigger a content release by clicking **Release content**
- [x] Visit the Lovell - TRICARE section of the front end and verify the alert you created is visible

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

### CODE REVIEW

**Comment by JayDarnell** [comment]
Those cypress accessibility failures seem out of place. Nothing I changed modified anything in terms of UI presentation. The front end also failed to build for me to do my initial tests so I'm rebuilding the tugboat environment now.

**Comment by ndouglas** [comment]
yeah, those accessibility test failures are #11761.

**Review by swirtSJW — APPROVED** [review]
Alphasort tests out good.
Existing alerts sill have their initial values set (no data loss)
Lovell VA and TRICARE options show up when those status pages are published.

Approved for merge when FE related testing is done on QA environtment  (thoses tests are unrelated to this pr, just suing the staged data from the environment.

**Comment by swirtSJW** [comment]
image

**Comment by JayDarnell** [comment]
I'm happy to report that these appear to be working fine on the front end operating status pages:
Screen Shot 2022-12-01 at 11 33 21 AM

Screen Shot 2022-12-01 at 11 34 05 AM

And on other pages within each system:
Screen Shot 2022-12-01 at 11 35 27 AM

Screen Shot 2022-12-01 at 11 35 04 AM

**Comment by JayDarnell** [comment]
All tests previously passed, squashing and merging before another branch is merged and this needs to be rebased again.

**Pull request merged**
