### PR TITLE
VACMS-1384: Update all instances of Revision Log Widget (hide_revision_field) to Textarea

### PR DESCRIPTION
**Pull request by oksana-c**
## Description

See #1384 .

This PR changes form display widget for Revision Log Message to Textarea.

**NOTE:** Once this Pr is merged and deployed, I'll open a PR for removal of hide_revision_field contrib.
## Testing done

Manual

## QA steps

As user 1
1. visit /admin/content/facility-status. -> select a few facilities and click on "Update Operating Status" button
   - [x]  Confirm that the VBO form for updating fields is displayed without errors
1. visit add Event node form /node/add/event
   - [x] Confirm that Editorial workflow fields match the screenshot below
Screen Shot 2020-04-14 at 12 10 58 PM

1. visit several other random content type forms
   - [x] confirm that Editorial workflow fields match the screenshot above

## Definition of Done
- [ ] Product release notes 
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

### CODE REVIEW

**Comment by swirtSJW** [comment]
I am anticipating that we'll need a behat test update since we are changing fields.

**Comment by oksana-c** [comment]
> I am anticipating that we'll need a behat test update since we are changing fields.

we're not changing fields, only form display widgets for editorial workflow fields, that are excluded from our behat tests.

**Comment by oksana-c** [comment]
hmm, this is interesting. Looking into it

> The field revision_log_settings has already been deleted and it is in[error]
> the process of being purged.

**Comment by oksana-c** [comment]
@swirtSJW , this PR will only change the config for form displays. Uninstall of the module will happen separately.

**Comment by swirtSJW** [comment]
@oksana-c Doesn't this cause it to be not-enabled which is not really a thing in drupal 8  There is either enabled, or uninstalled.
image

**Comment by oksana-c** [comment]
you're looking at an outdated set of files there @swirtSJW  ^

**Comment by oksana-c** [comment]
also, phpunit failure is a fluke https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1489#commitcomment-38494080 - tests are passing on latest commit

**Comment by kevwalsh** [comment]
QA'd on http://pr1489.ci.cms.va.gov/, looks good!

**Pull request merged**
