### PR TITLE
VACMS-3791: Add advancedqueue module and associated config

### PR DESCRIPTION
**Pull request by acrollet**
## Description

See #3791 - This is a first PR that only enables the advancedqueue module, to prevent the [main PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3864) from failing to deploy.

## Testing done

Automated testing.

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by indytechcook — APPROVED** [review]
Let's get this merged in so we can continue testing the background process on https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3864

**Review by ndouglas — APPROVED** [review]
I intended to check this out locally but I can do that later, I guess.

**Comment by ndouglas** [comment]
After merging `master` into another branch, I encountered the following issue:

Screen Shot 2020-12-31 at 10 43 47 AM

It persisted after a `lando composer install` and even a `lando composer nuke && lando composer install`.

I did fix it with this change, which I alluded to... yesterday?  Was it yesterday?  How long have I been here?  Sometimes I think I was born on the bloody grass in that grove of ash, with the taste of fire in my mouth and a hole in my chest. Are you my mother, Adrian?

Anyway, this change:

Screen Shot 2020-12-31 at 10 45 38 AM

worked:

Screen Shot 2020-12-31 at 10 47 58 AM

I don't know why Drupal reports the error that it does when it encounters this situation, but I suspected the (similar but not identical, I acknowledge) issue you encountered might have the same underlying issue: crap information being fed to the dependency graph manager.

Anyway, back to what I was doing, which was gazing into a different abyss...

**Comment by acrollet** [comment]
wow, that sounds "fun" - thanks for figuring that out!

**Pull request merged**
