### PR TITLE
VACMS-12450: updates for outdated content report

### LINKED ISSUE #12450: Update outdated content report to show only assigned sections
## Description

Currently the outdated content tool allows users to see all sections, even when they are not assigned those sections. In order to avoid confusion with the editorial experience, we should rework the filters to only show editors content in the drop down that they are responsible for/can access. 

Current view:

## Acceptance Criteria
- [x] limit section filter view to match only what editors have access to
- [x] Add sort to Last Saved by and Editor column, asc, and make it the default sort
- [x] Move OUtdated content to the content menu dropdown
- [x] Requires design review
- [ ] Requires accessibility review

### Team
Please check the team(s) that will do this work.

- [X] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

### PR DESCRIPTION
**Pull request by edmund-dunn**
## Description

Closes #12450.

## Testing done
Tested locally. Verified that the editor can only see the section(s) they are assigned to in the section filter. Also checked that the Last Saved by AN editor column is the default sort and sorts ascending now. Checked that the Outdated content menu item is in the Content menu dropdown. 

## Screenshots
CleanShot2023-02-09at13 08 22
CleanShot2023-02-09at13 08 28

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

Log in as Cullen.lyons@va.gov, Peter.Potter@va.gov and yourself (as super admin)
- [x] limit section filter view to match only what editors have access to
- [x] Add sort to Last Saved by and Editor column, asc, and make it the default sort
- [x] Move Outdated content to the content menu dropdown

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by EWashb — APPROVED** [review]
This looks good for me. It might be helpful to add which account Blake should log in as to test from the editor view. Do you have one that you prefer to use? I would say we might want to make sure to test this out from various editor perspectives (VAMC, Vet Center, etc.)

**Comment by swirtSJW** [comment]
@edmund-dunn Can we flesh out these testing steps a bit more?  
image

Who am I testing as? (preferably we need a user in one section and a user in multiple sections.) What am I doing?

**Comment by BlakeOrgan** [comment]
I just checked over everything using the following criteria and noticed a couple things.

**VAMC ([John.Taylor8@va.gov](mailto:John.Taylor8@va.gov) - VA Central Arkansas health care)**

- [x] Outdated Content is under the content dropdown
- [x] Default sort is by the most outdated first
- [x] This person only has access to view their facility.
- [x] “All outdated content” is the first view when clicking the outdated content report
- [x] All outdated and 30/60/90 overdue show most outdated content first
- [x] 30/60/90 upcoming show content that will become outdated first.

**VISN ([Matthew.Gowan@va.gov](mailto:Matthew.Gowan@va.gov) - VISN 16)**

- [x] Outdated Content is under the content dropdown
- [ ] Default sort is by the most outdated first
- [x] This person has access to view all facilities within their section.
- [x] “All outdated content” is the first view when clicking the outdated content report
- [x] All outdated and 30/60/90 overdue show most outdated content first
- [ ] 30/60/90 upcoming show content that will become outdated first.

**VET CENTER ([Samantha.Blevins@va.gov](mailto:Samantha.Blevins@va.gov) - Morgantown Vet Center)**

- [x] Outdated Content is under the content dropdown
- [x] Default sort is by the most outdated first
- [x] This person only has access to view their facility.
- [x] “All outdated content” is the first view when clicking the outdated content report
- [x] All outdated and 30/60/90 overdue show most outdated content first
- [x] 30/60/90 upcoming show content that will become outdated first.

**DISTRICT ([Joanne.Boyle@va.gov](mailto:Joanne.Boyle@va.gov) - District 1)**

- [x] Outdated Content is under the content dropdown
- [ ] Default sort is by the most outdated first
- [x] This person has access to view all facilities within their section.
- [x] “All outdated content” is the first view when clicking the outdated content report
- [x] All outdated and 30/60/90 overdue show most outdated content first
- [ ] 30/60/90 upcoming show content that will become outdated first.

Based on these criteria, mostly everything looked good, but I did notice two things.

- “This view is only available to admins.” at the top of the page needs to be removed because none of these people are listed as admins but will now have access to this view.
- When logged into a user that has access to multiple sections (Ex: VISN level user for VAMCs or District level user for Vet Centers) the dates are not listed in order when the list switches between the different facilities. I've attached images below.

**When logged in as [Matthew.Gowan@va.gov](mailto:Matthew.Gowan@va.gov) who has access to VISN 16, the dates are not in order of most outdated to least outdated when viewing content that is already out of date. This seems to happen when scrolling between the different facilities they have access to.**
Screen Shot 2023-02-10 at 1 57 34 PM


**When logged in as [Joanne.Boyle@va.gov](mailto:Joanne.Boyle@va.gov) who has access to District 1, the dates are not in order of most outdated to least outdated when viewing content that is already out of date. This seems to happen when scrolling between the different facilities they have access to.**
Screen Shot 2023-02-10 at 1 57 18 PM

**Comment by swirtSJW** [comment]
Thanks for the thorough testing @BlakeOrgan   Sorting on a grouped table it problematic.  That is why I reccomended that we remove the section grouping so that we get one list that can be sorted properly and people have the ability to filter by section, so the grouping does not offer anything they can't already do more effectively.

**Comment by BlakeOrgan** [comment]
@swirtSJW Agreed. I'm good with removing the grouping as long as the section column stays.

**Comment by ndouglas** [comment]
Not seeing the menu item when logged in as myself; am I missing something?

Screenshot 2023-03-07 at 12 52 09 PM

**Comment by edmund-dunn** [comment]
> Not seeing the menu item when logged in as myself; am I missing something?
> 
> Screenshot 2023-03-07 at 12 52 09 PM

Good catch! I forgot a fresh config export.

**Review by ndouglas — APPROVED** [review]
Screenshot 2023-03-07 at 1 23 28 PM
Screenshot 2023-03-07 at 1 23 22 PM
Screenshot 2023-03-07 at 1 22 50 PM
Looks right.

**Pull request merged**
