### PR TITLE
VAGOV-935 support services node type

### PR DESCRIPTION
**Pull request by beeyayjay**

### CODE REVIEW

**Comment by mbenziane** [comment]
Can one of the admins verify this pull request?

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-65<br><br> [button_visit-site](http://pr-65.va.agile6.com)

**Pull request merged**
