### PR TITLE
VACMS 3680: What's new in the CMS

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

See #3680.

There's some tweaking to be done with the CSS and date format and is probably not ready for review.

## Testing done
Manual testing.  This is a very UI kinda thing and pretty stock functionally.

## Screenshots
Screen Shot 2020-12-22 at 1 47 02 PM

## QA steps
As a user with permission to view CMS Help Pages:
1. View a [CMS Help Page](http://va-gov-cms.lndo.site/help/session-4-facilities).
1. Then validate Acceptance Criteria from issue #3680:
- [ ] a block that displays a link to the CMS Announcement page and the date of the latest published revision of this page is placed on all pages that have the following URL pattern `/help/*`

### Definition of Done

- [x] Documentation has been updated, if applicable.
- [x] Tests have been added if necessary.
- [x] Automated tests have passed.
- [x] Code Quality Tests have passed.
- [x] Acceptance Criteria in related issue are met.
- [x] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by oksana-c — COMMENTED** [review]
covering a few things from description comments:
* let's disable/delete the CTA block completely in this PR. Im also deleting it in #3850, but this one will go out sooner, so we should remove it here.
* I couldn't test the css for the block - it's not enabled in config here yet.
* let's add new date format to cover the one on the mock up. Also a question to @jordanamello in regards to the new format. 
   * 1) Dashboard designs have no space between hours and am/pm >> `08/11/20 8:50am ET`, "Whats new in CMS" block has a space `08/11/20 8:50 a.m. ET`- is there a rationale towards one versus the one? What should be our standard?
   * 2) `a.m.` in the new block has period separators and dashboard designs don't. In PHP language we can display the am/pm indicator in the following two ways( none has periods) (1) lowercase `am`,`pm`; (2) uppercase `AM`, `PM`.  Let's settle on a system-wide format as a part of this effort.

**Comment by oksana-c** [comment]
resulting pattern short-term: `mm/dd/yy hh:mm am TZ`

**Comment by ndouglas** [comment]
Screen Shot 2020-12-23 at 12 07 26 PM

I added a date format, "Standard" (`standard`): `m/d/y h:i a T`
- m -- month, leading zeros
- d -- day, leading zeros
- y -- year, two-digit
- h -- hour, 12-hour format, leading zeros
- i -- minute, leading zeros
- a -- am/pm, lowercase, no periods
- T -- timezone abbreviation

**Review by oksana-c — APPROVED** [review]
@ndouglas , I moved whats new block styles into its own library. When we refactor / remove this block in the future, it will be easier to find and remove that css. Also, we are adding a block in a custom module and not in a theme, so self-contained library that can be attached to a block instead of adding additional css for a broader application is a better way to go for maintenance. This PR is good to merge once test are ✅

**Pull request merged**
