### PR TITLE
[WIP] VACMS-829: Add entity revisions to blocks and media.

### LINKED ISSUE #829: Spike: entity revisions
We need a spike for this user story: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/830

Explore contrib modules for revisions on non-node entity types. 

Create PR environment with everything enabled for evaluation by Mike C and possibly Randi H.

### LINKED ISSUE #5102: Enable media revisions UI
## User Story or Problem Statement

As an editor of media, i want to see its revision history. 

## Acceptance Criteria
- [x] "Revisions" tab in the "Edit" section of media which displays a list of revisions and allows viewing, reverting or deleting revisions.

## Implementation steps
- [ ] Install and enable Media Revisions UI

### LINKED ISSUE #5672: Enable revision history for blocks
## User Story or Problem Statement

As a block editor, i want to see block revisions and revert if needed to older versions, just like nodes. 

See also 
* #830 (Taxonomy revisions)
* #5102 (Media revisions)

## Acceptance Criteria
- [ ] Revisions tab

## Implementation steps
- [ ] Install and enable https://www.drupal.org/project/block_content_revision_ui

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

### PR DESCRIPTION
**Pull request by swirtSJW**
## Description

Closes #829
Closes #5672
Closes #5102

Replaces this https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5692/ which was outdate and based on "master" which no longer exists.

## QA steps

As a CMS editor

- [x] I can edit a block (https://pr7775-juz3nh6lrhtxbxzmnzwljsgr4qt2spi5.ci.cms.va.gov/block/146)
- [x] I can click the revision tab and view existing revisions
- [x] I can click the 'revert' button to revert to a previous state
- [x] I can edit media (https://pr7775-juz3nh6lrhtxbxzmnzwljsgr4qt2spi5.ci.cms.va.gov/media/11393) and add a new revision
- [x] I can click the revision tab and view existing revisions
- [x] I can click the 'revert' button to revert to a previous state

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by swirtSJW — COMMENTED** [review]
Blocks:
image

Media: 
image

Diff works:
image

Fatal on taxonomy revisions. :( 
image

**Comment by swirtSJW** [comment]
So the error on taxonomy revisions seems to be related to existing terms vs new terms.
Existing term with a new save.
image

```
The website encountered an unexpected error. Please try again later.

InvalidArgumentException: The timestamp must be numeric. in Drupal\Component\Datetime\DateTimePlus::createFromTimestamp() (line 201 of core/lib/Drupal/Component/Datetime/DateTimePlus.php).
```

While a new term works fine
image

Also missing field for revision log.
image

**Comment by swirtSJW** [comment]
@msbtterswrth I think we have three choices here.
A) Remove 
   - bits enabling this for taxonomy
   -  associated perms 
   - associated perm tests
   
B) Figure out the issue and establish whether it is a defect in the module, needing an issue created and maybe a patch.  Or if it  is a problem unique to us.   Come up with plan of attack.

C) merge as is and create a defect ticket to follow up since very few people are looking at term revision history.

**Comment by msbtterswrth** [comment]
@swirtSJW, in the spirit of agile, I'm inclined to go with option c and follow up with b. Could we maybe 'hide' the revision tab until the follow up on terms?

**Comment by swirtSJW** [comment]
Looks like this need some more configuration.
As RyanS I can see revisions, but  I can not revert or do anything with them other than see the diff.
image

**Comment by swirtSJW** [comment]
@msbtterswrth  I removed the config and tests for taxonomy terms  so that issue is tabled for now and added notes in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/830.

However, in order to tick the boxed for #5672 and #5102 it is going to need perms and an update to perms tests.

**Comment by msbtterswrth** [comment]
I added some permissions and it looks like they're working as expected. Can you take a look to make sure I got them all?

image

**Review by swirtSJW — COMMENTED** [review]
Works great.  Thanks @msbtterswrth

**Comment by swirtSJW** [comment]
image

**Pull request merged**
