### PR TITLE
VACMS-17381: Updates views configuration.

### PR DESCRIPTION
**Pull request by omahane**
## Description

Relates to #17381

## Testing done
Manually

### Set up QA Content Publisher
- [ ] As an [admin](https://pr17721-0fgfioq95sm0vwnbjtb66620jxfv6us0.ci.cms.va.gov/), login
  - [ ] Assign the following role to QA Content Publisher
    - [ ] Content creator - VAMC
    - [ ] Content publisher
  - [ ] Assign the following section to QA Content Publisher
    - [ ] VA Boston health care
  
### Check the top task pages as QA Content Publisher
- [ ] Login as QA Content Publisher
- [ ] Go to [Billing and Insurance](https://pr17721-0fgfioq95sm0vwnbjtb66620jxfv6us0.ci.cms.va.gov/node/45600/edit)
  - [ ] Confirm that the fields in the Billing and insurance locations listings follow the intended order
- [ ] Go to [Medical records office](https://pr17721-0fgfioq95sm0vwnbjtb66620jxfv6us0.ci.cms.va.gov/node/45726/edit)
  - [ ] Confirm that the fields in the Medical records office locations listings follow the intended order
- [ ] Go to [Register for care](https://pr17721-0fgfioq95sm0vwnbjtb66620jxfv6us0.ci.cms.va.gov/node/45852/edit)
  - [ ] Confirm that the fields in the Register for care locations listings follow the intended order

If desired, check other sections as an admin, visiting other of the following pages:
- [Billing and Insurance](https://pr17721-0fgfioq95sm0vwnbjtb66620jxfv6us0.ci.cms.va.gov/admin/content?title=&type=vamc_system_billing_insurance&moderation_state=All&owner=All)
- [Medical records office](https://pr17721-0fgfioq95sm0vwnbjtb66620jxfv6us0.ci.cms.va.gov/admin/content?title=&type=vamc_system_medical_records_offi&moderation_state=All&owner=All)
- [Register for care](https://pr17721-0fgfioq95sm0vwnbjtb66620jxfv6us0.ci.cms.va.gov/admin/content?title=&type=vamc_system_register_for_care&moderation_state=All&owner=All)

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### CODE REVIEW

**Review by laflannery — COMMENTED** [review]
@omahane My one comment is that in the ticket it says that the desired order is:

> field_building_name_number
field_wing_floor_or_room_number

With these 2 being on separate lines (at least that's what I am assuming), but I'm seeing these on the same line in all 3 content types:
Screenshot 2024-04-04 at 9 47 47 AM

**Comment by omahane** [comment]
> @omahane My one comment is that in the ticket it says that the desired order is:
> 
> > field_building_name_number
> > field_wing_floor_or_room_number
> 
> With these 2 being on separate lines (at least that's what I am assuming), but I'm seeing these on the same line in all 3 content types: Screenshot 2024-04-04 at 9 47 47 AM

@laflannery @davidmpickett This should now be fixed:
https://pr17721-0fgfioq95sm0vwnbjtb66620jxfv6us0.ci.cms.va.gov/node/45665/edit
Screenshot 2024-04-04 at 10 49 50

**Review by laflannery — APPROVED** [review]
LGTM, thanks @omahane!

**Review by srancour — APPROVED** [review]
Looks good to me.

**Review by davidmpickett — APPROVED** [review]

**Pull request merged**
