### PR TITLE
🎉  TUGBOAT MIGRATION 🎉 

### PR DESCRIPTION
**Pull request by indytechcook**
## Description

Moving the tugboat config to cms

PR from `cms-test`

* https://github.com/department-of-veterans-affairs/va.gov-cms-test/pull/182
* https://github.com/department-of-veterans-affairs/va.gov-cms-test/pull/181
* https://github.com/department-of-veterans-affairs/va.gov-cms-test/pull/180
* https://github.com/department-of-veterans-affairs/va.gov-cms-test/pull/179
* https://github.com/department-of-veterans-affairs/va.gov-cms-test/pull/177
* https://github.com/department-of-veterans-affairs/va.gov-cms-test/pull/171
* https://github.com/department-of-veterans-affairs/va.gov-cms-test/pull/170
* https://github.com/department-of-veterans-affairs/va.gov-cms-test/pull/166
* https://github.com/department-of-veterans-affairs/va.gov-cms-test/pull/165
* https://github.com/department-of-veterans-affairs/va.gov-cms-test/pull/164
* https://github.com/department-of-veterans-affairs/va.gov-cms-test/pull/163
* https://github.com/department-of-veterans-affairs/va.gov-cms-test/pull/162
* https://github.com/department-of-veterans-affairs/va.gov-cms-test/pull/161
* https://github.com/department-of-veterans-affairs/va.gov-cms-test/pull/160
* https://github.com/department-of-veterans-affairs/va.gov-cms-test/pull/159
* https://github.com/department-of-veterans-affairs/va.gov-cms-test/pull/158
* https://github.com/department-of-veterans-affairs/va.gov-cms-test/pull/157
* https://github.com/department-of-veterans-affairs/va.gov-cms-test/pull/156
* https://github.com/department-of-veterans-affairs/va.gov-cms-test/pull/151

### CODE REVIEW

**Review by ElijahLynn — DISMISSED** [review]
W00t!

Worth noting that we did all the work in this in a variety of PRs on the https://github.com/department-of-veterans-affairs/va.gov-cms-test/pulls repo.

**Comment by ElijahLynn** [comment]
I'm testing this now on Tugboat to make sure tests pass, before we switch over. Doing this on a `composer yaml-tests --dry-run` so it won't mess with test results from DevShop coming in.

**Comment by ElijahLynn** [comment]
> I'm testing this now on Tugboat to make sure tests pass, before we switch over. Doing this on a `composer yaml-tests --dry-run` so it won't mess with test results from DevShop coming in.

Passed in my test on Tugboat with the changes Neil just pushed: 
image

**Review by ElijahLynn — APPROVED** [review]

**Comment by indytechcook** [comment]
From Tugboat:

```
Executed all tests
==================
 ------------------------ ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- --------------------- 

  Test Results                                                                                                                                                                                                                                                                                                                                        
 ------------------------ ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- --------------------- 
  va/tests/phplint         composer va:test:lint                                                                                                                                                                                                                                                                                 ✔ Passed             
  va/tests/phpunit         phpunit --exclude-group disabled tests/phpunit --colors=always                                                                                                                                                                                                                                        ✔ Passed             
  va/tests/accessibility   composer va:test:accessibility                                                                                                                                                                                                                                                                        ✘ Failed (Ignoring)  
  va/web/build             composer va:web:build | tee /dev/stderr | grep "Failed to pipe Drupal content into Metalsmith!" -B1000 -C8 && echo "tests.yml | composer va:web:build included the Drupal/Metalsmith error." && exit 1 || echo "tests.yml | Front end site was built! Check $DRUPAL_ADDRESS/static for raw output!"   ✔ Passed             
  va/tests/behat           cd tests/behat                                                                                                                                                                                                                                                                                        ✔ Passed             
                           behat --colors                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                      
  va/tests/revision-log    ./tests/scripts/check-revision-logs.sh                                                                                                                                                                                                                                                                ✔ Passed             
  va/tests/status-error    drush $DRUSH_ALIAS core-requirements --severity=2 | grep . && exit 1 || echo 'Success: No Drupal status requirement errors were found.'                                                                                                                                                               ✔ Passed             
 ------------------------ ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- --------------------- 
```

**Comment by indytechcook** [comment]
Devshop passing screenshots:


AwesomeScreenshot-devshop-cms-va-gov-node-283485-2020-12-11_4_36_part1

**Pull request merged**
