### PR TITLE
VAGOV-972 Run full php units testing

### PR DESCRIPTION
**Pull request by mbenziane**

### CODE REVIEW

**Comment by mbenziane** [comment]
rebuild

**Comment by ElijahLynn** [comment]
failed because
> (service devops-vagovcms-3553) was unable to place a task because no container instance met all of its requirements. The closest matching (container-instance 70f06860-ccad-43f2-a787-182a258272fb) has insufficient memory available.

Cleaning up

**Comment by ElijahLynn** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Pull request closed without merging**
