### PR TITLE
VACMS-4335: Vet Center Community Access Point Content Type

### PR DESCRIPTION
**Pull request by kaise-lafrai**
…ontent type

## Description

See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/4335

## QA steps

- Login to preview environment
- [ ] Successfully navigate here: `/node/add/vet_center_cap`
- [ ] Confirm that the form looks like the following:

image

- [ ] Fill out the form and note the following fields:
- Vet Center: 
- Geographical Identifier: 
- [ ] Confirm the **URL alias pattern**: [field_vet_center:url_alias]/community-access-point/[title]
- [ ] Confirm the **Automatic entity title**: [Vet Center Name] - [geographical identifier]

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by kaise-lafrai** [comment]
@kevwalsh This is a draft environment to review the initial creation of the Vet Center Community Access Point content type

**Comment by kaise-lafrai** [comment]
@kevwalsh Can you please give this another look when possible? Thanks!

**Comment by swirtSJW** [comment]
Conflicted.

**Comment by kaise-lafrai** [comment]
@swirtSJW Thank you for the notice!

**Comment by swirtSJW** [comment]
@kevwalsh is this a blocker or should we follow-up later?
image

**Comment by swirtSJW** [comment]
@kevwalsh  Or this repetitive pathing ?
image

**Review by swirtSJW — APPROVED** [review]
Code looks good @kaise-lafrai 
Just waiting on tests to complete and feedback from Kev.

**Comment by swirtSJW** [comment]
Tests seem to have stalled out on this one on tugboat.   I just triggered a re-build of it.

**Pull request merged**
