### PR TITLE
VACMS-4137: Open-CLP-Field-Groups-With-Required-Empty-Field

### PR DESCRIPTION
**Pull request by kaise-lafrai**
… field group and open field groups with required empty fields

## Description

See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/4137

## QA steps

- Login to preview env.
- Navigate here: /node/15068/edit
- Leave audience field empty and keep the Why this matters fieldset closed
- Click Save
- [x] Confirm that the "Why this matters" field group is now open and field validation triggered.
- [x] Repeat the same steps as above but with different fields, open a field group, delete the value in the field, close the field group and select save.

Expected behavior
Form validation behavior should work as expected.
### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by swirtSJW — CHANGES_REQUESTED** [review]
In testing this your QA steps work, and they work with some other fieldsets, but I found at least one that does not work.   
In events clear out required "header".   Then close the fieldset and save the node.   It seems to just sit there.
image

Only if you open the fieldset does it indicate correctly that the field is required.   Same problem with the "stories", "spotlight" panel and any others that are optionally required if the panel has the checkbox to make it active..

**Comment by kaise-lafrai** [comment]
@swirtSJW Good catch - I narrowed this issue down to this field not being checked off for all the new 'Details With Image' field groups: _**Mark group as required if it contains required fields.**_. Once selected the proper classes are added and the field groups are opened up. I'll have the new config added to this ticket and pushed out for another round of testing in the morning. Thank you!

**Comment by kaise-lafrai** [comment]
@swirtSJW @kevwalsh 
This is ready for another look

**Review by kevwalsh — APPROVED** [review]
1. I went to https://pr4157-hyaoho8p1qfmpvov3dznwuj6eyfk4tfm.ci.cms.va.gov/node/15068/edit 
2. deleted the audience content
3. closed the Why this matters fieldgroup
4. Saved

Form validation message worked well, QA pass!

**Review by swirtSJW — APPROVED** [review]
I  tried multiple permutations of selecting and removing required fields and enabling and disabling panels and I could not get an unexpected response.   Nice work Kaise.

**Comment by swirtSJW** [comment]
image

**Pull request merged**
