### PR TITLE
 VACMS-5194: Change content-build repo to use source

### PR DESCRIPTION
**Pull request by indytechcook**
## Description

See #5194.   The `content-build` repo needs to use source so the branch changes work correctly.

## Testing done

Search for a branch

image

Auto-complete PR:

image

Full Build

image

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by indytechcook** [comment]
To get this to work on this tugboat branch I had to `composer nuke` then `composer install` to change the `content-build` package from dist to source.

**Comment by indytechcook** [comment]
The front end version isn't showing anymore.  I'm going to try to fix that as part of this ticket

**Comment by indytechcook** [comment]
Fixed issue with front end version display:

image

**Comment by acrollet** [comment]
I'm seeing recent PRs & branches, and the builds are completing successfully:

Screen Shot 2021-05-12 at 9 23 12 AM

Front end environment is built and functioning:

Screen Shot 2021-05-12 at 9 24 10 AM

**Review by acrollet — APPROVED** [review]

**Pull request merged**
