### PR TITLE
VACMS-14405 fix jsonapi responses

### PR DESCRIPTION
**Pull request by tjheffner**
## Description

Relates to #14405. This PR relates to next-build functionality -- the CMS's JSONAPI endpoint wasn't returning all the expected data without these two patches included. 

I also needed to remove the config for news story node's path value... something apparently related to base field override (possibly translations?) seems to mysteriously drop some fields in the json response. The BaseFieldOverride patch fixes that behavior, but the config was committed prior. Removing that config shows the path variable in the response as expected. Other content types may need their `core.base_field_override.node.NODE_TYPE.path.yml` files removed in the future for JSONAPI as well.

## Testing done
running locally, hitting a jsonapi endpoint for a news story node should include a `path` object underneath the `attributes` key:
https://va-gov-cms.ddev.site/jsonapi/node/news_story/1dbd5b1e-0fb2-43fb-8581-a2f9edfe3c83

## Screenshots
Screenshot 2023-07-13 at 1 36 34 PM

## QA steps
- What needs to be checked to prove this works?  
Visit the same endpoint without the patches from this PR applied and see that the path variable is missing.

You could also try running the next-build repo as-is. Story listing pages will fail because `entity.path.alias` is not found in the data for any of the listed news story nodes. There are other cleanup tasks pushed to that repo here: https://github.com/department-of-veterans-affairs/next-build/pull/126

- What needs to be checked to prove it didn't break any related things?  
- [ ] Do News Stories still translate as expected?
- [ ] Validate that the path of a newly created news story matches that of a newly created news story on staging.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [x] `Accelerated Publishing`

### CMS user-facing announcement
Is an announcement needed to let editors know of this change?
- [x] No announcement is needed for this code change.
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by ndouglas** [comment]
If y'all're gonna need specific things from the API, I'd like to have test coverage of those requirements so we don't inadvertently create obstacles for you, especially with things that depart from the JSON:API spec, default Drupal behavior, etc.

Could you add PHPUnit tests to perform a JSON:API request and verify that the raw response conforms to the schema that you need? 

If this is something you're not comfortable with, I can open up a followup issue and start creating tests and utility traits for this sort of thing.

Just wanna make sure we're holding up our end of the bargain 🙂

**Comment by tjheffner** [comment]
@ndouglas that is a great callout and something we will definitely want. I don't mind taking a crack at the PHPUnit tests, but do you mind if I include them in the next followup (that has updates for image styles?)

These two patches are the bare minimum right now for next-build to successfully run locally, and I'd like to get the AP team unblocked on that

**Comment by ndouglas** [comment]
@tjheffner Yeah, that's fine 🙂

**Comment by tjheffner** [comment]
Turns out there will not need to be a follow-up for image styles at this time... they're there, just moved slightly (and the missing height/width data is currently intentional, due to the "bug" the patch is fixing). I'll include a pass at schema tests in this PR.

**Comment by swirtSJW** [comment]
I added a QA step to validate the path of  news story since that override is being removed.

**Review by ndouglas — APPROVED** [review]

**Comment by ndouglas** [comment]
Story nodes aren't currently translatable. If and when they become translatable, I assume this might become an issue, but at present I'm not inclined to set up translation for the content type just to see if this breaks it 🙂 

Created a story node, nothing weird happened 🤷🏻‍♂️  Path alias unaffected.

**Comment by tjheffner** [comment]
i murdered the git history again attempting to rebase.... going to close and reopen a clean one off the updated main. ugh. sorry for the noise.

**Pull request closed without merging**
