### PR TITLE
VACMS-2551: Q&A drag and drop UX

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #2552 

## Testing done
Visual / Behat

## Screenshots
image

## QA steps
As an admin, go to `/node/add/faq_multiple_q_a` after adding 2 published Q&A nodes. Add them to the `Q&A GROUPS` fieldset, and visually verify that they are in a horizontally stacked, draggable display.

### CODE REVIEW

**Comment by oksana-c** [comment]
talked with @ethanteague about next steps in exploring alternative approaches to achieving desired drag-n-drop UX without adding an extra nested step to the Q&A form. This ticket will remain a stretch goal for Sprint 13.

**Comment by ethanteague** [comment]
> talked with @ethanteague about next steps in exploring alternative approaches to achieving desired drag-n-drop UX without adding an extra nested step to the Q&A placement form. This ticket will remain a stretch goal for Sprint 13.

This is updated, and ready for qa, @oksana-c

**Comment by swirtSJW** [comment]
@oksana-c When you have a chance can you verify this does what is needed?

**Comment by oksana-c** [comment]
@ethanteague , looks like you're in the zone on this one  🎸 
I havent checked the behavior in PR environment, but had some time to review DO moderation status patch. Here's some feedback - https://www.drupal.org/project/entity_browser_table/issues/3166953#comment-13798791

**Comment by ethanteague** [comment]
> @ethanteague , looks like you're in the zone on this one 
> I havent checked the behavior in PR environment, but had some time to review DO moderation status patch. Here's some feedback - https://www.drupal.org/project/entity_browser_table/issues/3166953#comment-13798791

Good advice, @oksana-c . Just updated the issue with a new patch :+1:

**Comment by ethanteague** [comment]
> perfect! thank you @ethanteague !

YAY!!

**Pull request merged**
