### PR TITLE
VACMS-18928-add-permission

### PR DESCRIPTION
**Pull request by davidmpickett**
## Description

Relates to #18928. 

## Testing done

Manual in tugboat 

## Screenshots

Screenshot 2024-08-15 at 1 51 21 PM

Screenshot 2024-08-15 at 1 52 46 PM

## QA steps

What needs to be checked to prove this works?
What needs to be checked to prove it didn't break any related things?
What variations of circumstances (users, actions, values) need to be checked?

As user _Joshua.Tuscher@va.gov_
1. Log in to [PR Tugboat](https://pr18958-qkxzcxenoqgw6nhcovclsixzjkak95rh.ci.cms.va.gov/)
2. Then click on the menu Manage > Content > Add content
   - [x] Validate that Full Width Alert appears
3. Create a [new Full Width Banner](https://pr18958-qkxzcxenoqgw6nhcovclsixzjkak95rh.ci.cms.va.gov/node/add/banner)
   - [x] Fill out all fields
   - [x] Save as draft

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Automated tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### CODE REVIEW

**Review by dsasser — COMMENTED** [review]
Changes look good but I found a possible issue:

As Joshua.Tuscher@va.gov, when creating a new FWB, the paths field is not editable. This is true when editing as well.

Screenshot 2024-08-21 at 8 58 50 PM
Screenshot 2024-08-21 at 8 59 02 PM

**Review by dsasser — CHANGES_REQUESTED** [review]
Requesting changes to ensure we don't get an auto-merge while we sort out the paths field concern.

**Comment by davidmpickett** [comment]
@dsasser 

Looks like that is controlled by a custom module https://github.com/department-of-veterans-affairs/va.gov-cms/blob/fe080b2efb86459900e581ea0974895c606f003c/docroot/modules/custom/va_gov_banner/src/EventSubscriber/EntityEventSubscriber.php

That really takes this out of my skills as a site builder. Probably need an engineeer to take I over

**Comment by dsasser** [comment]
@davidmpickett I added the piece to check for the homepage manager role in order to edit the paths field. This should complete this work, but we may need to change the QA steps to include testing un-happy paths.

**Review by dsasser — APPROVED** [review]

**Comment by dsasser** [comment]
> @davidmpickett any chance you could rerun the QA steps here? If not, holler and I can help toward EOD.

Looks like the auto-merge (which I didn't notice was on) merged this already.

**Pull request merged**
