### PR TITLE
[WIP] VAGOV-4945: VAMC Operating status and banner alerts.

### PR DESCRIPTION
**Pull request by kevwalsh**

### CODE REVIEW

**Comment by ElijahLynn** [comment]
These latest errors are legit, I am getting them locally on this PR too. Run `lando test` to see locally. 

*PhpUnit*
> The permissions for the content_editor do not match the expected permissions:                                       
> The permissions for the content_reviewer do not match the expected permissions 
> The permissions for the content_publisher do not match the expected permissions

*Behat*
>  Then exactly the following content entity type bundles should exist  
>  Then exactly the following fields should exist

**Comment by kevwalsh** [comment]
@ElijahLynn Yes this is WIP, mainly due to testing.

**Comment by ElijahLynn** [comment]
> @ElijahLynn Yes this is WIP, mainly due to testing.

**Comment by ElijahLynn** [comment]
I changed the base branch from `develop` to `master` as we switched our CD to be based on the GitHub Flow model (as opposed to Git Flow) and `develop` is now deprecated (https://github.com/department-of-veterans-affairs/va.gov-cms/pull/617). It may be best instead of fixing conflicts to rebase/replay your commits on top of current master:

`git fetch --all`
`git rebase origin/master`
`git push --force`

**Pull request closed without merging**
