### PR TITLE
VACMS-1073 Add menu item for user email view.

### PR DESCRIPTION
**Pull request by swirtSJW**
## Description

See #1073 . 

## Testing done
Locally

## Screenshots
image

## QA steps

As yourself
1. Visit /admin/people/ 
-[ ] Validate the 'Email list' tab is present 
1. Click that tab.  
-[ ] Validate that you see a list of email addresses.
1. Click the "Download the csv" link
- [x] validate that a txt file is downloaded.
- [ ] validate that the entries in the text file are separated by ';' to make outlook happy.

## Definition of Done
- [ ] Product release notes 
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

### CODE REVIEW

**Comment by howardbrande** [comment]
@swirtSJW the txt file downloaded but it only contained the word 'mail'

**Comment by swirtSJW** [comment]
@howardbrande   Sorry I forgot about sanitization on CI..   all the email addresses get stripped from all users.  So the list would be empty :(

If the email addresses had been there you would have seen 
```
mail
jonsmith@va.gov;
steve.wirt@civicactions.com;
Jillsmith@va.gov;
```

**Comment by howardbrande** [comment]
Ok cool! This is good to go then :-)

**Comment by howardbrande** [comment]
Just used this on PROD, looks great!

**Pull request merged**
