### PR TITLE
VAGOV-839 Support for composer caching

### PR DESCRIPTION
**Pull request by ElijahLynn**
There is a parallel PR in devops repo for this here https://github.com/department-of-veterans-affairs/va.gov-cms-devops/pull/29

### CODE REVIEW

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-151<br><br> [button_visit-site](http://pr-151.va.agile6.com)

**Comment by ElijahLynn** [comment]
Do not merge yet. Still testing.

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
First passing build consuming cache is 9m 42s (will be more noticeable in VAEC).

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
Second run was 8m40s

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
K, most recent run was 8m8s!

This is ready for merge now, but needs to be merged precisely with https://github.com/department-of-veterans-affairs/va.gov-cms-devops/pull/29

**Comment by ElijahLynn** [comment]
build

**Pull request merged**
