### PR TITLE
VACMS-4513: Disallow wysiwyg on core tax description field.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #4513

## Testing done
Visual / behat

## Screenshots
image

## QA steps

As user _uid_ with _user_role_
As an administrator, go to `taxonomy/term/94/edit` and visually verify that wysiwyg is no longer attached to description field.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by kevwalsh — COMMENTED** [review]
I'm wondering 

1. What may need to happen on vets-website before this gets merged (if anything)
2. What happens to the existing html tags in this field (like in that screenshot). Do we need a script to rip them out?

**Comment by ethanteague** [comment]
> I'm wondering
> 
> 1. What may need to happen on vets-website before this gets merged (if anything)
> 2. What happens to the existing html tags in this field (like in that screenshot). Do we need a script to rip them out?

@kevwalsh 
1) The structure of the field is not changing (at least not the way it is fetched via graphql), so nothing to change on the frontend.
2) I don't think we need to strip out the p tags (it won't cause a ruckus in the build). I think we can let the user decide if they want to remove them. That said, it wouldn't be a big deal to do a strip_tags() on the field (just don't think it's necessary).

**Comment by kevwalsh** [comment]
@ethanteague Will editors need to add `<p>` tags to get line breaks?

**Comment by ethanteague** [comment]
> @ethanteague Will editors need to add `<p>` tags to get line breaks?

Nope, @kevwalsh

**Comment by kevwalsh** [comment]
Per zoom: I think we want to consider stripping html from these (all `<p>` tags i believe) to reduce confusion for editors. I also want to manually QA that text breaks will make their way all to the FE. 

@swirtSJW

**Comment by swirtSJW** [comment]
@kevwalsh @ethanteague    Yah I think, as it is, we are creating the same kind of situation that we had with the old description field that allowed html as plain text.   IF we are opposed to html then we should run it through the plain text filter.   Otherwise people could put html in that is not being cleaned up by the wysiwYg and create bigger issues.

**Review by swirtSJW — APPROVED** [review]

**Pull request merged**
