### PR TITLE
VACMS-3468: Collect User ID via GA/GTM

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

See #3468. 

## Testing done
Added function to Behat context to concisely express the test conditions and added Behat tests for test-created users of a couple of roles.  Manually tested with my account and an anonymous account.

I'm not crazy about how the tests for the newly created users don't compare against a known sane value.

For instance, I'd prefer the test to look something like this:
```gherkin
  @user
  Scenario Outline: Google Tag Manager should be provided with an appropriate hashed UID for the current user.
    Given I am logged in as a user with the <role> role
    And I am on "/user"
    And google tag manager data layer value for "userId" should be <hashed>
    Examples:
    | uid | hashed                                          |
    | 1   | 'a4ayc_80_OGda4BO_1o_V0etpOqiLx1JwB5S3beHW0s'   |
    | 2   | '1HNeOiZeFu7gP1lxi5tdAwGcB9i2xR-Q2jpmbuwTqzU'   |
    | 3   | 'TgdAhWK-24tgzgXB3s_jrRa3IjCWfeAfZAt-Rym0n84'   |
```

But this doesn't seem to be trivially accomplishable and adding that sort of mechanism is probably outside the bounds of this issue.  I'm a Behat newbie though, so I'll cheerfully accept suggestions/modifications/demands.

## Screenshots
Screen Shot 2020-11-23 at 10 00 29 AM
Screen Shot 2020-11-23 at 11 31 31 AM

## QA steps

As any user:
1. Find your Drupal user ID.
1. Then run the following command: `lando drush eval "echo \Drupal\Component\Utility\Crypt::hashBase64('<insert your user ID here>')"` to derive a user ID as hashed by Drupal's [`hashBase64()`](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Component%21Utility%21Crypt.php/function/Crypt%3A%3AhashBase64/8.2.x) function.
1. Then load any page and enter the following in the Developer Console: `dataLayer[1].userId`
    - [ ] Validate that this value matches the hashed user ID returned by the console command in step 2.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met (involves updating GTM and GA)
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by acrollet** [comment]
@ndouglas the one thing I can think of is to add a step condition something like:

`And the google tag manager userID value for the logged in user should match the base64 hash of their uid`

I believe that with the behat Drupal context it shouldn't be too difficult to grab the user ID, but it's not something I've done in the past either. Happy to co-work on this too.

**Comment by acrollet** [comment]
@ndouglas oh jeez, that's pretty much what you already did. I'm going to finish my coffee before commenting again :p

**Comment by ndouglas** [comment]
Well, I appreciate the validation 😁

**Review by oksana-c — COMMENTED** [review]
quick 2 cents:
The goal of User ID is to be able to identify unique identifiable users (logged in).
I see on screenshots that we assign anonymous users an ID. We should only assign/send an ID for logged in users who have numeric UID that is not = 0

**Comment by ndouglas** [comment]
Yeah, good point.  Fixed.

**Review by oksana-c — APPROVED** [review]
📈 ✅

**Pull request merged**
