### PR TITLE
VACMS-15085: Eevents can break content build

### PR DESCRIPTION
**Pull request by dsasser**
## Description
Adds a new constraint to the event date field which prevents saving an event if it

Relates to #15085

## Testing done
Manual testing

## Screenshots
Screenshot 2023-09-06 at 1 57 23 PM

## QA steps
Set recurring: recur every day for 7 days, until 10/7/2023
Save draft
1. Create an event: 10/1/2023, 8-9a
2. Set recurring: recur every day for 7 days, until 10/7/2023
3. Save draft
4. Edit draft
5. Open Edit recurrences window
6. Dropdown arrow on each recurrence -> Remove recurrence
7. Save draft
   - [x] Validate an error message appears that read: 'Events cannot be created without a start and end date.'

### Definition of Done
- [x] Documentation has been updated, if applicable.
- [x] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [x] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### CODE REVIEW

**Review by chri5tia — DISMISSED** [review]

**Comment by thejordanwood** [comment]
@dsasser My only suggestion would be to change the error message to "Please enter a start and end date."

**Comment by wesrowe** [comment]
I'm feeling a disconnect between the steps to trigger the error and the error message. Is the only circumstance when this would come up that they created a recurring event with no recurrences?

**Comment by chri5tia** [comment]
@wesrowe The bug, and with this PR fix and error message, it comes up if someone creates a recurring event and then deletes all the occurrences (including the original).

**Comment by wesrowe** [comment]
We took the error message discussion [to slack](https://dsva.slack.com/archives/C52CL1PKQ/p1694191372470519?thread_ts=1694191344.621619&cid=C52CL1PKQ) for quicker resolution. Conclusion: some wordsmithed version of "A recurring event must have at least one recurrence".

**Pull request merged**
