### PR TITLE
VACMS-11455: change text color for field_label

### LINKED ISSUE #11455: Change colors of title text in CMS to Hex #212121
## Description
This is an implementation ticket for https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10071.

In the CMS on the view screen, there are read only blocks of text. Some blocks have titles as seen in "FAQs" and "Title" in the images below. These titles are currently `#757576` which does not pass WCAG 2.0 AA color contrast requirements against the light gray `#f1f1f1` background of the surrounding block or the red background `#f9dede` if the content is set to draft.

To ensure that this text is ADA compliant against all background colors that we use, the color of this text will need to be changed to  `#212121`.

image
image

## Acceptance Criteria
- [ ] Colors of title text are changed to `#212121`
- [ ] Requires design review
- [ ] Accessibility Review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by edmund-dunn**
## Description

Closes #11455.

## Testing done
Tested locally by checking field labels on VAMC Detail page view and a FAQ page view. 

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As user _uid_ with _user_role_
1. View 3 different pieces of content on the view node
   - [ ] One of these pieces of content should be a Draft or Archived (so that is has a light red background)
   - [ ] One of these pieces of content should have a read-only text block (i.e. VAMC Facility)
   - [ ] Validate that the field labels have a color of color: var(--va-gray-darkest)
   - [ ] Run an axe check on these pages and verify that no color contrast issues are flagged for these field label elements

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by laflannery — APPROVED** [review]
Looks good!

**Review by BlakeOrgan — APPROVED** [review]
Approved!

**Review by ndouglas — APPROVED** [review]
1. View 3 different pieces of content on the view node
   - [x] One of these pieces of content should be a Draft or Archived (so that is has a light red background)
   - [x] One of these pieces of content should have a read-only text block (i.e. VAMC Facility)
   - [x] Validate that the field labels have a color of color: var(--va-gray-darkest)
   - [x] Run an axe check on these pages and verify that no color contrast issues are flagged for these field label elements


Screen Shot 2023-01-18 at 9 05 57 AM

Screen Shot 2023-01-18 at 9 09 16 AM

Screen Shot 2023-01-18 at 9 09 44 AM

Screen Shot 2023-01-18 at 9 06 22 AM

Screen Shot 2023-01-18 at 9 08 34 AM

**Review by EWashb — APPROVED** [review]
Looks good!

**Pull request merged**
