### PR TITLE
VACMS-2934: Add html cleanup to table field.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #2934 

## Testing done
Visual / behat

## QA steps
- As an administrator, go to /node/471/edit
- In Main content section, add a table paragraph
- Enter content with broken html tags in multiple cells
- Save form, and confirm table displays properly on node save
- Return to edit form, and confirm broken html has been cured in table cells

### CODE REVIEW

**Comment by swirtSJW** [comment]
Waiting for PR environment for hand QA.

**Comment by swirtSJW** [comment]
QA checks out great

Going in:
image


Actually saved
image



rendered:
image

**Comment by swirtSJW** [comment]
image

**Review by swirtSJW — APPROVED** [review]

**Comment by acrollet** [comment]
pretty neat that it corrects the missing end tag!

**Pull request merged**
