### PR TITLE
VACMS-11506: updated outdated content report

### LINKED ISSUE #11506: Update outdated content report with human-edited field
## Description

After the completion of #11497 and #11505, we will need to update the outdated content report to reflect the new field. The outdated content report should only account for the last human-edited content. 

## Acceptance Criteria
- [ ] refactor outdated content report to only use the last-human edited date
- [ ] refactor CSV export of outdated content to only use the last-human edited date
- [ ] update the existing "1 year outdated" filter to say "All outdated content"

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by edmund-dunn**
## Description

Closes #11506.

## Testing done
Tested locally.

## Screenshots
CleanShot 2022-12-09 at 08 16 10

## QA steps

1. Navigate to the Outdate content report under Admin Content.
   - [x] There should now be a Last Saved by an Editor column.
   - [x] Verify that the Last Saved by and Editor filter works for all choices. 
2. Then
   - [x] Verify that the CSV is generated and can be downloaded.
3. Then validate Acceptance Criteria from issue 
  - [x] refactor outdated content report to only use the last-human edited date
  - [x] refactor CSV export of outdated content to only use the last-human edited date
  - [x] update the existing "1 year outdated" filter to say "All outdated content"
  

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by ndouglas — CHANGES_REQUESTED** [review]
CSV download doesn't work for me.  Other than that, everything looks great!

**Comment by edmund-dunn** [comment]
> CSV download doesn't work for me. Other than that, everything looks great!

Fixed this with patch #18 from this issue https://www.drupal.org/project/views_data_export/issues/3189135#comment-14818885

**Review by ndouglas — APPROVED** [review]
Verified behavior matches QA steps 🙂

**Comment by EWashb** [comment]
Looks good to me! It's working for me as expected in the QA steps

**Pull request merged**
