### PR TITLE
VACMS-16300: Update audits/views for service location changes

### PR DESCRIPTION
**Pull request by Becapa**
## Description

Relates to #16300.
This can't be merged until after the `integration-service-location` branch is merged into main and validated. 

Removes the fields that will no longer be included on the facility services content type. 

## Testing done
Manually Tested

## QA steps

As an administrator
1. Browse to the Service Locations Detailed Audit (/admin/content/audit/service-locations-detailed)
   - [x] Validate that the following columns have been removed:
     - [x]  field_hservice_appt_intro_select ('OLD: Appointment intro text')
     - [x] field_hservice_appt_leadin ('OLD: Appointment lead-in text')
     - [x] field_online_scheduling_availabl ('OLD: Is online scheduling available for this service?')
     - [x] field_walk_ins_accepted ('OLD: Are walkins accepted?')
     - [x] field_phone_numbers_paragraph ('OLD: Phone number for appointments')
2. Browse to the VAMC Facility Health Services view (/admin/content/facilities/vamc-facility-health-services)
   - [x] Validate that the following columns have been removed:
     - [x] field_walk_ins_accepted ('Walkins accepted')
     - [x] field_online_scheduling_availabl ('Online scheduling')
   - [ ] Validate that the following exposed filters have been removed:
     - [x] field_walk_ins_accepted_value ('Walkins accepted')
     - [x] field_online_scheduling_availabl_value ('Online scheduling')

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.
- [ ] If there are field changes, front end output has been thoroughly checked.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by omahane — COMMENTED** [review]
This looks right and meets the ACs. 

I noticed that the "New:" in the column headers of the first view are no longer relevant after the old fields are removed. Should we change those labels?

Screenshot 2024-03-14 at 11 25 05 AM

**Comment by Becapa** [comment]
> This looks right and meets the ACs.
> 
> I noticed that the "New:" in the column headers of the first view are no longer relevant after the old fields are removed. Should we change those labels?

That makes sense to me! I'll fix those up right quick.

**Review by omahane — COMMENTED** [review]
This looks great.
Screenshot 2024-03-14 at 4 05 39 PM

We'll need to rebase this branch once `integration-service-location` is merged.

**Review by dsasser — APPROVED** [review]
Looks good!

Screenshot 2024-05-15 at 10 23 38 AM

**Pull request merged**
