### PR TITLE
VACMS-5234: Execute all steps of multi-step tasks and return errors appropriately.

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

See #5234.  This probably needs to be rewritten further, but there's an open issue for refactoring a lot of this logic.

## Testing done
Ran periodic and daily tasks and verified that exit codes of the command as a whole matched what I saw from stdout/stderr.

## Screenshots
Screen Shot 2021-05-18 at 11 52 08 AM

## QA steps

As user _uid_ with _user_role_
1. Run `[lando] task --taskfile=tasks-periodic.yml periodic` and confirm that results and exit code match acceptance criteria:
    - [ ] Task <sub>_n_ + 1</sub> from a list of periodic tasks will executed whether Task <sub>_n_</sub> succeeds or fails.
    - [ ] Exit code for the command is 0 iff all tasks pass, otherwise 1.
2. Run `[lando] task --taskfile=tasks-periodic.yml daily` and confirm that results and exit code match acceptance criteria:
    - [ ] Task <sub>_n_ + 1</sub> from a list of periodic tasks will executed whether Task <sub>_n_</sub> succeeds or fails.
    - [ ] Exit code for the command is 0 iff all tasks pass, otherwise 1.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by acrollet — APPROVED** [review]
Approach makes sense to me, I verified the same tasks are present and that a single failed task does not cancel the whole run and gives an exit code of `1` to the whole job.

**Comment by mchelen-gov** [comment]
@ndouglas ah ok, so the upstream task runner that we are wrapping in BASH trap is https://github.com/go-task/task? i wonder if they have an open issue for this problem

**Comment by ndouglas** [comment]
@mchelen-gov Yeah, that's the one.  We actually have an open issue or two right now about refactoring some of this logic out of the task files (a terrible place for this logic, for a number of reasons).  The ideal place for a decent chunk of it is within go-task itself, and they seem pretty amenable to PRs, but since this was marked as a critical defect I just focused on getting it fixed now.

**Comment by mchelen-gov** [comment]
@ndouglas ok cool, yeah do you have links to those issues? i agree it would be good to get logic out of this task file, either into go-task itself or at least a wrapper

**Comment by ndouglas** [comment]
@mchelen-gov #5087 is the one I was thinking of. (And note that its main subject of concern is [tests.yml](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/tests.yml).  pls don't judge me mike)
 
It's focused mostly on shifting the logic into a separate bash script/library, but that's mostly because I think there's room for more discovery there in terms of other things we need from the task runner that will come up when refactoring.  Right now, we're effectively using a single command to get a few different pieces of information:

- success/failure
- github status message (e.g. "Failed because there are three unmet core requirements")
- github PR comment (e.g. list of unmet core requirements)
- github line-level PR comments (syntax/static analysis checks, etc)

etc, and there might be more to come, for instance as we try to pare down the output from failing Behat or Cypress or whatever tests to post that into a GH comment while preserving the full output on Tugboat/Jenkins and streaming it.

[TL;DR](https://www.youtube.com/watch?v=Jw36ivnRHRQ)

**Pull request merged**
