### PR TITLE
VACMS-5339 vamc meta refactoring

### LINKED ISSUE #5339: Refactor metags on VAMC product to pull directly from node titles (h1s)
## User Story or Problem Statement

As a PAO, i don't want to have to specify metatags manually, they should be auto generated

## Acceptance Criteria
- [ ] For each VAMC content type (`Detail Page, Event, Event listing, VAMC system operating status, VAMC system health service, VAMC system banner alert with situation updates, VAMC system, VAMC facility health service, Story listing, Story, Staff profile, News releases listing, News release, Locations listing, Leadership listing, Health services listing, VAMC facility`)
  - [ ] "Meta title tag" (`field_meta_title`) has been removed, if it exists
  - [ ] field_meta_tags settings has been update to use the following pattern [from the style guide](https://design.va.gov/content-style-guide/seo#meta-properties): `H1 Page Title | VAMC Plain Language System Name | Veterans Affairs` eg `[node:title] | [node:field_office] | Veterans Affairs`.   Drupal will not have the Initial Casing, that will be applied in the FE. 
  - [ ] Requires design review

## Implementation steps
- [ ] Update config
- [ ] This can be merged before FE has transformed the metatag into initial case (issue forthcoming)

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
Closes #5339

## Testing done
Visual / behat

## QA steps
- As an administrator, visit content type page for each vamc (outlined in task) and visually verify field_meta_title is not present.
- As an administrator, visit admin/config/search/metatag/node and verify that Page title pattern is set to `[node:title] | [node:field_office] | Veterans Affairs`

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by swirtSJW — COMMENTED** [review]
@ethanteague  have we confirmed that `field_meta_title` is not used on the FE or in the queries?

**Comment by ethanteague** [comment]
> @ethanteague have we confirmed that `field_meta_title` is not used on the FE or in the queries?

No sir. I meant to talk with @kevwalsh about this one. Gonna put this back into draft. Sorry for the spin, @swirtSJW

**Comment by swirtSJW** [comment]
I am seeing these
https://github.com/department-of-veterans-affairs/content-build/search?q=fieldMetaTitle

**Comment by ethanteague** [comment]
> I am seeing these
> https://github.com/department-of-veterans-affairs/content-build/search?q=fieldMetaTitle

Yeah, I guess it's more of a process q.....who do I/we talk to about removing, or should I just put in a pr? Don't wanna upset the cart by jumping out of my swimlane, but it's nothing to just remove.

**Comment by ethanteague** [comment]
Once https://github.com/department-of-veterans-affairs/content-build/pull/272 is merged and deployed, we can merge this pr, @swirtSJW @kevwalsh

**Comment by ethanteague** [comment]
This is ready for merge, @kevwalsh (front end removal piece has been merged/deployed) - just lemme know if okay with you.

**Pull request merged**
