### PR TITLE
VACMS-5282: Replace button on user login form with get help link.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #5282

## Testing done
Visual / behat

## Screenshots
image

## QA steps
- As an anonymous user, go to '/' and visually verify that the `Get help` button appears, and clicking it takes you to `/help`

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by rachel-kauff** [comment]
Some feedback! cc: @ethanteague @kevwalsh 

1. **Label**: I pondered the label, I think it works for this purpose, despite how funny it sounds out of context. Natalie had a great suggestion for making the first few words of the Help Center intro text mirror the `Get help` CTA, so I'll be tweaking that paragraph accordingly.

2. **Button color:** I believe we discussed making the button color the same as the D7 admin theme primary action button. Something like # 1179BF

3. **Placement**: In the PR environment I noticed that the button still appears on /help. It should only show up on the login page. 
Screen Shot 2021-05-12 at 12 15 55 PM

**Comment by ethanteague** [comment]
Thanks for catching that button path issue, @rachel-kauff !
Updated this, and the button color.
image
image

**Comment by acrollet** [comment]
@rachel-kauff @ethanteague I just wanted to surface this issue while you're actively working on this button: #4302 
thanks!

**Comment by rachel-kauff** [comment]
@ethanteague Super! Thanks. I assume your screenshots are showing the primary button color as filtered through Ethan's special color lens? Otherwise looks great.

**Comment by rachel-kauff** [comment]
@acrollet Thanks for pointing that out. Urgh, so much 😬 with the site alerts.

**Comment by acrollet** [comment]
@rachel-kauff yeah, sorry for the churn but as long as we're touching it...

**Comment by ethanteague** [comment]
> @rachel-kauff yeah, sorry for the churn but as long as we're touching it...

Np to fix, @acrollet - will update my pr.

**Comment by acrollet** [comment]
thanks @ethanteague !

**Comment by swirtSJW** [comment]
Both this button and our previous button have 508 issues. So I don't think it is worth blocking this change.. but I did create this defect ticket https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5313

**Review by swirtSJW — DISMISSED** [review]

**Comment by ethanteague** [comment]
> Both this button and our previous button have 508 issues. So I don't think it is worth blocking this change.. but I did create this defect ticket #5313

Good catch, @swirtSJW . Updated this pr to follow guidance, here: https://design.va.gov/components/action-links. Also added :focus & :hover styling.
image

**Comment by rachel-kauff** [comment]
The button placement as adjusted for the possibility of multiple site alerts is visually awkward when the site alerts aren't active, imho. I'm starting to wonder if this approach to providing help center access maybe should have been different, given the site alerts constraints, but don't want to hold up progress here, I know we're going for "good enough for now." 

PS. Some breakpointy things happening when width is reduced.

Screen Shot 2021-05-13 at 8 46 34 AM
Screen Shot 2021-05-13 at 8 46 06 AM

Screen Shot 2021-05-13 at 8 44 39 AM

**Comment by ethanteague** [comment]
@swirtSJW updated the focus treatment to match existing site pattern.

**Review by swirtSJW — APPROVED** [review]

**Review by swirtSJW — APPROVED** [review]
Looks good and meets A11y.   Seems like we have a failing test though.

**Comment by swirtSJW** [comment]
Correction:  the failing test was from the menu thing from earlier.   Rebasing and the test should pass.

**Review by swirtSJW — APPROVED** [review]

**Comment by swirtSJW** [comment]
image

**Pull request merged**
