### PR TITLE
VACMS-19077: Aging Content for News Spotlight blocks

### PR DESCRIPTION
**Pull request by dsasser**
## Description

Relates to #19077

## Testing done
Automated and manual

## Screenshots
Queued Expired/Warned News Spotlight Notifications:
Screenshot 2024-09-27 at 11 05 59 AM

### Generate Test Content
Expirable content is dependant on the content having changed 14 days ago. In order to ensure we have content to test with, I wrote a script at scripts/content/VACMS-19077-generate-test-content.php that creates 3 blocks: one expired, one in warning, and another that is neither.

- [ ] Open a [Terminal](https://tugboat.vfs.va.gov/tush/66f5d1cc6677b1a6f6781165)
- [ ] Run `drush scr scripts/content/VACMS-19077-generate-test-content.php`
- [ ] There is no output from the command.

### QA Steps
- [x] Open the [Expired View](https://pr19340-r092vpginorzsbkce2twamu5ihaauty7.ci.cms.va.gov/admin/structure/views/view/aging_content_content_block/edit/v2_news_spotlight_expired)
- [x] In the Preview section, ensure you see a block with the description: `Expirable Content Test Block:expired`
- [x] Open the [Warn View
](https://pr19340-r092vpginorzsbkce2twamu5ihaauty7.ci.cms.va.gov/admin/structure/views/view/aging_content_content_block/edit/v2_news_spotlight_warn)
- [x] In the Preview section, ensure you see a block with the description: `Expirable Content Test Block:warn`
- [x] Wait for mighnight's Cron
- [x] Check that there are two News Spotlight blocks in the Queue with the status of 'Queued' that have the same descriptions. A quick way to search is CMD+F+description from above, eg 
- [x] Check the [Captured Mail](https://tugboat.vfs.va.gov/66f5d1cb6677b1a6f678108f) on the Tugboat and ensure you see at lest two emails representing the expected notifications (tbd needs QA step improvement)

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.
- [ ] If there are field changes, front end output has been thoroughly checked.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### CODE REVIEW

**Review by jv-agile6 — APPROVED** [review]
Reviewed code quality for form and logic, and found no defects. Tested for quality by following listed step to a successful outcome. Approval granted

**Review by anantais — COMMENTED** [review]
Changes to the va_gov_notifications_moduel look good.

**Review by anantais — APPROVED** [review]
Changes to the va_gov_notifications_moduel look good.

**Review by edmund-dunn — APPROVED** [review]
I have no concerns. Nicely done!

**Pull request merged**
