### PR TITLE
VACMS-9196: Add EFF field to top of billing page.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
Relates to #9196

## Testing done
Visual / behat

## Screenshots
image

## QA steps
- [ ] As an administrator, go to `node/45650/edit` and save the node
- [ ] Visit `texas-valley-health-care/billing-and-insurance` and visually verify `Questions about copay balance` paragraph appears on top of content block inside of a tooltip fieldset.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by JayDarnell** [comment]
Something seems very wrong with the node form on this branch @ethanteague. See the following screenshots as an example. The browser on the left is editing this node on my local. The browser on the right is the tugboat environment for this PR. Something appears to be broken with the template.
Screen Shot 2022-05-27 at 2 38 28 PM
Screen Shot 2022-05-27 at 2 40 23 PM

**Comment by ethanteague** [comment]
Form weirdness, @JayDarnell - just updated.

**Review by swirtSJW — APPROVED** [review]
Not in love with the naming that we backed ourselves into with these  Top of page, above top of page.. more above top of page, but it follows the existing pattern.

**Review by JayDarnell — APPROVED** [review]
Looks good. QA passes as well.

**Pull request merged**
