### PR TITLE
VAGOV-2197 local migration tests

### PR DESCRIPTION
**Pull request by beeyayjay**
Includes:
- New tests comparing source content with the content saved to paragraphs.
- Logger to write tests, errors, and paragraph counts to csv files.
- Migration that migrates all the detail pages we'll be migrating.
- Updates to migration yamls to work with github api source.

### CODE REVIEW

**Comment by ElijahLynn** [comment]
This appears to be failing with, this may be our custom composer cache. I am testing locally now. 

```
Fatal error: Uncaught Error: Class 'Drupal\migration_tools\Event\MessageEvent' not found in /app/docroot/modules/custom/va_gov_migrate/src/EventSubscriber/MessageLogger.php on line 58

15:23:39
Error: Class 'Drupal\migration_tools\Event\MessageEvent' not found in /app/docroot/modules/custom/va_gov_migrate/src/EventSubscriber/MessageLogger.php on line 58
```

**Comment by ElijahLynn** [comment]
rebuild

**Comment by ElijahLynn** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Comment by ElijahLynn** [comment]
From Slack, that file is added by a patch:

After adding a patch we need to get composer.lock updated with `composer update drupal/migration_tools`. If that is okay, sometimes we don't want to update the module though. The way our custom composer cache is architected right now is it looks at the hash in composer.lock. If it matches it doesn't run composer install again. So the only way to get it updated is for that hash to change. composer-patches 2.0 will not have this issue but right now it doesn't update the lock file.

**Comment by ElijahLynn** [comment]
There is some documentation around this in README.md in the "Apply patches" section.

**Comment by ElijahLynn** [comment]
Odd, the last build did a clean composer install because there was no cache (expected, good) and I still see the error:
> Fatal error: Uncaught Error: Class 'Drupal\migration_tools\Event\MessageEvent' not found in /app/docroot/modules/custom/va_gov_migrate/src/EventSubscriber/MessageLogger.php on line 58

**Comment by ElijahLynn** [comment]
Blargh, another connectivity issue with debian server. 
> 503  Service Unavailable [IP: 130.89.148.14 80

Didn't create the image.

**Comment by ElijahLynn** [comment]
rebuild

**Comment by ElijahLynn** [comment]
rebuild - Rebuilding on DevOps cluster and job so I can debug private S3 fetching in the Jenkins Slave containers.

**Comment by ElijahLynn** [comment]
rebuild

**Comment by mbenziane** [comment]
Created an environment devops-vagovcms#pr-282<br><br> [button_visit-site](http://internal-devops-vagovcms-3235-1222497937.us-gov-west-1.elb.amazonaws.com)

**Comment by mbenziane** [comment]
Created an environment devops-vagovcms#pr-282<br><br> [button_visit-site](http://internal-devops-vagovcms-3769-1910388408.us-gov-west-1.elb.amazonaws.com)

**Comment by ElijahLynn** [comment]
Please rebase/merge latest `origin/develop` and this should pass now.

**Comment by ElijahLynn** [comment]
This is running against `devops` (my bad), it is effectively the same code etc right now and can be trusted if it passes. Next run will be normal run.

**Pull request merged**
