### PR TITLE
VACMS-1593: Install and enable fieldhelptext module.

### PR DESCRIPTION
**Pull request by kevwalsh**
## Description

See #1593. 

## Testing done

As admin go to /admin/structure/fieldhelptext

Edit help text for all fields on a content type:
* Click event (/admin/structure/fieldhelptext/by-bundle/node/event)
* Update help text for all event fields
* Go to /node/add/event and see your changes. 

Edit one field across all content types
* Go back to  /admin/structure/fieldhelptext
* In the Edit by Field section, click field_intro_text
* Edit the field 
* Change the field label and Description
* Open a bunch of forms that contain this field and see that your changes are there.

### CODE REVIEW

**Comment by kevwalsh** [comment]
@rachel-kauff You can do this QA at http://pr1593.ci.cms.va.gov/ ... once this gets merged, i'll create a demo environment where you'll actually do this bulk editing.

**Comment by swirtSJW** [comment]
I just resolved the conflict on composer.lock.   Just waiting on tests to pass.

**Comment by rachel-kauff** [comment]
Super cool. I played around in the test environment. Looks good to me. I assume I don't need to worry about undoing my test helptext before merging?

**Comment by swirtSJW** [comment]
Another conflict.... I'll have to rebase this to resolve the conflict.

**Pull request merged**
