### PR TITLE
VAGOV-920: Create promo blocks

### PR DESCRIPTION
**Pull request by kevwalsh**

### CODE REVIEW

**Comment by andyhawks** [comment]
@kevwalsh in this one the load balance failed to create, which can happen when there are too many pr test environments created. if there are too many outstanding pr's, merging one can free up an instance. best thing to do in cases like this for now is ping me, @ElijahLynn or @mbenziane to double-check the jenkins logs and I'll ask those guys about getting jenkins accounts to view logs for devs. .

**Comment by andyhawks** [comment]
build

**Comment by andyhawks** [comment]
@kevwalsh you'll need to update content_model.feature here to fix the conflict, but wait until @ethanteague does it for PR #72

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-73<br><br> [button_visit-site](http://pr-73.va.agile6.com)

**Pull request merged**
