### PR TITLE
VACMS-9615 Addresses and addresses.csv in audit view

### LINKED ISSUE #9615: Create an audit view of all content with geodata
## User Story or Problem Statement

As a content manager or content engineer investigating geodata issues, I want a view of all content that has addresses and/or geodata, so that i can take action to remediate issues or plan improvements.

## Acceptance Criteria

- [x] machine name `addresses` on the existing Facilities view
- [x] URL [`/admin/content/facilities/addresses`]
- [x] Menu item setting: Addresses, child tab of Facilities
- [x] limit to 100 per page, paginated
- [x] show result count in header
- [x] default columns
  - [x] Title (sortable) 
  - [x] Edit button (not operations, no heading) 
  - [x] Content type (sortable)
  - [x] Moderation State
  - [x] Section (field_administration) (sortable)
  - [x] Last updated (date time and by user) (sortable, default sort, DESC)
  - [x] Address, one column per field
  - [x] Lat 
  - [x] Lon
- [ ] filters
  - [x] text search (exposed)
  - [x] content type (exposed)
  - [x] moderation state (exposed)
  - [x] section (exposed) (workbench access section; single select, show children)
  - [x] Lat long filters, with operators if they exist (exposed)
  - [x] Address filters, with operators if they exist (exposed)
  - [x] Content type, allow more than one selection, but only show facility content types as options (like admin/content/facilities)
  - [x] Reset button exists
  - [x] Apply button says 'Filter'
- [ ] CSV export, per [Views style guide](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1740472321/CMS+Views+Style+Guide)

## Implementation steps

Drupal views config. It will probably help to start by cloning the admin/content/facilities display 

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by omahane**
## Description

Closes #9615 

## Testing done
Manual testing

## Screenshots

Screen Shot 2022-06-30 at 11 04 53 AM
Screen Shot 2022-06-30 at 11 24 54 AM

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As  a developer with the admin role
1. Navigate to https://pr9660-f7oae9lmjnt6qplu811frhcgaohoggze.ci.cms.va.gov/admin/content/facilities/addresses
   - [ ] Validate that a list of Vet Centers, their addresses and their geolocations are displaying
2. Then
   - [ ] Validate the filters work
3. Then 
   - [ ] Validate that the filters are applied when exporting the CSV that the view filters are applied to the downloaded file

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by swirtSJW** [comment]
The cypress test failure I think is a fluke

image

**Review by msbtterswrth — DISMISSED** [review]
Looks good, confirmed the filters work. This view is getting big and the tabs collapse for me now into the mobile stack, I wonder if we open a separate ticket up for investigating improvements there.

**Comment by swirtSJW** [comment]
I just pushed a change to reduce the number of options on the filters less intimidating and also shorten the query params so copying and pasting the url does not get crazy.

**Review by swirtSJW — APPROVED** [review]
Checks out good and download follows the filters of the main
image

Nice work.

**Pull request merged**
