### PR TITLE
VACMS-8485 office hours upgrade et

### LINKED ISSUE #8485: Upgrade drupal/office_hours to new version of module.
## Description
Relates to https://github.com/department-of-veterans-affairs/va.gov-cms/pull/8461

The [update to office_hours adds](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/8461) a bunch of improvements.   It will need to be tested on VAMC facilities and non-clinical  services to make sure it does not break the existing implementation.

I know for sure that one of our patches does not apply cleanly so it will need to be investigate for either re-roll or removal if it has already been merged.

## Acceptance Criteria
- [ ] Module is updated
- [ ] patch(es) not applying are resolved 
- [ ] No loss of existing functionality on  vamc facility field_office_hours
- [ ] No loss of existing functionality on non-clinical services service_location field_office_hours.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
closes #8485 
**This patch:**
1. rerolls original accessibility fix in https://www.drupal.org/project/office_hours/issues/3227169
2. addresses https://www.drupal.org/project/office_hours/issues/3227169#comment-14214820 
3. fixes an additional issue with office hours discovered during testing: leaving start / end times blank when validation is on, but start and end time requirements are not throws notices

## Testing done
Visual, composer install, behat

## Screenshots
image
image
image

## QA steps
 - [ ] As Crystal.Davis-Noble3@va.gov, go to `/node/1524/edit` and change the start value and end value of two different fields, and add a comment to a third.
 - [x] Save as published, and visually verify form successfully saves and appears as expected on node view
 - [x] Edit the field, setting the start value of one field after the end value of the same field, and visually verify form provides meaningful error messages on save.
 - [x] As an administrator, go to `/admin/structure/types/manage/health_care_local_facility/fields/node.health_care_local_facility.field_office_hours/storage` and set start and end times to required
 - [x] As Crystal.Davis-Noble3@va.gov, go to `/node/1524/edit` and visually verify at least one start date and one end date is empty on the office hours field.
 - [x] Save form, and visually verify meaningful notices appear, indicating that start and end times are required.

### CODE REVIEW

**Review by swirtSJW — APPROVED** [review]
Good - Doesn't match QA step but it she is not supposed to be able to edit times... so that is good.
image

Table field is still showing on facility health service, which is good.
image

Works as Sam
image

End before start validation works  
image

**Comment by swirtSJW** [comment]
Had to use Sam and this node for testing of editing  https://pr8515-5s399gut0dwh799t6skag2q89shd1nsb.ci.cms.va.gov/node/41988
Crystal can't edit times on facilities... which is as it should be.

**Comment by swirtSJW** [comment]
Nice work @ethanteague

**Comment by swirtSJW** [comment]
I bumped the patch to RTBC  https://www.drupal.org/project/office_hours/issues/3227169#comment-14461473

**Comment by ethanteague** [comment]
> Had to use Sam and this node for testing of editing https://pr8515-5s399gut0dwh799t6skag2q89shd1nsb.ci.cms.va.gov/node/41988 Crystal can't edit times on facilities... which is as it should be.

Argh. Sorry about that buddy. I'm trying to do a better job on my qa instructions.

**Comment by ethanteague** [comment]
> I bumped the patch to RTBC https://www.drupal.org/project/office_hours/issues/3227169#comment-14461473

Ty, sir.

**Comment by ethanteague** [comment]
> Nice work @ethanteague

@swirtSJW thanks for your eyes on this, buddy.

**Pull request merged**
