### PR TITLE
VACMS-7995: Disabled entity embed module

### LINKED ISSUE #7995: Disable Entity Embed module
## Description

This module is no longer in use and can be disabled and removed.

## Acceptance Criteria
- [x] update hook in va_gov_db uninstalls it (see existing pattern)
- [ ] Entity embed is gone

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by netboss**
- Disabled entity embed dependencies in Rich Text and Rich Text limited editors.
- Disabled Entity Embed module.
- Uninstalled Entity Embed module.
- ~Removed the "Entity Embed" module from code base via composer.~  This needs to be done in a separate PR that follows this one.

## Description

closes #7995 

## Testing done
Passes all tests

## Screenshots

**_Entity Embed_ module not listed in "Extend"**
VACMS-7995-extend-no-entity-embed-module

**No embed buttons in the "Embed buttons" admin page**
VACMS-7995-embed-buttons-local

## QA steps

As user administrator
1. Go to `/admin/modules`:
    - [ ] Search for "embed" to verify and confirm that the "Entity Embed" module is not listed
2. Go to `/admin/config/content/embed`:
    - [ ] Check that there are no embed buttons listed

See above screen shots for reference.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by netboss** [comment]
@swirtSJW 
This have been stuck running tests for a day. What should I do?

**Review by swirtSJW — CHANGES_REQUESTED** [review]
This doesn't execute an uninstall because it removes it from code before it runs any disabling of the module.  The hook_uninstall can never run because it doesn't exist.
The steps our pipeline runs are
1) build codebase from composer (which does not include entity_embed)
2) runs updb (which should be executed in an uninstall but that code is missing even though it is called out as an AC)
3) runs config import.

This needs to be broken down into 2 PRS

PR 1) performs a hook_update_n to uninstall the module, and disables the module in config


PR 2) removes the module from composer


These two PRs need to be merged once cms deploy apart.

**Comment by netboss** [comment]
@swirtSJW 
Now I'm getting this error message when trying to run `ddev drush cim` (from within this feature branch):

> The following reasons prevent the modules from being uninstalled: Provides a filter plugin that is in use in the following filter formats: <em class="placeholder">Rich Text</em>

The weird thing is that I already disabled the entity embed in the rich text WYSIWYG. See diff: config/sync/filter.format.rich_text.yml

**Comment by swirtSJW** [comment]
Because you have not uninstalled the module.  You are skipping the crucial step
image

**Comment by swirtSJW** [comment]
Steps freshly documented here 
https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/workflow.md#module-removal--uninstall

**Review by swirtSJW — APPROVED** [review]
This looks good.   Just triggered a rebuild, so I am waiting on tests to run.

**Comment by swirtSJW** [comment]
I just rebased this to re-trigger tests.

**Comment by swirtSJW** [comment]
Looks like there is a problem with an existing filter

```
> >  [error]  The following reasons prevent the modules from being uninstalled: Provides a filter plugin that is in use in the following filter formats: <em class="placeholder">Rich Text</em> 
> >  [error]  Update failed: va_gov_db_update_9002 

```
You may have to remove it from that filter format first in a different pr that goes first.

**Comment by swirtSJW** [comment]
This PR can not be merged until after #8137 lands on prod.   8137 should go out with todays CMS release.

**Review by swirtSJW — APPROVED** [review]
Looks good.

**Comment by swirtSJW** [comment]
@netboss  This looks like it is still running into issues with existing use.  It is failing on updb, so never builds.
```
 >  [notice] Update started: va_gov_db_update_9002                            
   [error]  Finished performing updates.                                       
                                                                               
   <em class="placeholder">Rich Text</em>                                      
  >  [error]  Update failed: va_gov_db_update_9002                             
   [error]  Update aborted by: va_gov_db_update_9002                           
  >  [error]  The following reasons prevent the modules from being uninstalle  
  d: Provides a filter plugin that is in use in the following filter formats:  
```

**Comment by netboss** [comment]
> @netboss This looks like it is still running into issues with existing use. It is failing on updb, so never builds.
> 
> ```
>  >  [notice] Update started: va_gov_db_update_9002                            
>    [error]  Finished performing updates.                                       
>                                                                                
>    <em class="placeholder">Rich Text</em>                                      
>   >  [error]  Update failed: va_gov_db_update_9002                             
>    [error]  Update aborted by: va_gov_db_update_9002                           
>   >  [error]  The following reasons prevent the modules from being uninstalled:
>    Provides a filter plugin that is in use in the following filter formats:  
> ```

@swirtSJW 
I rebased and updated the PR configs, ad that seemed to fix the build and tests failures issues.

**Review by swirtSJW — APPROVED** [review]
Looks good and tests are happy.  Nice work @netboss.

**Comment by swirtSJW** [comment]
image

**Pull request merged**
