### PR TITLE
VACMS-11115: Add VA Form flag Views.

### LINKED ISSUE #11115: Form audit tool: Changed Filename
## Description

Add a tab to display all "Filename changed" form flags, similar to [existing flag audit table](https://prod.cms.va.gov/admin/content/flagged?type=va_form&workbench_access_section__section=All) filtered for "VA Form" content type, but with only one flag type. Include bulk ability to clear these flags.

## Developer Notes
This is achievable by:
- Cloning the existing flagged content view (or by creating a new display on the existing view.
- Adding a Views Bulk Operation field to the display (note: this is from the Global category, not the content category, see image below)
- Patching of the flag module is required to work with VBO. I have tested the [patch](https://www.drupal.org/files/issues/2020-07-25/flag-vbo-2893259-40.patch) [from this issue](https://www.drupal.org/project/flag/issues/2893259) and it is functional.

Configuring the VBO field is a bit tricky due to the naming of some of the flag's actions.
Screen Shot 2022-10-06 at 10 44 32 AM
Screen Shot 2022-10-06 at 10 48 19 AM

## Acceptance Criteria
- [ ] New view should appear in VA Forms area: https://prod.cms.va.gov/admin/content/va-forms
- [ ] New view follows [CMS Views style guide](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1740472321/CMS+Views+Style+Guide)
- [ ] Display flags with columns
  - Title
  - Edit button
  - Content type
  - Updated (timestamp and author)
  - Moderation state
  - Section
  - Lock
  - <NEW> Form administration
- [ ] Bulk action to clear flags on selected items
- [ ] Requires PM/DM review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### LINKED ISSUE #11116: Form audit tool: New/Deleted forms
## Description

Add a tab to display all "New" form flags, and Deleted forms, similar to [existing flag audit table](https://prod.cms.va.gov/admin/content/flagged?type=va_form&workbench_access_section__section=All) filtered for "VA Form" content type, but with only one flag type. Include bulk ability to clear these flags.

## Acceptance Criteria
- [ ] New view should appear in VA Forms area: https://prod.cms.va.gov/admin/content/va-forms
- [ ] New view follows [CMS Views style guide](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1740472321/CMS+Views+Style+Guide)
- [ ] Display flags with columns
  - Title
  - Edit button
  - Content type (necessary?)
  - Updated (timestamp and author)
  - Moderation state
  - Section
  - Lock
- [ ] Bulk action to clear flags on selected items
- [ ] Requires PM/DM review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### LINKED ISSUE #11117: Form audit tool: Deleted form
## Description

Add a tab to display all "Deleted" form flags, similar to [existing flag audit table](https://prod.cms.va.gov/admin/content/flagged?type=va_form&workbench_access_section__section=All) filtered for "VA Form" content type, but with only one flag type. Include bulk ability to clear these flags.

## Acceptance Criteria
- [ ] New view should appear in VA Forms area: https://prod.cms.va.gov/admin/content/va-forms
- [ ] New view follows [CMS Views style guide](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1740472321/CMS+Views+Style+Guide)
- [ ] Display flagged forms with columns
  - Title
  - Edit button
  - Content type (?)
  - Updated (timestamp and author)
  - Moderation state
  - Section
  - Lock
- [ ] Bulk action to clear flags on selected items
- [ ] Requires PM/DM review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### LINKED ISSUE #11118: Form audit tool: Changed Title
## Description

Add a tab to display all "Changed Title" form flags, similar to [existing flag audit table](https://prod.cms.va.gov/admin/content/flagged?type=va_form&workbench_access_section__section=All) filtered for "VA Form" content type, but with only one flag type. Include bulk ability to clear these flags.

## Acceptance Criteria
- [ ] New view should appear in VA Forms area: https://prod.cms.va.gov/admin/content/va-forms
- [ ] New view follows [CMS Views style guide](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1740472321/CMS+Views+Style+Guide)
- [ ] Display flagged items with columns
  - Title
  - Edit button
  - Content type (?)
  - Updated (timestamp and author)
  - Moderation state
  - Section
  - Lock
  - Flags
  - {NEW} Form Administration
- [ ] Bulk action to clear flags on selected items
- [ ] Requires PM/DM review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by chri5tia**
## Description

Closes #11115 ~, #11118, #11117, #11116~  (no github magic if you list them like this)
Closes #11118
Closes #11117
Closes #11116

Adds 3 new views to the VA Forms content administration area: 
* Changed Filename
* Changed Title
* New and deleted forms

## Testing done:
(Updated)
- [ ] Views bulk operation clears flags
- [ ] View shows flagged items according to link tab, page title and table caption
- [ ] Title/Name filter
- [ ] Moderation state filter
- [ ] Section filter
- [ ] Form administration filter shows (VACO, VBA, VHA, NCA, OCTO)
- [ ] Edit links
- [ ] Columns match style guide order
- [ ] Custom text and rewrite tokens work: updated by, locked by, edit button

## Screenshots
Screen Shot 2022-10-19 at 4 50 54 PM

## QA steps
- [ ] New view should appear in VA Forms area: https://cms-gcjxrl4huhyj4lipesbplzfbyy2zsjcs.ci.cms.va.gov/admin/content/va-forms
- [ ]  New view follows [CMS Views style guide](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1740472321/CMS+Views+Style+Guide)
- [ ] Display flags with columns
- - [ ] Title
- - [ ] Edit button
- - [ ] Content type
- - [ ] Updated (timestamp and author)
- - [ ] Moderation state
- - [ ] Section
- - [ ] Lock
- - [ ] Form administration
- [ ]  Bulk action to clear flags on selected items and that the action matches the type of flags shown
- [ ] Requires PM/DM review
- [ ] Click on edit for one form on each tab, then go back (no need to save)
- [ ] Ensure that the form specifies that it is now locked in the lock column, for each tab
- [ ] Ensure that edited by shows author
- [ ] Check that all exposed filter views work

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by chri5tia** [comment]
Thanks for the feedback @dsasser on #11118. Applying it here first. I need this PR to deploy first because it has the patch for VBO and flags.

> Content type filter is not necessary
Removed

> Missing title/form name exposed filter per views style guide
Added

> VBO checkbox is in the far right column; should be far left column
Fixed

> Content type column is not necessary
Removed

> We should probably follow the existing practice employed by Facilities, which is to add all related product views to the same View as individual displays. See /admin/structure/views/view/facility_services/edit/content_audit_facilities?destination=/admin/content/facilities

All the form views are different displays of the "flagged" view, because they are basic duplicates of that view with small alterations. I'd rather keep it here for now, since backend changes to this should all be in the same place.

> Column order does not follow views style guide.
Fixed

> Missing moderation state filter per views style guide
Added

**Review by swirtSJW — CHANGES_REQUESTED** [review]
Noticed a couple of things

- [ ] updated is missing the user reference 

image


- [x] The edit button links are missing the node ids so the links don't function
image


- [x] The locked column does not reflect that something is locked.  Though to be honest, with how crowded the table it, we may want to consider abandoning the locked column in favor of readability
image

- [x] The last "Changed Filename" view tab is actually a Deleted View.
   - [x] The deleted should be included in the "New Form" View as that will surface the common issue of one being deleted and a duplicate created.  I suggest changing the name of the View to  "New/Deleted Forms"  

- [x] Tables need captions. (Please add captions to our style guide doc, I think it is missing.) 
image

**Comment by jilladams** [comment]
In addition to Steve's note: 
- [ ] For Flags and Lock columns, the Table header and table columns are swapped (wrong header appears on the column). 
  - [ ] Flags column header should appear over Flags field
  - [ ] Lock header should appear over Lock field, unless we remove it altogether. (I'm ok with removing.)
- [ ] Can you add Form administration as a Filter on all 4 views?


#11118 https://pr11251-gcjxrl4huhyj4lipesbplzfbyy2zsjcs.ci.cms.va.gov/admin/content/va-forms/changed-title
#11115  https://pr11251-gcjxrl4huhyj4lipesbplzfbyy2zsjcs.ci.cms.va.gov/admin/content/va-forms/changed-filename
#11117 https://pr11251-gcjxrl4huhyj4lipesbplzfbyy2zsjcs.ci.cms.va.gov/admin/content/va-forms/new-form
#11116 https://pr11251-gcjxrl4huhyj4lipesbplzfbyy2zsjcs.ci.cms.va.gov/admin/content/va-forms/deleted-form

**Comment by chri5tia** [comment]
The above comments and concerns are fixed. I realized I broke some things when I rearranged columns for the style guide. Oops! 

QA Steps:
- [ ] Click on edit for one form on each tab, then go back (no need to save)
- [ ] Ensure that the form specifies that it is now locked in the lock column, for each tab
Screen Shot 2022-10-19 at 4 31 34 PM
- [ ] Ensure that bulk operations works for each and that the action matches the type of flags shown

**Review by swirtSJW — CHANGES_REQUESTED** [review]
@chri5tia This is looking really good.   A couple things 
- [ ] Lets not surface the field name in the filter.  Filed names are only for us drupal geeks and don't have much value to others, and create more confusion.
image


- [ ] The pattern of the actions on the other Views use the pattern of <flag name> resolved
Where the new deleted breaks that pattern 
image
HOWEVER, I would also touch base quickly with @BlakeOrgan Since these are names for actions, I think they want to be phrased as an action, not a noun.  Example: "Remove Deleted flag", "Remove Filename Changed flag"  

- [ ] This one is scope creep so consult with @jilladams and @wesrowe  but I think I recall Dave suggesting this AND it is super easy to add.  I suggest removing the locked column and adding the revision log message to ALL the View displays.  I think it makes these tools even more useful than they already are.
image

**Comment by dsasser** [comment]
@chri5tia @swirtSJW quick note on the lock field in the table: lock changes are not immediately visible in the View. To replicate:
- Find an unlocked node in the View
- Edit the node in a new tab
- Refresh the View
- Notice the lock column doesn't change for the affected node
- Perform a cache clear
- Refresh the View
- Notice the lock column is now correct

This may be expected/well known, but figured I would flag it up for visibility.

**Comment by swirtSJW** [comment]
@chri5tia I see what you mean about the actions.  They are being pulled from the flag itself.
image

I think the wording of those should change, but does not have to be part of this issue.  I am spinning up another ticket now to
- [ ] Reword "Unflag link text" to describe the action.

**Comment by swirtSJW** [comment]
And if we are in removing the lock... please add the revision log message :)

**Review by dsasser — APPROVED** [review]
Approved pending changes requested by Steve Wirt.

**Comment by chri5tia** [comment]
Revision recommendations resolved, except for fixing the previous flagged view, which I think needs a lot of changes. It would be great if it matched the other views, such as column order, etc. I can fix that now.

If we decide to tackle https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11285, I can do that today.

**Comment by chri5tia** [comment]
Ready to re-pre-review while I investigate the test failures.

**Comment by chri5tia** [comment]
Hmm, why is the spec tool failing?

```
      | Flagged Content | Changed Filename | changed_filename | Page |
      | Flagged Content | Changed Title | changed_title | Page |
      | Flagged Content | Default | default | Default |
      | Flagged Content | Flagged Content | flagged_content | Page |
      | Flagged Content | New/Deleted Forms | new_deleted | Page |
```

Screen Shot 2022-10-20 at 12 31 33 PM

```
      +++ Unexpected views displays (present in Drupal, absent from specification)
      | Flagged Content | Deleted Form | deleted_form | Page |
      | Flagged Content | New Form     | new_form     | Page | (TravisCarden\BehatTableComparison\UnequalTablesException)
```

**Comment by laflannery** [comment]
Steve mentioned this issue during our scrum today so I took a look for any accessibility concerns.  I have 2 but they might be more sitewide/out of scope for this issue, just let me know and I can create separate issues if so:
1. The top header checkbox (that selects all) has a `title` attribute.  Can that be changed to `aria-label`?
image
2. The column header for the Edit link column is empty.  I had previously thought this was a sitewide issue but looking at the QA steps I saw that the Views style guides states this should not have a title which makes me think that maybe this is a per/table issue?  
   1. The style guide is not correct, all table header cells need to have content. Are you able to add content into this particular table header cell?

**Comment by chri5tia** [comment]
@laflannery I can add a header to the edit column. I am not sure about the aria-label. I need to learn more about what that is.

**Comment by laflannery** [comment]
@chri5tia Yes I will add separate ticket for the aria-label. However I'm not seeing content in the edit header? 
image

**Comment by swirtSJW** [comment]
> @chri5tia Yes I will add separate ticket for the aria-label. However I'm not seeing content in the edit header? 

This one is a little goofy.   In our style guide for Views we remove the text for the edit header, because the heading says the exact same thing as the button. Visually it is bad and listing to it in a screen reader is also bad / confusing.


@laflannery taking that into account, if you feel strongly that it should be there. we should update our [Views style guide](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1740472321/CMS+Views+Style+Guide).

**Review by dsasser — APPROVED** [review]

**Comment by laflannery** [comment]
@swirtSJW I do feel this should be addressed and updated, I had found it during my original audit I just didn't realize it was a choice that was done on purpose #9822. My reasoning behind this if it helps:

- It is definitely best practice to not have empty table headers.  My ultimate dream is to expand the cypress-axe tests to include best-practices and if/when we eventually do this, this will fail:
image
- I think the header text could be more specific than just "Edit".  It could say "Edit form link" or something similar to make it different
- The individual edit links themselves are also not great as you mentioned since each is just "edit" rather than being unique.  I have a separate issue for that #9823

**Comment by swirtSJW** [comment]
@laflannery to expand on what I mean by it "sounds bad"
If I have my readers not read the header when I tab through, sounds fine...it sounds like
- About VA Form 28-1900 link
- edit link
- 10/19/22 12:00 am EDT by CMS Migrator link

But if I set my reader to track headers, it sounds like 
- Title. About VA Form 28-1900 link
- edit. edit link
- Updated. 10/19/22 12:00 am EDT by CMS Migrator link

the edit edit can drive you bonkers.

**Review by swirtSJW — CHANGES_REQUESTED** [review]
Something broke.  The new/deleted view is empty
image

**Comment by swirtSJW** [comment]
@chri5tia not critical if you are already in the middle of the fix, but the counter should go after the filters
image

**Comment by swirtSJW** [comment]
This needs a `ddev composer install` followed by `ddev composer update --lock` to resolve the conflict on the lock file.

**Comment by jilladams** [comment]
Re-verified on https://pr11251-gcjxrl4huhyj4lipesbplzfbyy2zsjcs.ci.cms.va.gov/:
* All 3 new tabs match page contents / flags
* Edit links working on all 3 views
* Filters working on all 3 views
* Flag actions on New / Deleted are updated
* Action to remove flag is working
* Column order is consistent across all 3 views
* Headers match table contents
* Lock column is removed
* Updated column shows username
* Revision log message shows on all 3 
* Form admin filter doesn't show machine name
* New/deleted is showing table data 

Only thing I don't know how to verify is that all 3 tables have captions added. (Could someone show me that?)

**Review by swirtSJW — APPROVED** [review]
Tests out good.  Nice work.

I added a commit did a couple of barely noticeable things.

1. I removed the lock releated fields from the table as they were now all hidden.  
2. I removed the label overrides so they they could be controlled by the content on the flag, rather than config in the override on the view.  ALso it is a separate ticket needing design input https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11285
3. Rearranged the filters to move moderation state left of section.  Section and admin are somewhat paired so it makes sense to have them paired visually.

**Comment by swirtSJW** [comment]
I think the php unit test is a fluke.  
image

I am running it again

**Comment by chri5tia** [comment]
Yeah, it has to do with the database save point failing and using a previous save point. I don't think we need to worry about that.

```
1) tests\phpunit\Content\NodeLinkEnforcementFilterTest::testProcess with data set #5 ('<a href="node/230947230952309...st</a>')
Drupal\Core\Entity\EntityStorageException: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT savepoint_1 does not exist: ROLLBACK TO SAVEPOINT savepoint_1; Array
(
)
```

**Pull request merged**
