### PR TITLE
VACMS-15635: Replace help text for CLP Hero Banner

### PR DESCRIPTION
**Pull request by chri5tia**
## Description

Relates to #15635

## Testing done
Functional

## Screenshots
Screenshot 2023-10-13 at 12 44 21 PM

## QA steps

As a content admin, go to node/add/campaign_landing_page
- [x] Page title – Add a page title with sentence case capitalization. [See capitalization guidelines](https://design.va.gov/content-style-guide/capitalization)
- [x] Page introduction – Add a brief introduction that will also be used as a meta description in search results.
- [x] Hero image – Provide an image to display in the hero. Your image will be displayed at a 1:1 aspect ratio. If your image does not already match that size, specify the square crop when prompted. If you do not add a hero image, the hero banner will display as a gradient background color.

hero-banner-guide

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.
- [ ] If there are field changes, front end output has been thoroughly checked.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by dsasser — APPROVED** [review]
Looks good!

Screenshot 2023-10-16 at 12 36 40 PM

**Comment by dsasser** [comment]
Approved, but not merging due to AC specifying as much.

**Comment by chri5tia** [comment]
Screenshot 2023-10-17 at 3 31 46 PM
Put the text change in the wrong place. Fixed.

**Review by dsasser — APPROVED** [review]

**Comment by dsasser** [comment]
Per sprint planning 12/6/23, this is ok to merge.

**Pull request merged**
