### PR TITLE
VACMS-3487:  remove system fields step 2 of 3

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #3487 
Step 2 of 3. (Step 1 = remove fields from vets-web, Step 3 = remove fields from db in update hook)
Do not merge until vets-web pr https://github.com/department-of-veterans-affairs/vets-website/pull/15019 to remove fields from graphql is merged

## Testing done
VIsual / Behat (will need to update tests before changing from draft to ready for review)

## Screenshots
disabled_fields
removed_fields

## QA steps
- As as admin, go to `admin/structure/types/manage/health_care_region_page/form-display` and visually verify that `Regional Health Service Offerings.` is disabled
- As an admin, go to `admin/structure/types/manage/health_care_region_page/fields` and visually verify that Featured content and Press release blurbs fields have been removed.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review
- [ ] `Core Application Team`
- [x] `Product Support Team`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by ElijahLynn** [comment]
> Pulling side nav menus from Drupal...
> http://pr3523.ci.cms.va.gov response time: : 1875.851ms
> [
>   {
>     "message": "Cannot query field \"fieldFeaturedContentHealthser\" on type \"NodeHealthCareRegionPage\".",
>     "category": "graphql",
>     "locations": [
>       {
>         "line": 1170,
>         "column": 5
>       }
>     ]
>   },
>   {
>     "message": "Cannot query field \"fieldPressReleaseBlurb\" on type \"NodeHealthCareRegionPage\".",
>     "category": "graphql",
>     "locations": [
>       {
>         "line": 1243,
>         "column": 5
>       }
>     ]
>   }
> ]
> Error: Drupal query returned with errors
>     at getContentViaGraphQL (/var/aegir/projects/cms/pr3523/docroot/vendor/va-gov/web/src/site/stages/build/drupal/metalsmith-drupal.js:215:13)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> Failed to pipe Drupal content into Metalsmith!
> /var/aegir/projects/cms/pr3523/docroot/vendor/va-gov/web/src/site/stages/build/index.js:280
>     if (err) throw err;
>              ^

**Comment by ethanteague** [comment]
> > Pulling side nav menus from Drupal...
> > http://pr3523.ci.cms.va.gov response time: : 1875.851ms
> > [
> > {
> > "message": "Cannot query field "fieldFeaturedContentHealthser" on type "NodeHealthCareRegionPage".",
> > "category": "graphql",
> > "locations": [
> > {
> > "line": 1170,
> > "column": 5
> > }
> > ]
> > },
> > {
> > "message": "Cannot query field "fieldPressReleaseBlurb" on type "NodeHealthCareRegionPage".",
> > "category": "graphql",
> > "locations": [
> > {
> > "line": 1243,
> > "column": 5
> > }
> > ]
> > }
> > ]
> > Error: Drupal query returned with errors
> > at getContentViaGraphQL (/var/aegir/projects/cms/pr3523/docroot/vendor/va-gov/web/src/site/stages/build/drupal/metalsmith-drupal.js:215:13)
> > at process._tickCallback (internal/process/next_tick.js:68:7)
> > Failed to pipe Drupal content into Metalsmith!
> > /var/aegir/projects/cms/pr3523/docroot/vendor/va-gov/web/src/site/stages/build/index.js:280
> > if (err) throw err;
> > ^

Yep - gonna bump this up to ready for review once the front end piece that removes the query from the front end is merged in https://github.com/department-of-veterans-affairs/vets-website/pull/15019

**Review by swirtSJW — APPROVED** [review]

**Comment by swirtSJW** [comment]
@ethanteague can you resolve the conflict?

**Comment by ethanteague** [comment]
> @ethanteague can you resolve the conflict?

Updated, @swirtSJW

**Comment by ethanteague** [comment]
@swirtSJW @kevwalsh - let's hold off on merging this one. Need some clarity from facilities team about whether or not these items are needed.

**Review by swirtSJW — APPROVED** [review]
This works for me.

**Comment by ElijahLynn** [comment]
> Step 3 of 36 start: Get Drupal content
> Drupal content unavailable in local cache: /var/lib/tugboat/docroot/vendor/va-gov/web/.cache/vagovdev/drupal/pages.json
> Attempting to load Drupal content from API at https://pr3523-p7q381oisinu3dj7hqlrwv0t9zf1e4ck.ci.cms.va.gov
> https://pr3523-p7q381oisinu3dj7hqlrwv0t9zf1e4ck.ci.cms.va.gov response time: : 1.013s
> [
>   {
>     "message": "Cannot query field \"fieldFeaturedContentHealthser\" on type \"NodeHealthCareRegionPage\".",
>     "category": "graphql",
>     "locations": [
>       {
>         "line": 1170,
>         "column": 5
>       }
>     ]
>   }
> ]
> Error: Drupal query returned with errors

**Comment by ethanteague** [comment]
> > Step 3 of 36 start: Get Drupal content
> > Drupal content unavailable in local cache: /var/lib/tugboat/docroot/vendor/va-gov/web/.cache/vagovdev/drupal/pages.json
> > Attempting to load Drupal content from API at https://pr3523-p7q381oisinu3dj7hqlrwv0t9zf1e4ck.ci.cms.va.gov
> > https://pr3523-p7q381oisinu3dj7hqlrwv0t9zf1e4ck.ci.cms.va.gov response time: : 1.013s
> > [
> > {
> > "message": "Cannot query field "fieldFeaturedContentHealthser" on type "NodeHealthCareRegionPage".",
> > "category": "graphql",
> > "locations": [
> > {
> > "line": 1170,
> > "column": 5
> > }
> > ]
> > }
> > ]
> > Error: Drupal query returned with errors

@ElijahLynn looks like the cache needs to be updated. `fieldFeaturedContentHealthser` hasn't been on `NodeHealthCareRegionPage` for a while. 
image

**Comment by ethanteague** [comment]
Apologies, @ElijahLynn - put in a frontend pr to remove this: https://github.com/department-of-veterans-affairs/vets-website/pull/15351

**Comment by ElijahLynn** [comment]
> Apologies, @ElijahLynn - put in a frontend pr to remove this: https://github.com/department-of-veterans-affairs/vets-website/pull/15351

Nice, no worries, I was just making sure you saw it because we have so many false failures sometimes.

**Comment by ethanteague** [comment]
> > Step 3 of 36 start: Get Drupal content
> > Drupal content unavailable in local cache: /var/lib/tugboat/docroot/vendor/va-gov/web/.cache/vagovdev/drupal/pages.json
> > Attempting to load Drupal content from API at https://pr3523-p7q381oisinu3dj7hqlrwv0t9zf1e4ck.ci.cms.va.gov
> > https://pr3523-p7q381oisinu3dj7hqlrwv0t9zf1e4ck.ci.cms.va.gov response time: : 1.013s
> > [
> > {
> > "message": "Cannot query field "fieldFeaturedContentHealthser" on type "NodeHealthCareRegionPage".",
> > "category": "graphql",
> > "locations": [
> > {
> > "line": 1170,
> > "column": 5
> > }
> > ]
> > }
> > ]
> > Error: Drupal query returned with errors

@indytechcook @ElijahLynn this error is cured by vets-website pr https://github.com/department-of-veterans-affairs/vets-website/pull/15351 - this made it into the mix a couple of days ago, but when I do a `https://github.com/department-of-veterans-affairs/vets-website/pull/15351` I'm not getting the new vets-website version. Can you all assist?

**Comment by ElijahLynn** [comment]
> > > Step 3 of 36 start: Get Drupal content
> > > Drupal content unavailable in local cache: /var/lib/tugboat/docroot/vendor/va-gov/web/.cache/vagovdev/drupal/pages.json
> > > Attempting to load Drupal content from API at https://pr3523-p7q381oisinu3dj7hqlrwv0t9zf1e4ck.ci.cms.va.gov
> > > https://pr3523-p7q381oisinu3dj7hqlrwv0t9zf1e4ck.ci.cms.va.gov response time: : 1.013s
> > > [
> > > {
> > > "message": "Cannot query field "fieldFeaturedContentHealthser" on type "NodeHealthCareRegionPage".",
> > > "category": "graphql",
> > > "locations": [
> > > {
> > > "line": 1170,
> > > "column": 5
> > > }
> > > ]
> > > }
> > > ]
> > > Error: Drupal query returned with errors
> 
> @indytechcook @ElijahLynn this error is cured by vets-website pr https://github.com/department-of-veterans-affairs/vets-website/pull/15351 - this made it into the mix a couple of days ago, but when I do a `lando composer update va-gov/web` I'm not getting the new vets-website version. Can you all assist?

Ah yes, I had hardcoded a commit to lock it at a commit. See the commit message on the git blame for the line in composer.json for va-gov/web for revert instructions.

**Comment by indytechcook** [comment]
@ElijahLynn aren't you on vacation?  We have fixed this already.  Stay on vacation !

**Review by swirtSJW — APPROVED** [review]

**Pull request merged**
