### PR TITLE
VACMS-17019: Cleaning up config export.

### LINKED ISSUE #17019: Capture 87 config items to clean up config export
## User Story or Problem Statement

As a developer, I would like to only have the config I have changed exported during a config export, instead of 87 configuration files unrelated to my changes.

## Acceptance Criteria
- [ ] Configuration exported after a configuration change only produces files related to the change.

## Implementation steps
- Run a config export from the `main` branch
- Capture the exported config to the code base

## Screenshot
Screenshot 2024-01-24 at 3 11 59 PM

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

### PR DESCRIPTION
**Pull request by anantais**
## Description

Closes #17019
Relates to #17073

## Testing done
-downloaded latest database
-checked out and reviewed that files exported were only yml files

## Screenshots
Screenshot 2024-03-21 at 4 59 02 PM

## QA steps

What needs to be checked to prove this works?
What needs to be checked to prove it didn't break any related things?
What variations of circumstances (users, actions, values) need to be checked?

As user _uid_ with _user_role_
1. Do this
   - [ ] Verify that files are only yml changes

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.
- [ ] If there are field changes, front end output has been thoroughly checked.

### Select Team for PR review

- [x] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by edmund-dunn — APPROVED** [review]
Looks good.

**Review by omahane — CHANGES_REQUESTED** [review]
I wasn't 100% sure why there's such a big difference, but I'm seeing about 50 more items  than I was expecting. I went to look at Prod vs. Tugboat, and Prod approximately the number of the changes you have here. I'm not sure, though, that we want to capture all of these. I was thinking that it would make sense to capture the config from a local environment, as those are the once we're most likely to have to deal with when making subsequent PRs . That number is going to be closer to 90, I think.

**Comment by anantais** [comment]
@omahane - There may be more changes because this ticket also has some files changed related to the linked ticket - #17073

@edmund-dunn - I am not sure how to proceed. Could you please advise?

**Review by omahane — APPROVED** [review]
Initially missed the two ticket work this PR is doing, but I'm glad we're out of in front of additional config changes.

**Pull request merged**
