### PR TITLE
1585 facility content structure

### PR DESCRIPTION
**Pull request by kevwalsh**

### CODE REVIEW

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-138<br><br> [button_visit-site](http://pr-138.va.agile6.com)

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-138<br><br> [button_visit-site](http://pr-138.va.agile6.com)

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-138<br><br> [button_visit-site](http://pr-138.va.agile6.com)

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-138<br><br> [button_visit-site](http://pr-138.va.agile6.com)

**Comment by kevwalsh** [comment]
Merge !139 first.

**Comment by ElijahLynn** [comment]
build

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-138<br><br> [button_visit-site](http://pr-138.va.agile6.com)

**Pull request merged**
