### PR TITLE
VACMS-14971 - Cypress tugboat logs missing failure details

### PR DESCRIPTION
**Pull request by ariperez**
closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14971

### CODE REVIEW

**Comment by ariperez** [comment]
validated that this on argument re-adds cypress scripts.

Add this discussion in case we need to improve multi-reporters for cypress in the future: https://github.com/tnicola/cypress-parallel/issues/30

**Comment by ariperez** [comment]
@teeshe , that error for `va/tests/content-build-gql` is still popping up on this branch in tugboat.

tagging @edmund-dunn and @ndouglas  in case this is a known issue:
```Error: GraphQL query GetOutreachAssets has an error:

  query($onlyPublishedContent: Boolean!) {
    
  outreachAssets: nodeQuery(filter: {conditions: [{field: "type", value: "outreach_asset", field: "status", value: ["1"], enabled: $onlyPublishedContent}]}, limit: 10000) {
    entities {
      ... on NodeOutreachAsset {
        entityId
        title
        status
        changed
        fieldFormat
        fieldBenefits
        fieldDescription
        fieldListing {
          targetId
        }
        fieldMedia {
          entity {
            ... on MediaImage {
              entityBundle
              image {
                entity{
                  filesize
                }
                url
                alt
              }
            }
            ... on MediaDocument {
              entityBundle
              fieldDocument {
                entity {
                  filesize
                  url
                }
              }
            }
            ... on MediaVideo {
              entityBundle
              fieldMediaVideoEmbedField
              thumbnail {
                derivative(style: LARGE) {
                  url
                }
              }
            }
          }
        }
      }
    }
  }

  }


Error with GetOutreachAssets. Scroll up for the GraphQL query that has an error:

[
  {
    "message": "Cannot query field \"fieldBenefits\" on type \"NodeOutreachAsset\". Did you mean \"fieldMedia\", \"fieldMetaTags\", or \"fieldDescription\"?",
    "category": "graphql",
    "locations": [
      {
        "line": 12,
        "column": 9
      }
    ]
  }
]
    at parallelQuery (/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/drupal/api.js:191:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 3)
    at async Object.getAllPagesViaIndividualGraphQlQueries (/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/drupal/api.js:245:7)
    at async getContentViaGraphQL (/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/drupal/metalsmith-drupal.js:221:19)
    at async loadDrupal (/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/drupal/metalsmith-drupal.js:264:23)
    at async Ware.<anonymous> (/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/drupal/metalsmith-drupal.js:434:20)
Failed to pipe Drupal content into Metalsmith!
/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/plugins/download-assets.js:11
  throw up;
  ^

Error: GraphQL query GetOutreachAssets has an error:

  query($onlyPublishedContent: Boolean!) {
    
  outreachAssets: nodeQuery(filter: {conditions: [{field: "type", value: "outreach_asset", field: "status", value: ["1"], enabled: $onlyPublishedContent}]}, limit: 10000) {
    entities {
      ... on NodeOutreachAsset {
        entityId
        title
        status
        changed
        fieldFormat
        fieldBenefits
        fieldDescription
        fieldListing {
          targetId
        }
        fieldMedia {
          entity {
            ... on MediaImage {
              entityBundle
              image {
                entity{
                  filesize
                }
                url
                alt
              }
            }
            ... on MediaDocument {
              entityBundle
              fieldDocument {
                entity {
                  filesize
                  url
                }
              }
            }
            ... on MediaVideo {
              entityBundle
              fieldMediaVideoEmbedField
              thumbnail {
                derivative(style: LARGE) {
                  url
                }
              }
            }
          }
        }
      }
    }
  }

  }


Error with GetOutreachAssets. Scroll up for the GraphQL query that has an error:

[
  {
    "message": "Cannot query field \"fieldBenefits\" on type \"NodeOutreachAsset\". Did you mean \"fieldMedia\", \"fieldMetaTags\", or \"fieldDescription\"?",
    "category": "graphql",
    "locations": [
      {
        "line": 12,
        "column": 9
      }
    ]
  }
]
    at parallelQuery (/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/drupal/api.js:191:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 3)
    at async Object.getAllPagesViaIndividualGraphQlQueries (/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/drupal/api.js:245:7)
    at async getContentViaGraphQL (/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/drupal/metalsmith-drupal.js:221:19)
    at async loadDrupal (/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/drupal/metalsmith-drupal.js:264:23)
    at async Ware.<anonymous> (/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/drupal/metalsmith-drupal.js:434:20)
error Command failed with exit code 1.```

**Comment by teeshe** [comment]
Looks good to me.

**Review by teeshe — APPROVED** [review]

**Review by teeshe — APPROVED** [review]

**Review by ndouglas — APPROVED** [review]
Thank you! I saw that the errors were reported with more context 🙂

**Pull request merged**
