### PR TITLE
VACMS-4222: Refactor and add tests for BRD frontend build class.

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

See #4222.  Not to be confused with #4228, which is just intended to caveman-debug why the current `exec()` call is failing on BRD.

This is mostly geared toward refactoring the class into discrete, more testable methods and replacing the `exec()` call with the AWS PHP SDK.

Caveats:
- I don't have AWS access or a Jenkins API token (AFAIK), so I can't physically test whether this functions as expected.  All I can really test is that this operates how I think it operates, and in a fairly superficial manner.
- The AWS SDK uses the normal [credential chain](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials.html), so I wouldn't expect surprises in terms of retrieving and using credentials, but I don't have AWS credentials on my work computer.
- I don't have a local Jenkins installation at this time, so I can't create my own server and test this interactively to create more realistic mocks.

## Testing done
Forthcoming.

## Screenshots
Won't be interesting.

### Definition of Done
- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review
- [x] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by indytechcook — APPROVED** [review]
Remove the PHPStand stuff but this is good to go!  Nice job!

**Comment by ElijahLynn** [comment]
From Slack: 
1. Push branch to upstream (not fork)
2. Build commit (replace ref) http://jenkins.vfs.va.gov/job/builds/job/cms/
3. Deploy commit http://jenkins.vfs.va.gov/job/deploys/job/cms-vagov-dev

**Comment by ndouglas** [comment]
Verified with a deployment to vagov-dev that this works and correctly retrieves the Jenkins API token and starts the frontend build appropriately.

**Comment by ndouglas** [comment]
jeff pls

**Review by ElijahLynn — APPROVED** [review]
Approved on the Ops side. Also we tested this morning and it was working. Wait for approval from @indytechcook before merging.

**Review by indytechcook — APPROVED** [review]
@ndouglas and I have reviewed this together on the phone a few times.  This has lead to some very good code organization!

**Comment by ndouglas** [comment]
Squashed and merged because it's been waiting a loooooooong time.

**Pull request merged**
