### PR TITLE
[WIP] Tour experiment for CLP

### PR DESCRIPTION
**Pull request by kevwalsh**
## Description

See _issueid_. 

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by kevwalsh** [comment]
@rachel-kauff go to https://pr4048-uymeiisbulblb8xpwwq1dr6xrolqnck1.ci.cms.va.gov/node/add/campaign_landing_page and click the Tour button in the top right. Or enjoy this gif. 

We can use this PR environment to do some more experimentation. 

tour-module

**Comment by swirtSJW** [comment]
Note: as part of unused modules the Tour module has been removed.  It will need to be added back in if needed.

**Comment by ElijahLynn** [comment]
Is this still needed? Doing cleanup.

**Comment by rachel-kauff** [comment]
@ElijahLynn From my perspective, we don't need it any more. I got a tour of Tour, and we don't plan to implement this in the near future. Will defer to @kevwalsh though since he installed it and added all that excellent content.

**Pull request closed without merging**
