### PR TITLE
VACMS-17516 and 17518: Migrating certain Service location values to null

### PR DESCRIPTION
**Pull request by omahane**
## Description

Relates to #17516.
Relates to #17518.

## Testing done
Manually

### Making sure it works
- [x] As an admin, go to the [Service locations audit](https://pr17703-6mjk854eoun3nortmfc4mqde3bjequwc.ci.cms.va.gov/admin/content/audit/service-locations-detailed)
- [x] Compare "Are Walkins accepted?" choices across the old and new columns
  - [x] Old [blank], "2" or "Unspecified" => New [blank]
  - [x] Old "Yes" => New "Yes, with or without an appointment"
  - [x] Old "No" => New "Yes, by appointment only"
- [x] Compare online scheduling choices across the old and new columns
  - [x] Old [blank], "2" or "Unspecified" => New [blank]
  - [x] Old "Yes" => New "Yes"
  - [x] Old "No" => New "No"

### Making sure it didn't break anything
- [x] Compare Old Appointment intro text to New
  - [x] Old "Use custom text" => New "Use custom text"
  - [x] Old "Remove text" => New "Remove text"
  - [x] Old "Default text" => New "Default text"

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.
- [ ] If there are field changes, front end output has been thoroughly checked.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### Is this PR blocked by another PR?

- [x] `DO NOT MERGE`

### CODE REVIEW

**Comment by omahane** [comment]
@dsasser @edmund-dunn In addition to the work I did in 
- scripts/content/script-library.php
- va_gov_vamc/src/ServiceLocationMigration.php
- va_gov_post_api/src/Service/PostFacilityServiceVamc.php
There are additional changes from `main` that need to be brought into the integration branch.

**Review by edmund-dunn — APPROVED** [review]
Everything looked good from QA steps, code is nice and clean! Good work!

**Comment by dsasser** [comment]
I'm not seeing a "new" column for the 'Are walkins accepted?' column, just the old one:

Screenshot 2024-04-03 at 12 31 05 PM

Am I looking at the right columns?

**Comment by omahane** [comment]
> I'm not seeing a "new" column for the 'Are walkins accepted?' column, just the old one:
> 
> Screenshot 2024-04-03 at 12 31 05 PM
> 
> Am I looking at the right columns?

Great question:
Are walkins accepted?
became
Office visits

**Comment by omahane** [comment]
Screenshot 2024-04-03 at 3 30 47 PM

**Pull request merged**
