### PR TITLE
Upgrade to Drupal 9.2

### LINKED ISSUE #5936: Upgrade Drupal Core to 9.2
## Description

Upgrade Drupal Core to 9.2

## Acceptance Criteria
- [ ] Drupal is upgraded to 9.2

Drupal 9.2 change record: https://www.drupal.org/list-changes/drupal/published?keywords_description=&to_branch=9.2.x&version=&created_op=%3E%3D&created%5Bvalue%5D=&created%5Bmin%5D=&created%5Bmax%5D=

### PR DESCRIPTION
**Pull request by indytechcook**
## Description

Closes #5936. 

Drupal 9.2 change record: https://www.drupal.org/list-changes/drupal/published?keywords_description=&to_branch=9.2.x&version=&created_op=%3E%3D&created%5Bvalue%5D=&created%5Bmin%5D=&created%5Bmax%5D=

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by acrollet — COMMENTED** [review]
@indytechcook I'm not seeing that core-recommended is upgraded, am I missing it?

**Comment by indytechcook** [comment]
Issue: `/node` breadcrumb does not appear.  

image

HTML for breadcrumbs:

```
<div id="block-vagovadmin-breadcrumbs" class="block block-system block-system-breadcrumb-block">
  
    
        <nav class="breadcrumb" role="navigation" aria-labelledby="system-breadcrumb">
    <h2 id="system-breadcrumb" class="visually-hidden" style="width: 1px !important; height: 1px !important; inset: 162px auto auto 32.5156px !important;">Breadcrumb</h2>
    <ol>
          <li>
                  <a href="/">Home</a>
              </li>
          <li>
                  <a href="/node"></a>
              </li>
          <li>
                  <a href="/node/add">Add content</a>
              </li>
        </ol>
  </nav>

  </div>
```

**Comment by indytechcook** [comment]
Views fail with Drupal Spec Tool

**Comment by indytechcook** [comment]
```
      --- Missing views displays (present in specification, absent from Drupal)
      | Administration section                     | Master | default | Master |
      | Advanced Queue jobs                        | Master | default | Master |
      | Archive                                    | Master | default | Master |
      | Benefit Hub Contact Information            | Master | default | Master |
      | Benefit Hubs Categories                    | Master | default | Master |
      | Benefits hub list                          | Master | default | Master |
      | Blocks listing                             | Master | default | Master |
      | Build info                                 | Master | default | Master |
      | CMS Knowledge Base search results          | Master | default | Master |
      | Child terms                                | Master | default | Master |
      | Content                                    | Master | default | Master |
      | Content Entity Reference Source            | Master | default | Master |
      | Content entity browsers                    | Master | default | Master |
      | Content release logs                       | Master | default | Master |
      | Content served from Drupal                 | Master | default | Master |
      | Custom block entity browsers               | Master | default | Master |
      | Custom block library                       | Master | default | Master |
      | Date fields                                | Master | default | Master |
      | Detail page URL audit and bulk udpate      | Master | default | Master |
      | Facility Governance                        | Master | default | Master |
      | File browsers                              | Master | default | Master |
      | Files                                      | Master | default | Master |
      | Frontpage                                  | Master | default | Master |
      | Glossary                                   | Master | default | Master |
      | Health care service names and descriptions | Master | default | Master |
      | Image Style Warmer Warmup Files            | Master | default | Master |
      | Knowledge Base Article administration      | Master | default | Master |
      | Listing page dashboard                     | Master | default | Master |
      | Local facilities entity reference view     | Master | default | Master |
      | Locked content                             | Master | default | Master |
      | Media                                      | Master | default | Master |
      | Media library                              | Master | default | Master |
      | Moderated content                          | Master | default | Master |
      | Moderation history                         | Master | default | Master |
      | People                                     | Master | default | Master |
      | Recent content                             | Master | default | Master |
      | Redirect                                   | Master | default | Master |
      | Right sidebar latest revision              | Master | default | Master |
      | Search                                     | Master | default | Master |
      | Section administration and export          | Master | default | Master |
      | Services                                   | Master | default | Master |
      | Taxonomy entity browsers                   | Master | default | Master |
      | Taxonomy term                              | Master | default | Master |
      | User creation & editing activity           | Master | default | Master |
      | User email csv                             | Master | default | Master |
      | User history                               | Master | default | Master |
      | User history list                          | Master | default | Master |
      | Users in section                           | Master | default | Master |
      | VA Forms                                   | Master | default | Master |
      | VAMC alerts and operating statuses         | Master | default | Master |
      | VAMC operating statuses                    | Master | default | Master |
      | VAMC top task page revision histories      | Master | default | Master |
      | VAMCs                                      | Master | default | Master |
      | VHA Health service taxonomy                | Master | default | Master |
      | Vet Center facility listing                | Master | default | Master |
      | Vet centers                                | Master | default | Master |
      | Watchdog                                   | Master | default | Master |
      | Webform submissions                        | Master | default | Master |
      | Who's new                                  | Master | default | Master |
      | Who's online block                         | Master | default | Master |
      +++ Unexpected views displays (present in Drupal, absent from specification)
      | Administration section                     | Master | default | Default |
      | Advanced Queue jobs                        | Master | default | Default |
      | Archive                                    | Master | default | Default |
      | Benefit Hub Contact Information            | Master | default | Default |
      | Benefit Hubs Categories                    | Master | default | Default |
      | Benefits hub list                          | Master | default | Default |
      | Blocks listing                             | Master | default | Default |
      | Build info                                 | Master | default | Default |
      | CMS Knowledge Base search results          | Master | default | Default |
      | Child terms                                | Master | default | Default |
      | Content                                    | Master | default | Default |
      | Content Entity Reference Source            | Master | default | Default |
      | Content entity browsers                    | Master | default | Default |
      | Content release logs                       | Master | default | Default |
      | Content served from Drupal                 | Master | default | Default |
      | Custom block entity browsers               | Master | default | Default |
      | Custom block library                       | Master | default | Default |
      | Date fields                                | Master | default | Default |
      | Detail page URL audit and bulk udpate      | Master | default | Default |
      | Facility Governance                        | Master | default | Default |
      | File browsers                              | Master | default | Default |
      | Files                                      | Master | default | Default |
      | Frontpage                                  | Master | default | Default |
      | Glossary                                   | Master | default | Default |
      | Health care service names and descriptions | Master | default | Default |
      | Image Style Warmer Warmup Files            | Master | default | Default |
      | Knowledge Base Article administration      | Master | default | Default |
      | Listing page dashboard                     | Master | default | Default |
      | Local facilities entity reference view     | Master | default | Default |
      | Locked content                             | Master | default | Default |
      | Media                                      | Master | default | Default |
      | Media library                              | Master | default | Default |
      | Moderated content                          | Master | default | Default |
      | Moderation history                         | Master | default | Default |
      | People                                     | Master | default | Default |
      | Recent content                             | Master | default | Default |
      | Redirect                                   | Master | default | Default |
      | Right sidebar latest revision              | Master | default | Default |
      | Search                                      │
```

**Comment by indytechcook** [comment]
https://www.drupal.org/node/3189589 caused the Views display plugin called `Master` to `Default`

**Comment by ndouglas** [comment]
Have you considered re-exporting config IAW this? https://www.drupal.org/node/3114725

**Comment by indytechcook** [comment]
> Have you considered re-exporting config IAW this? https://www.drupal.org/node/3114725

I had.  I went against it to keep the PR smaller.  But I can see doing this again.

**Comment by ndouglas** [comment]
Maybe we could do it as a followup.  Nonessential obv but I was literally just thinking about this yesterday while trying to visually parse a difference in a config export.

**Review by ndouglas — APPROVED** [review]
I read through the change records and did not see anything that was 1) relevant to this codebase, 2) not already addressed by changes in this PR, and 3) necessary to change at this time.

**Comment by ndouglas** [comment]
These PHPStan errors are... interesting.

```
Note: Using configuration file /home/runner/work/va.gov-cms/va.gov-cms/phpstan.neon.
 ------ -------------------------------------------------------------------- 
  Line   docroot/modules/custom/va_gov_backend/va_gov_backend.install        
 ------ -------------------------------------------------------------------- 
  285    Call to method delete() on an unknown class                         
         Drupal\field\Entity\Drupal\field\FieldConfigInterface.              
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  305    Call to method delete() on an unknown class                         
         Drupal\field\Entity\Drupal\field\FieldConfigInterface.              
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  311    Call to method delete() on an unknown class                         
         Drupal\field\Entity\Drupal\field\FieldConfigInterface.              
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  361    Call to method delete() on an unknown class                         
         Drupal\field\Entity\Drupal\field\FieldConfigInterface.              
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  369    Call to method delete() on an unknown class                         
         Drupal\field\Entity\Drupal\field\FieldConfigInterface.              
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  388    Call to method delete() on an unknown class                         
         Drupal\field\Entity\Drupal\field\FieldConfigInterface.              
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
 ------ -------------------------------------------------------------------- 
```

obv there's no `Drupal\field\Entity\Drupal\field\FieldConfigInterface`, and `FieldConfigInterface` isn't even referenced in `va_gov_backend.install`.  `Drupal\field\Entity\FieldConfig` _is_ referenced, and of course it implements `Drupal\field\FieldConfigInterface`, but that stuff appears to be referenced correctly.  Poking around trying to figure out what's up.

**Comment by swirtSJW** [comment]
Can we handle the phpstan issues with just some `@var` declarations?

**Comment by ndouglas** [comment]
I'll update the branch and see if a re-run fixes it.

**Comment by ndouglas** [comment]
I was hoping it was a burp, since the code is AFAICT completely correct.  I'll add the errors to the baseline just in the interests of getting this out, then I'll try to figure out what's bedeviling PHPStan 👿

**Comment by swirtSJW** [comment]
I just added some `/** @var Drupal\field\FieldConfigInterface $field */` which seemed to solve the issue locally.

**Review by swirtSJW — APPROVED** [review]

**Pull request merged**
