### PR TITLE
VACMS 2681: Alter Redirect view to work around redirect_options behavior.

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

See #2681. 

This PR edits the displays of the Redirects view to display the redirect destination, as one would expect, rather than the "Server" or "Template" string.  I was not able to replicate the issue reported wherein edited redirects no longer worked.

## Testing done
Edited a few redirects, essentially at random, and verified that they continued to function and that the view displayed a linked destination path rather than a "Server" or "Template" string.  Also verified that edited redirects continued to function, even after clearing caches, etc.

## Screenshots
Screen Shot 2021-01-11 at 3 01 52 PM

## QA steps
As a user with admin access:
1. View the [admin redirects page](http://va-gov-cms.lndo.site/admin/config/search/redirect)
2. Then validate Acceptance Criteria from issue #2681:
    - [x] When editing a redirect,and saving it should not say "Server" in the destination. It should show the path like it did before editing.
    - [x] An edited redirect should actually redirect.

As a user with the 'Redirect Admin' role:
1. View the [non-admin redirects list](http://va-gov-cms.lndo.site/redirects-list)
2. Then validate Acceptance Criteria from issue #2681:
    - [x] When editing a redirect,and saving it should not say "Server" in the destination. It should show the path like it did before editing.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review
- [x] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by ndouglas** [comment]
@acrollet I know you have a lot going on right now, but if you have a free minute I'd appreciate a quick glance at this -- it's functionally minor and should be pretty easy.

**Comment by ndouglas** [comment]
After saving `/admin/config/search/redirect/edit/461` without changes, @acrollet reported that the redirect does not seem to work, so this means the original issue is now reproducible 🎉   And that I've wasted some time letting this sit around...

**Comment by ndouglas** [comment]
I think that the redirects are not working _before_ they're saved and then continue to not work _after_ being saved.

It's a little difficult to confirm this, given that the only redirects that provably _haven't_ been saved with `redirect_options` active (i.e. `redirect_redirect__title` IS NULL) are also redirects that function correctly.

For example, take `locations/tobyhanna-va-clinic`, which currently works.  It will continue to work after saving.

Screen Shot 2021-01-26 at 3 16 34 PM

DB row prior:
Screen Shot 2021-01-26 at 3 24 40 PM

and after:
Screen Shot 2021-01-26 at 3 25 03 PM

The default sort of this View is problematic for testing, because it sorts ascending by date:
Screen Shot 2021-01-26 at 3 30 54 PM

But I think the main issue is that these path sources have a trailing slash.  If I remove the slash, everything works -- both here and on my ex-employer's CMS that doesn't have `redirect_options` installed.

If you can confirm that, I think we're still good to go.  Minus the fact that I just lost several hours of my life that I'll never get back because of trailing slashes.

**Comment by acrollet** [comment]
I can confirm that with the trailing '/' removed, the redirect works with and without the trailing slash:

https://pr3971-0jzed8iphkaolhvtv4y3hkbcrtydwara.ci.cms.va.gov/employment/job-seekers/alternative/ and https://pr3971-0jzed8iphkaolhvtv4y3hkbcrtydwara.ci.cms.va.gov/employment/job-seekers/alternative both redirect to https://pr3971-0jzed8iphkaolhvtv4y3hkbcrtydwara.ci.cms.va.gov/careers-employment

**Review by acrollet — APPROVED** [review]

**Pull request merged**
