### PR TITLE
VAGOV-5292 CI Migration

### PR DESCRIPTION
**Pull request by ElijahLynn**
This PR is for changes required for CI Migration from Jenkins CI to DevShop CI.

### CODE REVIEW

**Comment by jonpugh** [comment]
@ElijahLynn There's nothing in this PR that's not in my other one: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/493

Can you continue any changes you think you need over there? 

Thanks

**Comment by ElijahLynn** [comment]
> @ElijahLynn There's nothing in this PR that's not in my other one: #493
> 
> Can you continue any changes you think you need over there?
> 
> Thanks

There isn't yet, but there is more in the other one, including a lightning update. I want to test more minimally in this one as the other one has too many changes that I don't think are needed for this migration.

**Comment by jonpugh** [comment]
W000t
Screenshot from 2019-08-07 13-53-33

**Comment by ElijahLynn** [comment]
rebuild

**Comment by ElijahLynn** [comment]
Testing this against current Jenkins CI now by removing devops label and `rebuild`. Also doing a deploy to DEV now of this branch as well.

**Comment by jonpugh** [comment]
Go JENKINS GO! :D

**Comment by ElijahLynn** [comment]
build

**Comment by jonpugh** [comment]
🎆🎇🎆🔥🎉🎊🎉🎈🥳💥💥💥

**Pull request merged**
