### PR TITLE
VACMS-6434: Vets-website content release integration

### LINKED ISSUE #6434: Discovery: Allow users to select a `vets-website` branch with which to build tugboat previews
## User Story or Problem Statement

As a front end developer, I need to be able to select a `vets-website` branch when building content previews on tugboat, so that I can verify new functionality works correctly and connect it to a content-build branch/pr

As an engineer on any team I am able to set up a demo environment or PR environment where I am using code from CMS, content-build, and vets-website that has not been merged to main(s) yet.

## Tasks
- [ ] Determine how `vets-website` builds actually occur, and evaluate this in light of the present content release system.
  - [ ] With what steps?
  - [ ] Are there any build tools necessary that aren't currently present on Tugboat?
  - [ ] Are there any data sources necessary that aren't currently present on Tugboat?
  - [ ] Are there any credentials or other sensitive pieces of information that aren't currently present on Tugboat?
  - [ ] Is the current form as used in `vets-website` local development suitable for Tugboat?
  - [ ] Do we need to support performing builds on current checkouts, e.g. if an engineer makes a change within Tugboat and doesn't want to push the commit upstream?
  - [ ] If not, do we need to refactor the current local/Tugboat content release process to support an extension to cover `vets-website`?
    - [ ] If so, how extensive is this? What will it involve? What is the best way of managing this?
  - [ ] Will this be complicated by the need to support changes related to Accelerated Publishing?
    - [ ] If so, how complicated?
  - [ ] Do we need to support specifying a content-build branch _and_ a `vets-website` branch?
    - [ ] If so, how is this currently managed in `vets-website`?
    - [ ] What complications does this flexibility introduce into our system?
    - [ ] How can we avoid repeating ourselves?
  - [ ] Do we need to _newly_ support local checkouts of `vets-website`?
    - [ ] How does this impact the Tugboat base preview flow?
    - [ ] How does this impact the DDEV flow?
    - [ ] How does this complicate the workflow for other environments (i.e. staging, prod)?
    - [ ] Does this have impacts for security or performance?
    - [ ] Does this introduce additional requirements for the GitHub token used in Tugboat environments?
    - [ ] How might this impact infrastructure, e.g. disk usage?
- [ ] Determine dependencies between the 'content-build' and 'vets-website' branches.
  - [ ] Because this is a deliberative process, this shouldn't often be an issue, but this might/will impact how errors need to be propagated for transparency.
- [ ] Determine the requirements for the backend implementation for managing `vets-website` builds.
  - [ ] How is this designed in a way that:
    - [ ] maximizes testability?
    - [ ] maximizes transparency to engineers?
    - [ ] propagates errors effectively?
    - [ ] is documentable and comprehensible?
    - [ ] is the least surprising?
- [ ] Are current systems well-situated to handle this?
  - [ ] What changes are needed to the `FrontendBranchAutocompleteController`?
    - [ ] Do we need to refactor it? I've somewhat anticipated this by specifying that current repo-specific services are named accordingly, but are any further changes needed?
    - [ ] How can this class be made more testable?
    - [ ] How can this class be more transparent? Do we need a progress indicator?
    - [ ] How can this class propagate errors more effectively? (Currently, errors are not reported except through the watchdog log, making the form somewhat mysterious)
- [ ] Determine the requirements for the frontend form implementation.
  - [ ] Do we need design/UX input or can we just hack something out of the current form?
  - [ ] Can the form elements be refactored in such a way that we can test those components independently?
- [ ] Determine followup actions:
  - [ ] What needs to be documented?
  - [ ] What needs to be communicated, and to whom?
  - [ ] Is any cleanup needed?

## Acceptance Criteria
- [ ] Local and Tugboat environments are able to build content previews using:
  - [ ] `main` `content-build`
  - [ ] specific `content-build` branch
  - [ ] specific `content-build` PR
  - [ ] `main` `content-build` and `main` `vets-website`
  - [ ] `main` `content-build` and specific `vets-website` branch
  - [ ] `main` `content-build` and specific `vets-website` PR
  - [ ] specific `content-build` branch and `main` `vets-website` branch
  - [ ] specific `content-build` branch and specific `vets-website` branch
  - [ ] specific `content-build` branch and specific `vets-website` PR
  - [ ] specific `content-build` PR and `main` `vets-website` branch
  - [ ] specific `content-build` PR and specific `vets-website` branch
  - [ ] specific `content-build` PR and specific `vets-website` PR
- [ ] All dependencies, data sources, tools, and credentials necessary for 'vets-website' builds are present and properly configured on Tugboat.
- [ ] All dependencies, data sources, tools, and credentials necessary for 'vets-website' builds are present and properly configured on local environments.
- [ ] All changes on BRD environments have been made and are backward-compatible.
- [ ] Staging environment (including post-deploy tests) is not adversely affected; tested on CMS-Test
- [ ] Production environment (including content release) is not adversely affected
- [ ] The system provides transparent feedback on the build process, including progress indicators and error messages.
- [ ] The new functionality does not introduce significant security risks, performance issues, or excessive disk usage.
- [ ] The change does not disrupt the regular content release system on production or local environments.
- [ ] Documentation is updated to reflect these changes and new functionality.
- [ ] All necessary parties have been communicated with about these changes.

### PR DESCRIPTION
**Pull request by ndouglas**
Closes #6434.

## QA Steps

I did the following:

### A normal build

Screenshot 2023-11-08 at 3 05 13 PM

Screenshot 2023-11-08 at 3 05 23 PM

```
Wed Nov  8 06:26:03 PM UTC 2023
content-build version: __default
vets-website version: __default
==> Starting a frontend build. This file will be updated as the build progresses.
==> Resetting VA repos to default versions
Gathering patches for root package.
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 1 install, 0 updates, 0 removals
  - Syncing va-gov/content-build (v0.0.3383) into cache
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Installing va-gov/content-build (v0.0.3383): Cloning ec4aa8360e from cache
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.
Package simplesamlphp/simplesamlphp-module-authfacebook is abandoned, you should avoid using it. No replacement was suggested.
Package simplesamlphp/simplesamlphp-module-authwindowslive is abandoned, you should avoid using it. No replacement was suggested.
Package simplesamlphp/simplesamlphp-module-oauth is abandoned, you should avoid using it. No replacement was suggested.
Package simplesamlphp/simplesamlphp-module-riak is abandoned, you should avoid using it. No replacement was suggested.
Package simplesamlphp/simplesamlphp-module-sanitycheck is abandoned, you should avoid using it. No replacement was suggested.
Package simplesamlphp/twig-configurable-i18n is abandoned, you should avoid using it. No replacement was suggested.
Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
Package twig/extensions is abandoned, you should avoid using it. No replacement was suggested.
Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.
Generating optimized autoload files
113 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
==> Using default content-build version
==> Installing yarn dependencies
> # Prepare content-build project.
> ! ./scripts/should-run-directly.sh || ./scripts/web-install.sh
/var/lib/tugboat/bin /var/lib/tugboat /var/lib/tugboat
/var/lib/tugboat /var/lib/tugboat
Found '/var/lib/tugboat/.nvmrc' with version <16.19.1>
v16.19.1 is already installed.
Now using node v16.19.1 (npm v8.19.3)
Node v16.19.1
NPM 8.19.3
Yarn 1.19.1
Installed yarn version '1.19.1' matches the required version '1.19.1'.
/var/lib/tugboat/web /var/lib/tugboat /var/lib/tugboat
Found '/var/lib/tugboat/web/.nvmrc' with version <14.15.0>
v14.15.0 is already installed.
Now using node v14.15.0 (npm v6.14.8)
yarn run v1.19.1
warning ../../../../package.json: License should be a valid SPDX license expression
$ ./script/install-repos.sh
Cloning into '../vagov-content'...
Cloning into '../vets-website'...
Cloning into '../vets-api'...
Updating files: 100% (8676/8676), done.
Done in 20.26s.
Warning: Ignoring extra certs from `/etc/pki/tls/certs/ca-bundle.crt`, load failed: error:02001002:system library:fopen:No such file or directory
yarn install v1.19.1
warning ../../../../package.json: License should be a valid SPDX license expression
[1/4] Resolving packages...
warning Resolution field "lodash@4.17.21" is incompatible with requested version "lodash@^2.4.1"
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @department-of-veterans-affairs/eslint-plugin@1.1.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@^6.5.1".
warning " > @department-of-veterans-affairs/eslint-plugin@1.1.0" has incorrect peer dependency "eslint-plugin-sonarjs@^0.12.0".
warning " > @department-of-veterans-affairs/eslint-plugin@1.1.0" has incorrect peer dependency "eslint-plugin-unicorn@^35.0.0".
warning " > @department-of-veterans-affairs/web-components@4.9.6" has unmet peer dependency "@department-of-veterans-affairs/formation@^7.0.1".
warning " > @department-of-veterans-affairs/web-components@4.9.6" has unmet peer dependency "i18next@*".
warning " > @department-of-veterans-affairs/web-components@4.9.6" has unmet peer dependency "i18next-browser-languagedetector@*".
warning " > eslint-plugin-prettier@4.0.0" has incorrect peer dependency "prettier@>=2.0.0".
warning " > mocha-snapshots@4.2.0" has incorrect peer dependency "mocha@^4.0.1".
[4/4] Building fresh packages...
$ husky install
Warning: Ignoring extra certs from `/etc/pki/tls/certs/ca-bundle.crt`, load failed: error:02001002:system library:fopen:No such file or directory
husky - Git hooks installed
Done in 12.46s.
/var/lib/tugboat /var/lib/tugboat
> ./scripts/should-run-directly.sh || ddev composer va:web:install --
==> Using default vets-website version
...
Done in 2644.99s.
/var/lib/tugboat /var/lib/tugboat
Replacing s3 address with local in generated files.
> ./scripts/should-run-directly.sh || ddev composer va:web:build --
==> Build complete
```

### A build with specified `content-build` and `vets-website` versions:

Screenshot 2023-11-08 at 2 20 22 PM

Screenshot 2023-11-08 at 2 20 31 PM

```
Wed Nov  8 07:20:33 PM UTC 2023
content-build version: 1783
vets-website version: 26628
...
==> Checking out the requested frontend version
From https://github.com/department-of-veterans-affairs/content-build
 * branch                refs/pull/1783/head -> FETCH_HEAD
Previous HEAD position was ec4aa8360 fix naked link, remove aria label, use va-link component (#1782)
HEAD is now at 314282203 Enable form 21-0966
...
==> Checking out the requested vets-website version
From https://github.com/department-of-veterans-affairs/vets-website
 * branch                  refs/pull/26628/head -> FETCH_HEAD
Note: switching to 'FETCH_HEAD'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at bbe24f57fd Reenable deep linking PACT Act test after devops change
...
Done in 2324.76s.
/var/lib/tugboat /var/lib/tugboat
Replacing s3 address with local in generated files.
> ./scripts/should-run-directly.sh || ddev composer va:web:build --
==> Build complete
```

## Automated Tests

See this video: https://pr15523-fd72c9bfvnmyedcrkvhxbnlciqgevv3m.ci.cms.va.gov/cypress/videos/platform/content_release.feature.mp4

### CODE REVIEW

**Comment by jilladams** [comment]
O M G 🎉 discovered this PR live while on a call about wow how much easier would things be if this ticket got moving. Sitewide ❤️ s Nate and the CMS team for making this happen!!

**Comment by ndouglas** [comment]
@jilladams Yeah, hoping to have this in by the end of the sprint 🙂

**Comment by ndouglas** [comment]
@jilladams No need to test anything, but I'd appreciate it if you could tell me whether this roughly matched the experience you had in mind for this functionality. If there are any small changes you'd like 😓, I could roll them into a followup ticket.

**Comment by ndouglas** [comment]
Not seeing any accessibility issues.

These two are for best practices and related to the toolbar, not my changes.

Screenshot 2023-11-08 at 3 18 01 PM

**Review by edmund-dunn — APPROVED** [review]
Nicely done! Clean!

**Comment by jilladams** [comment]
The interface makes sense, conceptually. I think the help text is confusing. I don't know if this is within our control (and it may not be worth the effort to change), but: for example, if I type `clp` in the vets-website picker:  I can select a 3 year old PR, with a deleted branch: 

Screenshot 2023-11-08 at 2 20 26 PM

PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16896
Branch: https://github.com/department-of-veterans-affairs/vets-website/tree/kelsonic-23418-campaign-mission-act-analytics

Would the build succeed if I did that? What branch would it use? ( I didn't do a content release to find out, because that takes a long time.)

Again: that may already be default behavior for the content-build picker, and I think by and large people bothering to use this field will specify a branch they care about that still exists.

**Comment by jilladams** [comment]
Nevermind - I checked the prod mirror tugboat and this is how it already is for the content-build one so: feel free to call it good enough! Woo!

**Pull request merged**
