### PR TITLE
VACMS-3738: danse workflow transitions plugin

### PR DESCRIPTION
**Pull request by acrollet**
## Description

See #3738

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by acrollet** [comment]
@indytechcook here's a WIP branch with the module re-namespaced, cleaned up and functioning to create events with the editor uid set:

Screen Shot 2021-01-12 at 5 39 00 PM

Maybe we can touch base about next steps tomorrow?

**Comment by indytechcook** [comment]
@acrollet can you change the merge to branch to https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3996

**Comment by acrollet** [comment]
Content moderation events are being generated on the preview environment:

Screen Shot 2021-01-14 at 10 10 13 AM

**Comment by acrollet** [comment]
Link to drupal project: https://www.drupal.org/project/danse_content_moderation

**Comment by acrollet** [comment]
@indytechcook I was about to remove the explicit dependency on `hook_event_dispatcher` in `composer.json` but I'd be surprised if we didn't end up using it in other places, so leaving it.

**Review by indytechcook — APPROVED** [review]

**Pull request merged**
