### PR TITLE
VACMS-10164 Fix core content landmark issue 2942404

### LINKED ISSUE #10164: Contentinfo landmark should not be nested
## Description
In the CMS, there are messages that appear at the top of the View and Edit screens (Content lock, broken links, etc.).  These messages are contained in a contentinfo landmark which is a top level landmark and should not be nested.

This also occurs on the login page with the error message on the form.

## Additional Context
I found 2 related Drupal Core issues:
- https://www.drupal.org/project/drupal/issues/2942404
- https://www.drupal.org/project/drupal/issues/3159933

## Screenshot
image

image

## Accessibility Standard

WCAG version 2.0 A, [Criterion 1.3.1](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html)

## Acceptance Criteria
- [ ] Review Drupal issues and determine if they are in fact referring to the same elements this ticket is
- [ ] Determine path forward for remediation

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by swirtSJW**
## Description

closes #10164

This is a test of the patch from this core issue  https://www.drupal.org/project/drupal/issues/2942404
It breaks our styling but I want to be sure if solves the problem before chasing the CSS issues.

## Screenshots
image

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As any loggged in user
1. go to here https://pr12929-ld5t601kxvpuxhhfie02xzscb3knvyzj.ci.cms.va.gov/minneapolis-health-care/programs/neuromuscular-disorders
   - [x] Validate that it looks the same as the design for error messages on prod. (no visual regression)
   - [x] validate that the messages region no longer contains a role-"contentinfo" and now contains a 
   ```
   role="region" aria-label="Status message"
   ```

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by swirtSJW** [comment]
@laflannery  an you check the structure of 
https://pr12929-ld5t601kxvpuxhhfie02xzscb3knvyzj.ci.cms.va.gov/minneapolis-health-care/programs/neuromuscular-disorders  and verify this solved the content landmark issue?

**Comment by swirtSJW** [comment]
That is interesting though.  When I views the source of the page raw, it is not there. 
image

hmmm more digging needed.  Something else is adding it back.

**Comment by swirtSJW** [comment]
Oh I see what is going on.  The patch fixes it for node view, but not node edit.

**Comment by swirtSJW** [comment]
The mystery deepens.  'contentinfo' does not appear in our codebase....anywhere.
image

**Comment by swirtSJW** [comment]
Bah I found it.  We were putting it back in with our design system pattern.
image

**Comment by laflannery** [comment]
I checked both View and Edit screens and also the error message on the login screen - all are updated and correct

**Review by laflannery — APPROVED** [review]

**Review by edmund-dunn — DISMISSED** [review]
I don't see any issue with this.

**Comment by edmund-dunn** [comment]
The merge conflict will need to be fixed for this to be merged.

**Comment by swirtSJW** [comment]
Resolving conflict now.
image

**Pull request merged**
