### PR TITLE
VACMS-5439: Update cta config and remove legacy validation code.

### LINKED ISSUE #5439: Update CTA component labels and required status in CLP and Resources and support
## User Story or Problem Statement

A few things interrelated things here. 

The "Call to action" (`button` paragraph) component is optional in many places, but if _is_ used, both fields should be required. On CLP (/node/add/campaign_landing_page), the CTA form is pre-loaded for hte editor. At the moment, editors are not forced to fill out both fields, but they cannot remove the component. Editors can also complete one field without the other, which cause broken links It's easy for editors to create bad links with either URL or label. As of May 24 2021, the FE will produce a broken link if editors add a label but no URL, or if they don't fill it out at all.  **Both fields should be required when a CTA is created.** 

The first CTA on CLP is required, but the second one is not. (That's intentional). However, the second one comes pre-loaded, and probably should be more of an "opt-in", because it's currently confusing.  

CTAs are mostly displayed as Action links on the FE, although they were originally displayed as buttons (before Action links came about). We have some technical debt to remove the _button_ label, which assumes to much about FE display, and use the more generic "Call to Action label. 

CTAs are currently required on Resources and Support content, but editors have found that too be too rigid. [See slack thread.](https://dsva.slack.com/archives/C01K37HRUAH/p1634090690152700).  

There's some tech debt associated with how Q&As without stand-alone URLs require CTA fields to be filled out. They are not required if it's not a stand-alone URL, but they are rquired if it is. 

<details><summary>Screenshots</summary>

## Example broken link report

Slack___vfs-platform-builds___Digital_Service___VA___4_new_items

## CLP content type

Edit_Campaign_Landing_Page_Have_questions_before_you_get_your_COVID-19_vaccine____VA_gov_CMS

Veterans_Experience_Action_Center___Veterans_Affairs

## Resources and support

Q&A content type

Create_Q_A___VA_gov_CMS

Other content types (eg Checklist)

Create_Checklist___VA_gov_CMS

## Vet Center

Featured content component has a non-required CTA. But if an editor adds a CTA, both fields should be required. 

Create_Vet_Center___VA_gov_CMS

</details>

Button paragraph is used on several content types, including Resources and support forms that already contain some custom form validation. Any additional form validation should be done carefully.  

R&S team (and Sitewide content team) may be open to un-requiring CTA on R&S content types. 

### Paragraph bundle
- [x] Set both fields in the `button` paragraph bundle to required.  
- [x] Remove "button" from the interface for `button` paragraph. The component should only say "Call to action", and the FE can determine if it's an action link or buton.  
Create_Checklist___VA_gov_CMS

### Campaign Landing Page product
- [x] Primary CTA on /node/add/campaign_landing_page should remain required, and already loaded in the form (paragraphs experimental widget setting)
- [x] Secondary CTA form on /node/add/campaign_landing_page should remain optional, but _not_ loaded in the form. (paragraphs experimental widget setting)

###  Resources and support 

- [x] Unset "required" for `field_buttons` on the following content types: Step-by-Step, Q&A, FAQ - multiple Q&As, Checklist, Media list - Videos, Media list - Images, Resources and support Detail Page, and change the field label to "Calls to action". 
- [x] Field labels should be "Calls to action" for each of these cases. 
- [x] Change the form for the above content types. so that the CTA form is not pre-loaded, but must be added by the editor by clicking an "Add a Call to action" button. (paragraphs experimental widget setting)
- [x] Remove [custom validation in va_gov_backend](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/baa59c1942ff3d81535fab58c7df1fef2eb06dfa/docroot/modules/custom/va_gov_backend/va_gov_backend.module#L474) and any associated automated tests. 

## Knowledge base and training

- [x] Check with customer service team about need to update KB articles or training. 

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
Closes #5439

## Testing done
Visual / behat

## QA steps
**CLP Functional tests:**
 - [x] As user David.conlon@va.gov (he's a content_admin, but his experience should be the same as en editor's) go to  `node/add/campaign_landing_page`
 - [x] Visually verify the `Hero` fieldset displays an open CTA (button) paragraph requiring both fields
   - [x] Visually verify that the CTA cannot be removed.
 - [x] Visually verify the `Why this matters` fieldset displays an `Add call to action` button.
   - [x] Click the button, and visually verify it loads a CTA (button) paragraph requiring both fields~~
   - [x] Visually verify that the CTA _can_ be removed.
- [x] Visually verify that CTAs cannot be collapsed

**Vet center Functional tests:**
 - [x] As user David.conlon@va.gov (he's a content_admin, but his experience should be the same as en editor's) go to  `node/add/vet_center`
 - [x] Visually verify the `Featured content` fieldset displays an `Add featured content` button.
 - [x] Click the button, and visually verify it loads a Featured content paragraph requiring both fields, and an `Add call to action` button
 - [x] Click the `Add call to action` button, and visually verify it loads a CTA (button) paragraph requiring both fields
 - [x] Visually verify that the CTA _can_ be removed.
 - [x] Visually verify that CTAs cannot be collapsed

**R&S (checklist) Functional tests:**
 - [x] As user David.conlon@va.gov (he's a content_admin, but his experience should be the same as en editor's) go to  `node/add/checklist`
 - [x] Visually verify the `Calls to action` fieldset displays an `Add call to action` button, with help text stating `Add a Call to Action button. At least 1 required. Up to 2 max.`
 - [x] Click the `Add call to action` button, and visually verify it loads a CTA (button) paragraph requiring both fields
 - [x] Visually verify that the CTA _can_ be removed.
 - [x] Visually verify that CTAs cannot be collapsed
 - [x] Visually verify that CTAs do not have "Duplicate" option available. 

**Across all 3 cases**
- [x] Visually verify that the word "button" doesn't appear anywhere in the interface. These are CTAs. "Call to action" singular, "Calls to action" plural. "Button link" should just be "Link" and "Button text" should just be "Link text".

### CODE REVIEW

**Review by kevwalsh — CHANGES_REQUESTED** [review]
Thanks for those clear instructions! 

A few change requests, i've updated the QA steps accordingly. 

One small enhancement (moving the goalposts here, but this is all about reducing UI clutter
- [x] Visually verify that CTA paragraphs cannot be collapsed in any of these situations
- [ ] Visually verify that CTA paragraphs cannot be duplicated in the R&S content types where 2 CTAs are allowed.

<details><summary>Screenshot</summary>

Create_Checklist___VA_gov_CMS

Create_Checklist___VA_gov_CMS

Manage_form_display___VA_gov_CMS



</details>

One small defect (although my ACs not very clear)

- [ ] Visually verify that the word "button" doesn't appear anywhere in the interface. These are CTAs. "Call to action" singular, "Calls to action" plural. "Button link" should just be "Link" and "Button text" should just be "Link text".

<details><summary>Screenshot</summary>

Create_Checklist___VA_gov_CMS

</details>

One stretch thing, probably it's own issue. 
- [ ] As a user who has added a paragraph to a single value paragraph field, i should not see any interface related to dragging and dropping, because it's useless and doesn't make sense.

<details><summary>Screenshot</summary>

Create_Campaign_Landing_Page___VA_gov_CMS


</details>

**Comment by ethanteague** [comment]
@kevwalsh update :+1: 
I didn't apply logic to remove the drag and drop header thing to all paragraph bundles & instances. I _did_ install a module that does it for us on a per form basis / for all of the button paragraph instances ref'd in this ticket. Happy to dig into this deeper, though!

**Comment by swirtSJW** [comment]
Conflicted.

**Comment by ethanteague** [comment]
> Conflicted.

We all are, @swirtSJW

**Review by kevwalsh — COMMENTED** [review]
QA pass! The new "Show drag and drop" option is great. i did not test this out, is the default checked/true? I would think this is something we woule want to turn off carefully.
Manage_form_display___VA_gov_CMS

**Review by kevwalsh — DISMISSED** [review]
Never mind, i checked elsewhere and see that the default is true. During demo we should highlight this opportunity to remove UI clutter elsewhere.

**Comment by ethanteague** [comment]
> QA pass! The new "Show drag and drop" option is great. i did not test this out, is the default checked/true? I would think this is something we woule want to turn off carefully.
> 
> Manage_form_display___VA_gov_CMS
> 
>   

Yep, default is true/on. I had to manually uncheck the box.

**Review by kevwalsh — APPROVED** [review]
I guess my last comment should have been an Approval. @swirtSJW over to you.

**Review by swirtSJW — APPROVED** [review]

**Pull request merged**
