### PR TITLE
VACMS-8475: Broaden styles to target all field_office hours widgets.

### LINKED ISSUE #8475: field_office_hours broken when more than one service location
## Describe the defect
When adding a second instance of a service location, the handling to remove comment labels and operations from the edit form do not extend past the first intance.
image

## To Reproduce
1. go to /node/41988/edit
2. expand the first and second instance of  field_office_hours.
3. Notice that they are not the same

## Expected behavior
When there are multiple instances of field_office_hours on the edit form, they should all look like the first one.
  - not have multiple comment labels
  - not have operations links or column heading.

 ## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

 
## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
closes #8475

## Testing done
Visual

## Screenshots
image
image

## QA steps
 - [ ] As an administrator, go to `node/41988/edit` and visually verify hours field is formatted properly (table headers, etc.)
 - [ ] Add two more service locations.
 - [ ] Visually verify first and subordinate instances show hours fields formatted properly .
 - [ ] validate node view of the same node shows days, times and comments.

### CODE REVIEW

**Review by swirtSJW — CHANGES_REQUESTED** [review]
This seems to have messed with node view.
image


Prod looks ok 
image

**Comment by ethanteague** [comment]
@swirtSJW Argh....apologies, buddy. <shame>Didn't consider node view.</shame>

**Comment by swirtSJW** [comment]
> @swirtSJW Argh....apologies, buddy. `<shame>Didn't consider node view.</shame>`

I added a QA step  :)

**Comment by ethanteague** [comment]
> > @swirtSJW Argh....apologies, buddy. `<shame>Didn't consider node view.</shame>`
> 
> I added a QA step :)

Ty buddy. Just updated / included a node view screenshot.

**Review by swirtSJW — APPROVED** [review]
All good
image


image

**Pull request merged**
