### PR TITLE
VAGOV-1654: Add and enable Graphql Metatag module.

### PR DESCRIPTION
**Pull request by beeyayjay**
This just adds and enables graphql_metatag. There will be more work on 1654, but I wanted to get this in asap so it will be available on stg when we start using it in queries on the vets-website side.

### CODE REVIEW

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-180<br><br> [button_visit-site](http://pr-180.va.agile6.com)

**Comment by andyhawks** [comment]
rebuild

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-180<br><br> [button_visit-site](http://pr-180.va.agile6.com)

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-180<br><br> [button_visit-site](http://pr-180.va.agile6.com)

**Pull request merged**
