### PR TITLE
VACMS-7260 Remove facility status migration

### LINKED ISSUE #7260: Remove facility status migrations
## Description
Now that we are down to all VAMC sites being in  full production on CMS   IT is time to remove the status migration

For clarification Lovell is still there.. but has never had any status details in its endpoint. 

## Acceptance Criteria
- [x] Remove va_node_health_care_local_facility_status from config/sync
- [x] Remove va_node_health_care_local_facility_status from va_gov_migrate config install
- [x] Remove from config/sync config/sync/migrate_plus.migration.va_node_facility_vet_centers_status.yml
- [x] Remove va_gov_migrate config install  /migrate_plus.migration.va_node_facility_vet_centers_status.yml
- [x] remove migrate_source/vet-center-facility-status.csv
- [x] remove  migration group config/sync/migrate_plus.migration_group.facility_status.yml
- [x] remove status migrations from /tasks-periodic.yml
- [x] Close all issues related to facility status migration and reference this issue in them.
- [x] facility status migration documentation is removed from readmes
- [x] Validate migrations are removed in migrate UI after config import. 
- [x] Remove migrate-map and migrate_message tables from DB in hook_update_n.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

### LINKED ISSUE #7620: Runbook for VA health connect phone request fulfillment
Once #7619 gets merged, CMS help desk should be ready to know what to do if requests come in to update the VA health connect field on the VAMC system content type. 

Dave: This will be "talk to the Facilities team"

### PR DESCRIPTION
**Pull request by swirtSJW**
## Description

closes #7260 

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As an admin
1. Go here https://pr13696-brjeattyrw3cxmu8om9kx2q7xbcpjlvi.ci.cms.va.gov/admin/structure/migrate
   - [x] Validate that there is no migration containing the word 'status'.
2. 
   - [x] In the tuboat terminal validate that the 2  map and 2 messages tables were dropped.  

image

ACs met 
image

### Is this PR blocked by another PR?

- This is blocked by the Lovell going to full state.

### CODE REVIEW

**Review by omahane — COMMENTED** [review]
Should we remove the phpunit test, too?
`tests/phpunit/Migration/VaHealthCareLocalFacilityStatusMigrationTest.php`

**Review by omahane — DISMISSED** [review]
I see no issue here. The migrations are gone. And I don't see any files except the test file that seems related to these migrations.

**Comment by swirtSJW** [comment]
Good catch on the migration test.  I'll remove that too.

**Comment by swirtSJW** [comment]
I just pushed the removal of that test.

**Comment by swirtSJW** [comment]
image

**Comment by swirtSJW** [comment]
Merging this so it will land on our prod tomorrow.

**Pull request merged**
