### PR TITLE
VACMS-3910: Add details with image fieldgroup formatter type.

### PR DESCRIPTION
**Pull request by ethanteague**
## Implementation notes
Once released to prod, will require entering the svg assets found here: https://drive.google.com/drive/u/1/folders/1wX2Ay1F8cLzRPpmrRSA3dltC4Yce_Vi4 with corresponding alt text for each svg, found here: https://www.figma.com/file/VFo6GLTHXwuyNeNCSdl2YU/CLP-visual-guides?node-id=0%3A1 on the clp form found here: /admin/structure/types/manage/campaign_landing_page/form-display

## Description
See #3910 

## Testing done
Visual / Behat

## Screenshots
image
image

## QA steps
- As an administrator, go to admin/structure/types/manage/campaign_landing_page/form-display and open up the Hero panel.
- Visually verify that it reads `Details with image`
- Add an svg from assets folder: https://drive.google.com/drive/u/1/folders/1wX2Ay1F8cLzRPpmrRSA3dltC4Yce_Vi4 to this panel, and add some alt text.
- Repeat this process for the `Why this matters` panel
- Save, then visit `node/15051/edit`
- Visually verify that the svgs appear at the top of the expanded fieldsets, and the images have the alt text you entered on the clp form.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by swirtSJW — APPROVED** [review]
Great solution Ethan.

**Comment by swirtSJW** [comment]
image

**Comment by ethanteague** [comment]
> Great solution Ethan.

Really appreciate you teaching me how to do this, @swirtSJW ! Super slick.

**Comment by kevwalsh** [comment]
I have some questions about how this works with config management and version control. 

What happens after we edit these fieldsets on prod, with config management? Will we need to sync dbs and export config again? 

Also, if we want to make changes to these images later, will there be config management? I was hoping these assets would be managed in version control so we could just swap them out and push.

**Comment by ethanteague** [comment]
> I have some questions about how this works with config management and version control.
> 
> What happens after we edit these fieldsets on prod, with config management? Will we need to sync dbs and export config again?

We will, @kevwalsh 

> Also, if we want to make changes to these images later, will there be config management? I was hoping these assets would be managed in version control so we could just swap them out and push.

We could go that way, but @swirtSJW suggested that we make this a pattern that we reuse in other places, e.g.: a new formatter.

**Comment by kevwalsh** [comment]
yeah i love this approach more generally, but instead of the config dance where images are stored as content, what about a path field, like this? 

VA_gov_Admin_Theme___VA_gov_CMS

**Comment by ethanteague** [comment]
> yeah i love this approach more generally, but instead of the config dance where images are stored as content, what about a path field, like this?
> 
> VA_gov_Admin_Theme___VA_gov_CMS
> 
> Then the files could be stored in the theme layer and version controlled.

I can do this, but this is going to make us more tied into our current theme (not that big of a deal to change when we switch to a new theme, but it's a debt we will have to pay in the future). @swirtSJW what say you?

**Comment by kevwalsh** [comment]
Hmm good point. My suggestion would mean refactoring this config when we launch a new theme. 

Or, these assets could be stored elsewhere, like in a custom module?

**Comment by ethanteague** [comment]
> Hmm good point. My suggestion would mean refactoring this config when we launch a new theme.
> 
> Or, these assets could be stored elsewhere, like in a custom module?

Well......now that we are talking, the way this logic is setup, after saving an svg to a panel, that file id and path to the file lives in config. So, a new db dump wouldn't be required across environments - it would just be a matter of doing a file sync.

**Comment by swirtSJW** [comment]
Yah it should all ride in config no problem.

**Comment by kevwalsh** [comment]
alt text too?

**Comment by ethanteague** [comment]
> alt text too?

Yep.

**Pull request merged**
