### PR TITLE
VACMS-19173: Sort content type filter on Content Search view

### PR DESCRIPTION
**Pull request by davidmpickett**
## Description

Relates to #19173

## Testing done

Manual in tugboat

## Screenshots

Screenshot 2024-09-10 at 3 42 45 PM

Screenshot 2024-09-10 at 2 20 57 PM

## QA steps

What needs to be checked to prove this works?
What needs to be checked to prove it didn't break any related things?
What variations of circumstances (users, actions, values) need to be checked?

As a Content Admin or above (e.g. david.pickett@va.gov)
1. Log into the [Tugboat](https://pr19174-cjxiqspnzmgbwxaf2nhket5cmqeykad6.ci.cms.va.gov/)
2. Then go to Content > Content Audit tools > [Content Search](https://pr19174-cjxiqspnzmgbwxaf2nhket5cmqeykad6.ci.cms.va.gov/admin/content/audit/search)
3. Look at the Content type filter and scroll through to see it's in alpha order
4. **SOLO** 
   - [ ] Select a Content type (or ctrl-click to select multiple) and click Filter
   - [ ] Validate that the results only include the selected Content Type(s)
   - [ ] Click the Reset button
5. **NULL** 
   - [ ] Perform a search using another filter (e.g. Title contains "chicago") but no Content Type selected
   - [ ] Validate that the results are not restricted by content types
   - [ ] Click the Reset button
6. **COMBO**
   - [ ] Perform a search using another filter (e.g. Title contains "chicago") & a Content Type selected (e.g. VAMC facility)
   - [ ] Validate that the results match both filter conditions
   - [ ] Click the Reset button

### Definition of Done

- [x] Automated tests have passed.
- [x] Code Quality Tests have passed.
- [x] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### CODE REVIEW

**Comment by jilladams** [comment]
QA steps check out, also tested multi-select for multiple content types. Approving!

There is one quirk that I don't think should block this PR bc it may require eng work to resolve and the work in here is a net improvement on the UX even if we don't fix this right now: the list of Content Types is alpha sorted _except_ for the first entry, which starts with M in the user friendly value, and K in the machine name, but appears atop the list:  

Screenshot 2024-09-10 at 2 05 24 PM

**Review by jilladams — APPROVED** [review]

**Comment by davidmpickett** [comment]
> QA steps check out, also tested multi-select for multiple content types. Approving!
> 
> There is one quirk that I don't think should block this PR bc it may require eng work to resolve and the work in here is a net improvement on the UX even if we don't fix this right now: the list of Content Types is alpha sorted _except_ for the first entry, which starts with M in the user friendly value, and K in the machine name, but appears atop the list:
> 
> Screenshot 2024-09-10 at 2 05 24 PM

That is a test content type that is created when lower environments are built. I think something about order of operations of how Tugboat builds might be what's bumping it out of alpha order. Agree that it shouldn't block PR given that otherwise we've made a big improvement

**Comment by jilladams** [comment]
Christian signed off: https://dsva.slack.com/archives/C0FQSS30V/p1726072919469939?thread_ts=1726072832.206209&cid=C0FQSS30V.  Enabled auto-merge, so once it passes tests again, it should merge.

**Review by omahane — APPROVED** [review]
I agree that this is an improvement, but I also noticed the same issue of the first item being out of order. But it seems to change which one it is. 

Before config sync:
Screenshot 2024-09-12 at 10 03 22 AM

After config sync:
Screenshot 2024-09-12 at 10 18 52 AM

**Pull request merged**
