### PR TITLE
VACMS-13150 Update to more recent core truncation patch.

### PR DESCRIPTION
**Pull request by swirtSJW**
## Description

Relates #13150  (which has already been closed.)

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As user _uid_ with _user_role_
As an admin
1. Go to https://pr13198-2w92pma8g4qbryqeftqbvjoubjiltr2r.ci.cms.va.gov/admin/config/search/path?search=/lovell-federal-health-care-tricare/health-services/returning-service-member
   - [x] Validate that the alias data is not truncated and that you can see the difference in alias between the two results.
2. Go to https://www.drupal.org/project/drupal/issues/3351638 and leave a comment that you reviewed and tested it, mark it as RTBC and that it works.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [x] `Facilities`
- [ ] `User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by swirtSJW** [comment]
I'll fix the composer hash being out of date error after @omahane finshes his review.

**Review by omahane — APPROVED** [review]
I just checked this out and it's looking great.
Screen Shot 2023-04-07 at 1 59 23 PM

**Comment by swirtSJW** [comment]
image
Just updating the composer lock file now.

**Comment by swirtSJW** [comment]
Passed the remaining check after rebase 
image

**Pull request merged**
