### PR TITLE
VACMS-9591: Augment html_tag_usage filtering

### LINKED ISSUE #9591: Improve HTML tage usage module
## Description
There are some additional improvements i think we can make to HTML tag usage and/or potentially spin off into a mew module.

Currently you generate a report and click into an HTML entity: 

It would be nice if at this screen we could filter by entity type > [select node]  > node type, so we can find results in a subset of node types. I would think this should be recursive up the parent tree until it hits the top-level parent (in the case of paragraphs and such which may end up in a node),

It would also be nice if we had a text search on this screen to further filter results. For example, I want to find all TTY links, so I select a[href] as the entity and get about 50k results. I can then type in `TTY` into a text box that further filters those results into a smaller list.

This second part could potentially be split into it's own module/submodule. This module searches every text field regardless of where it is located (node, block, paragraph, term...) which is IDEAL for content audits and currently very hard to do via drupal views. We could harness this structure to provide a simple text search for all text fields since in most cases we can't be sure _how_ the requested search term is entered. The above TTY example will ONLY find linked TTY, I would need to run that query again under paragraph entities at the very minimum. For this report we don't much care about the HTML entity that's attached to the term, we just want to search ALL text fields and spit out a report. 

## Acceptance Criteria
- [ ] Can filter by parent node type
- [ ] Can filter by parent node status (nice to have/stretch)
- [ ] Can filter by keyword/search terms (could be submodule/separate module)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
closes #9591

## Testing done
Visual / filtering

## Screenshots
image

image

## QA steps
 - [x] Go to `admin/reports/html_tag_usage` and select one of the count items (e.g.: `Rich text -> a -> href: count`)
 - [x] On subsequent page, select `node` entity and visually verify bundle and search string filters appear
 - [x] Visit an entity listed in the table, and copy a snippet of text from the field that is highlighted as a match in the table
 - [x] Return to the filter form, enter the name of the field in the `Name of the field to filter` filter, choose `node` for entity type, enter the node bundle in the bundle filter, and paste the snippet in the `Search by string` filter
 - [x] Click `Apply filters` and verify your node is returned (may be more than one result if item appears on other pages)
 - [x] Choose `paragraph` for the entity type filter
 - [x] Visually verify 4 filters appear
 - [x] Choose an entity type that is not `node` or `paragraph` and visually verify only two filters appear
 - [x] If QA meets use case, please mark https://www.drupal.org/project/html_tag_usage/issues/3270450 as `Reviewed and tested by the community`

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by swirtSJW — CHANGES_REQUESTED** [review]
I left a comment on the upstream issue https://www.drupal.org/project/html_tag_usage/issues/3270450#comment-14588448

**Comment by ethanteague** [comment]
> I left a comment on the upstream issue https://www.drupal.org/project/html_tag_usage/issues/3270450#comment-14588448

Good catch, @swirtSJW - updated.

**Comment by swirtSJW** [comment]
@ethanteague can we get some actual QA steps on this?  You added a bunch of code in that patch and it would be helpful to have your insights on how to test that.

Also adding qa steps to the d.o issue would make that lift a lot easier on the maintainer too.

**Comment by swirtSJW** [comment]
Disregard.   ^^ I figured it out.    The count items was off the right side of my screen.

**Comment by ethanteague** [comment]
> I think something has gone astray. When I visit https://pr9604-j8huzccleibhuibomq641aglgv3ngjgn.ci.cms.va.gov/admin/reports/html_tag_usage I see no filters
> 

You have to click into one of the `Count` links, @swirtSJW - filters are on the next page

**Comment by swirtSJW** [comment]
I may be missing something about the intent here... but something doesn't seem right.  When I choose "a" as the initial count.  The title of "Inspect a[*] for Rich Text" makes me think I am searching within the a tag for the link text.
But really it seems like it is returning all nodes that have an a tag and have the string that I searched for, regardless of whether it is in the  a tag or not.
https://pr9604-j8huzccleibhuibomq641aglgv3ngjgn.ci.cms.va.gov/admin/reports/html_tag_usage/rich_text/a/%2A?token=EMkAfMQPTSK5KcHVRTGMdUUQhLCw1AqbKJk1gDPXzvs&entity_name=node&string_name=Jeffery%20Steidler
image

**Review by swirtSJW — APPROVED** [review]
I enabled the module and ran the initial scan.
The search now works as expected
image

Nice work @ethanteague

**Comment by swirtSJW** [comment]
Just adding a breadcrumb for my own memory here.  This module was not enabled in prod, but is in the codebase.  The intent was to enable it in a tugboat environment when it is needed.  Because the scan is big and is not recommended for running on prod.

**Pull request merged**
