### PR TITLE
VACMS-3542: update revision log permissions

### PR DESCRIPTION
**Pull request by acrollet**
## Description

See #3542 

NB: because the States API is used to hide the revision log field when the 'Create new revision' field is hidden, it was necessary to also add the `override all revision option` permission so that all users can see the checkbox. It is still disabled for all roles:

Screen Shot 2020-11-24 at 11 16 35 AM

## Testing done

Tested editing nodes as a user with the content publisher role.

## Screenshots

Screen Shot 2020-11-24 at 11 16 26 AM

## QA steps

As a user with the "Content Publisher" role:
1. Edit an 'Event' page (verifies previously working content type)
- [x] A revision log message can be entered and saved
1. Edit a 'Staff Profile' page (verifies not previously working content type)
- [x] A revision log message can be entered and saved

### Definition of Done

- [x] Documentation has been updated, if applicable.
- [x] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [x] Code Quality Tests have passed.
- [x] Acceptance Criteria in related issue are met.
- [x] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [x] Yes, and it's written in issue #3579 and queued for publication. 
  - [x] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by ndouglas — APPROVED** [review]
Yup, worked as expected for me.

**Comment by ndouglas** [comment]
Also: nice tests.

**Review by oksana-c — APPROVED** [review]
👍

**Comment by acrollet** [comment]
Closing in favor of #3589

**Pull request closed without merging**
