### PR TITLE
VACMS-2982: Remove legacy fields from config. Future release to remove from db.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #2982 
Step 2 of 3
Merge after https://github.com/department-of-veterans-affairs/vets-website/pull/14829 deployed to va.gov

## Testing done
Visual / behat

## Screenshots
N/A

### CODE REVIEW

**Comment by ethanteague** [comment]
@kevwalsh if you could put eyes on this one - once the frontend piece (merged: https://github.com/department-of-veterans-affairs/vets-website/pull/14829) makes it to prod, I wanna have this one ready to go for upgrade from draft status->merge->deployment.
cc: @swirtSJW

**Comment by swirtSJW** [comment]
@ethanteague  I have a feeling this one is going to keep failing testing unless there is an update to our composer to bring in the newly merged version of vetsweb.

**Comment by indytechcook** [comment]
> Hmmm.......I thought this was happening automagically, now. @indytechcook - can you weigh in?

Dependabot will sometimes create a PR.  Go ahead and manually update if you need it.

**Comment by ethanteague** [comment]
> > Hmmm.......I thought this was happening automagically, now. @indytechcook - can you weigh in?
> 
> Dependabot will sometimes create a PR. Go ahead and manually update if you need it.

Where do I do that, @indytechcook ?

**Comment by indytechcook** [comment]
Just use composer to update `vets-website` in this branch.

`lando composer update va-gov/web`git

**Comment by swirtSJW** [comment]
@ethanteague dependabot only submits up to 10 prs a day and it rarely gets through to the bottom of the list where where vetsweb  sists, so it is pretty rare that it updates automagically.  Just update it with this PR and the two can ride together.

**Comment by ethanteague** [comment]
Updated, @swirtSJW

**Review by swirtSJW — APPROVED** [review]

**Comment by swirtSJW** [comment]
THis is ready to be merged in CMS,  the requisite PR on vetsweb has been merged https://github.com/department-of-veterans-affairs/vets-website/pull/14829   
and went out with a release last  week
image

**Pull request merged**
