### PR TITLE
VACMS-000 upgrade vetweb and nodejs

### PR DESCRIPTION
**Pull request by swirtSJW**
## Description

See _issueid_. 

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by ElijahLynn** [comment]
> /libxmljs: Command failed.

Probably an OS dependency issue. Looking into this.

**Comment by ElijahLynn** [comment]
https://github.com/libxmljs/libxmljs/issues/582#issuecomment-730755405

**Comment by ElijahLynn** [comment]
> > Composer install failed with the yarn install post-install-cmd.
> > > /libxmljs: Command failed.
> 
> And this appears to be because of:
> 
> > command not found make
> 
> And that is because it falls back to building from source if a binary is not found. So, I'll see about putting make on the server but hrm, don't really like that, but oh well.
> 
> See [libxmljs/libxmljs#582 (comment)](https://github.com/libxmljs/libxmljs/issues/582#issuecomment-730755405)

Actually `make` is on the server and the full error is:
> make: g++: Command not found make

So it looks like: `yum install gcc-c++` is the answer here. I just installed this on server and re-running now.

**Comment by ElijahLynn** [comment]
This appears to work on the CI server which we don't have as Infrastructure as Code anymore (drifted). 

I made a PR for devops/BRD envs here though that will need to get merged in. https://github.com/department-of-veterans-affairs/devops/pull/8061/files

**Review by indytechcook — APPROVED** [review]

**Comment by swirtSJW** [comment]
Thanks for digging in to this Elijah.   Nothing that this is blocked until https://github.com/department-of-veterans-affairs/devops/pull/8061 is merged.

**Comment by ElijahLynn** [comment]
I am discussing in Slack #vfs-frontend the possibility of using `libxml2` so we don't need to have an OS make level dependency added. 

https://dsva.slack.com/archives/C5HP4GN3F/p1605894432045100

**Comment by ElijahLynn** [comment]
> I am discussing in Slack #vfs-frontend the possibility of using `libxml2` so we don't need to have an OS make level dependency added.
> 
> https://dsva.slack.com/archives/C5HP4GN3F/p1605894432045100

:new: https://github.com/department-of-veterans-affairs/va.gov-team/issues/16486

**Comment by ElijahLynn** [comment]
I suppose we should still roll this out for now though. I am testing the devops change on a dev deploy now.

**Comment by ElijahLynn** [comment]
@swirtSJW Did you test this on the Lando container by chance? If not I'll test it.

**Comment by ElijahLynn** [comment]
> @swirtSJW Did you test this on the Lando container by chance? If not I'll test it.

I was testing this locally and it fails but with a different error on Python not in PATH, so I added it to .lando.yml build step and then got a different error which am stuck on. 

> gyp ERR! configure error                              
> gyp ERR! stack Error: `gyp` failed with exit code: 1  

SO, I made a PR to vets-website to just update to libxmljs2 which gets rid of the need to do the `make` on this library and think we should pursue that path instead. 

Once this PR is merged > https://github.com/department-of-veterans-affairs/vets-website/pull/15096 (issue https://github.com/department-of-veterans-affairs/va.gov-team/issues/16486) then we can close the DevOps PR too as it will "just work".

**Comment by indytechcook** [comment]
closing in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3600

**Comment by indytechcook** [comment]
Closing since this was done https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3600

**Pull request closed without merging**
