### PR TITLE
VACMS-17241 Rework service location script for keeping state and reporting

### PR DESCRIPTION
**Pull request by swirtSJW**
## Description

Relates to #17241

This can not be merged into integration until #17236 is merged to main AND #15622 is then rebased on main.

## QA steps

What needs to be checked to prove this works?
What needs to be checked to prove it didn't break any related things?
What variations of circumstances (users, actions, values) need to be checked?

IN the terminal
1. run `ddev drush scr ./scripts/content/VACMS-15559-migrate-service-location-from-node-to-paragraph.php`
   - [x] Validate that output looks like this
   
image

   
2. Use Ctrl-C to halt the script.
3. Make note of the last reported item to run.
   
image

5. run the script again
   - [x] Validate that it picks up where it left off.  It will be off by one, but not because of a code error.  See my comment father down.  ctrl C actually undoes the last database transaction. This happening has more to do with how ctrl C works than how the code works.
image

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.
- [ ] If there are field changes, front end output has been thoroughly checked.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by swirtSJW** [comment]
Related to the re-running of the last step.... it is not a ctrl-c timing like I suggested in the QA steps.  It actually has to do with the Drupal shutdown function which runs when something unnatural like trl-C happens.   It undoes the last database transaction.  So we see the state value go back on 
image

**Comment by omahane** [comment]
@swirtSJW (cc: @Becapa ) It seems like this has only been tested locally.
But in Tugboat, I can't seem to replicate the reported/expected behavior:
Screenshot 2024-02-15 at 5 30 22 PM

I think I'll still merge it, but there's something funky.

**Comment by omahane** [comment]
Ok, now that I rebased this branch with `integration-service-location` after rebase it with `main`. And now that we are caught up, lo and behold:
Screenshot 2024-02-15 at 5 45 48 PM

Right as it says on the tin.

**Review by omahane — APPROVED** [review]
Works exactly right.

**Comment by omahane** [comment]
We'll need to get code owners approval before merging into main, so we should wait until then.

**Pull request merged**
