### PR TITLE
VACMS-6074 Accordions

### LINKED ISSUE #6074: Support accordions in KB articles
## User Story or Problem Statement

As a KB user, i want concise pages for skimability, and some content to be only visible if it's relevant.

## Acceptance Criteria
- [ ] USWDS/VADS style accordions are supported in two paragraph types in the KB 
  - [ ] Accordion group
  - [ ] Q&A Section (when accordion is chosen)
- [ ] Our approach to accordions is abstracted out enough to support the above two paragraph use cases, but also for other use cases (eg views rows, etc)

## Implementation steps
Drupal theming

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
Closes #6074
**I didn't constrain the accordion treatment for either paragraph type to Knowledge Base - can do this if required, but since these items weren't very well themed, probably should allow new treatment, everywhere.**

## Testing done
Visual

## Screenshots
image

image

image

## QA steps
 - [x] As an administrator, go to `node/35029/edit` and add a `Q&A section` paragraph to the Main Content field
 - [x] Add a couple of Q&A's to the paragraph.
 - [x] Add an `Accordion group` paragraph to the Main Content field
 - [x] Add a couple of `Accordion items` to the paragraph.
 - [x] Save node as published
 - [x] Visually verify node display for new paragraph items looks like screenshots, above

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by kevwalsh** [comment]
> **I didn't constrain the accordion treatment for either paragraph type to Knowledge Base - can do this if required, but since these items weren't very well themed, probably should allow new treatment, everywhere.**

i think this is a good thing! Definitely needs some QA though, especially for Benefits Hub Detail pages, which _do_ have some special treatment.

**Comment by ethanteague** [comment]
> > **I didn't constrain the accordion treatment for either paragraph type to Knowledge Base - can do this if required, but since these items weren't very well themed, probably should allow new treatment, everywhere.**
> 
> i think this is a good thing! Definitely needs some QA though, especially for Benefits Hub Detail pages, which _do_ have some special treatment.

@kevwalsh `Benefits Hub Detail pages` only have lists of links paragraphs. `Benefits Detail pages` have Accordions and Q&A's - did some cleanup, and updated this pr. I used `/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program` & `draft-get-a-covid-19-vaccine-at-va` for proofing.

**How Do I Get this Benefit process list paragraph has new treatment coming in pr https://github.com/department-of-veterans-affairs/va.gov-cms/pull/6358**
image
image
image

**Review by swirtSJW — APPROVED** [review]

**Comment by swirtSJW** [comment]
@ethanteague CSS collisions I'm afraid.

**Comment by ethanteague** [comment]
> @ethanteague CSS collisions I'm afraid.

Updated, @swirtSJW :+1:

**Review by swirtSJW — APPROVED** [review]

**Comment by swirtSJW** [comment]
image

**Pull request merged**
