### PR TITLE
VAGOV-3663: Update graphql module

### PR DESCRIPTION
**Pull request by acabouet**
This PR updates the Drupal GraphQL module to the latest RC version.

**Updating this module requires some changes to query syntax in vets-website. Please see this PR for a summary of changes: https://github.com/department-of-veterans-affairs/vets-website/pull/10085.** 

**This update is not backwards compatible - meaning that after this PR is merged and deployed, the front-end build will be broken until vets-website PR #10085 is merged and deployed.**

See this JIRA ticket for more context about the update: https://va-gov.atlassian.net/browse/VAGOV-3026

### CODE REVIEW

**Comment by andyhawks** [comment]
@ethanteague the `composer.lock` changes here are fine and normal - just datestamps, authors, etc. if it had global library version upgrades that would be a concern. 

@acabouet i added a comment on https://github.com/department-of-veterans-affairs/vets-website/pull/10085 that it should be a feature flag PR, as this CMS PR will not be deployed to all environments simultaneously. https://github.com/department-of-veterans-affairs/vets-website/pull/10085, with feature flag added for dev, should be merged BEFORE this PR. let me know when https://github.com/department-of-veterans-affairs/vets-website/pull/10085 is updated and merged, thx!

**Comment by andyhawks** [comment]
rebuild

**Comment by acabouet** [comment]
rebuild

**Comment by ElijahLynn** [comment]
rebuild

**Comment by ElijahLynn** [comment]
Drupal permission tests failed, @schiavo.

**Comment by andyhawks** [comment]
rebuild

**Pull request merged**
