### PR TITLE
VACMS-4387: Inline entity forms on CLP. 

### PR DESCRIPTION
**Pull request by kevwalsh**
## Description

See #4387 . 

## Testing done

Manual

### Improvement to promo form

As content admin or admin, edit a promo block from admin/structure/block/block-content 

- [ ] Note redundant "link teaser" label is no longer there. 
- [ ] Note reordered fields to match the order in the content design.
- [ ] Note the redundant "Block description" field is no longer there in the form. 
- [ ] Save the block, and note that the description has been updated to concatenate the link and link summary. 

Repeat over at admin/content/promos 
- [ ] Note block description is gone from this view. 

#### Before

Promos___VA_gov_CMS

#### After

Promos___VA_gov_CMS

#### Before

You can add existing promos, and edit them. but you can't create them inline.

Edit_Campaign_Landing_Page_VA_Solid_Start___VA_gov_CMS

#### After

Go to  /node/15068, to the "What you can do" segment. 
- [x] Create a promo inline on a CLP form (you may have to delete one first). 
- [x] Edit an existing promo inline.
- [x] Click save. 

Edit_Campaign_Landing_Page_VA_Solid_Start___VA_gov_CMS

#### Before

Edit_Campaign_Landing_Page_VA_Solid_Start___VA_gov_CMS

#### After

Go to  /node/15068, to the "Downloadable resources" segment. 
- [x] Note that you can now add a Downloadable resource inline

Edit_Campaign_Landing_Page_VA_Solid_Start___VA_gov_CMS

Edit_Campaign_Landing_Page_VA_Solid_Start___VA_gov_CMS

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by swirtSJW — APPROVED** [review]
This looks good.  
Sad to lose the linkit test, but not issues.

Just waiting on tests to pass.

**Comment by kevwalsh** [comment]
@swirtSJW 

> This looks good.
> Sad to lose the linkit test, but no issues.
> 
> Just waiting on tests to pass.

I can create an issue to bring this Linkit test back, but with an exception for the Document - External link, for which the core Link field is superior.

**Comment by swirtSJW** [comment]
I am seeing this error which seems legit
image

**Comment by swirtSJW** [comment]
This PR is blocked until this https://github.com/department-of-veterans-affairs/vets-website/pull/16150 is merged in vetswebsite and we pull the new release into cms.

**Comment by swirtSJW** [comment]
Vetsweb was just updated in CMS so this should pass now (knock on wood)

**Pull request merged**
