### PR TITLE
Remove references to (soon to be) deprecated drupal_get_path

### PR DESCRIPTION
**Pull request by acrollet**
## Description

See https://www.drupal.org/node/2940438

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by ndouglas** [comment]
Oh, far out.  This is a good one to know about. 📣

**Review by ndouglas — APPROVED** [review]
Approved pending tests.

**Comment by acrollet** [comment]
It would probably be good to get @swirtSJW's eyes on this since it affects govdelivery - I did just confirm to be 100% sure that we get the same path from both approaches:

Screen Shot 2021-07-22 at 12 09 34 PM

**Review by indytechcook — APPROVED** [review]

**Review by swirtSJW — COMMENTED** [review]
The code looks good.   None of our migrations right now need the file move.  So that can be tested when/if we need it the next time.

I do have a concern about the vagov delivery  mail body as we just got that working again.   We should test that to make sure its ok.   I'll try to test it locally and verify it still formats the email body payload correctly

**Review by swirtSJW — APPROVED** [review]
I think we are error free on this
I created a banner alert with the govdelivery option set.
Veriofied one got queued
image
Then I ran the queue and verified one got processed.   No errors.
image

**Comment by swirtSJW** [comment]
image

**Comment by acrollet** [comment]
Thanks @swirtSJW !

**Pull request merged**
