### PR TITLE
Only run graphql queries instead of the full content build

### PR DESCRIPTION
**Pull request by cweagans**
## Description

Instead of running a content build, which can take 15-20 minutes, we can just run the graphql queries. This provides the safety net we need re: how content build integrates with the CMS, but in a fraction of the time.

With this PR, I've seen total build times as low as 11 minutes, but the normal case seems to be closer to 15-17 minutes.

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by ndouglas — DISMISSED** [review]
leonardo-beautiful

**Review by swirtSJW — COMMENTED** [review]
Just wanted to make sure...because i didn't carefully follow the content-build change.   this will run the menu queries and the rest of the content queries?

**Comment by cweagans** [comment]
>  this will run the menu queries and the rest of the content queries?

Yep, this runs all of the gql queries that the content build runs.

**Comment by swirtSJW** [comment]
closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8805

**Pull request merged**
