### PR TITLE
VACMS-12529: Adds missing entity.smart_date_override.route definition.

### PR DESCRIPTION
**Pull request by dsasser**
## Description
Adds missing entity.smart_date_override.canonical.

Relates to  #12529

## Testing done
Successful edit and save of an event series override.

## Screenshots
Prior to change, the following is visible in the console log when trying to save an event series override:

Screen Shot 2023-02-09 at 11 55 27 AM

## QA steps

As content admin
1. Visit this node: /node/51553/edit
2. Under 'Date and time' fieldset, click the 'Edit event series' button
3. Click the 'edit' button next to any event date/time.
4. Change the time to a later hour
5. Click save
   - [x] Verify that you are returned to the full event series modal view
   - [x] Verify that you can close the modal
6. Save the node
7. Perform steps 2-3
   - [x] Verify you see the updated time for the event date/time you changed earlier.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [x] `Public websites`
- [ ] `Facilities`
- [ ] `User support`

### CODE REVIEW

**Comment by swirtSJW** [comment]
I am still seeing an ajax error.  I can't open the edit screen 
image

**Comment by dsasser** [comment]
> I am still seeing an ajax error. I can't open the edit screen image

I'm not having this problem on the tugboat env logged in as my admin account.

**Comment by swirtSJW** [comment]
INteresting.  it is working now.  We might have been colliding in a weird way with tests that were running.

**Review by swirtSJW — APPROVED** [review]

**Comment by swirtSJW** [comment]
Tested and approved

**Comment by dsasser** [comment]
> INteresting. it is working now. We might have been colliding in a weird way with tests that were running.

Yeah some combination of saving the node corrected the underlying problem, which is related to this issue: https://www.drupal.org/node/3274881

Trying the patch to see if it applies, because it is clear this can be a problem under some circumstances. This points to our need to upgrade smart_date to > 3.5 since this was fixed in 3.6 (but not 3.5).

**Comment by swirtSJW** [comment]
Confirmed working 
image

**Review by swirtSJW — APPROVED** [review]
Tests out 
image

I am not sure if we are fully testing that second patch, because I don't know why that first attempt failed but I repeated the same steps so that is largely good enough ;)

**Comment by swirtSJW** [comment]
image

**Pull request merged**
