### PR TITLE
VACMS-3605: CLP Event Panel

### PR DESCRIPTION
**Pull request by kaise-lafrai**
## Description

See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3605

## Screenshots

Screen Shot 2020-12-04 at 2 44 37 PM

Screen Shot 2020-12-04 at 2 45 06 PM

## QA steps

As user _uid_ with _user_role_

- Login into PR environment
- Navigate here: /node/add/campaign_landing_page
- Select the 'Events' panel tab
- [ ] Confirm no fields appear other than **Add an Events panel** boolean
-  Select **Add an Events panel** boolean and confirm **Events Header*** and **ADD UP TO TWO EVENTS** appear.
-  Enter a value in the **Events Header**
-  Select the **ADD UP TO TWO EVENTS** fieldset and select **Select Events** button
- [ ] Confirm **Select Events** entity browser appears with 2 filters: Owner and Title.
-  Select 2 events and select **Select Entities** .
- Complete remainder of tabs on form
- Confirm **Save** is successful

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by kevwalsh — CHANGES_REQUESTED** [review]
Nice work on the stretch AC. It brought up a few new issues, and i've added a few other items here. 

- [x] Help text on Events header seems to be missing a `".` at the end. 

Create_Campaign_Landing_Page___VA_gov_CMS


In the entity modal: 
- [x] The dialog box is titled "Select events" and then there is help text "Select Event(s)." Let's standardize those as much possible. Ideally it would say 
  - [x] "Select events" in the title of the modal, 
  - [x] Then the next instructions should say. `You can select up to two events that already exist in the CMS, such as on the <a href="/outreach-and-events/events/" target=”_blank”>Outreach Hub</a> or on a VAMC event calendar.`

Create_Campaign_Landing_Page___VA_gov_CMS

- [x] Change "Title" filter label to "Filter events by title" and "Owner" filter label to "Filter events by owner"
  - [ ] Stretch: would be great to get the Apply button on the same line as the filters. Right now, the Apply button seems like it would do the event selecting, instead of filtering. 
- [x] Change "Select entities" button to "Select events"
- [x] Reduce the number of events per page to 20
- [x] Remove the link to the event on the Title field. We don't want people clicking on it from here (the event loads inside the modal). We could consider opening it in a new tab with `target="_blank"`, too. But i think removing link altogether is probably best. 
- [x] Change default sort to the event start date
- [x] if i select 3 events with checkboxes and click "Select entities", the form doesn't submit, and i get an unhelpful error message. This issue looks similar to something we saw on Resources & support. 

Create_Campaign_Landing_Page___VA_gov_CMS


After selecting two events, let's use the Teaser view mode on the Entity browser widget settings, and "Show widget details open by default"

Manage_form_display___VA_gov_CMS

- [x] Speaking of which, let's make sure "Show widget details open by default" is applied to similar entity browser fields on this form. Once a user opts into a fieldset, they shouldn't have to click to open a fieldset _inside_ that fieldset.

**Comment by kaise-lafrai** [comment]
@kevwalsh PR has latest changes.

**Review by kevwalsh — CHANGES_REQUESTED** [review]
- [ ] DEFECT: At least one event should be required when i've clicked "Add an Events panel"
- [ ] Minor design change: In the modal: let's reduce the number of events to 10. i'm concerned about confusion between "apply" and "select event" when "select event" requires scrolling. 
- [ ] Minor design change: If it's easy, can you change "apply" to "apply filters"? 
- [ ] DEFECT: Events should be sorted by date ASC, not DESC. still only future events.

**Comment by kaise-lafrai** [comment]
@kevwalsh 

All updates have been addressed with the acception of **DEFECT: At least one event should be required when i've clicked "Add an Events panel"**. @ethanteague has a PR that will address this throughout CLP.

Thank you!

**Review by kevwalsh — APPROVED** [review]
Good stuff Kaise!

**Comment by ethanteague** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3714

**Pull request closed without merging**
