### PR TITLE
VACMS-14405 add patches for jsonapi

### LINKED ISSUE #14405: Fix issues with JSON API responses
## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

### PR DESCRIPTION
**Pull request by tjheffner**
## Description

Closes #14405. Apologies for the duplicate pr, I messed up rebasing and it was quicker to start fresh.

Adds two patches necessary for JSON:API. The `consumer_image_styles` patch fixes a schema validation error that is generated while handling image styles resulting from a recent update to the module.

The core patch about `BaseFieldOverride` adds the entity path alias back to the JSON:API response for a given entity. No configuration updates were needed.

## Testing done
running locally, hitting a jsonapi endpoint for a news story node should include a `path` object underneath the `attributes` key:
https://va-gov-cms.ddev.site/jsonapi/node/news_story/1dbd5b1e-0fb2-43fb-8581-a2f9edfe3c83

## Screenshots
Screenshot 2023-07-13 at 1 36 34 PM

## QA steps
- What needs to be checked to prove this works?  
Visit the same endpoint without the patches from this PR applied and see that the path variable is missing.
- [x] Compare data between [this branch](https://pr14583-srk5lpodda7vjwkb0rpx0pq2rhajwyyy.ci.cms.va.gov/jsonapi/node/news_story/1dbd5b1e-0fb2-43fb-8581-a2f9edfe3c83) and [prod](https://prod.cms.va.gov/jsonapi/node/news_story/1dbd5b1e-0fb2-43fb-8581-a2f9edfe3c83) It shows the only diff being the expected one.

You could also try running the next-build repo as-is. Story listing pages will fail because `entity.path.alias` is not found in the data for any of the listed news story nodes. There are other cleanup tasks pushed to that repo here: https://github.com/department-of-veterans-affairs/next-build/pull/126

- What needs to be checked to prove it didn't break any related things?  
- [ ] Do News Stories still translate as expected?
- [x] Validate that the path of a newly created news story matches that of a newly created news story on staging.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [x] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [x] `Accelerated Publishing`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [x] No announcement is needed for this code change.
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by ndouglas** [comment]
>Do News Stories still translate as expected?

I'd appreciate a bit more clarity about this, since news stories aren't currently translated. To me, that means this is low risk 😁

**Comment by swirtSJW** [comment]
- [x] Compare data between [this branch](https://pr14583-srk5lpodda7vjwkb0rpx0pq2rhajwyyy.ci.cms.va.gov/jsonapi/node/news_story/1dbd5b1e-0fb2-43fb-8581-a2f9edfe3c83) and [prod](https://prod.cms.va.gov/jsonapi/node/news_story/1dbd5b1e-0fb2-43fb-8581-a2f9edfe3c83)   It shows the only diff being the expected one.
image

**Comment by swirtSJW** [comment]
Following on @ndouglas question about translation comparison.  They match in that neither is translatable in staging or this PR.

- [x]  Do News Stories still translate as expected?
image

**Review by swirtSJW — DISMISSED** [review]
With the exception of the question around translation, this seems to be passing QA.  So I am giving it my approval but still contingent on whether there is more to test related to translation.

**Comment by edmund-dunn** [comment]
We also need to make sure these are good for D10.

**Comment by ndouglas** [comment]
Screenshot 2023-08-01 at 1 25 48 PM

@tjheffner This just means you need to run `composer update --lock` again locally to update the `content-hash` and ensure that the Composer system is internally consistent.

**Comment by ndouglas** [comment]
Merged since this is blocking another team and there don't seem to be any substantial concerns that haven't been addressed.

**Pull request merged**
