### PR TITLE
VAGOV-4398: Permissions for moderation sidebar.

### PR DESCRIPTION
**Pull request by kevwalsh**
QA: https://va-gov.atlassian.net/browse/VAGOV-4398

### CODE REVIEW

**Comment by mbenziane** [comment]
rebuild

**Comment by andyhawks** [comment]
rebuild

**Comment by andyhawks** [comment]
rebuild

**Comment by andyhawks** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Pull request merged**
