### PR TITLE
VACMS-4262: Remove tome, zippy and va_gov_content_export

### PR DESCRIPTION
**Pull request by indytechcook**
## Description

See #4262. 

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [x] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

---
This change is [Reviewable](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/4535)

### CODE REVIEW

**Review by ndouglas — APPROVED** [review]
indytechcook is a pretty cool guy, eh kills custom moduels and doesn't afraid of anything

**Comment by indytechcook** [comment]
Do not merge until https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4544 is deployed.

**Comment by indytechcook** [comment]
Now https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4544 is also required

**Comment by indytechcook** [comment]
Replace with https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4650

**Pull request closed without merging**
