### PR TITLE
VACMS-9560: Fix claro handling of non admin cc content.

### LINKED ISSUE #9560: Centralized content descriptor content should show as non-editable (view mode) for non-admins
## Describe the defect

As a non-admin, the Scope paragraphs on Centralized Content _forms_ should show in view mode, just as it does on node view. 

## To Reproduce
1. As jeffrey.grandon@va.gov
2. Go to /node/33340/edit
3. See that the Centralized content descriptor paragraphs appear in edit mode.

## AC / Expected behavior
They should appear in view mode.

## Screenshots

How it looks
Edit_Centralized_Content_VAMC_System_-__Medical_records__page_content___VA_gov_CMS

How it's supposed to look (from a pre-Claro screenshot in #6707)

image

## Background

This was implemented in #6707 for #4016

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
closes #9560

## Testing done
Visual / behat

## Screenshots
image

## QA steps
- [x] As david.conlon@va.gov, go to `node/33340/edit` and visually verify Centralized content wysiwygs are disabled, and theme matches above screenshot.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by swirtSJW — CHANGES_REQUESTED** [review]
Both edit and view modes should be the same.  These are showing different shading and spacing.
I am not sure which is the "right one, but they should be the same.
image

**Review by swirtSJW — CHANGES_REQUESTED** [review]
Also seems like we have a separate bug or something.
Why are all the WYSIWG fields disabled?   If a person can edit the page, but is not an admin, they should be able to edit all the fields that are not inside the scopes.  
image

Seems unrelated to this.. but calling it out because it was in the testing steps.

**Comment by ethanteague** [comment]
@swirtSJW @kevwalsh couple things going on here, and I think this is gonna need @tjheffner 's input to get right. 

1. The screenshot  @kevwalsh posted / recollection of old theme implementation  led me to believe scope content should be disabled for content_admin
2. Old theme implementation form and node views don't match when I switch to old theme as david.conlon@va.gov

**Review by swirtSJW — CHANGES_REQUESTED** [review]
The WYSIWYG seems to have been shrunk 
image

**Pull request merged**
