### PR TITLE
VACMS-4415: Add 4 new fields to view.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #4415

## Testing done
Visual / behat

## Screenshots
image

## QA steps
As an administrator, go to `vha-health-services` and visually verify 4 new fields appear, per screenshot

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by kevwalsh — CHANGES_REQUESTED** [review]
A few things 

On the web-based view

- [x]  Add some helpful labels to distinguish the VAMC specific fields from the Vet Center fields (see screenshot)
- [x] Reorder the fields a bit (see screenshot), following this order for VAMCs, then Vet Center
  - [x] Type of care
  - [x] Patient friendly name
  - [ ] Common conditions
  - [ ] Description
  - [ ] Number of uses by ...
- [ ] Stretch: Add a field "Number of uses by Vet Centers", copying the approach from "Number of uses by VAMCs"

On the CSV download display
- [ ]  Add Vet Center fields
- [ ]  Remove the "Number of uses by VAMCs" field (and don't include the Number of uses by Vet Centers"
- [ ] Replace field labels with machine names

**Comment by kevwalsh** [comment]
@ethanteague Here's that screenshot i forgot to attach.  I ordered the fields and showed what to prepend on each label. 

VHA_Health_service_taxonomy___Veterans_Affairs

**Comment by ethanteague** [comment]
@kevwalsh did all with the exception of `Stretch: Add a field "Number of uses by Vet Centers", copying the approach from "Number of uses by VAMCs"` - wasn't able to figure out how to separate the counts by bundle in the view.

**Review by kevwalsh — APPROVED** [review]
LGTM

**Pull request merged**
