### PR TITLE
VACMS-7487: Hide operations button from office hours widget

### LINKED ISSUE #7487: Remove/hide Operations fields from all Office hours widget
## User Story or Problem Statement

Top task pages will expose `field_office_hours` to editors for the first time. It's not a great UX 

[needs updating]

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires KB article update

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

### PR DESCRIPTION
**Pull request by JayDarnell**
## Description

Closes #7487 

## Testing done

Visual testing

## QA steps

As an admin user
- [ ] Visit /node/1464/edit
- [ ] Verify that the OPERATIONS column is no longer displayed

### Select Team for PR review

- [ ] `Platform CMS team`
- [X] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### CODE REVIEW

**Comment by JayDarnell** [comment]
Failed behat item seems unrelated to my work

**Comment by JayDarnell** [comment]
I recently found instances where this field exists but the comments have already been removed. This means my CSS solution above will not work. Refactoring now.

**Comment by JayDarnell** [comment]
I removed the comment column using field configuration and removed the operations column using CSS.

**Comment by JayDarnell** [comment]
Based on feedback from @swirtSJW the comment column must stay. CSS change updated to only hide the operations column.

**Review by swirtSJW — APPROVED** [review]
image
  Works for me.

**Pull request merged**
