### PR TITLE
VACMS-11744: external link status report view added

### LINKED ISSUE #11744: Linky 404 report
## Description
Linky is able to provide a 404 report of broken links. By turning this on, we could provide a useful tool for the Sitewide Content team that could help to surface broken links and assist them in fixing these proactively rather than having to find out from a Veteran or another source that there is a broken link on their VA.gov page.

## Acceptance Criteria
- [ ] ~Turn on the 404 report tool~
- [ ] ~Configure the tool sensibly (raise questions if you have them about what is sensible)~
- [ ] Configure link checking to run  Linkychecker (/admin/config/linkychecker) to run on cron with a crawl interval of 7 days.
- [ ] Clone our existing Linky View display  "Managed links"  (/admin/content/linky) to "External Link Status"  (/admin/content/linky/status) 
  - [ ] title: External Link Status
  - [ ] machine name: external_link_status
  - [ ] access: admin only
  - [ ] caption: External link status results
  - [ ] Add  field Linky status  or whatever it is called by Linkychecker module
  - [ ] Add filter if one exists, to filter by link status.
  - [ ] Add field error (boolean)
  - [ ] Add field Error message
  -  ignore the normally Views Style guide requirements as this is just to see if the link checker is going to have too many false alarms, or if it gives us meaningful information.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by edmund-dunn**
## Description

Closes #11744.

## Testing done
Tested locally.

## Screenshots
CleanShot 2022-12-12 at 12 50 30

## QA steps

- [x] Configure link checking to run  Linkychecker (/admin/config/linkychecker) to run on cron with a crawl interval of 7 days.
- [x] Clone our existing Linky View display  "Managed links"  (/admin/content/linky) to "External Link Status"  (/admin/content/linky/status) 
  - [x] title: External Link Status
  - [x] machine name: external_link_status
  - [x] access: admin only
  - [x] caption: External link status results
  - [x] Add  field Linky status  or whatever it is called by Linkychecker module
  - [x] Add filter if one exists, to filter by link status.
  - [x] Add field error (boolean)
  - [x] Add field Error message
  -  ignore the normally Views Style guide requirements as this is just to see if the link checker is going to have too many false alarms, or if it gives us meaningful information.

To access the Status Report:
- [x] Go to https://pr11920-w3wuffu341dmfxrcwvxwdlsprz4pp2qo.ci.cms.va.gov/admin/content/linky/status (Main Nav > Content > Managed Links > External Link status)
- [x] Verify the results can be filters by:
  - [x] Title
  - [x] Destination
  - [x] HTTP Status

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by laflannery — APPROVED** [review]
This makes sense to me - at least for a default report for us to figure out what it's giving us

**Comment by EWashb** [comment]
Tugboat is failing for me

**Review by swirtSJW — APPROVED** [review]
Tests out.
Confirmed configuration was  was set to  7 days.

All filters work as intended 
image


Nice work @edmund-dunn

**Comment by swirtSJW** [comment]
It seems odd that some have error of yes, but no  error message.  I imagine that is a problem with the module and not with the view.

**Comment by swirtSJW** [comment]
image

**Comment by EWashb** [comment]
Thanks swirt! I didn't review it yet, but I trust all of you to have done it! Sorry I didn't get in there sooner.

**Pull request merged**
