### PR TITLE
VACMS-7702: implement UX enhancements for non-clinical services

### LINKED ISSUE #7702: Implement UX enhancements for non-clinical services from #7595
## User Story or Problem Statement

Update the user experience for top task pages / non-clinical services to reflect the changes outlined in #7595 

### Register for care
See [Register for care](https://www.figma.com/file/kWXId7MIDBh5ToX5VqJPBK/%236872-Non-clinical-services-editorial-experience?node-id=290%3A418) frame in figma file for reference
- [x] Add help text after "register for care locations" heading
- [x] Add facility name to location card, style as h3
- [x] Style office name as bold body text
- [x] remove facility name from address
- [x] Add edit link to bottom of location card
- [x] Add "add facility" link underneath the last location card

### Billing and insurance
See [Billing and insurance](https://www.figma.com/file/kWXId7MIDBh5ToX5VqJPBK/%236872-Non-clinical-services-editorial-experience?node-id=290%3A483) frame in figma file for reference
- [x] Add help text after heading (note that help text is different for each of the three pages)
- [x] Add facility name to location card, style as h3
- [x] Style office name as bold body text
- [x] remove facility name from address
- [x] Add edit link to bottom of location card
- [x] Add "add facility" link underneath the last location card

### Medical records office
See [Medical records](https://www.figma.com/file/kWXId7MIDBh5ToX5VqJPBK/%236872-Non-clinical-services-editorial-experience?node-id=290%3A437) frame in figma file for reference
- [x] Add help text after heading (note that help text is different for each of the three pages)
- [x] Add facility name to location card, style as h3
- [x] Style office name as bold body text
- [x] remove facility name from address
- [x] Add edit link to bottom of location card
- [x] Add "add facility" link underneath the last location card

### "No location" message
see [No Location frame](https://www.figma.com/file/kWXId7MIDBh5ToX5VqJPBK/%236872-Non-clinical-services-editorial-experience?node-id=263%3A289) in Figma file for reference
- [x] Add body text 
- [x] Add "add location" link
- [x] Text and link are contained in a box
- [x] Regular "add facility" link should not appear

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [x] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected.
- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by JayDarnell**
## Description

Closes #7702 

## Testing done

Visual testing

## Screenshots

Register for care (multiple locations)
Screen Shot 2022-01-25 at 9 19 29 AM

Register for care (no locations)
Screen Shot 2022-01-25 at 9 20 37 AM

Billing and insurance
Screen Shot 2022-01-25 at 9 21 04 AM

Billing and insurance (no locations)
Screen Shot 2022-01-25 at 9 21 13 AM

Medical records offices
Screen Shot 2022-01-25 at 9 21 37 AM

Medical records offices (no locations)
Screen Shot 2022-01-25 at 9 21 44 AM

## QA steps

As an admin user

- [x] Visit /admin/content
- [x] Filter the content to locate a **VAMC System Register for Care** node within the **VA Eastern Colorado health care** section
- [x] Verify the styles for the non-clinical services match the specification from #7595
- [x] Filter the content to locate a **VAMC System Billing and Insurance** node within the **VA Eastern Colorado health care** section
- [x] Verify the styles for the non-clinical services match the specification from #7595
[ ] Filter the content to locate a **VAMC System Medical Records** node within the **VA Eastern Colorado health care** section
- [x] Verify the styles for the non-clinical services match the specification from #7595
- [x] In each of the above examples, delete the related non-clinical service nodes and revisit the top task page. Verify that the displayed (no results) text matches the specification from #7595 

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product Support`

### CODE REVIEW

**Comment by suzanne-gray** [comment]
@JayDarnell the edit link is missing from the location cards on all three pages. :(
Screen Shot 2022-01-25 at 9 09 08 AM

**Comment by suzanne-gray** [comment]
Logged in as Jim, when I click "add facility" on any of the top task pages I get "access denied"
Screen Shot 2022-01-25 at 9 19 37 AM

**Comment by suzanne-gray** [comment]
Sorry it took a million years for me to get back to this. It looks good to me! As discussed, I'm moving the view node conundrum into a new ticket.

**Review by swirtSJW — APPROVED** [review]
Nice work Jay

**Pull request merged**
