### PR TITLE
VAGOV-1641 Apply GraphQL Patch "Fix broken entity reference query filter".

### PR DESCRIPTION
**Pull request by ElijahLynn**
See commit message.

### CODE REVIEW

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-171<br><br> [button_visit-site](http://pr-171.va.agile6.com)

**Comment by andyhawks** [comment]
@ElijahLynn can you run a `composer update` and add composer.lock to this PR? don't want to get out of sync. Thx!

**Comment by ElijahLynn** [comment]
K, the way composer patches works it doesn't actually use the lock file unfortunately (https://github.com/cweagans/composer-patches/issues/12) and it doesn't have a way to just update the patches portion of the compose.lock file (https://github.com/cweagans/composer-patches/issues/23) . Running `composer update drupal/graphql` does appear to at least put the patch in composer.lock, plus it adds another one that was left out last time for path_redirct_import. 

I don't recommend updating core and all modules for this story with `composer update` as it is outside the scope of this story and introduces too many changes to troubleshoot errors. 

Are you okay with the `composer update drupal/graphql` above, which gets the patch into the lock file?

**Comment by andyhawks** [comment]
@ElijahLynn yep, please do `composer update drupal/graphql` and add the composer.lock. thx!

**Comment by ElijahLynn** [comment]
@andyhawks done :heavy_check_mark:

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-171<br><br> [button_visit-site](http://pr-171.va.agile6.com)

**Pull request merged**
