### PR TITLE
VACMS-11265: Reveal Linky destination to editor.

### LINKED ISSUE #11265: Reveal linky destination in link editor
## User Story or Problem Statement

As an editor I would like to see the actual destination of my link when I edit it, and not the linky equivalent so that I may more transparently see and edit my content.

Currently. clicking the edit button for an external link brings up
image

and the only way to change the link is to delete out the linky reference and put in the link destination.

[Related slack conversation in CMS support](https://dsva.slack.com/archives/CDHBKAL9W/p1666127982707249)
## Acceptance Criteria
- [ ] When editing a wysiwyg link to an external place, I can see the actual destination and not the linky reference.
- [ ] saving the link does not result in two linkies.

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

Closes #11265.

## Testing done
Local testing.

## Screenshots

https://user-images.githubusercontent.com/1318579/197853029-845bf6a4-47ea-482b-8c62-c0114ba41198.mov

## QA Steps
As any user capable of editing:

1. Browse to [the Managed Links page](https://cms-0x2qygiqnblqzee86kwgivpdlnlzn2fy.ci.cms.va.gov/admin/content/linky).
    - [x] Verify that there's a link to ArsTechnica (our test external link).
2. Open up [this node](https://cms-0x2qygiqnblqzee86kwgivpdlnlzn2fy.ci.cms.va.gov/test-data-my-test-office)
3. Click the Edit tab and expand the Content thing.
Screen Shot 2022-10-25 at 3 14 23 PM
    - [x] Click inside the External Link, click the "Link" button, and verify that the actual URL (not the Linky link) is displayed.
    - [x] Click inside the Internal Link, click the "Link" button, and verify that it's still linked to an entity and isn't doing weird stuff.
4. Update the External Link to point to another external site, preferably not a VA.gov website (for verification purposes).
5. Save the node.
6. Browse to [the Managed Links page](https://cms-0x2qygiqnblqzee86kwgivpdlnlzn2fy.ci.cms.va.gov/admin/content/linky).
    - [x] Verify that there's now a Linky pointing to the external site you specified.
    - [x] Verify the original linky destination exists. (it didn't overwrite the original)

### CODE REVIEW

**Comment by ndouglas** [comment]
@swirtSJW @EWashb @laflannery Is this the experience we had in mind?

**Comment by laflannery** [comment]
This makes sense to me

**Comment by swirtSJW** [comment]
It tests out great Nate.  I confirmed that editing the link results in a new linky, so it works perfectly.

**Review by swirtSJW — CHANGES_REQUESTED** [review]
Tests out great.  Full success.  

If we can move it to va_gov_links it would make a wee bit more sense for findability and stuff.  I know va_gov_links is more about content build stuff but I think it can do both and would help by not adding more lines of code to va_gov_backend which is about to burst  ;)

**Comment by ndouglas** [comment]
Fair 'nuff, @swirtSJW -- moved to `va_gov_links`.

**Review by swirtSJW — APPROVED** [review]
Awesome work on this.

**Pull request merged**
