### PR TITLE
 VACMS-1297: fix axe webdriverjs error

### PR DESCRIPTION
**Pull request by acrollet**
## Description

See #3110 - this also introduces a fix for a specific accessibility issue caused by the hidden environment indicator toolbar tab.

## Testing done

Ran accessibility test locally.

## QA steps

1. Run accessibility tests
- [ ] Verify that deprecation warnings are no longer shown

### CODE REVIEW

**Review by ElijahLynn — APPROVED** [review]
Nice work and initiative here!

**Comment by ElijahLynn** [comment]
Can you screenshot the before (different PR) and after output (this PR) and attach here?

**Comment by acrollet** [comment]
Before:

Screen Shot 2020-10-14 at 9 49 07 AM

After:

Screen Shot 2020-10-14 at 9 50 42 AM

**Comment by ElijahLynn** [comment]
Thank you!

**Pull request merged**
