### PR TITLE
VACMS-7163: Remove "VA Lovell Federal health care" menu in CMS

### LINKED ISSUE #7163: H1 and breadcrumb is wrong for Lovell Federal health care
## To Reproduce
1. Go to https://va.gov/lovell-federal-health-care
2. Note that it reads VA Lovell Federal health care for the h1, and Lovell FHCC for the breadcrumb

## Expected behavior
- [ ] It should read Lovell Federal health care in both places

## Screenshots 
<details><summary>FE</summary>

VA_Lovell_Federal_Health_Care___Veterans_Affairs

</details>

<details><summary>CMS</summary>

These all need to read "Lovell Federal health care
VA_Lovell_Federal_health_care___Veterans_Affairs

</details>

 ## Additional context

There may need to be a change on the FE `va-lovell-federal-health-care',`  may need to be `lovell-federal-health-care` in order to change the h1 / VAMC system name [in this file](https://github.com/department-of-veterans-affairs/content-build/blob/32b4170dffa06c4b4cf95d044ca390072e97e273/src/site/stages/build/drupal/graphql/navigation-fragments/facilitySidebar.nav.graphql.js#L90).

This may require a new menu in drupal too, with that machine name, and which will need to be enabled for all VAMC content types. 

This may require some careful change management. 

I did some digging but i could not figure out where the "FHCC" is coming from in the Drupal breadcrumb.

### PR DESCRIPTION
**Pull request by netboss**
- Disabled "VA Lovell Federal health care" menu in all content types.
- Cleared "VA Lovell Federal health care" menu data.
- Deleted "VA Lovell Federal health care" menu.

## Description

closes #7163 

## Testing done

Passes all tests.

## QA steps

As user administrator
1. [ ] Go to `/admin/content-models/content` and verify and confirm that the "VA Lovell Federal health care" menu doesn't exist
1. [ ] Go to `/admin/structure/menu/manage/lovell-federal-health-care` and verify that this menu and its menu items are accessible and there are no errors
1. [ ] Go to the `/lovell-federal-health-care` node, edit it, change its page title to "Lovell Federal health care" and verify that there is no "VA Lovell Federal health care" menu available and the "Lovell Federal health care" menu is assigned to it

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [ ] `Sitewide CMS Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by netboss** [comment]
@swirtSJW 
I think I'll need your help here. I don't know where to look. The (failed) [tugboat build](https://pr7386-cgsotztmknxpyjuj6qjdftyfza7cth4p.ci.cms.va.gov/) above doesn't show anything. See screen shot.
Screenshot from 2022-01-07 10-05-43

**Comment by netboss** [comment]
@swirtSJW This is ready for review.

**Review by swirtSJW — APPROVED** [review]

**Comment by swirtSJW** [comment]
image

**Comment by swirtSJW** [comment]
@netboss Lets not re-create the next steps here.  The steps are spelled out in the main ticket.   I'll go visit them there and make sure they are still accurate.

**Comment by swirtSJW** [comment]
@netboss I updated the steps here. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7163#issuecomment-989304021

**Pull request merged**
