### PR TITLE
VACMS-3667: bulk user import

### PR DESCRIPTION
**Pull request by acrollet**
## Description

See #3667 

UI available here: https://pr3911-v0ybkmefsjp6tdfvvzbgi31pwsiytyqh.ci.cms.va.gov/migrate_source_ui

Sample csv:

```
email,roles,sections
test_user@example.com,"content_editor,content_admin",""
another_user@example.com,"content_editor,content_publisher","VA Wilmington health care, VA Coatesville health care"
```

[Documentation](https://github.com/acrollet/va.gov-cms/blob/VACMS-3667-migrate_approach/READMES/user_import.md)

## Screenshots

Screen Shot 2020-12-31 at 11 28 08 AM

## QA steps

As an admin user
1. Create a CSV file in the specified format
1. [Upload it here](https://pr3911-v0ybkmefsjp6tdfvvzbgi31pwsiytyqh.ci.cms.va.gov/migrate_source_ui)
1. Then validate Acceptance Criteria from issue
- [ ] Users are created
- [ ] roles are set correctly
- [ ] sections are set correctly

### Definition of Done

- [x] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by ndouglas** [comment]
Well, you made that look easy 😃 

It worries me a bit that you can import user csv with the default value set and it'll not throw any warnings or anything:

Screen Shot 2020-12-31 at 2 30 26 PM

and will create some garbage nodes:

Screen Shot 2020-12-31 at 2 29 13 PM

In the event of a mistake, they're easy enough to delete or just ignore -- they're not published by default -- but it's off-putting that the module's so blasé about CSV like this.

I'm not sure the cost-benefit ratio is there for a big change, but it might be worth discussing.

**Review by ndouglas — DISMISSED** [review]
Works as intended when used as intended, and works well with reuploads, uploads with duplicate rows, etc, AFAICT.

**Comment by ndouglas** [comment]
Maybe it might be worth making a custom form that works only with users and validates the CSV to that end.  🤷

**Comment by acrollet** [comment]
Oh hmm, we should form alter and only allow the user import then.

**Comment by acrollet** [comment]
> Maybe it might be worth making a custom form that works only with users and validates the CSV to that end. 🤷

oh ha, I didn't see this. The solution I pushed feels like less tech debt than a whole form and validation code of our own but I'm convinceable, let me know what you think :-)

**Comment by ndouglas** [comment]
It's definitely less tech debt right now, but I could see us using this for other things in the future.  That said, it'll be equally easy to do it when needed, this solution adds less tech debt right now, and going by my dubious past predictive power, I'd say there's a 99% chance that YAGNI for a special form.

I just tested the test environment and it works great :-)

**Review by ndouglas — APPROVED** [review]
Yup, still works 😎

**Pull request merged**
