### PR TITLE
VACMS-5321: Set default value for vc intro text field.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #5321

## Testing done
Visual / behat

## QA steps

- [] As an administrator, go to `admin/structure/types/manage/vet_center/fields/node.vet_center.field_intro_text` and visually verify the default value reads ```We offer confidential help for Veterans, service members, and their families at no cost in a non-medical setting. Our services include counseling for needs such as depression, posttraumatic stress disorder (PTSD), and the psychological effects of military sexual trauma (MST). We can also connect you with more support in VA and your community.```
- [ ] Spot check multiple vc nodes, and verify intro text matches the default.
- [ ] CHeck dblog to see if the update hook reported correctly and stopped running when it was supposed to.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by kevwalsh — APPROVED** [review]
QA pass

**Review by swirtSJW — CHANGES_REQUESTED** [review]
Something seems off.   The revision is not showing on some
image

But is showing on others.  
image

**Comment by swirtSJW** [comment]
Revision mystery resolved.  It is the case of the paragraph npt getting  a new revision if there was no data change.  In this case Escanaba already had the data it was supposed to have.

**Review by swirtSJW — APPROVED** [review]
Update behaved as expected and scoped properly.
image

**Pull request merged**
