### PR TITLE
VAGOV-1503

### PR DESCRIPTION
**Pull request by ethanteague**
Few things going on here, @andyhawks @ElijahLynn:

## Logic
- I created a `Redirect Options` module, and added it as a contrib project to d.o.: https://www.drupal.org/project/redirect_options - it is getting sucked in via composer, and then turned on in config

1. This module does the following:  
2. Creates a new vocabulary: `Type of Redirect` and adds the terms `Server` and `Template`.
4. Adds `Select redirect type` selection field to redirect form, pulling values from `Type of Redirect` vocabulary
5. Creates a new table: `redirect_options` used for storing redirect type and redirect association
6. Adds the redirect type to the `redirect` table `title` column. This will change the `To` column here: admin/config/search/redirect to output the redirect type as the name of the redirect link for each result. This can be modified in the view: `admin/structure/views/view/redirect/edit/page_1`

- I created a sanitized csv of redirects that lives in ./docroot/redirects.csv, populated with data provided by Jeff Balboni from here: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/react_routes.yml
- In the interest of keeping the redirect_options contrib module generic enough for community use, I have created a separate custom module to import the redirects: `va-gov_backend`.
- This importer (va_gov_backend) module needs to be manually enabled, either via drush or in the ui to trigger the import process.
- For some reason, the terms aren't being created on install, but turning redirect_options on and off again resolves this issue. This doesn't impact the import, or how values for redirects are stored.

## Assumptions
Redirects repo doc provided by adhoc doesn't indicate type (e.g., "Template" or "Server") per each item.
To this end, I assigned all redirects the "Server" designation. Assuming a list of which items are template level in said doc is provided to me, I can easily create an update hook to update the redirects table to change subject items to "Template" type.

## Graphql
Query looks like this:
```
{
  redirectQuery {
    entities {
      ... on Redirect {
        type
        statusCode
        created
        redirectSource {
          path
        }
        redirectRedirect {
          title
          uri
          url {
            path
            routed
          }
        }
      }
    }
  }
}
```
Output looks like this:
```
{
  "data": {
    "redirectQuery": {
      "entities": [
        {
          "type": "redirect",
          "statusCode": 301,
          "created": 1551035131,
          "redirectSource": {
            "path": "education/apply-for-education-benefits/application/1990n"
          },
          "redirectRedirect": {
            "title": "Server",
            "uri": "internal:/education/apply-for-education-benefits/application/1990N",
            "url": {
              "path": "/education/apply-for-education-benefits/application/1990N",
              "routed": false
            }
          }
        },
        {
          "type": "redirect",
          "statusCode": 301,
          "created": 1551035131,
          "redirectSource": {
            "path": "pension/application/527ez"
          },
          "redirectRedirect": {
            "title": "Server",
            "uri": "internal:/pension/application/527EZ",
            "url": {
              "path": "/pension/application/527EZ",
              "routed": false
            }
          }
        },
        {
          "type": "redirect",
          "statusCode": 301,
          "created": 1551035131,
          "redirectSource": {
            "path": "facility-locator"
          },
          "redirectRedirect": {
            "title": "Server",
            "uri": "internal:/facilities/",
            "url": {
              "path": "/facilities/",
              "routed": false
            }
          }
        },
        {
          "type": "redirect",
          "statusCode": 301,
          "created": 1551035131,
          "redirectSource": {
            "path": "disability-benefits/claims-process/ratings/"
          },
          "redirectRedirect": {
            "title": "Server",
            "uri": "internal:/disability-benefits/eligibility/ratings/",
            "url": {
              "path": "/disability-benefits/eligibility/ratings/",
              "routed": false
            }
          }
        },
        {
          "type": "redirect",
          "statusCode": 301,
          "created": 1551035131,
          "redirectSource": {
            "path": "disability-benefits/claims-process/presumed-disability/"
          },
          "redirectRedirect": {
            "title": "Server",
            "uri": "internal:/disability-benefits/eligibility/presumed-disability/",
            "url": {
              "path": "/disability-benefits/eligibility/presumed-disability/",
              "routed": false
            }
          }
        },
        {
          "type": "redirect",
          "statusCode": 301,
          "created": 1551035131,
          "redirectSource": {
            "path": "disability-benefits/claims-process/claim-types/"
          },
          "redirectRedirect": {
            "title": "Server",
            "uri": "internal:/disability-benefits/apply/claim-types/",
            "url": {
              "path": "/disability-benefits/apply/claim-types/",
              "routed": false
            }
          }
        },
        {
          "type": "redirect",
          "statusCode": 301,
          "created": 1551035131,
          "redirectSource": {
            "path": "disability-benefits/claims-process/evidence/"
          },
          "redirectRedirect": {
            "title": "Server",
            "uri": "internal:/disability-benefits/apply/evidence/",
            "url": {
              "path": "/disability-benefits/apply/evidence/",
              "routed": false
            }
          }
        },
        {
          "type": "redirect",
          "statusCode": 301,
          "created": 1551035131,
          "redirectSource": {
            "path": "disability-benefits/claims-process/date/"
          },
          "redirectRedirect": {
            "title": "Server",
            "uri": "internal:/disability-benefits/after-you-apply/date/",
            "url": {
              "path": "/disability-benefits/after-you-apply/date/",
              "routed": false
            }
          }
        },
        {
          "type": "redirect",
          "statusCode": 301,
          "created": 1551035131,
          "redirectSource": {
            "path": "disability-benefits/claims-process/what-happens-after-rating/"
          },
          "redirectRedirect": {
            "title": "Server",
            "uri": "internal:/disability-benefits/after-you-apply/what-happens-after-rating/",
            "url": {
              "path": "/disability-benefits/after-you-apply/what-happens-after-rating/",
              "routed": false
            }
          }
        },
        {
          "type": "redirect",
          "statusCode": 301,
          "created": 1551035131,
          "redirectSource": {
            "path": "disability-benefits/apply-for-benefits/help/"
          },
          "redirectRedirect": {
            "title": "Server",
            "uri": "internal:/disability-benefits/apply/help/",
            "url": {
              "path": "/disability-benefits/apply/help/",
              "routed": false
            }
          }
        }
      ]
    }
  }
}
```

### CODE REVIEW

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-155<br><br> [button_visit-site](http://pr-155.va.agile6.com)

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-155<br><br> [button_visit-site](http://pr-155.va.agile6.com)

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-155<br><br> [button_visit-site](http://pr-155.va.agile6.com)

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-155<br><br> [button_visit-site](http://pr-155.va.agile6.com)

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-155<br><br> [button_visit-site](http://pr-155.va.agile6.com)

**Comment by ElijahLynn** [comment]
K, testing locally, we need to fix the 'updb' _before_ merge, as that will be a pain to deploy to DEV and STG if that is an issue.

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-155<br><br> [button_visit-site](http://pr-155.va.agile6.com)

**Comment by ElijahLynn** [comment]
> K, testing locally, we need to fix the 'updb' _before_ merge, as that will be a pain to deploy to DEV and STG if that is an issue.

I tested this locally by pulling your branch and `lando db-sync-stg` and it works fine, HOWEVER, I don't see the `va_gov_db` module enabled with a `drush pm:list` and when I enable the module I get an error:
> Unable to install modules va_gov_db due to missing modules va_gov_db. 

This needs to be fixed and then there needs to be an update hook in some other base custom module that enables this module. Then the update hook for that will run automatically on enable.

**Comment by ElijahLynn** [comment]
DOH, my hub command never checked out the branch, disregard, testing all again.

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-155<br><br> [button_visit-site](http://pr-155.va.agile6.com)

**Comment by ElijahLynn** [comment]
Not sure how the build passed, this error happens during composer install.                                                            

>   [Seld\JsonLint\ParsingException]                                 
>   "./composer.lock" does not contain valid JSON                    
>   Parse error on line 15361:                                       
>   ...o_entitylabel": 10,<<<<<<< HEAD=======                        
>   ---------------------^                                           
>   Expected: 'STRING' - It appears you have an extra trailing comma 

because of this unresolved merge conflict:

image

**Comment by ethanteague** [comment]
Just pushed a fix for the above, @ElijahLynn

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-155<br><br> [button_visit-site](http://pr-155.va.agile6.com)

**Comment by andyhawks** [comment]
rebuild

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-155<br><br> [button_visit-site](http://pr-155.va.agile6.com)

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-155<br><br> [button_visit-site](http://pr-155.va.agile6.com)

**Pull request merged**
