### PR TITLE
VACMS-3013: Enable TOC On LC Content Types

### PR DESCRIPTION
**Pull request by kaise-lafrai**
## Description

See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3013

## QA steps

As an editor
- [ ] Log into preview environment. (This can be found in devshop) 

## checklist 

- Navigate to `node/add/checklist`
  - [x] Confirm a new details group field exists, labeled as: INCLUDE TABLE OF CONTENTS?
  - [x] Confirm new fields exists by selecting the details group field: Label: Generate a table of contents from major headings | machine-name: field_table_of_contents_boolean
  - Select the checkbox
  - Complete all required fields.
  - Save form.
  - [x] Confirm the display reveals the new field in the following way:
    - **GENERATE A TABLE OF CONTENTS FROM MAJOR HEADINGS**
           Include table of contents

## step_by_step

- Navigate to `node/add/step_by_step`
  - [x] Confirm a new details group field exists, labeled as: INCLUDE TABLE OF CONTENTS?
  - [x] Confirm new fields exists by selecting the details group field: Label: Generate a table of contents from major headings | machine-name: field_table_of_contents_boolean
  - DO NOT Select the checkbox
  - Complete all required fields.
  - Save form.
  - [x] Confirm the display reveals the new field in the following way:
    - **GENERATE A TABLE OF CONTENTS FROM MAJOR HEADINGS**
           No table contents

## media_list_images

- Navigate to `node/add/media_list_images`
  - [x] Confirm a new details group field exists, labeled as: INCLUDE TABLE OF CONTENTS?
  - [x] Confirm new fields exists by selecting the details group field: Label: Generate a table of contents from major headings | machine-name: field_table_of_contents_boolean
  - Select the checkbox
  - Complete all required fields.
  - Save form.
  - [x] Confirm the display reveals the new field in the following way:
    - **GENERATE A TABLE OF CONTENTS FROM MAJOR HEADINGS**
           Include table of contents

## media_list_videos

- Navigate to `node/add/media_list_videos`
  - [x] Confirm a new details group field exists, labeled as: INCLUDE TABLE OF CONTENTS?
  - [x] Confirm new fields exists by selecting the details group field: Label: Generate a table of contents from major headings | machine-name: field_table_of_contents_boolean
  - DO NOT Select the checkbox
  - Complete all required fields.
  - Save form.
  - [x] Confirm the display reveals the new field in the following way:
    - **GENERATE A TABLE OF CONTENTS FROM MAJOR HEADINGS**
           No table contents

## landing_page

- Navigate to `node/add/landing_page`
  - [x] Confirm a new details group field exists, labeled as: INCLUDE TABLE OF CONTENTS?
  - [x] Confirm new fields exists by selecting the details group field: Label: Generate a table of contents from major headings | machine-name: field_table_of_contents_boolean
  - Select the checkbox
  - Complete all required fields.
  - Save form.
  - [x] Confirm the display reveals the new field in the following way:
    - **GENERATE A TABLE OF CONTENTS FROM MAJOR HEADINGS**
           Include table of contents

## Definition of Done
- [ ] Product release are written (or in progress), if required.
- [ ] Documentation has been updated, if applicable.

### CODE REVIEW

**Review by oksana-c — CHANGES_REQUESTED** [review]
@kaise-lafrai on the FAQ CT `/node/add/faq_multiple_q_a`  ToC needs to go above the CTA field
Everything else looks good.

**Review by swirtSJW — DISMISSED** [review]
Passes review.   Though it seems odd to hide one field in a field group.
image

**Comment by kaise-lafrai** [comment]
> @kaise-lafrai on the FAQ CT `/node/add/faq_multiple_q_a` ToC needs to go above the CTA field
> Everything else looks good.

@oksana-c I have repaired this mistake. Thank you

**Comment by kaise-lafrai** [comment]
> Passes review. Though it seems odd to hide one field in a field group.
> image

@swirtSJW Acceptance criteria stated to use the detail page content type as an example, although it would make sense to have the details group type be open by default. I have made updates per Oksana's request and have pushed the latest changes out. Thank you

**Comment by kaise-lafrai** [comment]
@swirtSJW @oksana-c Behat tests are not failing locally for me. Looking into this now.

**Review by swirtSJW — APPROVED** [review]

**Pull request merged**
