### PR TITLE
VACMS-5188: Add office hours module field to facilities.

### LINKED ISSUE #5188: Migrate field_hours to field_office_hours on VAMC facility
Screenshot_2021-04-29__1_19_PM

Screenshot_2021-04-29__1_20_PM

ACs
- [ ] new field_office_hours exists
- [ ] populated by migration (migration updates both `field_hours` and `field_office_hours`)
- [ ] backwards compatibility
  - [ ] old field_hours field is hidden
  - [ ] new field_office_hours field is visible to non-admin editors in view mode on both the edit and view screens
  - [ ] new field_office_hours field is visible to admins in edit mode on edit screen (like on Vet Centers)
- [ ] Design review

Not included
-[ ] Redesign field_office_hours form widget (because this form widget is only visible to admins)

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
Closes #5188

## Implementation
 - After deploy to prod, run facilities migration, setting the update option

## Testing done
Visual / Behat

## Screenshots
image
image

## QA steps
- [x]  validate that new field displays on node view and the old version is not displayed
- [x] validate when editing as admin, the new field is available and editable.
- [x] when editing as RyanS, the new field is not editable
 - [x] validate after facilities migration, new office hours widget should be populated with hours data.
 - [x] validate the old field is still present and is also still having data migrated to it.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by swirtSJW — CHANGES_REQUESTED** [review]
I was expecting to see two migration ymls.

**Comment by swirtSJW** [comment]
Also expect to see the new field disabled by the same logic that disables the current form values.

@ethanteague  one thing we did not cover on 16 minute this morning is that the migration needs to keep migrating data into both fields  so that they stay in-sync until we are ready to remove the old.

**Comment by ethanteague** [comment]
> I was expecting to see two migration ymls.

Not sure I'm following you, @swirtSJW - I updated both migration yamls:
image

**Comment by ethanteague** [comment]
> Also expect to see the new field disabled by the same logic that disables the current form values.

No problem, but I thought we did / are doing away with disabling api fields, with the exception of the ID - probably just mis-remembering, but double checking.


> @ethanteague one thing we did not cover on 16 minute this morning is that the migration needs to keep migrating data into both fields so that they stay in-sync until we are ready to remove the old.

I didn't do anything to stop the migration of the existing field........or so I thought. Did I miss something? Looks to me like I just added an additional field that will be populated by hours data from the api, @swirtSJW

**Comment by swirtSJW** [comment]
@ethanteague 

>>  I was expecting to see two migration ymls.
> Not sure I'm following you, @swirtSJW - I updated both migration yamls:

Sorry for the confusion I think I was looking at an outdated diff.   

> I didn't do anything to stop the migration of the existing field........or so I thought. Did I miss something?

Nope it was me not seeing your migration ymls.   There is no problem with what you did.

> Also expect to see the new field disabled by the same logic that disables the current form values.

> No problem, but I thought we did / are doing away with disabling api fields, with the exception of the ID - probably just mis-remembering, but double checking.

No.  Anything that comes in from the Facility API should not be editable by ordinary editors.  Only admin for resolving a temporary emergency.

**Comment by ethanteague** [comment]
Updated, @swirtSJW

**Review by swirtSJW — CHANGES_REQUESTED** [review]
I think this is a different view mode for non-admins.  It will have to be updated.
image

And I forgot about the view mode being the protection against non-admin editing, so that code I had you add was not needed and can be removed.  Sorry about that.

**Review by swirtSJW — APPROVED** [review]
QA pass.

**Comment by swirtSJW** [comment]
image

**Comment by swirtSJW** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5188#issuecomment-1033121343

**Pull request merged**
