### PR TITLE
VAGOV-325 basic auth config

### PR DESCRIPTION
**Pull request by acabouet**

### CODE REVIEW

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-85<br><br> [button_visit-site](http://pr-85.va.agile6.com)

**Comment by ElijahLynn** [comment]
follow up to #78

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-85<br><br> [button_visit-site](http://pr-85.va.agile6.com)

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-85<br><br> [button_visit-site](http://pr-85.va.agile6.com)

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-85<br><br> [button_visit-site](http://pr-85.va.agile6.com)

**Comment by acabouet** [comment]
Please note merging this in will currently break AdHoc's integration of the metalsmith-graphql stuff on vets-website.

**Comment by ElijahLynn** [comment]
Nice, and I see it is doing real basic auth as well. 
image

**Comment by ElijahLynn** [comment]
> Please note merging this in will currently break AdHoc's integration of the metalsmith-graphql stuff on vets-website. To fix they just have to add an authorization header with Drupal credentials to their Apollo request

We should ping them and have them test against this PR first.

**Pull request merged**
