### PR TITLE
VAGOV-3935: Create base install profile and command to instantiate CMS in one command.

### PR DESCRIPTION
**Pull request by jonpugh**
NOTE: This branch is INCLUDED in #391 If that PR is merged, this one will be too.

```bash
$ composer va:start
Gathering patches for root package.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
...
> drush site:install va_gov --yes --account-name admin --account-pass admin --ansi --site-name='Veterans Affairs'

 // You are about to CREATE the 'sites/default/files/.sqlite' database. Do you  
 // want to continue?: yes.                                                     

 [notice] Starting Drupal installation. This takes a while.

> drupal server localhost:9000 --ansi
                                                                               
 [OK] Executing php from "/usr/bin/php".                                        
                                                                                                                                                               
 Listening on "http://localhost:9000".                                

```

## Dependencies
Now, to get a base instance of the CMS running, the server/laptop only needs:

- Git
- PHP-CLI
- SQLite
- Composer

## Launch

1. `git clone https://github.com/department-of-veterans-affairs/va.gov-cms`
2. `cd va.gov-cms`
3. `composer va:start` 

The composer `va:start` command even includes the `composer install` in order to get this working in as few commands as possible.

### CODE REVIEW

**Comment by ElijahLynn** [comment]
build

**Comment by jonpugh** [comment]
Looks like the project does get cloned into the same folder every time.

Whatever jenkins does to that folder is causing this: 
```
12:14:37  ┃   [RuntimeException]                                                         
12:14:37  ┃                                                                              
12:14:37  ┃   Source directory docroot/core has uncommitted changes.                     
12:14:37  ┃                                                              
```
http://jenkins.cms.va.gov/job/Static%20Tests/13/console

@TODO:

- [ ] Figure out why docroot/core has uncommitted changes.
- [ ] Clone the repo into a build-specific folder. Instead of `/var/jenkins_home/workspace/Static Tests/va.gov-cms` use a dynamic path like `/var/jenkins_home/workspace/Static Tests/${BUILD_ID}va.gov-cms`

**Comment by mbenziane** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Comment by jonpugh** [comment]
Builds are failing because of GitHub rate limit check: 

From http://jenkins.cms.va.gov/log/all
```
GitHub rate limit after check department-of-veterans-affairs/va.gov-cms: GHRateLimit{remaining=4963, limit=5000, resetDate=Wed Jun 19 22:57:01 UTC 2019}, consumed: 0, checked PRs: 11
Jun 19, 2019 10:09:02 PM INFO org.jenkinsci.plugins.github.pullrequest.utils.LoggingTaskListenerWrapper info
Finished GitHub Pull Request trigger check for department-of-veterans-affairs/va.gov-cms at Jun 19, 2019 10:09:02 PM. Duration: 2250ms
```

**Comment by jonpugh** [comment]
build

**Comment by jonpugh** [comment]
Closing in favor of #391, which includes all of this code.

**Pull request closed without merging**
