### PR TITLE
VAGOV-5481: Canary Build: Stabilize CMS with node edit/web rebuild/node view test.

### PR DESCRIPTION
**Pull request by jonpugh**
# Stabilize CMS: The Canary Build

This Pull Request contains the test that will confirm that Drupal edits get propagated to the `vets-website` front end.

Once this build passes, we know that all of the issues surrounding WEB generation from our desired Drupal site are solved.

### CODE REVIEW

**Comment by swirtSJW** [comment]
Behat failing on these behat tests?

**Comment by ElijahLynn** [comment]
I am getting "driver drush not registered" in Lando when testing this PR locally. 

@jonpugh @ethanteague Do you remember this one? Is the solution to add an aliases file with BEHAT_PARAMS locally?

**Comment by jonpugh** [comment]
> I am getting "driver drush not registered" in Lando when testing this PR locally.
> 
> @jonpugh @ethanteague Do you remember this one? Is the solution to add an aliases file with BEHAT_PARAMS locally?

See `.env-local` @ElijahLynn . It is copied during `composer install`. It is NOT copied if the file already exists, so be sure to remove it when `.env-local` is updated

**Comment by swirtSJW** [comment]
All of these tests just ran and passed locally in lando, but it looks like something is stuck in the ci tests.   @jonpugh can we prioritize getting this resolved?

**Comment by swirtSJW** [comment]
@jonpugh Still running fine locally, but failing in CI.

**Comment by jonpugh** [comment]
LOL how did that make it back in there?

**Comment by swirtSJW** [comment]
Nice work Jon

**Comment by ElijahLynn** [comment]
This is causing errors for me locally with:
>>>  $ drush $DRUSH_ALIAS cr Output:/path/to/file                                                     
 ┃ PHP Fatal error:  Uncaught Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in  
e/lib/Drupal/Core/Database/Driver/mysql/Connection.php:405

**Pull request merged**
