### PR TITLE
VACMS-3387: Schemata entries pollute dblog.

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

See #3387.  A vague attempt to curry favor with Swirt.

I opened an issue and submitted a patch [upstream](https://www.drupal.org/project/schemata/issues/3190131#comment-13950489), then added it to `composer.json`.

## Testing done
Ran `composer install` and observed that the offending statement was removed from SchemaFactory::create().

## QA steps
As an administrator:
1. Look at the [dblog](/admin/reports/dblog?type%5B%5D=schemata&severity%5B%5D=5) after export.
2. Verify the restoration of a quieter, more peaceful dblog:
- [x] when the cms export is pulled, nothing related to schemata appears in the logs.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by swirtSJW** [comment]
Testing:   
- [x]  Visited https://pr3865-hfiybgrlo1jd4lf7isa8liv9n8ngpxi5.ci.cms.va.gov/cms-export/content to request tar which requested a Schema refresh.
- [x]  
image


This all worked for me.

The patch was effective.   It probably won't get merged, but it works for our purpose.   Adding a bit of config to disable the reporting might be better received by the maintainer, but we'll see what happens.

Nice work Nate.

**Comment by ndouglas** [comment]
I'll just keep rerolling the patch as long as I need to :joy:

**Review by swirtSJW — CHANGES_REQUESTED** [review]
This looks good Nate, but I think you need to run a `lando composer update --lock` to make it add the patch details to the lock file.   It is not needed to function, but it freaks the next person out when they update the lock file and see an addition they did not make.

**Comment by ndouglas** [comment]
Ah, thanks.  That's a good tip.

**Review by swirtSJW — APPROVED** [review]

**Comment by ndouglas** [comment]
Sorry @swirtSJW , I created a conflict and had to resolve it.  Thanks for the review.

**Review by swirtSJW — APPROVED** [review]

**Pull request merged**
