### PR TITLE
VACMS-4537 field office vc

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #4537 #4550
## Testing done
Visual / behat

## QA steps
@kevwalsh to manually review (please)

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by indytechcook** [comment]
I love the move to standardize/reusable fields!!

**Review by swirtSJW — CHANGES_REQUESTED** [review]
I am not sure this is working.   
When I assign a user to Cincinnati vet center and and make them a content editor, That user's node  owner is preselected for cincinati which is good, but cincinati is not available in the Vet Center selector.
image

I  verified the Cincinnati Vet Center node exists.  So it seems like something in the logic is not right.

**Comment by ethanteague** [comment]
> I am not sure this is working.
> When I assign a user to Cincinnati vet center and and make them a content editor, That user's node owner is preselected for cincinati which is good, but cincinati is not available in the Vet Center selector.
> image
> 
> I verified the Cincinnati Vet Center node exists. So it seems like something in the logic is not right.

It has to be published to appear in the vet selector, @swirtSJW - this _seems_ correct to me. Think I should open the dropdown up to drafts, as well?

**Comment by swirtSJW** [comment]
> > I am not sure this is working.
> > When I assign a user to Cincinnati vet center and and make them a content editor, That user's node owner is preselected for cincinati which is good, but cincinati is not available in the Vet Center selector.
> > image
> > I verified the Cincinnati Vet Center node exists. So it seems like something in the logic is not right.
> 
> It has to be published to appear in the vet selector, @swirtSJW - this _seems_ correct to me. Think I should open the dropdown up to drafts, as well?

We discussed this in scrum today but just following up  to close the loop.   People are staging these pages so they will need to be able to assign vet centers that are not published yet.   This should allow selecting any vet center that is draft or published though probably not archived.

We also discussed that this list should be alpha sorted.

**Comment by ethanteague** [comment]
@swirtSJW @kevwalsh - tabling the vet center content creator filtering / options display, per this slack thread: https://dsva.slack.com/team/UDHGXBCSX

That said, the results are now alpha sorted, and I replaced all `node:field_vet_center` alias / path config for vc's with `node:field_office` , and I lumped #4550 into this pr.

**Review by swirtSJW — APPROVED** [review]
This all checks out and I approve.   
@kevwalsh  I did want to call this out as ugly and make sure this is what is expected
image

**Comment by ethanteague** [comment]
> This all checks out and I approve.
> @kevwalsh I did want to call this out as ugly and make sure this is what is expected
> image

Yowza.

**Pull request merged**
