### PR TITLE
VACMS-2927: Add visn 8 to config.

### PR DESCRIPTION
**Pull request by ethanteague**
## Implementation note
Adding Visn 8 to the admin menu will need to be performed on prod. I tried to add it via our contrib module `menu_export`, which did save it to config, however, import throws a long stack of errors that I spent about an hour trying to debug. Probably just easier to create Visn 8, and then move the systems (e.g., Bay Pines, Miami, et.al) in config after this code is released.

## Description
See #2927 

## Testing done
Visual / behat

## QA steps
Another manual by @kevwalsh scenario (apologies, Kev).

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by kevwalsh — CHANGES_REQUESTED** [review]
QAd and looked good, but per slack: 

custom menu item in the admin menu for VISN 8 needs to be added on prod. Can you do that, then sync down the db, add the new menus as children of that custom menu item , export and re-push? Actually while we’re at it, we might as well add custom menu items for VISN 7, 8, 9, 12, 15, 17, 20, 22, cause we’ll be adding those menus soon.

**Comment by ethanteague** [comment]
Updated, @kevwalsh

**Review by kevwalsh — CHANGES_REQUESTED** [review]
@ethanteague the tugboat environment doesn't seem to have the latest prod db, so this isn't looking right yet. I see the new custom menu items at https://prod.cms.va.gov/admin/structure/menu/manage/admin but not at https://pr3727-njo2nrtoblkynqf9ldu7ylw9q1kuvb7g.ci.cms.va.gov/admin/structure/menu/manage/admin?destination=/admin/structure/menu

I'm not sure how to refresh the dbs from Prod on tugboat yet.

**Comment by ethanteague** [comment]
> @ethanteague the tugboat environment doesn't seem to have the latest prod db, so this isn't looking right yet. I see the new custom menu items at https://prod.cms.va.gov/admin/structure/menu/manage/admin but not at https://pr3727-njo2nrtoblkynqf9ldu7ylw9q1kuvb7g.ci.cms.va.gov/admin/structure/menu/manage/admin?destination=/admin/structure/menu
> 
> I'm not sure how to refresh the dbs from Prod on tugboat yet.

Just rebuilt it, @kevwalsh - all looks good if you wanna take a look.

**Comment by kevwalsh** [comment]
@swirtSJW @ethanteague I just had a look and it looks good. We may want to merge it, to meet sprint goal for VISN 8. But i can imagine that ethan's new work on the other seven VISNs is building off this.

**Comment by kevwalsh** [comment]
@ethanteague menus are missing workbench access settings. Alos, can you update the PR name? i'm updating the issue title for #2927 .

**Review by kevwalsh — CHANGES_REQUESTED** [review]
See comment above.

**Comment by ethanteague** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3809 @kevwalsh @swirtSJW

**Pull request closed without merging**
