### PR TITLE
VACMS-17587: Fixes revision squashing during migrate

### PR DESCRIPTION
**Pull request by Becapa**
## Description

Relates to #17587.

## Testing done
Manual

## QA steps

As an administrator
1. Change the title of the Hemet VA Clinic (/node/62682/edit) by updating the 'Name of facility' field, entering a 'Revision log message' and saving the node as 'Published'
   - [x] Validate that the 'Changed name' flag is not set for this node. (/admin/content/facilities/flagged)
2. Then run a migration import for that node.
   - Open up an SSH to the tugboat (Open environment's page on Tugboat, click the "Terminal" link on the line for the "php" service)
   - On the command line run `drush migrate:import va_node_health_care_local_facility --update --idlist=vha_605GG`
   - [x] Validate that the 'Changed name' flag is set for this node. (/admin/content/facilities/flagged)
   - [x] Validate that the latest revision for this node only includes the most recent name change from the CMS Migrator (Go to /node/62682/revisions and compare the latest two revisions)

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.
- [ ] If there are field changes, front end output has been thoroughly checked.

### Select Team for PR review

- [x] `CMS Team`
- [x] `Public websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by dsasser — COMMENTED** [review]
Changes look like what I would expect, however I'm seeing some odd behavior:

> Change the title of the Hemet VA Clinic (/node/62682/edit) by updating the 'Name of facility' field, entering a 'Revision log message' and saving the node as 'Published'

I changed the title for this node, and Drupal appears to create 4 revisions:

Screenshot 2024-03-26 at 11 24 11 AM

However, on the revisions page, it shows only one change, but no mention of the flag being set in this revision log. 

Screenshot 2024-03-26 at 11 27 42 AM

I'm probably just not up to speed on why the "recent changes" and the revisions page don't align, so I'm not sure how much of a problem this is at the db level, but I for the editor/support/admin, this is likely to cause confusion.

Similarly, the migration is creating several "recent changes" but only one revision, and the revision log has no mention of flags being set (on the revisions page)

Screenshot 2024-03-26 at 11 33 14 AM

Screenshot 2024-03-26 at 11 32 49 AM

**Comment by Becapa** [comment]
Added some changes to deal with the weirdness around the multiple revisions for a flags being updated:
- Instead of setting the isMigrating flag at the beginning and end of importing, set it at the beginning and end of the row save.
- Toggle off the isMigrating flag during revision log updates.
- Check for the isMigrating flag during the entity update.

**Review by edmund-dunn — APPROVED** [review]
All steps passed as expected with NO extra revisions. 
Screenshot 2024-03-26 at 14 18 52
Screenshot 2024-03-26 at 14 19 30
Nice work!!

**Review by dsasser — APPROVED** [review]
Looks great!

**Review by omahane — APPROVED** [review]
Really great work, @Becapa .  QA checks out and code looks good.

**Pull request merged**
