### PR TITLE
VACMS-6948: Adds patch to explicitly set menu-link bundle. [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

Relates to #6948.  An alternative to #7374 that may or may not work.  Should not be merged until we're aligned on an approach.

### Select Team for PR review

- [x] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### CODE REVIEW

**Comment by ndouglas** [comment]
I created a VAMC detail page, clicked "Save Draft and Continue", and verified that the menu link was created correctly.

```
root@php:/var/lib/tugboat# drush sql-cli
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 3326
Server version: 10.5.13-MariaDB-1:10.5.13+maria~focal mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [tugboat]> SELECT * FROM menu_link_content ORDER BY id DESC LIMIT 5;
+-------+-------------+------------------------+--------------------------------------+----------+
| id    | revision_id | bundle                 | uuid                                 | langcode |
+-------+-------------+------------------------+--------------------------------------+----------+
| 10418 |       10418 | va-alaska-health-care  | 97486dff-491a-4e5b-aaf0-6fe38d868b92 | en       |
| 10417 |       10417 | va-alaska-health-care  | 1a718d33-e350-4269-a71a-8496b43ddaa3 | en       |
| 10416 |       10416 | va-alaska-health-care  | 41b6958b-3305-439a-b2f5-7427b93ad36a | en       |
| 10415 |       10415 | outreach-and-events    | 806d7576-2b1f-4685-88ce-c145a2538ad5 | en       |
| 10414 |       10414 | va-madison-health-care | 19dfca22-d1fc-4e40-8fcd-28fa8bbe4879 | en       |
+-------+-------------+------------------------+--------------------------------------+----------+
5 rows in set (0.000 sec)

MariaDB [tugboat]> quit
Bye
```

Furthermore, running the content build successfully passed the point where the issue would've blown up (see the line containing `GetFacilitySidebar__vaAlaskaHealthCareFacilitySidebarQuery`):
```
root@php:/var/lib/tugboat# task --taskfile=./tests.yml va/web/build
task: [va/web/build] cat <<EOF | bash
  : "${SKIP_REPORTING:=0}"
  : "${RETURN_EXIT_CODE:=0}"
  set -o pipefail
  output="\$(mktemp -d)/output"
  mkfifo \$output
  (cat \$output&)
  result="\$(./tests/scripts/build-web.sh 2>&1 | tee \$output)"
  exit_code=\$?
  if [ "$SKIP_REPORTING" -ne 1 ]; then
    if [ "\$exit_code" -eq 0 ]; then
      github-status-updater -action=update_state -state=success -context='va/web/build' -description='Success'
    else
      github-status-updater -action=update_state -state=failure -context='va/web/build' -description='Failed'
    fi
  fi
  if [ "$RETURN_EXIT_CODE" -ne 0 ]; then
    exit "\$exit_code";
  fi
EOF

> rm -rf docroot/vendor/va-gov/content-build/build/vagovdev
> cd docroot/vendor/va-gov/vets-website && echo "Downloading assets for vets-website for vagovdev" 
Downloading assets for vets-website for vagovdev
> cd web && INSTALL_HOOKS=no NODE_ENV=production yarn build --pull-drupal --no-drupal-proxy --buildtype=vagovdev --api=https://dev-api.va.gov
yarn run v1.21.1
$ node script/prebuild.js
$ node --max-old-space-size=5000 --expose-gc script/build-content.js --pull-drupal --no-drupal-proxy --buildtype=vagovdev --api=https://dev-api.va.gov
Pulling feature flags from Drupal...
overloading terminal writes

Step 1 of 53 start: Get Drupal content
Drupal content cache found: /var/lib/tugboat/docroot/vendor/va-gov/content-build/.cache/vagovdev/drupal/pages.json
Attempting to load Drupal content from API at https://pr7868-6higzix326mwwfzup4mjl7h2buad3wsw.ci.cms.va.gov
Pulling from Drupal via GraphQL...
Received node counts...
┌────────────────────────────┬───────┐
│          (index)           │ count │
├────────────────────────────┼───────┤
│        benefitPages        │  294  │
│           vaForm           │  431  │
│         vetCenters         │  130  │
│        newsStories         │  860  │
│       pressReleases        │  626  │
│  healthCareLocalFacility   │ 1238  │
│   healthServicesListing    │  139  │
│        eventListing        │  140  │
│           event            │ 1837  │
│ healthCareRegionDetailPage │ 5139  │
│    healthCareRegionPage    │  139  │
│       personProfile        │ 3841  │
│           nodeQa           │  144  │
└────────────────────────────┴───────┘
Beginning GraphQL queries with parallelization at 15 requests...
| GetTaxonomies | 0s | [n/a] pages |
| GetPromoBanners | 0s | [n/a] pages |
| GetBanners | 0s | [n/a] pages |
| GetHomepage | 0s | [n/a] pages |
| GetOutreachSidebar | 0s | [n/a] pages |
| GetMenuLinks | 1s | [n/a] pages |
| GetAlerts | 0s | [n/a] pages |
| GetFacilitySidebar__vaSiouxFallsHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaNebraskaWesternIowaHealthFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaStCloudHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaIowaCityHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaFargoHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaCentralIowaHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaSouthernArizonaHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaMinneapolisHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaBlackHillsHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaSanDiegoHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaPhoenixHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaNorthernArizonaHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaLomaLindaHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaLongBeachHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaSouthernNevadaHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaNewMexicoHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaGreaterLosAngelesHealthCaFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaSierraNevadaHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaPacificIslandsHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaSanFranciscoHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaPaloAltoHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaCentralCaliforniaHealthCarFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaWallaWallaHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaSouthernOregonHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaRoseburgHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaSpokaneHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaNorthernCaliforniaHealthCaFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaBoiseHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaPugetSoundHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaAlaskaHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaSheridanHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetBannnerAlerts | 3s | [n/a] pages |
| GetFacilitySidebar__vaWesternColoradoHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaPortlandHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaSaltLakeCityHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaEasternOklahomaHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaCheyenneHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaOklahomaHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaMontanaHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaWestTexasHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaTexasValleyHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaEasternColoradoHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaElPasoHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaAmarilloHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaCentralTexasHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaSouthTexasHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaNorthTexasHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaSoutheastLouisianaHealthCaFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaGulfCoastHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaJacksonHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaShreveportHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaWichitaHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaPoplarBluffHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaAlexandriaHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaFayettevilleArkansasHealthFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaMarionHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaStLouisHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaKansasCityHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaCentralArkansasHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaHoustonHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaEasternKansasHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaColumbiaMissouriHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaTomahHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaMilwaukeeHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaIronMountainHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaIllianaHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__lovellFederalHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaHinesHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaChicagoHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaMadisonHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaDetroitHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaSaginawHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaNorthernIndianaHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaBattleCreekHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaIndianaHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaDaytonHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaChillicotheHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaNortheastOhioHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaCincinnatiHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaCentralOhioHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaAnnArborHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaMountainHomeHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaLexingtonHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaWestPalmBeachHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaLouisvilleHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaTennesseeValleyHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaMemphisHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaOrlandoHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaTampaHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaTuscaloosaHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaMiamiHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaCaribbeanHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaDublinHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaBayPinesHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaNorthFloridaHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaCentralAlabamaHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaColumbiaSouthCarolinaHealtFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaAugustaHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaCharlestonHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaSalisburyHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaSalemHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaAtlantaHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaHamptonHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaRichmondHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaBirminghamHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaAshevilleHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaFayettevilleCoastalHealthCFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaDurhamHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaHuntingtonHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaWashingtonDcHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaBeckleyHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaMartinsburgHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaMarylandHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaClarksburgHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaWilmingtonHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaPhiladelphiaHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaWilkesBarreHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaLebanonFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaErieHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaCoatesvilleHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaButlerHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaAltoonaHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaNorthportHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaWesternNewYorkHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaNewYorkHarborHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaSyracuseHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaBronxHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__pittsburghHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaHudsonValleyHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaFingerLakesHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaNewJerseyHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaAlbanyHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaWhiteRiverJunctionHealthCFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaProvidenceHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetIcsFiles | 0s | [n/a] pages |
| GetFacilitySidebar__vaManchesterHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetRegisterForCarePages | 0s | 0 pages |
| GetMedicalRecordsOfficePages | 0s | 0 pages |
| GetBillingAndInsurancePages | 0s | 0 pages |
| GetFacilitySidebar__vaMaineHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaConnecticutHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaCentralWesternMassachusettsFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaBedfordHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetFacilitySidebar__vaBostonHealthCareFacilitySidebarQuery | 0s | [n/a] pages |
| GetNodeMediaListVideos | 0s | 0 pages |
| GetNodeBasicLandingPage | 0s | 1 pages |
| GetNodeMediaListImages | 0s | 0 pages |
| GetNodeChecklist | 0s | 0 pages |
^Ctask: signal received: interrupt
```

This appears to resolve our issues, though I don't think it's a 100% correct solution -- just an expedient and effective one.

**Comment by indytechcook** [comment]
I do agree this will work.  Just to note that when the time is `0s` normally that means the response was cached.

**Comment by ndouglas** [comment]
I `drush cr`ed and it's still 0s and it still passes that area, FWIW.  I'll leave it running just to be sure the menu link doesn't cause any issues with the rest of the content build.

**Review by swirtSJW — COMMENTED** [review]
This patch looks good.  As long as we test using "save draft and continue editing" and the menu is properly created then we are good.

**Review by swirtSJW — APPROVED** [review]
Nice work Nate and thanks for documenting your testing on it.

**Pull request merged**
