### PR TITLE
VACMS-18108: Updates references to v0 to v1

### PR DESCRIPTION
**Pull request by omahane**
## Description

Relates to #18108 

_Note: Lighthouse no longer has an endpoint that returns all facilities. Instead, they have a paged endpoint with a maximum count of 1000. Given that we have 2566 facilities at present, 3 pages should be sufficient for the foreseeable future._

## Testing done
Manually, PHPUnit, Cypress and with Lighthouse

## Screenshots
Screenshot 2024-05-23 at 7 27 37 AM

#### Creating a VAMC Facility 
- [x] Delete [Bradenton VA Clinic (vha_516GD)](https://pr18149-ohhbrbyutdeejv4ujo5n4xaxs8rguvav.ci.cms.va.gov/bay-pines-health-care/locations/bradenton-va-clinic)
- [x] Run the following command in the [Tugboat terminal](https://tugboat.vfs.va.gov/tush/6646749e391492c1b319d0f6): `drush migrate:import va_node_health_care_local_facility --update --idlist=vha_516GD`
- [x] In the browser, go to [Bradenton VA Clinic (vha_516GD)](https://pr18149-ohhbrbyutdeejv4ujo5n4xaxs8rguvav.ci.cms.va.gov/locations/bradenton-va-clinic)
- [x] Confirm that it exists
- [x] Click edit
- [x] Confirm that it has a "New facility" flag

#### Creating a NCA Facility
- [x] Delete [Miramar National Cemetery (nca_992)](https://pr18149-ohhbrbyutdeejv4ujo5n4xaxs8rguvav.ci.cms.va.gov/nca-facilities/locations/miramar-national-cemetery)
- [x] Run the following command in the [Tugboat terminal](https://tugboat.vfs.va.gov/tush/6646749e391492c1b319d0f6): `ddev drush migrate:import va_node_facility_nca --update --idlist=nca_992`
- [x] In the browser, go to [Miramar National Cemetery (nca_992)](https://pr18149-ohhbrbyutdeejv4ujo5n4xaxs8rguvav.ci.cms.va.gov/nca-facilities/locations/miramar-national-cemetery)
- [x] Confirm that it exists
- [x] Click edit
- [x] Confirm that it has a "New facility" flag

#### Creating a VBA Facility
- [x] Delete [Albuquerque VA Regional Benefit Office (vba_340)](https://pr18149-ohhbrbyutdeejv4ujo5n4xaxs8rguvav.ci.cms.va.gov/albuquerque-va-regional-benefit-office)
- [x] Run the following command in the [Tugboat terminal]: `ddev drush migrate:import va_node_facility_vba --update --idlist=vba_340`
- [x] In the browser, go to [Albuquerque VA Regional Benefit Office (vba_340)](https://pr18149-ohhbrbyutdeejv4ujo5n4xaxs8rguvav.ci.cms.va.gov/albuquerque-va-regional-benefit-office)
- [x] Confirm that it exists
- [x] Click edit
- [x] Confirm that it has a "New facility" flag

#### Creating a Vet Center Facility
- [x] Delete [Nassau Vet Center (vc_0138V)](https://pr18149-ohhbrbyutdeejv4ujo5n4xaxs8rguvav.ci.cms.va.gov/nassau-vet-center)
- [x] Run the following command in the [Tugboat terminal]: `ddev drush migrate:import va_node_facility_vet_centers --update --idlist=vc_0138V`
- [x] In the browser, go to [Nassau Vet Center (vc_0138V)](https://pr18149-ohhbrbyutdeejv4ujo5n4xaxs8rguvav.ci.cms.va.gov/nassau-vet-center)
- [x] Confirm that it exists
- [x] Click edit
- [x] Confirm that it has a "New facility" flag

#### Creating a Vet Center - Mobile Vet Center
- [x] Delete [Baltimore Mobile Vet Center (vc_0858MVC)](https://pr18149-ohhbrbyutdeejv4ujo5n4xaxs8rguvav.ci.cms.va.gov/baltimore-vet-center/baltimore-mobile-vet-center)
- [x] Run the following command in the [Tugboat terminal]: `ddev drush migrate:import va_node_facility_vet_centers_mvc --update --idlist= vc_0858MVC `
- [x] In the browser, go to [Baltimore Mobile Vet Center (vc_0858MVC)](https://pr18149-ohhbrbyutdeejv4ujo5n4xaxs8rguvav.ci.cms.va.gov/baltimore-vet-center/baltimore-mobile-vet-center)
- [x] Confirm that it exists
- [x] Click edit
- [x] Confirm that it has a "New facility" flag

#### Creating a Vet Center - Outstation
- [x] Delete [Clarksville Vet Center Outstation (vc_7241OS)](https://pr18149-ohhbrbyutdeejv4ujo5n4xaxs8rguvav.ci.cms.va.gov/nashville-vet-center/clarksville-outstation)
- [x] Run the following command in the [Tugboat terminal]: `ddev drush migrate:import va_node_facility_vet_centers_os --update --idlist=vc_7241OS`
- [x] In the browser, go to [Clarksville Vet Center Outstation (vc_7241OS)](https://pr18149-ohhbrbyutdeejv4ujo5n4xaxs8rguvav.ci.cms.va.gov/clarksville-vet-center)
- [x] Confirm that it exists
- [x] Click edit
- [ ] Confirm that it has a "New facility" flag

#### Updating a VAMC Facility
- [x] Change the name of [Libby VA Clinic](https://pr18149-ohhbrbyutdeejv4ujo5n4xaxs8rguvav.ci.cms.va.gov/node/2165/edit). (_Note: All facility name change tickets use the same mechanism for flagging, so only testing one type is sufficient. Plus, VAMC facilities are the only whose name can be changed in the UI by an admin._
  - [x] Save the node
  - [x] Confirm that the facility has been updated
  - [x] Run a migration in [Tugboat terminal](https://tugboat.vfs.va.gov/tush/6646749e391492c1b319d0f6) with the following command: `drush migrate:import va_node_health_care_local_facility --update --idlist=vha_668QB` 
  - [x] Check the [Libby VA Clinic](https://pr18149-ohhbrbyutdeejv4ujo5n4xaxs8rguvav.ci.cms.va.gov/node/2165)
  - [x] Confirm that the name has changed back
  - [x] Click "Edit"
  - [x] Check the Flags
  - [x] Confirm that a "Name changed" flag is checked

### Push data
- [x] Clear out the post_api_queue by running the following command in the [Tugboat terminal](https://tugboat.vfs.va.gov/tush/6646749e391492c1b319d0f6): `drush queue:delete post_api_queue`
 
#### Send status information
- [x] Edit [East Front Avenue VA Clinic](https://pr18149-ohhbrbyutdeejv4ujo5n4xaxs8rguvav.ci.cms.va.gov/spokane-health-care/locations/east-front-avenue-va-clinic) 
- [x] Change the operating status information
- [x] Check the [queue](https://pr18149-ohhbrbyutdeejv4ujo5n4xaxs8rguvav.ci.cms.va.gov/admin/config/post-api/queue) for an entry with that node ID
- [x] Click "Process queue"
- [x] Confirm that the queue is empty after processing
#### Send service information
- [x] Edit [Sleep medicine - Seattle VA Medical Center](https://pr18149-ohhbrbyutdeejv4ujo5n4xaxs8rguvav.ci.cms.va.gov/puget-sound-health-care/locations/seattle-va-medical-center/sleep-medicine), a VAMC Facility Health Service (any change will do).
- [x] Check the [queue](https://pr18149-ohhbrbyutdeejv4ujo5n4xaxs8rguvav.ci.cms.va.gov/admin/config/post-api/queue) for an entry with that node ID
- [x] Click "Process queue"
- [x] Confirm that the queue is empty after processing

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### CODE REVIEW

**Comment by edmund-dunn** [comment]
First test case, after running import, was expecting facility at `/bay-pines-health-care/locations/bradenton-va-clinic` but the URL was actually `/locations/bradenton-va-clinic`

**Comment by edmund-dunn** [comment]
Creating a Vet Center - Outstation 
URL issues, was expecting `/nashville-vet-center/clarksville-outstation` and got `/clarksville-vet-center`

**Comment by edmund-dunn** [comment]
Send service information
the queue did not empty.

**Review by edmund-dunn — COMMENTED** [review]
Three issues, see comments on the PR. Code looks good.

**Comment by omahane** [comment]
> Creating a VAMC Facility, after running import, was expecting facility at `/bay-pines-health-care/locations/bradenton-va-clinic` but the URL was actually `/locations/bradenton-va-clinic`

Sorry. Newly migrated VAMC Facilities are put in the VAMC Facilities section, and have to be manually moved to the correct section. This is actually the correct behavior. I have updated the QA to reflect that.

**Comment by omahane** [comment]
> Creating a Vet Center - Outstation URL issues, was expecting `/nashville-vet-center/clarksville-outstation` and got `/clarksville-vet-center`

For the same reason, Vet Center - Outstations are not in a section upon migration. This is also the correct behavior, and this has now been corrected in the QA.

**Comment by omahane** [comment]
> Send service information the queue did not empty.

[Adam from Lighthouse and I](https://dsva.slack.com/archives/C02BTJTDFTN/p1718047401546969) figured this one out. The queue did not empty because the TIC though our national description of sleep medicine, which contained HTML that included `sleep` a number of times and even `&nbsp; sleep` was an attempt to issue the *nix `sleep` command, so it was being rejected. I made an update to the national description in Tugboat and will do the same in Production. 

Per Adam:
> In any event, Devops is putting in a change request to the TIC to remove "sleep" from the block rules for this endpoint so hopefully we won't see this again down the road.

**Review by JakeBapple — APPROVED** [review]
Issues clarified or fixed. Approved!

**Review by dsasser — APPROVED** [review]
Code looks good; QA steps completed and all passed.

**Review by timcosgrove — APPROVED** [review]

**Pull request merged**
