### PR TITLE
VACMS-3607: Disables grid view in Media Library.

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

See #3607.

I think something's borked, not sure if it's my dev environment or my changes, so that's why this is a draft request.  I'll update when I get things working again.

## Testing done
Visited the media page before and after the change.  Before,  there 'twas a Grid link.  After, 'twasn't one.

## Screenshots
Screen Shot 2020-12-07 at 1 38 43 PM

## QA steps

As an authenticated user:
1. Visit [`admin/content/media`](http://va-gov-cms.lndo.site/admin/content/media)
1. Confirm there is no `Grid` option.
1. Then validate Acceptance Criteria from issue
- [ ] the Grid view is disabled (not removed) in the Media Library View - /admin/structure/views/view/media_library/edit/page

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by acrollet** [comment]
@ndouglas it would make sense to me to add a couple liner behat test to confirm that the link for the Grid view is not seen on the media library. Since we're over-riding a default it seems like it would be somewhat easy for it to come back on its own.

**Comment by ndouglas** [comment]
there was about twenty minutes of increasingly sublime confusion when writing this test and Lando decided to stop perceiving consensual reality

Screen Shot 2020-12-10 at 9 05 47 AM

**Comment by acrollet** [comment]
@ndouglas don't you know reality is just, like... an *illusion*, man?

**Comment by ndouglas** [comment]
ntc1vvw

**Review by acrollet — APPROVED** [review]
Code looks good, I confirmed ACs are met on the devshop preview. Approved pending tests passing.

**Pull request merged**
