### PR TITLE
VACMS-15492: Allow Content Admins to view Content Model Reports

### PR DESCRIPTION
**Pull request by davidmpickett**
## Description

Relates to #15492.

## Screenshots

Screenshot 2023-10-02 161424

Screenshot 2023-10-02 161513

## QA steps

What needs to be checked to prove this works?
What needs to be checked to prove it didn't break any related things?
What variations of circumstances (users, actions, values) need to be checked?

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by davidmpickett** [comment]
After first commit, I am able to log into Tugboat instance as a Content Admin and see Content Model Documents under the Structure Menu and also as a tab when Editing Vocabularies. May have to do something else to add reports to my menu.

Screenshot 2023-10-02 161424

Screenshot 2023-10-02 161513

**Comment by davidmpickett** [comment]
I can navigate to the content model reports with URL even though they don't appear in nav bar
Screenshot 2023-10-02 162914

**Comment by davidmpickett** [comment]
Giving the Content Admin role the System / access site reports permission added Reports to my Toolbar, but it also now shows me a bunch of reports other than the Content Model Documentation ones.

Screenshot 2023-10-02 172042

**Comment by davidmpickett** [comment]
And then I went down the rabbit hole and realized that this is documented issue in core https://www.drupal.org/node/1635646

**Comment by davidmpickett** [comment]
I might be vastly oversimplifying here but seems like we just need to add a new permission to https://git.drupalcode.org/project/drupal/-/blob/11.x/core/modules/system/system.permissions.yml
and then update https://git.drupalcode.org/project/drupal/-/blob/11.x/core/modules/system/system.routing.yml to use that new permission to control viewing the reports Menu in toolbar without ALSO granting access to dblogs

system.admin_reports:
  path: '/admin/reports'
  defaults:
    _controller: '\Drupal\system\Controller\SystemController::systemAdminMenuBlockPage'
    _title: 'Reports'
  requirements:
    _permission: 'access site reports'

**Comment by swirtSJW** [comment]
Giving content-admin access to reports would also make it easier to move some of our "reports" out of 'admin/content/*' and into the reports namespace where they actually belong.

Reports are handy for all users.... could easily see this stretch to content publishers and maybe all users.

**Comment by davidmpickett** [comment]
Thanks for the feedback @swirtSJW. I think I got a little over ambitious here and tried to solve a much deeper problem than the one I originally scoped. I'm slimming this down to just focus on granting Content Admins the ability to view Content Model Documents & Reports without touching the Reports toolbar issue. That would probably warrant its own issue (and a more experienced Drupal developer than me) to properly resolve

**Comment by davidmpickett** [comment]
On tugboat, I am able to log in as a Content Admin and access Content Model Documents and Content Model Reports!

screencapture-cms-mcg0n7eeoph0iyykadvi64hdh9gnwamf-ci-cms-va-gov-admin-structure-types-manage-centralized-content-document-2023-10-27-19_03_19

screencapture-cms-mcg0n7eeoph0iyykadvi64hdh9gnwamf-ci-cms-va-gov-admin-reports-content-model-2023-10-27-19_04_00

**Pull request closed without merging**
