### PR TITLE
VACMS-18064: Drupal Events json api for OPIA.

### LINKED ISSUE #18064: Create Query for Drupal Events Data as JSON file to OPIA Team
## User Story or Problem Statement
To deliver the OPIA team the events data they need, the CMS team needs to first create a query and script to pull the events data. 

## Steps for Implementation
- Construct a REST API query that gives the OPIA team all of the events data
- Process the section to get the section name for each event type 
- Create a JSON object for all the events data 
- Write a script that pulls all the data

## Acceptance Criteria
- [x] An MVP solution that queries the data the OPIA team needs to do discovery work for their project.

### PR DESCRIPTION
**Pull request by anantais**
## Description

Closes #18064.

## QA steps

As user with admin access:
1. Verify that the view exists by going to /admin/structure/views/view/events_data
2. Verify that you can see the feed by going to /all-events-data
3. The view is currently only accessible to admins so you can log in as non-admin user and you will not be able to see the feed.

### Definition of Done

Feed is verified by an admin user.

### Select Team for PR review

- [x] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by edmund-dunn — CHANGES_REQUESTED** [review]
Please change the machine name for teh view to something meaningful like `events_rest_api`. We also need to make sure we include the query string for the format.

**Comment by anantais** [comment]
The link to the read me for this is: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/events-api.md

**Comment by anantais** [comment]
The url for the api call is: /all-events-data_format=json

**Review by edmund-dunn — APPROVED** [review]
Nicely done! This is good to go!

**Pull request merged**
