### PR TITLE
VACMS-10776: Add new forms audit view.

### LINKED ISSUE #10776: Forms: Create Forms audit view to help determine which are sufficiently populated to publish
## Description
When forms are migrated into the CMS from the Forms DB, a draft node is created. We need to audit these nodes and work with Sitewide Content to develop governance for reviewing each node, determining if it has the necessary data required for a standalone Form detail page. 

First step, understand existing VA Form nodes, and their contents. 
Forms: https://prod.cms.va.gov/admin/content?title=&type=va_form&owner=All   (includes Draft & Published)

### Description 

**Follow the pattern of views under Facilities content, where each view has a tab**

Create a content audit view in the VA Forms area (https://prod.cms.va.gov/admin/content/va-forms) that: 
* displays each VA form
* can be filtered by moderation status
* shows "form name" column
* shows "When to use" column
* shows "Online tool" column
* shows "Issue date"
* shows "Revision date"

## Additional context
To put tabs under tabs may be funny, and Jay Darnell has notes on how to make it work. 

## Acceptance Criteria
- [ ] Content audit VA Form table exists with columns above

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by dsasser**
## Description

Closes  #10776

## Screenshots
Screen Shot 2022-10-14 at 11 02 40 AM

## QA steps
Visit the new forms audit view page at: /admin/content/va-forms/audit and validate against the [CMS Views Styleguide](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1740472321/CMS+Views+Style+Guide):

- [ ] Display machinename, not `default`
- [ ] URL [`/admin/content/{{parent-view-name}}/name-of-view`]
- [ ] Menu item setting: [tbd]
- [x] Limit to 100 per page, paginated
- [x] Show result count in header (`<p>Displaying @start - @end of @total</p>`)
- [x] Columns
  - [x] Title (sortable) 
  - [x] Edit button (not operations, no heading) 
  - [ ] Content type (sortable)
  - [x] Moderation State
  - [x] Section (field_administration) (sortable)
  - [x] Is Locked (optional)
  - [x] Last updated (date time and by user) (sortable, default sort, DESC)
  - [ ] [Other content fields as needed]
- [ ] Filters
  - [ ] Exposed
    - [x] "Title contains" (text search of title field)
    - [ ] "Content type" (single value drop down or multivalue? should options be limited)
    - [x] "Moderation state"  (single value drop down or multivalue?)
    - [x] "Section" (workbench access section; single select, show children)
    - [ ] Reset button exists
    - [x] Apply button says 'Filter' 
- [ ] Not exposed
    - [ ] [Any not exposed filters, as needed]

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by chri5tia** [comment]
Looks like the behat test failure is just related to the spec tool to update the content model for views:
drupal-spec-tool/views.feature:90

```
+++ Unexpected views displays (present in Drupal, absent from specification)
      | VA Forms | Audit | audit | Page | (TravisCarden\BehatTableComparison\UnequalTablesException)
```

**Comment by chri5tia** [comment]
For the steps to check, can you connect with me about where to look for these two:

> Display machinename, not default
> URL [/admin/content/{{parent-view-name}}/name-of-view]

I also didn't see content type, but I'm guessing that you passed on that.

**Review by chri5tia — CHANGES_REQUESTED** [review]
Looks like you just need to add your new view to `drupal-spec-tool/views.feature` and there are a couple items missing from the checklist.

**Comment by dsasser** [comment]
> I also didn't see content type, but I'm guessing that you passed on that. Everything else looks good.

I am not sure what you are referring to. Where are you looking for a content type?

**Comment by chri5tia** [comment]
Screen Shot 2022-10-18 at 8 40 33 AM

A column in the acceptance criteria.

**Pull request merged**
