### PR TITLE
VACMS-3616: Prevent format on plain text table cells.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #3616 

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by ethanteague — COMMENTED** [review]
Thanks @acrollet 👍

**Comment by swirtSJW** [comment]
Testing locally because .... devshop
Saving a non bad data node.
image

Hand fixing broken data persisted through multiple saves without getting re-broken.
image

**Comment by swirtSJW** [comment]
Tested with html variations on a full_html paragraph.  All worked as expected.
image

**Comment by swirtSJW** [comment]
Switching to rich text limited also tested out ok.

image

**Review by swirtSJW — APPROVED** [review]
Changes look good and have been tested across all our use cases.

**Pull request merged**
