### PR TITLE
VACMS-9042: Create CMS announcement block type and example.

### PR DESCRIPTION
**Pull request by msbtterswrth**
## Description

Relates to #9042.

## Testing done
manual, automatic

## Screenshots
image

image

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As cms user
1. Create (or edit) a new CMS announcement block (`/block/166?destination=/admin/structure/block/block-content`)
   - [x] Validate that a title field exists
   - [x] Validate that a rich text limited body exists
   - [ ] Validate that an announcement type selector exists
2. Then save the block and place it on a page/content type/role in the content region
   - [x] Validate that it appears in the CMS based on the set conditions (https://pr9053-jgmutgaz1krhfoqqpxxmcxphh9ozmuex.ci.cms.va.gov/node/3621/edit)
3. Then validate Acceptance Criteria from issue
   - [x] title field
   - [x] limited rich text body field
   - [x] Announcement type (severity level)
   - [x] design/ux review

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by msbtterswrth** [comment]
@rachel-kauff this is ready for review!

**Review by rachel-kauff — COMMENTED** [review]
Styling looks great to me. TY Lynn!

**Comment by rachel-kauff** [comment]
**COVID-19 announcement block content**
_Here's where I'll continue to update the content as we continue to make small adjustments to comms._ 

`Heading`
Action requested: Update facility COVID-19 statuses by COB Friday, May 20

`Body content`
VHA has a new initiative that sets standard levels to determine COVID-19 health protection guidelines. You'll need to update the initial COVID-19 status for your locations and publish by Friday, May 20.

- Use the COVID-19 level set by your facility leadership.
- Update each location in your VAMC system separately.
- Remove any duplicated COVID content from your locations’ operating status fields.

[Learn more about how to update COVID-19 statuses (opens in a new window)](https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses/how-to-edit-covid-19-status-for-a-vamc-facility#undefined)

cc: @ContentBrewmaster

**Comment by swirtSJW** [comment]
Rolling this out with the promise that it needs followup tickets to make it look more sympatico with other messages on the screen
image

**Review by swirtSJW — APPROVED** [review]
Tests out fine.   
image


Will need followup to create the content blocks and then export for placement.

**Pull request merged**
