### PR TITLE
VACMS-9700: Patch smart_date for recurrence bug identified in d.o issue #3294350

### LINKED ISSUE #9700: Contribute patch to fix #9684
## Description

Implementation ticket for #6056

https://www.drupal.org/project/smart_date/issues/3294350
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9684

## Acceptance Criteria
- [ ] Events should start at the designated time in MST year-round, when Phoenix timezone is chosen.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by dsasser**
## Description

~Relates to~ Closes #9700

## Screenshots
Before:
Screen Shot 2022-07-06 at 12 31 01 PM

After:
Screen Shot 2022-07-06 at 12 30 21 PM

## QA steps

Go to /node/add/event
Create a recurring event starting at 9am, repeating weekly, for 1 year, and set time zone to Phoenix.
See that your event starts at 9am when DST is active in Eastern time zone

1. Modify your user profile and set your timezone to 'New York' if not already set in /user/[uid]/edit.
2. Go to /node/add/event and fill out a new test event.
3. Ensure the start date is November 5, 2022 @ 9:00AM
4. Set the timezone to Phoenix
5. Set daily recurrences until November 7, 2022.
6. Save the node
7. Then
   - [ ] Validate that each event occurrence starts at 9:00 AM in MST
8. Edit your user profile and change your timezone to 'Los Angeles'
9. Edit the node created earlier, make no changes, and re-save
10. Then
   - [ ] Validate that each event occurrence starts at 9:00 AM in MST

### Definition of Done
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [x] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### CODE REVIEW

**Comment by swirtSJW** [comment]
Nice work on this @dsasser.  Thank you for the great QA steps.   One thing that I am not sure if these QA steps cover, they seem to all cover EST  and MST but do they cover the situation with Arizona which is in perpetual MST while other states in the mountain time zone are MDT.  Maybe it is covered but  it seems a little fuzzy.  I would think one set of tests might need to be done involving actually changing the time of year of the site to March and then saving an event to make sure  it saves the same as setting the site's date to December and then saving an event.

The other aspect that I think needs checking out, is how does it get handled by the FE.   This checking for the save and display is only testing the editor's view in the CMS but we need to check that the FE is rendering it correctly too, as the graphql is not aware of the user's time zone.   This could all be tested and verified in tugboat.

**Comment by swirtSJW** [comment]
The items in the the release notes for the included module bump seem innocuous.   https://www.drupal.org/project/smart_date/releases/3.5.1

**Comment by dsasser** [comment]
> I would think one set of tests might need to be done involving actually changing the time of year of the site to March and then saving an event to make sure it saves the same as setting the site's date to December and then saving an event.

@swirtSJW can you elaborate on this a bit? I'm not sure what it means to change the time of the site in this context.

**Comment by dsasser** [comment]
> check that the FE is rendering it correctly too, as the graphql is not aware of the user's time zone.

@swirtSJW The Event graphql query is returning dates in UTC time, and includes the timezone specified on the node.
```
          "fieldDatetimeRangeTimezone": [
            {
              "duration": 60,
              "endTime": null,
              "endValue": 1667671200,
              "rrule": 69,
              "rruleIndex": 1,
              "startTime": null,
              "timezone": "America/Phoenix",
              "value": 1667667600
            },
```

When the FE displays the Event dates, it does so by converting the UTC dates to the specified timezone:
```
            // Derive starts at and ends at.
            const formattedStartsAt = moment
              .tz(startsAtUnix * 1000, timezone)
              .format('ddd MMM D, YYYY, h:mm a');
            const formattedEndsAt = moment
              .tz(endsAtUnix * 1000, timezone)
              .format('h:mm a');
            const endsAtTimezone = moment
              .tz(endsAtUnix * 1000, timezone)
              .format('z')
```

Therefore, this bug is only present within the backend and manifests as UTC timestamps being stored in the CMS incorrectly. That the users' timezone was being considered at all when a user provided a timezone on the node during save operations is the heart of the issue. The module was always storing the correct timezone in the DB, so no changes to the FE are necessary to realize the fix on va.gov.

If that doesn't satisfy your acceptance criteria, please let me know the process by which testing this can occur on Tugboat.

**Review by swirtSJW — APPROVED** [review]

**Pull request merged**
