### PR TITLE
VACMS-6561 Add and enable drupal graphql_menu module.

### LINKED ISSUE #6561: Make published state revealed as part of graphQL menuByName query
## User Story or Problem Statement

As consumer of the menuByName query I need to know whether a menu item is to a published node or not so I know whether to render the menu item on the front end.

As a consumer of the menuByName I need to have menu items to unpublished content available to me so I can accurately render content on preview.

I should never see menu items to archived nodes.

Related to 
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/29782
* https://dsva.slack.com/archives/C0FQSS30V/p1632770700465500

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform Team`
- [x] `Sitewide CMS Team`

### PR DESCRIPTION
**Pull request by swirtSJW**
## Description

Closes #6561 

At the moment this is just a test environment so the FE team can see if it does what they need.

## QA steps

As admin
1. go to https://pr6568-evjtc4b1rljtu67clslvtg444yrbfygw.ci.cms.va.govadmin/modules
- [ ] Validate  that GraphQl Menu is enabled
2. go to https://pr6568-evjtc4b1rljtu67clslvtg444yrbfygw.ci.cms.va.gov/graphql/explorer
3. execute the following query
```
{
  menuByName(name: "va-alexandria-health-care") {
    description
    name
    links {
      ...MenuItem
      links {
        ...MenuItem
        links {
          ...MenuItem
        }
      }
    }
  }
}

fragment MenuItem on MenuLink {
  expanded
  description
  label
  url {
    path
  }
  entity {
    ... on MenuLinkContent {
      linkedEntity(language_fallback: true, bypass_access_check: true) {
        ... on Node {
          entityPublished
          moderationState
        }
      }
    }
  }
}

```
- [ ]  validate that it returns results without error and shows the moderation state of nodes.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by swirtSJW** [comment]
Return results should look like 
image

**Comment by swirtSJW** [comment]
I am checking into the failing tests. now

**Comment by swirtSJW** [comment]
The failing tests were related to this page not being built
/health-care/about-va-health-benefits/vision-care/blind-low-vision-rehab-services
which seems to be an unrelated failure.   I triggered a rebuild to run them again.

**Comment by swirtSJW** [comment]
@indytechcook This module makes it possible for the FE to determine if they should show a menu item or not based on its moderation state.  It should reduce the number of broken links that come from them outputting menu links to unpublished nodes.

There is a risk this could slow down the menu queries they are doing now, which number somewhere between 140 and 200.   We could test the effect out on their front end PR once they write it and see the impact of the build time if you have concerns.

**Review by ethanteague — APPROVED** [review]
LGTM

**Comment by indytechcook** [comment]
@swirtSJW are they going to load the related entity to each menu item then load that entity's related moderation state entity then look at that moderation state entity status?   

Assuming that statement is true I would have the following thoughts:
* It does sound heavy but hopefully, most of that data is cached.   
* If the entity isn't cached, then I can see it priming the cache for the entity next load in the following graphQL calls.  
* This also means the amount of data being processed in the content build will grow which will have performance issues outside of the GraphQL call itself.
* Since the front end has no concept of sharing/caching entity data between GraphQL requests, lots of data will be duplicated between the menu  GraphQL calls and the content graphql calls.

If I'm reading the module code correctly, this just adds new GraphQL fields to entities so it should be passive for now so there isn't harm in merging this then testing.

**Review by indytechcook — APPROVED** [review]
After talking with @swirtSJW , we are going to merge this and get it to prod, then we will evaluate the PR submitted by the front end team.

**Pull request merged**
