### PR TITLE
Adds endpoint config patch from Geocoder module

### LINKED ISSUE #10055: Add patch for Mapbox endpoint config
## Composer Patch
This adds a composer patch that relates to the work done on the Geocoder module in https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/520

## Acceptance Criteria
- [ ] When the CMS is built, the Mapbox provider has a "Geocoding Mode" field on https://va-gov-cms.ddev.site/admin/config/system/geocoder/geocoder-provider/manage/mapbox
- [ ] The "Geocoding Mode" is populated with "mapbox.places" by default
- [ ] When changing the address of a Vet Center CAP, the geocode changes in accordance with the new address (verifiable as an admin).

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by omahane**
## Description

Closes #10055

https://www.drupal.org/project/geocoder/issues/3301383

## Testing done
Manually

## Screenshots
geocoder-provider-mapbox-changes

## QA steps

As an admin
1. Make sure the build is successful
2. Then visit /admin/config/system/geocoder/geocoder-provider/manage/mapbox
   - [x] Validate that the "Geocoding mode" has "mapbox.places" populated by default
3. Then change the "Geocoding mode" to "mapbox.places-permanent"
   - [x] Go to a Vet Center CAP
   - [x] Change the address
   - [x] Verify that the geocoding has changed in accordance with the address

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by omahane** [comment]
For the record, I just test Tugboat, using the "mapbox.places" and "mapbox.places-permanent" Geocoding modes. Both worked.

**Review by swirtSJW — CHANGES_REQUESTED** [review]
Text repeated from slack"
That patch looks good, but I can't accept it like this.  You are referencing a patch from the MR... which means that patch will float if someone adds to that MR.  I am not fully versed in the perms of drupal .org's gitlab but I am pretty sure others can contribute / poison your PR.

Can you copy the code of the actual patch and submit it as a patch file [on the issue](https://www.drupal.org/project/geocoder/issues/3301383)  ?   That will lock it in so it does not float with the eb and flow of the MR.

**Comment by omahane** [comment]
I have added the patch file to the issue and changed the patch path in composer.json

**Review by swirtSJW — DISMISSED** [review]
Tests out great.  Nicely done.

**Comment by swirtSJW** [comment]
Do we also need a config export so we pick up the value we need?

**Comment by omahane** [comment]
> 

No, it's already there because I set it as default in the annotation, mirroring how the constructor in the geocoder-php library sets mapbox.places as default.

**Comment by omahane** [comment]
@swirtSJW Config has been added. I see the config in the form.
Screen Shot 2022-08-04 at 4 46 40 PM

**Review by swirtSJW — APPROVED** [review]
Nice work.
image

**Pull request merged**
