### PR TITLE
VACMS-2756 Set file path location.

### PR DESCRIPTION
**Pull request by swirtSJW**
## Description

See #2756 . 

## Testing done
1. Saved a node with a defined image `/node/2299/edit`
2. inspected the output of that page in the content export 
`node.5f30741e-d04b-4d0e-858a-3ab94334e3ca.json`
3. examined metatag image paths to make sure they contained the proper domain and path.
image

4. Examined path to page and made sure it was unaffected.

image

5. Examined view of the page to make sure the rendering of the image still worked
`/wilkes-barre-health-care/locations/northampton-county-va-clinic`
image

## QA steps
Testing wont be possible in CI because those paths are dyanmic and unaffected by these changes.   Will need to be tested on dev or staging.

As an admin:

- [ ]  Save a node with a defined image `https://staging.cms.va.gov/node/2299/edit`
- [ ]  inspect the output of that page in the content export 
`docroot/sites/default/files/cms-export-content/node.5f30741e-d04b-4d0e-858a-3ab94334e3ca.json`
- [ ]  examine metatag image paths in the export file to make sure it contains the proper domain and path like this
`"image_src": "\/sites\/default\/files\/2020-04\/Northampton_480x330.jpg",`
- [ ] scroll down to the path element and make sure the path to the node is root relative like 
`"path": "\/wilkes-barre-health-care\/locations\/northampton-county-va-clinic"`
- [ ] Examine the view mode of the page `https://staging.cms.va.gov/wilkes-barre-health-care/locations/northampton-county-va-clinic` and validate the page still shows the image.
- [ ] Check pdf links here /pittsburgh-health-care/stories/free-flu-shots-for-veterans  

## Definition of Done
- [ ] Product release are written (or in progress), if required.
- [ ] Documentation has been updated, if applicable.

### CODE REVIEW

**Comment by swirtSJW** [comment]
Closing this to try to jumpstart devshop

**Comment by swirtSJW** [comment]
Reopening for devshop

**Comment by swirtSJW** [comment]
Closing this to re-create because devshop is lost.

**Comment by ElijahLynn** [comment]
It is getting the error below on http://devshop.cms.va.gov/node/172177. Can you make a new PR for this to see if that passes? Since we are likely moving to a new system soon, I think that this would be the easiest thing to try first, making a new PR. 

> WD node: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'rid' cannot be null: INSERT INTO {hosting_task} (vid, nid, task_type, task_status, rid, executed, delta) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6); Array
> (
>     [:db_insert_placeholder_0] => 210019
>     [:db_insert_placeholder_1] => 172195
>     [:db_insert_placeholder_2] => verify
>     [:db_insert_placeholder_3] => 0
>     [:db_insert_placeholder_4] => 
>     [:db_insert_placeholder_5] => 
>     [:db_insert_placeholder_6] => 
> )
>  in hosting_task_insert() (line 952 of /var/aegir/devmaster-1.x/profiles/devmaster/modules/contrib/hosting/task/hosting_task.module).

**Comment by swirtSJW** [comment]
Closing this as it is replaced by https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2971

**Pull request closed without merging**
