### PR TITLE
VACMS-4313: Use manually created patch for flood control

### PR DESCRIPTION
**Pull request by acrollet**
## Description

See #4313 

## Testing done

Manual testing.

## QA steps

Attempt to login with a valid username and incorrect password more than 5 times in a row. You should see a message that the account has been temporarily blocked. Then, review the [new documentation](https://github.com/acrollet/va.gov-cms/blob/VACMS-2824-2825-flood_control/READMES/user_management.md) and log in as a user with the `Administrator` role:

- [x] Confirm that the user login flood entries are set to expire 30 minutes after the login attempt was made
- [x] The blocked user account can be manually unblocked
- [x] No `undefined index` errors are present in dblog
- [ ] Extra credit - [d.o. patch](https://www.drupal.org/project/flood_control/issues/3191346) reviewed

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by ndouglas** [comment]
Screen Shot 2021-02-16 at 3 45 13 PM

Flood control works...

But seeing the warnings in the log:
Screen Shot 2021-02-16 at 3 46 08 PM
Screen Shot 2021-02-16 at 3 47 06 PM

**Comment by acrollet** [comment]
> Screen Shot 2021-02-16 at 3 45 13 PM
> 
> Flood control works...
> 
> But seeing the warnings in the log:

!!

I hadn't seen any... digging

**Comment by acrollet** [comment]
Ah ok, this is a different issue than the one I had previously fixed.

**Comment by acrollet** [comment]
Related d.o. issue: https://www.drupal.org/project/flood_control/issues/3192020

**Comment by ndouglas** [comment]
Uh... weird.  Did something happen?  The user I spammed the form with is `active` now.

**Comment by acrollet** [comment]
@ndouglas that user is active on prod, that should be right. I don't think that flood changes a user's status...

**Comment by ndouglas** [comment]
It should set it active -> blocked, right?

**Comment by acrollet** [comment]
@ndouglas hmm, I don't think so - [UserLoginForm](https://api.drupal.org/api/drupal/core%21modules%21user%21src%21Form%21UserLoginForm.php/8.9.x) directly calls [FloodInterface::isAllowed](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Flood%21FloodInterface.php/function/FloodInterface%3A%3AisAllowed/8.2.x)

**Comment by ndouglas** [comment]
Ah, TIL.  Guess actively blocking the account for arbitrary lengths of time wouldn't make sense with irregularly executed Drupal crons.

**Comment by acrollet** [comment]
ok @ndouglas thanks for catching that, patched and ready for re-review :-)

**Review by ndouglas — DISMISSED** [review]
Yes, works as intended, even fixes bugs that aren't part of the original AC's!

**Review by swirtSJW — APPROVED** [review]
Looks good @acrollet  just needs a rebase and a re-run of `lando composer update --lock` to resolve the hash collision.

**Review by ndouglas — APPROVED** [review]

**Pull request merged**
