### PR TITLE
VACMS-11961: Move DownloadableFileTest tests into Cypress.

### LINKED ISSUE #11961: Incorporate `DownloadableFileTest` tests into Cypress content type tests.
## Description
Followup from #10689.  These can cause deadlocks and would probably be best rewritten as 1-2 line additions to Cypress content type tests rather than separate features.

## Acceptance Criteria
- [ ] `DownloadableFileTest` tests are incorporated into Cypress content type tests.

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

Closes #11961.

QA steps, screenshots, etc forthcoming (the reason this is in draft).

Cypress test failure was unrelated (see #12430).

This PR doesn't change any of the tested code, just shifts the tests to Cypress to increase coverage of form behavior and interactions in a browser context.

## Testing done

Wrote tests iteratively.

## Screenshots / Video

https://user-images.githubusercontent.com/1318579/216611300-2d955832-0808-4480-8d85-424b036ad1b2.mp4

## QA steps

Optionally, check out the PR locally and:

- [ ] Run `npm run test:cypress:interactive` (_not_ within the DDEV context)
- [ ] Select the `media.feature` test
- [ ] Verify that the new tests run and complete successfully.

### CODE REVIEW

**Comment by ndouglas** [comment]
PHPUnit test fail is unrelated and should be fixed by another of these PRs... 😩

**Comment by ndouglas** [comment]
Another fail due to #12430, which is weird.

**Comment by timcosgrove** [comment]
## QA steps

- [ ] Run `npm run test:cypress:interactive` (_not_ within the DDEV context)
- [ ] Select the `media.feature` test
- [ ] Verify that the new tests run and complete successfully.

**Review by timcosgrove — APPROVED** [review]
Looks good, thank you for the xpath helpers.

**Pull request merged**
