### PR TITLE
VAGOV 1208 - Add PHPUnit migration test to confirm number of imported entities by type

### PR DESCRIPTION
**Pull request by schiavo**

### CODE REVIEW

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-83<br><br> [button_visit-site](http://pr-83.va.agile6.com)

**Comment by ElijahLynn** [comment]
@schiavo please rename title to be `VAGOV-1208` with the `-`, this way Jira will pick it up.

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-83<br><br> [button_visit-site](http://pr-83.va.agile6.com)

**Comment by ElijahLynn** [comment]
The title needs to have the `-` in between VAGOV-1208.

**Comment by ElijahLynn** [comment]
Why are there so many non-related commits in here?

**Comment by schiavo** [comment]
Made the mistake of merging develop into the branch. Feels free to reject and I'll redo the PR

**Comment by ElijahLynn** [comment]
Okay, standard practice is to re-use the same PR and force push to the branch. You probably just wanted to do a `git rebase develop` then force push.

**Pull request closed without merging**
