### PR TITLE
VACMS-4933: CAP-VC-Location -Updates

### PR DESCRIPTION
**Pull request by kaise-lafrai**
## Description

See _issueid_. #4933 #4934 

## QA steps

- Login as Vet Center editor here: https://pr4948-ialkjr84zhqljf9d5htvganh1kuspz6h.ci.cms.va.gov
- Navigate here: https://pr4948-ialkjr84zhqljf9d5htvganh1kuspz6h.ci.cms.va.gov/node/16626/edit
- [ ] Confirm that the Operating Status fields exist and look like this:
Screen Shot 2021-04-06 at 4 03 14 PM

- Navigate here: https://pr4948-ialkjr84zhqljf9d5htvganh1kuspz6h.ci.cms.va.gov/node/16478/edit
- [ ] Confirm that the nearby vet centers and outstations, nearby mobile vet centers look like the following:
Screen Shot 2021-04-06 at 4 05 06 PM

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by kevwalsh — CHANGES_REQUESTED** [review]
@kaise-lafrai looks great. 

Two thoughts now that i see this in action.

1. It would be great to align the editorial experience between the two "nearby" fields. That would mean a slightly larger lift, but i think it's worth it: 

- [x] Create an entity browser for Mobile Vet Centers, which matches the Nearby Vet Center and Outstations as closely as possible (but only shows/allows MVCs instead of Vet Centers and Outstations)

2. Minor thing

- [ ] Rearrange the order of the fields so that Nearby Mobile Vet Centers goes first (before Vet Centers/Outstations)

Also, a minor defect i just noticed, would work well in this PR.

- [ ] The Entity Browser for Nearby Vet Centers and Outstations displays Outstations as options, but if a user select an Outstation, the form does not validate. Looks like we need to enable Outstations as an eligible bundle for this field.

**Review by kevwalsh — CHANGES_REQUESTED** [review]
Awesome stuff! 

One defect: 

Editors should not see Mobile Vet Centers in the "Select Nearby Vet Centers and Outstations" entity browser. 

Edit_Vet_Center_Locations_List_Locations___VA_gov_CMS

**Comment by kaise-lafrai** [comment]
> Awesome stuff!
> 
> One defect:
> 
> Editors should not see Mobile Vet Centers in the "Select Nearby Vet Centers and Outstations" entity browser.
> 
> Edit_Vet_Center_Locations_List_Locations___VA_gov_CMS

Funny. I was going to ask if I should restrict this EB.

**Review by kevwalsh — CHANGES_REQUESTED** [review]
Per zoom

- [x] auth users need access to the new Mobile Vet Center entity browser.

**Review by swirtSJW — APPROVED** [review]

**Review by kevwalsh — APPROVED** [review]
Good stuff!

**Comment by swirtSJW** [comment]
image

**Pull request merged**
