### PR TITLE
VACMS-11246: Update VA Forms audit View.

### LINKED ISSUE #11246: Forms audit view: revise column order, fix clickable headers, & add Form admin field
## Description 
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10776 implemented a new view: https://prod.cms.va.gov/admin/content/va-forms/audit

We will use this view for: 
* Auditing which forms contain "When to use" content re: whether they should or should not be published as Form detail pages
* Auditing the Issue Date & Revision date re: upcoming PDF Certificate expiration
* Understanding which Admin owns the form

To that end, want to make some changes to organize the table more clearly for those tasks. Summarized here: 

Screen Shot 2022-10-21 at 2 55 19 PM
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10776#issuecomment-1282958939

ACs capture the changes as well.

## Acceptance criteria

- [ ] Columns are re-ordered per "Forms Audit tab (Revised)" order in screenshot above
- [x] Changed column header is changed to Updated
- [x] Form Administration is added as a new column
- [x] Form Administration is added as a new filter
- [x] Issue date table header is possible to click-sort

### PR DESCRIPTION
**Pull request by chri5tia**
## Description

~Closes 11246~  (no magic)
Closes #11246  (magic)

## Testing done
See QA steps.

## Screenshots
Screen Shot 2022-11-03 at 6 05 14 AM

Screen Shot 2022-11-03 at 6 05 22 AM

Screen Shot 2022-11-03 at 6 07 04 AM

Screen Shot 2022-11-03 at 6 06 55 AM

## QA steps
- [ ] Columns are re-ordered:
- - [ ] title
- - [ ] updated
- - [ ] moderation state
- - [ ] section
- - [ ] form name
- - [ ] form administration
- - [ ] issue date
- - [ ] revision date
- [ ] Filters match the column order
- [ ] Filter labels are the same size
- [ ] Changed column header is changed to Updated
- [ ] Form Administration is added as a new column
- [ ] Form Administration is added as a new filter
- [ ] Issue date table header is click sortable

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by dsasser** [comment]
Looks good to me:
Screen Shot 2022-10-25 at 9 21 01 AM

**Review by dsasser — APPROVED** [review]

**Comment by jilladams** [comment]
- [ ] Update markup to use .form-item class

The size of the label text on each of the filters is different. The ones using divs with the "form-item" class get a font-size set, and the new filters that are `fieldset` don't have that class, and get a different font size. The varying font-sizes make the big set of form filters feel a little chaotic -- cleaning up that class will help a bit. 

Screen Shot 2022-10-25 at 9 47 28 AM

**Review by jilladams — CHANGES_REQUESTED** [review]
- [x]  Update markup so filter labels use consistent font (I think using div / form-item classes will do it)

**Comment by chri5tia** [comment]
@jilladams Style seems to have been automatically set by drupal for all fields. The ones showing a different class (fieldset) are also all of the ones that have multiple operations available. 

Screen Shot 2022-10-25 at 3 29 00 PM

If I change "When to use" so that the operation is just "contains", then it sets it to the form item class. For the sake of simplicity, I think all the fields except for the issue date and revision date should be limited to the "contains" (key word). That would also fix the format of all but the date ones.

Screen Shot 2022-10-25 at 3 34 07 PM

Screen Shot 2022-10-25 at 3 36 48 PM

**Comment by chri5tia** [comment]
For Revision Date and Issue Date, here are the in-view style options, which I've played a bit with to no avail. I think this would need to be themed with a custom view template.

**Comment by jilladams** [comment]
I think we should leave the functionality of the filters (it's at its most useful) and add a style on those new markup labels then - is that an option? e.g.   update the CSS for `.label, .form-item__label` to add `.fieldset_label`? Doing that in my inspector seems to fix it. 

Screen Shot 2022-10-25 at 4 21 41 PM

**Comment by chri5tia** [comment]
@jilladams I may have to pair up with someone because I can't seem to fix this on the view level and it might require some templating work.

**Comment by chri5tia** [comment]
Looks like the updated styling for `fieldset__label` would need to go with these, in `docroot/thems/custom/vagovclaro/assets/scss/tokens/_typography.scss`

```
@mixin va-subsection-label {
  font-family: var(--font-family-sans);
  font-size: var(--va-subsection-s);
  font-weight: 600;
  line-height: var(--line-height-heading);
}

@mixin va-label {
  font-family: var(--font-family-sans);
  font-size: var(--va-subsection-xs);
  font-weight: 600;
  line-height: var(--line-height-form-label);
}
```

**Comment by chri5tia** [comment]
Found it in /scss/componants/_elements.scss

```
.label,
.form-item__label {
  @include va-label;
  margin-bottom: var(--spacing-xs);
}
```

I think all I have to do is add the .fieldset__label to that...

**Comment by chri5tia** [comment]
@jilladams This looks good now from my perspective and can be merged if you and a code reviewer. I have re-requested you and Steve. Thanks!

Screen Shot 2022-10-31 at 6 25 46 PM

**Comment by swirtSJW** [comment]
Technically I don't see any issues
It does seem odd to me that the order of the filters does not match the order of the columns.  Makes it more confusing than it already is (being a visually busy View)  Typically we try to make the order of the filters match the order of the columns.

image

**Review by swirtSJW — DISMISSED** [review]
Approved in case this needs to be merged even with the mismatched order on filters and columns  @jilladams  @chri5tia

**Comment by jilladams** [comment]
Interesting - that hadn't come up. Maybe we should add that note as guidance to the Views style guide? I'll cut a follow up task as tech debt and we can put it as stretch if folks end up with free time.

**Review by jilladams — APPROVED** [review]
so much better! thanks.

**Comment by swirtSJW** [comment]
> Interesting - that hadn't come up. Maybe we should add that note as guidance to the Views style guide? I'll cut a follow up task as tech debt and we can put it as stretch if folks end up with free time.

I added it to the style guide
image

It really stood out on this one while I was testing the revision date and issue date because I kept looking at the wrong column because the order is flip flopped.

**Comment by chri5tia** [comment]
Form administration filter seems to be missing, in https://cms-xqzwhjdu8iqvmcgg91mcyothppkp4pua.ci.cms.va.gov/admin/content/va-forms/audit...

**Comment by chri5tia** [comment]
I noticed that the Form administration elements were missing, so I re-added that, fixed a couple things that got lost in the shuffle and re-checked. Need another approval in order to merg.

**Comment by chri5tia** [comment]
Behat test is failing on a scenario:

```
  @lc_metatags_and_aliases
  Scenario: Confirm correct metatitles and aliases for checklist nodes            # features/lc_content.feature:31
    When I am logged in as a user with the "administrator" role                   # Drupal\DrupalExtension\Context\DrupalContext::assertAuthenticatedByRole()
      Form field with id|name|label|value|placeholder "Username" not found. (Behat\Mink\Exception\ElementNotFoundException)
```

This is my first time looking at these but I'll see if I can figure out how to fix it.

**Review by jilladams — APPROVED** [review]

**Review by swirtSJW — APPROVED** [review]
The filters look good and test out well.

The table is missing a caption, but it was missing a caption before (accessibility), so will not bind this filte change  to it.  Captions are part of the style guide so a follow up ticket would be good for caption on the VA forms and audit view.

**Comment by swirtSJW** [comment]
image

**Pull request merged**
