### PR TITLE
VAGOV-5519 behat: migration

### PR DESCRIPTION
**Pull request by swirtSJW**
@jonpugh this is putting your behat test back in that I removed before our deployment to staging.

### CODE REVIEW

**Comment by jonpugh** [comment]
Nice! Make sure it has the latest `develop` @swirtSJW and that the right command is in tests.yml.

**Comment by jonpugh** [comment]
Roping in @beeyayjay 

This PR can be used to add a basic migration test!

**Comment by swirtSJW** [comment]
This test is actually running correctly now.  Only the test itself seems to be legitimately failing or at least hitting a false positive. 
  ` The text "ERROR" appears in the text of this page, but it should not.`

**Comment by swirtSJW** [comment]
@jonpugh I got your test to pass, but I am not sure of:
a) the implication of changing api_driver from drush to drupal.
b) a more precise way to validate that errors are not present on the page.  The method you had seems to be failing  on 'error' which is in present in the menu.
(I am not having any success running this scenario locally so I can only test by pushing it up.)

**Pull request closed without merging**
