### PR TITLE
VACMS-2811 add timezones to date fields

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #2811 

## Testing done
Visual / Behat

## Screenshots
image
image
image

## QA steps
Visually verify that new smart time field (Date and time) appears, and is disabled on node and view forms for events, news releases, and situation update paragraphs.

### CODE REVIEW

**Review by kevwalsh — CHANGES_REQUESTED** [review]
Great stuff.  Per zoom meeting, let's take care of these little details. 

Create_Event___VA_gov_CMS

**Comment by ethanteague** [comment]
> Great stuff. Per zoom meeting, let's take care of these little details.
> 
> Create_Event___VA_gov_CMS

Updated, @kevwalsh

**Review by kevwalsh — DISMISSED** [review]
i un-hid the new field and tested on http://pr3120.ci.cms.va.gov/node/add/event

That looks great. 

BUT: 

News release and Situation update should not have a daterange. they should be just single date fields. 

we could considering merging this as is, to unblock the FE as soon as possible for the event content type. But i think we'll need a different solution for news release and situation update.

**Comment by ethanteague** [comment]
> i un-hid the new field and tested on http://pr3120.ci.cms.va.gov/node/add/event
> 
> That looks great.
> 
> BUT:
> 
> News release and Situation update should not have a daterange. they should be just single date fields.
> 
> we could considering merging this as is, to unblock the FE as soon as possible for the event content type. But i think we'll need a different solution for news release and situation update.

Just updated pr to only show the end date stuff on events, @kevwalsh . Here's what it looks like on a press release:
image

**Comment by swirtSJW** [comment]
Needs conflict resolution

**Comment by ethanteague** [comment]
> Needs conflict resolution

Updated, @swirtSJW :+1:

**Comment by swirtSJW** [comment]
behat fail :(

**Comment by ethanteague** [comment]
> behat fail :(

So, the failures look to be related to two terms that aren't on checklist - when the test tries to tick "Burials and memorials" or "Decision reviews and appeals," said terms aren't there. My pr isn't touching any term or checklist stuff, so I'm guessing this change occurred on prod, @swirtSJW @kevwalsh 
image
image

**Comment by acrollet** [comment]
@ethanteague shoot, that must have been a recent change. We should probably refactor the test to just check the first three of those checkboxes. CC @kaise-lafrai I bet this is why the tests work locally for you.

**Review by swirtSJW — APPROVED** [review]

**Pull request merged**
