### PR TITLE
VACMS 4898: Send node count data to Prometheus

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

See #4898, #4900, and #4902.

## QA steps

As user _uid_ with _user_role_
1. Navigate to /metrics
2. Validate ACs from #4898 :
    - [ ] [Drupal contrib module](https://www.drupal.org/project/prometheus_exporter) is installed
    - [ ] total node count data (published + unpublished) metrics are provided
3. Validate ACs from #4900 :
    - [ ] published node count is provided
4. Validate ACs from #4902:
    - [ ] number of total / active / blocked users is provided

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [x] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by ndouglas** [comment]
```
      │ https://pr5386-1znfkzo4zgyx4dnlsgq0cipcdunevfdc.ci.cms.va.gov/static/health-care/about-va-health-benefits/vision-care/blind-low-vision-rehab-services/
    And I am on "/static/health-care"                                                                                                                               # Drupal\DrupalExtension\Context\MinkContext::visit()
    Then the response status code should be 403                                                                                                                     # Drupal\DrupalExtension\Context\MinkContext::assertResponseStatus()
    Then I set the node with title "VA health care" to "published"                                                                                                  # CustomDrupal\FeatureContext::setTheNodeWithTitle()
    And I am on "/health-care"                                                                                                                                      # Drupal\DrupalExtension\Context\MinkContext::visit()
    Then I should see "Published" in the ".view-id-right_sidebar_latest_revision" element                                                                           # Drupal\DrupalExtension\Context\MinkContext::assertElementContainsText()

│
╳  Notice: MemcachePool::set(): Server memcache (tcp 11211, udp 0) failed with: SERVER_ERROR out of memory storing object
╳   (130) in /var/lib/tugboat/docroot/modules/contrib/memcache/src/Driver/MemcacheDriver.php line 17
│
└─ @AfterFeature @mock_va_gov_urls # CustomDrupal\ContentModelContextCustom::disableVaGovBackendHttpClient()
```

Huh, haven't seen that one before.

**Comment by ndouglas** [comment]
Looking at `stats` to see if I see anything weird:

```
STAT pid 7
STAT uptime 4469
STAT time 1621445166
STAT version 1.6.9
STAT libevent 2.1.8-stable
STAT pointer_size 64
STAT rusage_user 14.521036
STAT rusage_system 51.297565
STAT max_connections 1024
STAT curr_connections 2
STAT total_connections 3926
STAT rejected_connections 0
STAT connection_structures 68
STAT response_obj_oom 0
STAT response_obj_count 1
STAT response_obj_bytes 65536
STAT read_buf_count 23
STAT read_buf_bytes 376832
STAT read_buf_bytes_free 294912
STAT read_buf_oom 0
STAT reserved_fds 20
STAT cmd_get 2696651
STAT cmd_set 180990
STAT cmd_flush 0
STAT cmd_touch 0
STAT cmd_meta 0
STAT get_hits 741288
STAT get_misses 1955363
STAT get_expired 0
STAT get_flushed 0
STAT delete_misses 2908
STAT delete_hits 2227
STAT incr_misses 0
STAT incr_hits 0
STAT decr_misses 0
STAT decr_hits 0
STAT cas_misses 0
STAT cas_hits 0
STAT cas_badval 0
STAT touch_hits 0
STAT touch_misses 0
STAT auth_cmds 0
STAT auth_errors 0
STAT bytes_read 884150931
STAT bytes_written 3143466318
STAT limit_maxbytes 268435456
STAT accepting_conns 1
STAT listen_disabled_num 0
STAT time_in_listen_disabled_us 0
STAT threads 4
STAT conn_yields 9
STAT hash_power_level 16
STAT hash_bytes 524288
STAT hash_is_expanding 0
STAT slab_reassign_rescues 595
STAT slab_reassign_chunk_rescues 0
STAT slab_reassign_evictions_nomem 755
STAT slab_reassign_inline_reclaim 0
STAT slab_reassign_busy_items 0
STAT slab_reassign_busy_deletes 0
STAT slab_reassign_running 0
STAT slabs_moved 6
STAT lru_crawler_running 0
STAT lru_crawler_starts 12
STAT lru_maintainer_juggles 421798
STAT malloc_fails 0
STAT log_worker_dropped 0
STAT log_worker_written 0
STAT log_watcher_skipped 0
STAT log_watcher_sent 0
STAT unexpected_napi_ids 0
STAT round_robin_fallback 0
STAT bytes 223219362
STAT curr_items 69359
STAT total_items 181585
STAT slab_global_page_pool 0
STAT expired_unfetched 1
STAT evicted_unfetched 20302
STAT evicted_active 12
STAT evictions 24086
STAT reclaimed 0
STAT crawler_reclaimed 1
STAT crawler_items_checked 722227
STAT lrutail_reflocked 1750
STAT moves_to_cold 178682
STAT moves_to_warm 73775
STAT moves_within_lru 40244
STAT direct_reclaims 24086
STAT lru_bumps_dropped 0
END
```

`stats items` indicates there was an OOM on slab 18:

```
STAT items:18:number 9660
STAT items:18:number_hot 0
STAT items:18:number_warm 3738
STAT items:18:number_cold 5922
STAT items:18:age_hot 0
STAT items:18:age_warm 3262
STAT items:18:age 3304
STAT items:18:mem_requested 39282112
STAT items:18:evicted 513
STAT items:18:evicted_nonzero 0
STAT items:18:evicted_time 1349
STAT items:18:outofmemory 1
STAT items:18:tailrepairs 0
STAT items:18:reclaimed 0
STAT items:18:expired_unfetched 0
STAT items:18:evicted_unfetched 349
STAT items:18:evicted_active 11
STAT items:18:crawler_reclaimed 0
STAT items:18:crawler_items_checked 104477
STAT items:18:lrutail_reflocked 38
STAT items:18:moves_to_cold 29056
STAT items:18:moves_to_warm 15865
STAT items:18:moves_within_lru 1474
STAT items:18:direct_reclaims 513
STAT items:18:hits_to_hot 13449
STAT items:18:hits_to_warm 37443
STAT items:18:hits_to_cold 31405
STAT items:18:hits_to_temp 0
```

`stats slabs` gives a little more info about slab 18:

```
STAT 18:chunk_size 4544
STAT 18:chunks_per_page 230
STAT 18:total_pages 42
STAT 18:total_chunks 9660
STAT 18:used_chunks 9660
STAT 18:free_chunks 0
STAT 18:free_chunks_end 0
STAT 18:get_hits 82297
STAT 18:cmd_set 30011
STAT 18:delete_hits 55
STAT 18:incr_hits 0
STAT 18:decr_hits 0
STAT 18:cas_hits 0
STAT 18:cas_badval 0
STAT 18:touch_hits 0
```

That's a lot of chunks.  From what I understand, this OOM issue should only happen if there are too many chunks of the same size being written at the same time (which I don't _think_ applies here), or if the five oldest items in the cache, LRU-wise, are all locked (which could be).

This looks reasonable (output from `memcache-tool-ng`):

```
memcache:11211:
   #  Item_Size    Max_age   Pages     Count   Used Mem     To Store   Efficiency              Evicted  Evict_Time          OOM
   2       120B      2889s       1        14    1.00 MB      1.51 KB       0.15 %                    0           0            0
   3       152B      2889s       1         4    1.00 MB        494 b       0.05 %                    0           0            0
   4       192B         0s       1         0    1.00 MB          0 b       0.00 %                    0           0            0
   5       240B         0s       1         0    1.00 MB          0 b       0.00 %                    0           0            0
   6       304B      4420s       1        57    1.00 MB     16.07 KB       1.57 %                    0           0            0
   7       384B      5267s       2      3307    2.00 MB      1.13 MB      56.31 %                    0           0            0
   8       480B      5267s       2      3656    2.00 MB      1.40 MB      70.16 %                    0           0            0
   9       600B      4571s       1       352    1.00 MB    191.33 KB      18.68 %                    0           0            0
  10       752B      4561s       1       495    1.00 MB    319.66 KB      31.22 %                    0           0            0
  11       944B      4651s       1       908    1.00 MB    747.33 KB      72.98 %                    0           0            0
  12       1.2K      3805s       2      1158    2.00 MB      1.21 MB      60.48 %                  303         374            0
  13       1.4K      3719s       2      1415    2.00 MB      1.89 MB      94.59 %                 1810         754            0
  14       1.8K      4406s       4      1736    4.00 MB      2.79 MB      69.73 %                 1089        1357            0
  15       2.3K      4283s      19      8508   19.00 MB     16.21 MB      85.32 %                 6791        1366            0
  16       2.8K      4284s      16      5775   16.00 MB     15.33 MB      95.79 %                  430        1379            0
  17       3.5K      4288s      87     25023   87.00 MB     76.53 MB      87.96 %                12264        1372            0
  18       4.4K      4285s      42      9660   42.00 MB     37.46 MB      89.20 %                  513        1349            1
  19       5.5K      4283s      25      4600   25.00 MB     21.71 MB      86.85 %                  174        1374            0
  20       6.9K      4286s      10      1469   10.00 MB      8.75 MB      87.52 %                   89        1361            0
  21       8.7K      4273s       3       354    3.00 MB      2.61 MB      86.92 %                  121        1338            0
  22      10.8K      4239s       2       188    2.00 MB      1.78 MB      88.83 %                  108        1268            0
  23      13.6K      4529s       2       144    2.00 MB      1.70 MB      85.25 %                    0           0            0
  24      16.9K      3734s       2       120    2.00 MB      1.85 MB      92.75 %                  182         830            0
  25      21.2K      3816s       4       191    4.00 MB      3.38 MB      84.55 %                  144         880            0
  26      26.5K      4420s       2        75    2.00 MB      1.75 MB      87.35 %                   27        1539            0
  27      33.1K      3538s       1        29    1.00 MB    884.79 KB      86.41 %                   23         623            0
  28      41.4K      4283s       1         4    1.00 MB    148.67 KB      14.52 %                    0           0            0
  29      51.7K      4282s       1        15    1.00 MB    696.04 KB      67.97 %                    0           0            0
  30      64.7K      4280s       2        20    2.00 MB      1.18 MB      58.85 %                    0           0            0
  31      80.9K      4280s       2        22    2.00 MB      1.56 MB      77.97 %                    0           0            0
  32     101.1K      4286s       2        14    2.00 MB      1.21 MB      60.72 %                    0           0            0
  33     126.3K      4270s       2        15    2.00 MB      1.61 MB      80.38 %                    0           0            0
  34     157.9K      4257s       2         8    2.00 MB      1.07 MB      53.69 %                    0           0            0
  35     197.4K      4269s       2         8    2.00 MB      1.39 MB      69.74 %                    0           0            0
  36     246.8K      4264s       1         3    1.00 MB    656.24 KB      64.09 %                    0           0            0
  37     308.5K      2910s       1         1    1.00 MB    253.15 KB      24.72 %                    0           0            0
  38     385.6K      3080s       6        11    6.00 MB      3.54 MB      59.01 %                   18          89            0

Total used memory: 257.00 MB (for 212.88 MB of data)
Global efficiency:  82.83 %
```

There's just not a whole lot of pressure there.   There's a very definite bell curve with the distribution of chunk size and eviction, which indicates we could probably stand to tune our slab sizing, but it still seems surprising that we'd see an out-of-memory error here.

I'm going to assume this was just a passing blip, but leaving this info here if I have some free time to follow this up, or if someone else encounters the issue.

**Comment by ElijahLynn** [comment]
PR for Prometheus scrape job that @olivereri, @ndouglas and I worked on is here > https://github.com/department-of-veterans-affairs/devops/pull/9199, can be merged in any order.

**Comment by ndouglas** [comment]
[Here](https://cms-1znfkzo4zgyx4dnlsgq0cipcdunevfdc.ci.cms.va.gov/metrics) is the metrics page -- no auth required.

@ElijahLynn suggested there was no need to require authentication to view these statistics -- these are pretty harmless -- and authentication would present an added bit of aggravation in getting Prometheus working with the CMS and create a small amount of technical debt (credentials for basic auth).  I don't think it's likely that we'll be exporting sensitive metrics at any point, but it is possible to re-enable this in the future.

The patch is really pretty rudimentary -- I might submit a followup patch at some point to refactor the plugin to perform a single fielded query instead of multiple small count queries, but IDK how much value that would actually provide and my work as-is follows their pattern in that and other plugins, so eh.

**Review by acrollet — APPROVED** [review]

**Pull request merged**
