### PR TITLE
VAGOV-567 & 572: Adding behat tests for alerts and expandable text types.

### PR DESCRIPTION
**Pull request by ethanteague**

### CODE REVIEW

**Comment by ElijahLynn** [comment]
rebuild

**Comment by ElijahLynn** [comment]
This failed because it didn't have the Lando changes we made. It will need to be rebased off of `develop` for it to pass and build.

**Comment by ethanteague** [comment]
@ElijahLynn @andyhawks rebased and force pushed.

**Comment by ethanteague** [comment]
Build failed immediately after rebase, @ElijahLynn - console output isn't revealing anything obvious: http://jenkins-ecs-master-1574396032.us-gov-west-1.elb.amazonaws.com/job/ecs_ci_test/161/console

**Comment by ElijahLynn** [comment]
We ran out of ALBs in our limit, I just cleared some up.

**Comment by ElijahLynn** [comment]
rebuild

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-44<br><br> [button_visit-site](http://pr-44.va.agile6.com)

**Pull request merged**
