### PR TITLE
VACMS-12234 Refactor for Lovell name change

### LINKED ISSUE #12234: Back End: Refactor to complete name change
See: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12092

As a Back End Developer I want to know where in the code the current name of Lovell exists, so that I can make the name change, and I want to make that change.

# [va.gov-cms](http://va.gov-cms/) repo

The strings "Lovell Federal VA health care" and "Lovell Federal TRICARE health care" exist in the following:
## Drupal CMS
docroot/modules/custom/va_gov_lovell/js/limit_lovell.es6.js:
docroot/modules/custom/va_gov_lovell/src/LovellOps.php:
docroot/modules/custom/va_gov_lovell/src/LovellEventSubscriber.php:

## Cypress Testing code
tests/cypress/integration/behavioral/content_editing_vamc_facility_service.feature:

## Acceptance Criteria
Content
- [x] VAMC System names have been updated (TWO systems).

Code
- [x] Audit has been completed to discover where name change needs to be made.
    - [x] Breadcrumbs
    - [x] Menus
    - [x] Content within nodes
- [x] Cypress tests have been created, updated, or determined to be not needed.
- [x] Enumerate the _ways_ the Lovell names appear to editors, as described this [cms-12234 Google Sheet](https://docs.google.com/spreadsheets/d/1-imSVlbAASHl0RT6KBx5b4NX5jcOkPRfQTI2lg8vrl8/edit#gid=595146873).
- [x] Code has been updated with the name change.
- [x] Confirm that the name appears correctly in all _ways_ enumerated above.

### Non-code work to complete this issue
- [x] Update the TRICARE and VA systems
  - [x]  New names
  - [ ] New menu links
  - [x] New URL aliases
 - [x] Update all Lovell content through bulk edit
   - [x] Resave content
   - [x] Update URL alias

### PR DESCRIPTION
**Pull request by omahane**
## Description

Relates to #12234 

## Testing done
Manually

## Screenshots
new-name-lovell-tricare-system-page
new-name-lovell-va-system-page
old-name-search-tricare-after-bulk-save
old-name-search-va-after-bulk-save
new-name-facility-health-services

### As an admin
Go to the [VAMC System page for TRICARE](https://pr12328-v7fhnsgnlptfrsh8cy4kcordmbhs3rps.ci.cms.va.gov/lovell-federal-health-care-tricare)
- [x] Validate that the name is changed
- [x] Validate that the url is changed
- [x] Validate that the breadcrumb is changed

Go to the [VAMC System page for VA](https://pr12328-v7fhnsgnlptfrsh8cy4kcordmbhs3rps.ci.cms.va.gov/lovell-federal-health-care-va)
- [x] Validate that the name is changed
- [x] Validate that the url is changed
- [x] Validate that the breadcrumb is changed

Go to a [VAMC System Health Service for TRICARE](https://pr12328-v7fhnsgnlptfrsh8cy4kcordmbhs3rps.ci.cms.va.gov/lovell-federal-health-care-tricare/health-services/homeless-veteran-care-at-lovell-federal-health-care-tricare)
- [x] Validate that the name is changed
- [x] Validate that the url is changed
- [x] Validate that the breadcrumb is changed

Go to a [VAMC System Health Service for VA](https://pr12328-v7fhnsgnlptfrsh8cy4kcordmbhs3rps.ci.cms.va.gov/lovell-federal-health-care-va/health-services/internal-medicine-at-lovell-federal-health-care-va)
- [x] Validate that the name is changed
- [x] Validate that the url is changed
- [x] Validate that the breadcrumb is changed

Go to a [Blind and low vision rehabilitation - Captain James A. Lovell Federal Health Care Center](https://pr12328-v7fhnsgnlptfrsh8cy4kcordmbhs3rps.ci.cms.va.gov/lovell-federal-health-care-tricare/locations/captain-james-a-lovell-federal-health-care-center/blind-and-low-vision-rehabilitation)
- [ ] Validate that the name is changed
- [x] Validate that the url is changed
- [x] Validate that the breadcrumb is changed

Go to a [VAMC Facility Health Service for VA](https://pr12328-v7fhnsgnlptfrsh8cy4kcordmbhs3rps.ci.cms.va.gov/lovell-federal-health-care-va/locations/captain-james-a-lovell-federal-health-care-center/blind-and-low-vision-rehabilitation)
- [ ] Validate that the name is changed
- [x] Validate that the url is changed
- [x] Validate that the breadcrumb is changed

Go to the content audit tools
- [x] Search for "Lovell Federal TRICARE health care"
- [x] Validate the findings of the [vacms-12234 spreadsheet](https://docs.google.com/spreadsheets/d/1-imSVlbAASHl0RT6KBx5b4NX5jcOkPRfQTI2lg8vrl8/edit#gid=1080019887)
- [x] Search for "Lovell Federal VA health care"
- [x] Validate the findings of the [vacms-12234 spreadsheet](https://docs.google.com/spreadsheets/d/1-imSVlbAASHl0RT6KBx5b4NX5jcOkPRfQTI2lg8vrl8/edit#gid=1080019887)
- [x] Search for "Lovell Federal health care - TRICARE"
- [x] Validate the findings of the [vacms-12234 spreadsheet](https://docs.google.com/spreadsheets/d/1-imSVlbAASHl0RT6KBx5b4NX5jcOkPRfQTI2lg8vrl8/edit#gid=1080019887)
- [x] Search for "Lovell Federal health care - VA"
- [x] Validate the findings of the [vacms-12234 spreadsheet](https://docs.google.com/spreadsheets/d/1-imSVlbAASHl0RT6KBx5b4NX5jcOkPRfQTI2lg8vrl8/edit#gid=1080019887)

Go to the [content search tool](https://pr12328-v7fhnsgnlptfrsh8cy4kcordmbhs3rps.ci.cms.va.gov/admin/content/audit/search)
- [x] Search for "Lovell Federal TRICARE health care"
- [x] Validate the findings of the [vacms-12234 spreadsheet](https://docs.google.com/spreadsheets/d/1-imSVlbAASHl0RT6KBx5b4NX5jcOkPRfQTI2lg8vrl8/edit#gid=1080019887)
- [x] Search for "Lovell Federal VA health care"
- [x] Validate the findings of the [vacms-12234 spreadsheet](https://docs.google.com/spreadsheets/d/1-imSVlbAASHl0RT6KBx5b4NX5jcOkPRfQTI2lg8vrl8/edit#gid=1080019887)
- [x] Search for "Lovell Federal health care - TRICARE"
- [x] Validate the findings of the [vacms-12234 spreadsheet](https://docs.google.com/spreadsheets/d/1-imSVlbAASHl0RT6KBx5b4NX5jcOkPRfQTI2lg8vrl8/edit#gid=1080019887)
- [x] Search for "Lovell Federal health care - VA"
- [x] Validate the findings of the [vacms-12234 spreadsheet](https://docs.google.com/spreadsheets/d/1-imSVlbAASHl0RT6KBx5b4NX5jcOkPRfQTI2lg8vrl8/edit#gid=1080019887)

### As an editor
Log in as julie.ewart@va.gov

Edit a [TRICARE page](https://pr12328-v7fhnsgnlptfrsh8cy4kcordmbhs3rps.ci.cms.va.gov/node/52760/edit)
- [x] Save the page
- [x] Validate that the breadcrumb includes the new name
- [x] Validate that the name includes the new name
- [x] Validate that the url includes the new path 

Edit a [VA page](https://pr12328-v7fhnsgnlptfrsh8cy4kcordmbhs3rps.ci.cms.va.gov/node/39195/edit)
- [x] Save the page
- [x] Validate that the breadcrumb includes the new name
- [x] Validate that the name includes the new name
- [x] Validate that the url includes the new path 

Create a [TRICARE VAMC Facility Health Service](https://pr12328-v7fhnsgnlptfrsh8cy4kcordmbhs3rps.ci.cms.va.gov/node/add/health_care_local_health_service)
- [x] Save the page
- [x] Validate that the breadcrumb includes the new name (if applicable)
- [x] Validate that the name includes the new name (if applicable)
- [x] Validate that the url includes the new path (if applicable)

Create a [VA VAMC Facility Health Service](https://pr12328-v7fhnsgnlptfrsh8cy4kcordmbhs3rps.ci.cms.va.gov/node/add/health_care_local_health_service)
- [x] Save the page
- [x] Validate that the breadcrumb includes the new name (if applicable)
- [x] Validate that the name includes the new name (if applicable)
- [x] Validate that the url includes the new path (if applicable)

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [x] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by omahane** [comment]
At first it didn't pass the phpunit test.
I can in the Tugboat terminal `./bin/task --taskfile=tests.yml va/tests/phpunit`
A few minutes later, it showed as passing phpunit.

Then, I ran `./bin/task —taskfile=tests.yml va/tests/cypress`
Several minutes later, it showed as passing cypress.

**Comment by omahane** [comment]
@JayDarnell I just changed the code and tried it on lovell-federal-health-care-va/about-us/history
The new code seems to work.

**Review by JayDarnell — DISMISSED** [review]
Changes look good. All QA steps pass

**Comment by swirtSJW** [comment]
Chicken and egg problem with this test and content.   Cleanest solution is to disable the test as part of this PR and then after it lands on prod and the content is updated, we follow up with a PR to re-enable the tests.

**Comment by omahane** [comment]
After the content change, I ran cypress tests manually:
Screen Shot 2023-01-27 at 11 23 52 AM

Screen Shot 2023-01-27 at 11 22 37 AM

**Review by JayDarnell — APPROVED** [review]
Changes look good. Temporary removal of cypress tests is necessary to avoid a chicken / egg scenario caused by these changes being closely tied to upcoming content changes.

**Comment by omahane** [comment]
This PR was passing before merging latest from main.
Screen Shot 2023-01-30 at 9 33 57 AM

**Pull request merged**
