### PR TITLE
VAGOV-2142 Manual cherry-pick of yaml-tests from #348 to master for PROD release 

### PR DESCRIPTION
**Pull request by ElijahLynn**
Need this merge in master because deploys to STAGING and PROD are dependent on these.

This is meant to be a partial cherry-pick of #348 and is needed in `master` because we won't be merging in `develop` before the next release.

### CODE REVIEW

**Comment by ElijahLynn** [comment]
This is failing on container boot with an error 
> jinja2.exceptions.TemplateNotFound: /templates/ssmtp.ini.tpl

But that is odd since the PR to introduce the above was merged into `develop` and isn't on this branch or `master`.

**Comment by ElijahLynn** [comment]
Ahh, it was in the entrypoint. Amending to current commit and am force pushing, want to keep this all in one commit.

**Comment by ElijahLynn** [comment]
Hrm, odd, says now:

> Bad token. Set with --github-token option or GITHUB_TOKEN environment variable. Create a new token at https://github.com/settings/tokens/new?description=yaml-tests&scopes=repo:status,public_repo Message: Error completing request

**Comment by ElijahLynn** [comment]
@jonpugh can you help me figure this `bad token` out above? 

http://jenkins.cms.va.gov/job/ecs_ci_test/711/artifact/cms-deploy-hooks-results.log/*view*/

This is on `master`, your yaml-tests in `develop` haven't been merged in yet.

**Comment by ElijahLynn** [comment]
rebuild

**Comment by jonpugh** [comment]
Apologies for the poor exception handling in yaml-tests. There's a number of ways the API integration can go wrong.

Let me explain the error message:

> Bad token. Set with --github-token option or GITHUB_TOKEN environment variable. Create a new token at https://github.com/settings/tokens/new?description=yaml-tests&scopes=repo:status,public_repo Message: Error completing request  

The last part is the exact error string from the GitHub API: `Error completing request`.

Everythiing else is in YAML tests. I didn't catch a unique enough exception to print "Bad Token". It could be fine in this instance. I will make a github issue in the plugin to better handle exceptions.

**Comment by ElijahLynn** [comment]
> Apologies for the poor exception handling in yaml-tests. There's a number of ways the API integration can go wrong.
> 
> Let me explain the error message:
> 
> > Bad token. Set with --github-token option or GITHUB_TOKEN environment variable. Create a new token at https://github.com/settings/tokens/new?description=yaml-tests&scopes=repo:status,public_repo Message: Error completing request
> 
> The last part is the exact error string from the GitHub API: `Error completing request`.
> 
> Everythiing else is in YAML tests. I didn't catch a unique enough exception to print "Bad Token". It could be fine in this instance. I will make a github issue in the plugin to better handle exceptions.

Thanks, can you crosslink this issue to it.

**Comment by jonpugh** [comment]
https://github.com/provision-ops/yaml-tests/issues/18

**Pull request merged**
