### PR TITLE
VACMS-14704: Adding service location fields

### PR DESCRIPTION
**Pull request by omahane**
## Description

Relates to #14704

## Testing done
Manually

## Screenshots
Screenshot 2023-10-09 at 2 30 05 PM

### Add a service location
- As an admin, create a [VBA Facility Service](https://pr15599-ttbetaiddfuet2jtyhdiaqqrn8ewvo67.ci.cms.va.gov/node/add/vba_facility_service)
- [x] For **Section** select "Cheyenne VA Regional Benefit Office"
- [x] For **Facility** select "Cheyenne VA Regional Benefit Office"
- [x] For **Service name** select "Pensions"
- [x] For **Task-oriented description header** add "Get help filling out pension benefits paperwork."
- [x] For **Service location description** add "Our benefits counselors can help you fill out necessary paperwork and check your status."
- [x] Check the following boxes for **Service delivery options**:
  - [ ] Home based care
  - [ ] In-person appointments 
- [x] Save the Facility service
- [x] Confirm content in the node:view

### Edit a service location
- Edit the VBA Facility Service you just created
- [x] Check the following boxes for **Service delivery options**:
  - [x] Home based care
  - [x] In-person service desk
  - [x] Virtual service desk
- [x] Click "Add Service location"
  - [x] Add a **Task-oriented description header** of your choosing
  - [x] Add a **Service location description** of your choosing
  - [x] Select **Service delivery options**
- [x] Save
- [x] Confirm your changes in node:view

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### Is this PR blocked by another PR?

- [x] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [x] `Needs PO review`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by davidmpickett** [comment]
Should probably give the "Service delivery options" taxonomy a little love too
**Label:** VA Service delivery options
**Description:** Single source of truth for service delivery options (e.g. in-person appointments, virtual hotline)

**Comment by swirtSJW** [comment]
The fields all look good.  
This issue I think we ought to do something about, but not as part of this ticket.
image

**Comment by swirtSJW** [comment]
I just changed this PR to point to integration-service-location  so it is safe to merge when review is complete.

**Review by swirtSJW — APPROVED** [review]
This looks great @omahane   Well done.

**Pull request merged**
