### PR TITLE
VACMS-5696: Remove erie,  eastern OK, and lebanon facility status endpoints.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #5696

## Testing done
Visual

## QA steps
Visually verify Erie and Lebanon have been removed from the 2 migration files in this pr.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by kevwalsh — APPROVED** [review]
LGTM! Will set a reminder to merge after Friday's daily CMS deploy.

**Review by kevwalsh — CHANGES_REQUESTED** [review]
@ethanteague Can you split split out Erie into a separate PR with a Do Not Merge label? It will not be launching next week.

**Comment by ethanteague** [comment]
> @ethanteague Can you split split out Erie into a separate PR with a Do Not Merge label? It will not be launching next week.

You bet, @kevwalsh :+1:

**Comment by ethanteague** [comment]
Updated, @kevwalsh - erie pr is here: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5769

**Pull request merged**
