### PR TITLE
VAGOV-4180: Get Behat tests running against CI servers. 

### PR DESCRIPTION
**Pull request by jonpugh**
This PR will get the behat tests able to run against the CI sites.

Work is mostly being done in the DevOps repo: See branch `VAGOV-4180-behat-devops` https://github.com/department-of-veterans-affairs/va.gov-cms-devops/pull/87

For Behat to work against the Drupal sites, the following has to be set in a behat.yml config file dynamically, or set in BEHAT_PARAMS as JSON encoded:

```yml
  extensions:
    Behat\MinkExtension:
      base_url: 'http://url.for.site.to.test'
    Drupal\DrupalExtension:
      drush:
        alias: '@drush_alias_for_site_to_test'
      drupal:
        drupal_root: '/path/to/code/for/site/to/test'
```

It iis VERY tricky to get this YML JSON encoded by hand. 

I have found it easier to do automation by dynamically creating a `behat.environment.yml` file from the source `behat.yml` file and running `bin/behat --config=behat.environment.yml` instead.

This is how devshop automates behat test running. 

**NOTE:** The behat.yml file in the site codebase must NOT have those options like "drupal_root" set. They are commented out on purpose and there is a note there.

BEHAT_PARAMS will NOT override items in behat.yml, which is unfortunate. I've been working around this for years instead of diving in and fixing behat. Perhaps it's time to change that.

Another option would be to fork Behat and allow $ENVIRONMENT variable replacement in the YML, like docker-compose offers.

### CODE REVIEW

**Comment by ElijahLynn** [comment]
Does this need a coordinated merge with the devops PR?

**Comment by ElijahLynn** [comment]
Just closing this and reopening to destroy the old ENVs.

**Comment by ElijahLynn** [comment]
@jonpugh Are we waiting on this step?
> Given I am on the homepage                                                   
># Drupal\DrupalExtension\Context\MinkContext::iAmOnHomepage() 
> (1 passed, 1 undefined)  
> FeatureContext has missing steps. Define them with these snippets:

**Comment by mbenziane** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Pull request closed without merging**
