### PR TITLE
VACMS 10046: Update Link color across the CMS to meet WCAG 2.0 AAA contrast requirement

### LINKED ISSUE #10046: Update Link color across the CMS to meet WCAG 2.0 AAA contrast requirement
## Description
Reference design tickets:

[9916](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9916): The standard link style is blue underline with a hover style of a light blue background and no underline. This combination of blue does not pass the WCAG 2.0 AAA contrast requirements.

[9917](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9917): An accessibility audit found that on all products and all tables, the main content listing has tables that do not pass WCAG accessibility standards for hover states. Table rows currently have a hover state that changes to light blue.

[9915](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9915): On staging, the footer links have a background color of light blue which introduces an accessibility issue.

See approved [link design](https://www.figma.com/file/ScABI31f3MRFEvQ8WitVPa/CMS-Design-System?node-id=1956%3A95319)

The following changes to the links are documented here: [CMS DS Changelog ](https://www.figma.com/file/ktDP1ISywa2Lc5q3GC8ezh/Changelog?node-id=2%3A38)

- All standard links will be changed to the dark blue (004795)
- hover/focus state link color will be darker blue (003e73)
- We think having a background color would be beneficial as this would keep it as a similar format as the front end (they have a background color on hover) This is not an accessibility requirement.
- The hover/focus state should be the lighter blue (e4eff9). This is currently the color on some CMS links, not all. It is also different than the VA.gov front end hover color
- Footer links will remain white
- Footer links on hover/focus will keep their current background color (e4eff9) but the text will be darker blue (003e73)
- All links should have underline on default and then no underline on hover/focus

There is an additional condition for links in read-only content. To meet the same requirements we made an adjustment to the grey lighter color to #E5E3E1. See changes are documented here: [CMS DS Changelog](https://www.figma.com/file/ktDP1ISywa2Lc5q3GC8ezh/Changelog?node-id=2%3A2) 

## Acceptance Criteria
- [ ] Implement the design changes listed above across CMS
- [ ] Design and accessibility review
- [ ] QA

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by edmund-dunn**
## Description

Closes #10046.

## Testing done
Visually checked on my local machine.

## QA steps

Log in and click on Content. Verify that the Overview tab text is not white and not underlined. The Overview tab itself should show the underline/bottom border. 
Verify that the edit buttons have dark gray text and background darkens on hover. 

### Definition of Done

- [x] Acceptance Criteria in related issue are met.
- [x] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [x] No announcement is needed for this code change.
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by ndouglas** [comment]
That's a whole lotta commits.

**Comment by ndouglas** [comment]
>Verify that the Overview tab text is not white and not underlined.

Clicked: Screen Shot 2022-09-02 at 2 27 29 PM
Hover: 
Screen Shot 2022-09-02 at 2 27 36 PM

>Verify that the edit buttons have dark gray text and change to blue with white text on hover.

Screen Shot 2022-09-02 at 2 28 27 PM
Screen Shot 2022-09-02 at 2 28 32 PM

**Review by ndouglas — APPROVED** [review]

**Comment by ndouglas** [comment]
I'm a little unclear about what "click" means -- I clicked, but it's a link so it sent me back to the same page.  Did we mean "hover"?  Also wanna be clear about the meaning of "underline", since the link text is not underlined but the the tab as a whole _is_.  Arguably.

**Review by ndouglas — DISMISSED** [review]
LGTM.

**Comment by ndouglas** [comment]
I did merge the revert, so this might need to be squashed/rebased/resolved.

**Review by laflannery — COMMENTED** [review]
I found 2 additional link buttons that require updates:

1. Under Manage > People there is button "Download CSV of all users.  Text is white and it should be `#212121`
2. Red Delete buttons.  Example is under Manage > Content > Media > Images then click on an image to edit it.  Scroll to the bottom and you will see an example of this (The text is blue and it should be white)

**Review by laflannery — APPROVED** [review]
I didn't find any other issues! Looks good to me

**Review by ndouglas — APPROVED** [review]

**Comment by ndouglas** [comment]
Merging to make sure this gets out 🙂

**Pull request merged**
