### PR TITLE
[DO-NOT-MERGE] VAGOV-2848-SSM-SECRETS

### PR DESCRIPTION
**Pull request by mbenziane**
VAGOV-2848-SSM-HIDE-SECRETS

### CODE REVIEW

**Comment by mbenziane** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Comment by ElijahLynn** [comment]
Closing for now to free up PR ENVs as we likely will be using CredStash instead.

**Pull request closed without merging**
