### PR TITLE
VACMS-8404 Button audit

### PR DESCRIPTION
**Pull request by msbtterswrth**
## Description
This is a new view to find instances of 'usa-button' in `field_wysiwyg`. An airtable will be created to analyze this data and will be link to the original ticket. 

Relates to #8404 . 

## Testing done
Navigated to `/admin/content/audit/buttons` and clicked a few results to confirm buttons were present on the node. 

## Screenshots
image

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As cms admin
1. Navigate to https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/admin/content/audit/buttons
    - Validate the view meets standard view ACs
      - [x] display machine, not `default`
      - [x] URL [`/admin/content/{{parent-view-name}}/name-of-view`]
      - [ ] Menu item setting: [tbd]
      - [x] limit to 100 per page, paginated
      - [x] show result count in header
      - default columns
        - [x] Title (sortable) 
        - [x] Edit button  
        - [x] Content type (sortable)
        - [x] Moderation State
        - [x] Section (field_administration) (sortable)
        - [ ] Is Locked (optional)
        - [x] Last updated (date time and by user) (sortable, default sort, DESC)
        -  ~Other content fields as needed~
      - [ ] filters
        - [x] text search (exposed)
        - [x] content type (exposed)
        - [x] moderation state (exposed)
        - [x] section (exposed) (workbench access section; single select, show children)
        - [x] Reset button exists
        - [x] Apply button says 'Filter'
2. Then 
   - [x] Validate that the results shown in the view contain buttons

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by swirtSJW** [comment]
>  Validate that the view meets the view style guide criteria

Can we copy and paste those in here so the style guide AC's live on the ticket and can be referenced as passed or not?

**Comment by swirtSJW** [comment]
A nice improvement to this would be to be able to see the buttons as buttons in the View.   RIght now I have to go to the node to see which link is a button and which isn't

**Review by swirtSJW — CHANGES_REQUESTED** [review]
Hi @msbtterswrth  
A couple QA steps are not passing.
Please make sure you are using your own QA steps before asking a reviewer to.

**Comment by msbtterswrth** [comment]
@swirtSJW  there is a menu item for this view, though we've not decided on standards for that yet, which is why it says [tbd]:
image

The locked column is optional and should be added when bulk edit options are available (which they are not here) so i added `(optional)` to the default ACs in confluence.

I have updated the Updated column to include the user, that was an oversight on my part.
image

**Comment by swirtSJW** [comment]
@msbtterswrth QA steps on a PR should not create mysteries and be left of the to the QAer to decide whether the step ought to be there or not.   You as the creator are in the best position to know/determine these things.
image

**Review by swirtSJW — APPROVED** [review]
QA pass.
Looks great.  Nice solution.
image

**Comment by swirtSJW** [comment]
Tests got stalled out.  Rebuilding to re-run.  The axe failures (3) were due to timeout, not legit failures.
```
 1) Component accessibility test
       /node/add/health_care_local_facility has no detectable accessibility violations on load.:
     CypressError: `cy.task('log')` timed out after waiting `60000ms`.

https://on.cypress.io/api/task
      at https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:146834:19
      at tryCatcher (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:13212:23)
      at https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:8334:41
      at tryCatcher (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:13212:23)
      at Promise._settlePromiseFromHandler (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:11147:31)
      at Promise._settlePromise (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:11204:18)
      at Promise._settlePromise0 (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:11249:10)
      at Promise._settlePromises (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:11325:18)
      at _drainQueueStep (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:7919:12)
      at _drainQueue (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:7912:9)
      at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:7928:5)
      at Async.drainQueues (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:7798:14)
  From Your Spec Code:
      at Context.eval (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/tests?p=cypress/support/index.js:759:20)

  2) Component accessibility test
       /node/add/health_care_region_detail_page has no detectable accessibility violations on load.:
     CypressError: `cy.task('log')` timed out after waiting `60000ms`.

https://on.cypress.io/api/task
      at https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:146834:19
      at tryCatcher (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:13212:23)
      at https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:8334:41
      at tryCatcher (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:13212:23)
      at Promise._settlePromiseFromHandler (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:11147:31)
      at Promise._settlePromise (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:11204:18)
      at Promise._settlePromise0 (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:11249:10)
      at Promise._settlePromises (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:11325:18)
      at _drainQueueStep (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:7919:12)
      at _drainQueue (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:7912:9)
      at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:7928:5)
      at Async.drainQueues (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:7798:14)
  From Your Spec Code:
      at Context.eval (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/tests?p=cypress/support/index.js:759:20)


  3 failing
  3) Component accessibility test
       /node/add/health_care_region_page has no detectable accessibility violations on load.:
     CypressError: `cy.task('log')` timed out after waiting `60000ms`.

https://on.cypress.io/api/task
      at https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:146834:19
      at tryCatcher (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:13212:23)
      at https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:8334:41
      at tryCatcher (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:13212:23)
      at Promise._settlePromiseFromHandler (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:11147:31)
      at Promise._settlePromise (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:11204:18)
      at Promise._settlePromise0 (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:11249:10)
      at Promise._settlePromises (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:11325:18)
      at _drainQueueStep (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:7919:12)
      at _drainQueue (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:7912:9)
      at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:7928:5)
      at Async.drainQueues (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/runner/cypress_runner.js:7798:14)
  From Your Spec Code:
      at Context.eval (https://pr8438-3n9zyq7l45ut64svcznbde33jqlt0djf.ci.cms.va.gov/__cypress/tests?p=cypress/support/index.js:759:20)

```

**Comment by swirtSJW** [comment]
Good news is axe tests passed.   Bad news is the github runner based tasks never ran.   BUT they ran and passed previously so I am going to call this good an merge.    It won't be on the sprint demo environment though so you will have to demo locally or on staging.

**Pull request merged**
