### PR TITLE
VACMS-1421: remove wysiwyg field sync code

### PR DESCRIPTION
**Pull request by acrollet**
## Description

See #1421

## Testing done

Tested saving 'page' type nodes and ensured intro content is preserved and updates are visible.

## QA steps

As a user with the content admin role
- [ ] Ensure that changes to the intro field on Benefits Detail Page content are made as expected

## Definition of Done
- [ ] Product release notes are written (or in progress), if required.
- [ ] Documentation has been updated, if applicable.

### CODE REVIEW

**Comment by acrollet** [comment]
@ethanteague should we have a follow-on to remove ```field_intro_text_limited_html``` from the page content type? It seems that it's no longer in use, but I'm not clear on the history :-)

**Review by swirtSJW — COMMENTED** [review]
I am pretty sure we are still stuck on this one.   I don't think we ever made the front end switch from the old field to the new.   @ethanteague  can you confirm?

Last I recall, your front end PR was rolled back because we needed to wait on Table of Contents being supported... Which I think it is now, but I think the front end is still using the old field not the new.

**Comment by swirtSJW** [comment]
> field_intro_text_limited_html

is the one that should be used, but we never made the switch to it.

**Comment by ethanteague** [comment]
> I am pretty sure we are still stuck on this one. I don't think we ever made the front end switch from the old field to the new. @ethanteague can you confirm?
> 
> Last I recall, your front end PR was rolled back because we needed to wait on Table of Contents being supported... Which I think it is now, but I think the front end is still using the old field not the new.

That's right, @swirtSJW | @acrollet . Front end is still using the old field.

**Comment by swirtSJW** [comment]
@acrollet I am not sure why this has a status of closed.  The ticket needs to performed, just not right now.  I am going to conver this to draft to make sure it does not get merged accidentally.

**Comment by acrollet** [comment]
@swirtSJW weird, I don't think I closed it - anyway 👍 on leaving it in draft

**Comment by swirtSJW** [comment]
This has been removed by an earlier merge.

**Pull request closed without merging**
