### PR TITLE
VAGOV-2937: Unify CMS and WEB build processes. DEPRECATED

### PR DESCRIPTION
**Pull request by jonpugh**
## DEPRECATED

Good changes in this PR are being moved to other PRs:

- [ ]  #493

## ORIGINAL ISSUE

There is a way to integrate node/npm projects with Composer.

This PR builds the front-end code as well as Drupal on `composer install`. The front end right now goes into `./docroot/vendor/va/app` and the `post-install-cmd` sets up a symlink to `./app`.  

It uses the `mouf/nodejs-installer` package to actually download `node` and `npm` executables into the bin directory of the project on `composer install`

Then, you can add any `npm` command you want to run after `composer install` by adding it to the `scripts.post-install-cmd` section of `composer.json`.

This will allow us to create unified development environments where a CMS on a branch and a APP instance on another branch can live together.

Versions can be pinned in composer.json, so when you stamp a release of the front-end, you can then pin that version in the CMS codebase, and then with one shot, release the new version of CMS+FE.

This is a great example of how Node and PHP are really starting to play along.

I need assistance getting it fully up and running, and there are some design decisions to make, like what should the front-end app be called? what directory should it go in? Should we consider the option of designing our deployment system to be able to host both?

When I presented on this at DrupalNYC meetup, an audience member said they tweaked the Lando Node container to run as a host, not just as a CLI.

Food for thought!

WIP: This should block builds by standard job?

## UPDATE

This PR now includes code from https://github.com/department-of-veterans-affairs/va.gov-cms/pull/404 so if this is merged, that one will automatically be merged as well.

## Alignment

Here is the most accurate documentation on how to get the project working: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started

This page is very clear on how to set things up. We should aim to make things as easy as this.

# Update 2:

Determined command to generate HTML, so we can quickly render the front end inside the Drupal site, at `/web` for example:

https://dsva.slack.com/archives/CJ34D8TPB/p1561742139334600?thread_ts=1561741663.333000&cid=CJ34D8TPB

```
npm --no-color run build -- --buildtype=${envName} --asset-source=${assetSource} --drupal-address=${drupalAddress} ${drupalMode}
```

From @jbalboni:

 > Yep, that should do what you want. `drupalMode` should be `--pull-drupal`, since I don’t think you’ll want to use the cache. `assetSource` I’m not positive what you want there. You can pass in a vets-website commit hash and it’ll fetch some JS/CSS assets from S3 or if you do `local` it’ll run the webpack build process. I think you could pick whichever happens to be faster for you.
> You may also need to set DRUPAL_USERNAME and DRUPAL_PASSWORD env variables, to get the right user credentials for talking to the api. Or the defaults may work.
> You can check that it built correctly by running a simple http server in the `build/${envName` folder, where all the output is. You should be able to pull up the home page and click around and have things look correct.

### CODE REVIEW

**Comment by ElijahLynn** [comment]
Nice idea here, does this basically live at /app then? Looking forward to seeing the build output!

**Comment by ElijahLynn** [comment]
Couldn't pull the container, I killed the job. Trying again.

**Comment by ElijahLynn** [comment]
build

**Comment by jonpugh** [comment]
Folder name is arbitrary but yes! Many people have been wanting to be able to add multiple "routes" from domains to folders for a long time...

This is in scope of the provision-ops tools and deployment framework we are building. Just needs to be well thought out. 

Platform.sh does something similar but I would make it simpler...

``

**Comment by ElijahLynn** [comment]
Something hung on building the appserver image. 

>  15:03:48 TASK [roles/ecs_task_vagovcms_ci : Build Docker appserver image] ***************
> 16:01:28 FATAL: command execution failed
> 16:01:28 java.nio.channels.ClosedChannelException

**Comment by ElijahLynn** [comment]
build

**Comment by jonpugh** [comment]
Error messages on `composer install` > `yarn install`:

```
> cd app && yarn install
yarn install v1.16.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @department-of-veterans-affairs/formation-react@4.6.3" has incorrect peer dependency "@department-of-veterans-affairs/formation@^5.4.0".
[4/4] Building fresh packages...
error /home/jon/Projects/VA/va.gov-cms/docroot/vendor/vagov/app/node_modules/libxmljs: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build --loglevel http
Arguments: 
Directory: /home/jon/Projects/VA/va.gov-cms/docroot/vendor/vagov/app/node_modules/libxmljs
Output:
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v72-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v72-linux-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v72-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for libxmljs@0.19.5 and node@12.4.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v72-linux-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.4.0 | linux | x64
gyp info ok 
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/home/jon/Projects/VA/va.gov-cms/docroot/vendor/vagov/app/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/home/jon/Projects/VA/va.gov-cms/docroot/vendor/vagov/app/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/home/jon/Projects/VA/va.gov-cms/docroot/vendor/vagov/app/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/home/jon/Projects/VA/va.gov-cms/docroot/vendor/vagov/app/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/jon/Projects/VA/va.gov-cms/docroot/vendor/vagov/app/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/jon/Projects/VA/va.gov-cms/docroot/vendor/vagov/app/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/jon/Projects/VA/va.gov-cms/docroot/vendor/vagov/app/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:165:21)
gyp ERR! System Linux 5.0.17-200.fc29.x86_64
gyp ERR! command "/home/jon/Projects/VA/va.gov-cms/docroot/vendor/nodejs/nodejs/bin/node" "/home/jon/Projects/VA/va.gov-cms/docroot/vendor/vagov/app/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--loglevel=http" "--module=/home/jon/Projects/VA/va.gov-cms/docroot/vendor/vagov/app/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/home/jon/Projects/VA/va.gov-cms/docroot/vendor/vagov/app/node_modules/libxmljs/build/Release" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /home/jon/Projects/VA/va.gov-cms/docroot/vendor/vagov/app/node_modules/libxmljs
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/jon/Projects/VA/va.gov-cms/docroot/vendor/nodejs/nodejs/bin/node /home/jon/Projects/VA/va.gov-cms/docroot/vendor/vagov/app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --loglevel=http --module=/home/jon/Projects/VA/va.gov-cms/docroot/vendor/vagov/app/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/home/jon/Projects/VA/va.gov-cms/docroot/vendor/vagov/app/node_modules/libxmljs/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/jon/Projects/VA/va.gov-cms/docroot/vendor/vagov/app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Linux 5.0.17-200.fc29.x86_64
node-pre-gyp ERR! command "/home/jon/Projects/VA/va.gov-cms/docroot/vendor/nodejs/nodejs/bin/node" "/home/jon/Projects/VA/va.gov-cms/docroot/vendor/vagov/app/node_modules/libxmljs/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd /home/jon/Projects/VA/va.gov-cms/docroot/vendor/vagov/app/node_modules/libxmljs
node-pre-gyp ERR! node -v v12.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/home/jon/Projects/VA/va.gov-cms/docroot/vendor/nodejs/nodejs/bin/node /home/jon/Projects/VA/va.gov-cms/docroot/vendor/vagov/app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --loglevel=http --module=/home/jon/Projects/VA/va.gov-cms/docroot/vendor/vagov/app/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/home/jon/Projects/VA/va.gov-cms/docroot/vendor/vagov/app/node_modules/libxmljs/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Script cd app && yarn install handling the post-install-cmd event returned with error code 1


```

**Comment by jonpugh** [comment]
LOL wut? 
> info fsevents@1.2.9: The platform "linux" is incompatible with this module.

**Comment by jonpugh** [comment]
Ok, @jbalboni mentioned node version, of COURSE that's a problem!

Pinned node and yarn to the same versions used in `packages.json`...

# Errors

```
> cd app && yarn install
yarn install v1.16.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @department-of-veterans-affairs/formation-react@4.6.3" has incorrect peer dependency "@department-of-veterans-affairs/formation@^5.4.0".
[4/4] Building fresh packages...
$ npm rebuild node-sass
/home/jon/Projects/VA/va.gov-cms/docroot/vendor/nodejs/nodejs/lib/node_modules/npm/node_modules/npmlog/log.js:57
log.progressEnabled = log.gauge.isEnabled()
                                ^

TypeError: log.gauge.isEnabled is not a function
    at Object.<anonymous> (/home/jon/Projects/VA/va.gov-cms/docroot/vendor/nodejs/nodejs/lib/node_modules/npm/node_modules/npmlog/log.js:57:33)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /home/jon/Projects/VA/va.gov-cms/docroot/vendor/nodejs/nodejs/lib/node_modules/npm/bin/npm-cli.js:22:13
    at Object.<anonymous> (/home/jon/Projects/VA/va.gov-cms/docroot/vendor/nodejs/nodejs/lib/node_modules/npm/bin/npm-cli.js:153:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

**Comment by jonpugh** [comment]
verify

**Comment by jonpugh** [comment]
build

**Comment by jonpugh** [comment]
Ok, there is now a jenkins job that will run `tests.static.yml` before any server setup, so it will happen very fast.

http://jenkins.cms.va.gov/job/Static%20Tests/

I can't get it to start for this PR.

Maybe I'm just tired. @mouncifb @ElijahLynn ?

**Comment by jonpugh** [comment]
This works up until `yarn watch`.

According to the error messages and the documentation, these additional repos are required.

I'm trying to add these repositories using NPM/Yarn since they are dependencies of the WEB project. We could add these on our end, but if the WEB project requires them, the WEB provisioning tools should include those repos automatically.

I added a "install" hook to yarn scripts to clone all of these repos to the WEB repo: https://github.com/department-of-veterans-affairs/vets-website/pull/10270

Looking for feedback on this one.

**Comment by jonpugh** [comment]
rebuild

**Comment by jonpugh** [comment]
build

**Comment by jonpugh** [comment]
YES!

**Comment by jonpugh** [comment]
timestamp: 
git push

**Comment by jonpugh** [comment]
New build started!

**Comment by jonpugh** [comment]
rebuild

**Comment by jonpugh** [comment]
#9 pending

**Comment by jonpugh** [comment]
rebuild!

New jobs take up to a minute to queue, but once it starts, static tests pass or fail in seconds!

**Comment by jonpugh** [comment]
Composer install is now being tested immediately! 

Failures go to github error comments and commit status API.

rebuild!

**Comment by jonpugh** [comment]
It works!!

To test:

```bash
git clone https://github.com/department-of-veterans-affairs/va.gov-cms --branch VAGOV-2937-unity
cd va.gov-cms 
composer install
composer va:web:watch  # Wrapper for `yarn watch`
```

If you want to call `yarn` or `npm` directly, you can use the new `composer set-path` command:

```bash
$ composer set-path
> # Run the command output below to set your current terminal PATH variable.
> # This will allow you to run any command in the ./bin directory without a path.
> echo "export PATH=${PATH}"
export PATH=/home/jon/Projects/VA/va.gov-cms/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
```
once you copy and paste the `export` line, you can call `yarn` or `node` or `npm` and it will use the version installed via the composer.json file.

Screenshot from 2019-06-19 10-25-57

**Comment by jonpugh** [comment]
build

**Comment by jonpugh** [comment]
build

**Comment by jonpugh** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Comment by jonpugh** [comment]
I was trying last night and this morning to set the path so that `vagov/web` package gets installed directly in `/app` or `/web`.

It's possible to do this with `composer/installers`: https://github.com/composer/installers#custom-install-paths

But, we maintain a fake repository in our `/composer.json` for vagov/web, and it doesn't seem to care what I do, it always goes to `/vendor/`.

**Comment by ElijahLynn** [comment]
Superseded by #493.

**Pull request closed without merging**
