### PR TITLE
VAGOV-4972: Add field_teaser_text to landing page content type

### PR DESCRIPTION
**Pull request by jonbot**
*Description*
Adds the teaser text field that is needed for the full hub list on the home page. 

- Adds a teaser text field to the hub landing page content type. 
- Configures the field and its form display. 
- Includes a first pass at help text.

### CODE REVIEW

**Comment by andyhawks** [comment]
rebuild

**Comment by ElijahLynn** [comment]
rebuild

**Comment by ElijahLynn** [comment]
failed due to container failing to build.

**Comment by ElijahLynn** [comment]
rebuild

**Pull request merged**
