### PR TITLE
VACMS-5250: Update section labels.

### PR DESCRIPTION
**Pull request by kevwalsh**
## Description

See #5250.

Needs user guide update and announcement from #5251 before merging. 

This replaces #5151, which was used as a live prototype for testing.

## Testing done

Manual, behat.

## Screenshots
Content___VA_gov_CMS

Edit_CMS_Help_Page__Test_Data__Molestiae_qui_veritatis_ex_in____VA_gov_CMS

## QA steps

As admin 

1. Go to https://pr5285-r4jbzvazezkcgutivtgga5l3wjjgi2ek.ci.cms.va.gov/admin/content and see Section labels
2. Go to https://pr5285-r4jbzvazezkcgutivtgga5l3wjjgi2ek.ci.cms.va.gov/node/add, open a smattering of forms, and check out the Section settings. They should all match the above screenshot. 

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [x] Yes, but it hasn't yet been written 
  - [x] Don't merge yet -- @rachel-kauff is doing this in #5251 
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by swirtSJW — DISMISSED** [review]
Updates look good to me.

**Comment by rachel-kauff** [comment]
😆 smattering.

**Review by rachel-kauff — APPROVED** [review]
Yay! Figured it out.

**Review by swirtSJW — APPROVED** [review]

**Comment by swirtSJW** [comment]
I just pushed up a test fix.

image

**Pull request merged**
