### PR TITLE
VACMS-6057: Enable recurring date functionality.

### LINKED ISSUE #6057: Editor experience for repeating / recurring events
## User Story or Problem Statement

1. As an event editor, i should only be able to create a recurring event based on a simple pattern (like once a week, or 1st Tuesday of the month, or every M/W/F) 

2. As an event editor, i should only be able to create a single event date, or a single event date repeating pattern. I should not be able to create two "custom" dates, or two custom repeating patterns.

 - Smart date recurring module requires the date field to be multivalue. By default, this adds a "Add another item" button that is confusing. 

<details><summary>Screenshots</summary>

### New config for field_datetime_range_timezone	

From https://master-dzqiprnzpsoj5ifjekygsan9jad6kjdo.demo.cms.va.gov/admin/structure/types/manage/event/fields/node.event.field_datetime_range_timezone

Date_and_time_settings_for_Event___VA_gov_CMS

### Confusing multivalue UX

Create_Event___VA_gov_CMS

### Desired permissions

Permissions_filtered_by_modules___VA_gov_CMS

</details>

## Acceptance Criteria
- [x] Recurring events are enabled set to max out at 12 months (setting on field)
- [x] Field help text is removed (for now, at least)
- [x] Enabled time zones match the time zones currently seen at /node/add/event, _plus_ Europe/Berlin
- [x] Permissions are set so that content content editors/reviewers/publishers and content admins are able to use the module 
- [x] "Add another item" is hidden on the event form when smart_date_recur is enabled
- [x] If #6055 has shown that we can change cardinality of field_datetime_range_timezone  without impacting existing graphql or FE templates, this can potentially be merged
- [ ] If #6055 has shown that changing cardinality of field_datetime_range_timezone will break the content API, then just create a PR assuming that's been done elsewhere and mark as DO NOT MERGE. 

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [x] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

### PR DESCRIPTION
**Pull request by ethanteague**
## Description

Closes #6057

## Merge is blocked by 

- [ ] Editorial experience is ready to go ( and )
- [ ] FE is ready to receive repeating events (va.gov-team issue forthcoming)
- [ ] CMS announcement  for editors is written and ready to send (#6066)
- [ ] Knowledge base article(s) updated

## Testing done
Visual, phpunit, behat

## QA steps
 - As jacob.dillon@va.gov, test the following scenarios on the `node/add/event` path:
    - Recurring events are enabled set to max out at 12 months (setting on field)
    - Field help text is removed (for now, at least)
    - Enabled time zones match the time zones currently seen at /node/add/event, plus Europe/Berlin
    - Permissions are set so that content content editors/reviewers/publishers and content admins are able to use the module
    - "Add another item" is hidden on the event form when smart_date_recur is enabled

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [x] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by kevwalsh** [comment]
Awesome. 

We can't merge this as is, until:
- [ ] Editorial experience is ready to go (issue forthcoming)
- [ ] FE is ready to receive repeating events (va.gov-team issue forthcoming)
- [ ] Release note for editors is written and ready to send (issue forthcoming)
- [ ] Knowledge base article(s) updated

I've added this to the PR up top and added the Do not merge label. 

I can see us merging after removing the permissions to actually use it, but that needs some thinking.

**Comment by ethanteague** [comment]
> Awesome.
> 
> We can't merge this as is, until:
> 
> * [ ]  Editorial experience is ready to go (issue forthcoming)
> * [ ]  FE is ready to receive repeating events (va.gov-team issue forthcoming)
> * [ ]  Release note for editors is written and ready to send (issue forthcoming)
> * [ ]  Knowledge base article(s) updated
> 
> I've added this to the PR up top and added the Do not merge label.
> 
> I can see us merging after removing the permissions to actually use it, but that needs some thinking.

Thanks brother.

**Comment by indytechcook** [comment]
There is a new version of smart_date: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/6203

**Comment by kevwalsh** [comment]
@ethanteague can you fix the conflicts on this and get it a tugboat environment up again?

**Comment by ethanteague** [comment]
Updated / rebased on origin/main @kevwalsh @rachel-kauff @EWashb

**Comment by swirtSJW** [comment]
Closed as it is replaced by https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7307

**Pull request closed without merging**
