### PR TITLE
VACMS-10774: VACMS-10904: Adds help text with kb link on paths fields; changes 'add another item' button text

### LINKED ISSUE #10774: CMS: Add KB link to Path field description on Full-width Alert & Promo Banners
## Description
The Path field exists on both
* Full Width Alerts (https://prod.cms.va.gov/node/add/banner) 
* Promo Banners (https://prod.cms.va.gov/node/add/promo_banner)

Governance rules exist already on [the full-width-alert KB article](https://prod.cms.va.gov/help/homepage-alerts-and-promo-banners/full-width-alerts), under For content admins > Path field.

We need to update the CMS UI to add the KB link to the Path field on both content types.

## Acceptance Criteria

- [ ] Description is added to Path field on Full width alert and Promo banner content types
- [ ] Promo banner URL path = https://prod.cms.va.gov/help/full-width-alert-and-promo-banners/promo-banners
- [ ] Full width alert URL path = https://prod.cms.va.gov/help/homepage-alerts-and-promo-banners/full-width-alerts

## Additional context
* https://dsva.slack.com/archives/CDHBKAL9W/p1663706702436899?thread_ts=1663705417.634809&cid=CDHBKAL9W
* https://dsva.slack.com/archives/C52CL1PKQ/p1663732288255029

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### LINKED ISSUE #10904: Path field: Update "Add another item" button text to "Add another Path"
The Path field exists on both 
1. Full Width Alerts (https://prod.cms.va.gov/node/add/banner)
2. Promo Banners (https://prod.cms.va.gov/node/add/promo_banner)

In both cases, the button to add more says "Add another item." Update that text to say "Add another path."

**Before:** 
Screen Shot 2022-09-26 at 1 25 05 PM

**After:**
Screen Shot 2022-09-26 at 1 25 46 PM

## Acceptance criteria
- [ ] Path add more button on https://prod.cms.va.gov/node/add/banner says Add another path
- [ ] Path add more button on https://prod.cms.va.gov/node/add/promo_banner says Add another path

### PR DESCRIPTION
**Pull request by dsasser**
## Description

Closes #10774
Closes #10904

## Screenshots
Screen Shot 2022-12-07 at 11 35 45 AM

## QA steps

As a content_admin
1. Visit the add 'Promo Banners' node creation link: [/node/add/promo_banner](/node/add/promo_banner)
   - [x] (For #10774) Validate that the 'Paths' field help text is: `Add path(s) for pages that should display this content. All paths must begin with / and may use wildcards (*) or exclusions (!). (<a href="/help/homepage-alerts-and-promo-banners/promo-banners" target=“_blank”>See further guidelines</a>)`
   - [x] (For #10904) Validate the button displays 'Add another path' instead of 'Add another item'.
2. Visit the add 'Full Width Alert' node creation link: [/node/add/banner](/node/add/banner)
   - [x] (For #10774) Validate that the 'Paths' field help text is: `Add path(s) for pages that should display this content. All paths must begin with / and may use wildcards (*) or exclusions (!). (<a href="/help/homepage-alerts-and-promo-banners/promo-banners" target=“_blank”>See further guidelines</a>)`
   - [x] (For #10904) Validate the button displays 'Add another path' instead of 'Add another item'.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### CODE REVIEW

**Comment by jilladams** [comment]
The links to KBs from node forms look good. 

When you land on the KB articles, I do get an error at page top: 
* `User error: "attributes" is an invalid render array key in Drupal\Core\Render\Element::children() (line 98 of core/lib/Drupal/Core/Render/Element.php).`

**Comment by dsasser** [comment]
> The links to KBs from node forms look good.
> 
> When you land on the KB articles, I do get an error at page top:
> 
> * `User error: "attributes" is an invalid render array key in Drupal\Core\Render\Element::children() (line 98 of core/lib/Drupal/Core/Render/Element.php).`

That error was present already, unfortunately, and there are two issues tracking it: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11579
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11049

**Comment by jilladams** [comment]
(composer.lock file conflict)

**Review by swirtSJW — COMMENTED** [review]
I have some concerns about the dependency on autoservices.   I am a bit uneasy about the potential rewiring this is doing Drupal's use of symfony.

It seems like a fair amount of  risk, just so the author of change_labels can save himself the trouble of wrting a services.yml for his three event subscribers.
Lets discuss soon.

**Comment by swirtSJW** [comment]
Related slack discussion https://dsva.slack.com/archives/C52CL1PKQ/p1670440937230289

**Comment by jilladams** [comment]
https://pr11856-smmwwy1tm4p6bgz4bgp3fy9pi6ykiz15.ci.cms.va.gov/node/add/promo_banner
Screen Shot 2022-12-08 at 2 33 24 PM
links to https://pr11856-smmwwy1tm4p6bgz4bgp3fy9pi6ykiz15.ci.cms.va.gov/help/homepage-alerts-and-promo-banners/promo-banners

https://pr11856-smmwwy1tm4p6bgz4bgp3fy9pi6ykiz15.ci.cms.va.gov/node/add/banner
Screen Shot 2022-12-08 at 2 34 13 PM
links to https://pr11856-smmwwy1tm4p6bgz4bgp3fy9pi6ykiz15.ci.cms.va.gov/help/homepage-alerts-and-promo-banners/full-width-alerts

looks good!

**Review by jilladams — APPROVED** [review]

**Comment by swirtSJW** [comment]
Tests stalled out because tugboat fell down.  
image

I just triggered a rebuild.

**Comment by swirtSJW** [comment]
Hmm failed again to build.
```
   Install of va-gov/content-build failed

In Git.php line 471:
                                                                               
  Failed to clone https://github.com/department-of-veterans-affairs/content-b  
  uild.git via https, ssh protocols, aborting.                                 
                                                                               
  - https://github.com/department-of-veterans-affairs/content-build.git        
    Cloning into '/var/lib/tugboat/docroot/vendor/va-gov/content-build'...     
    done.                                                                      
    warning: failed to stat /var/lib/tugboat/docroot/vendor/va-gov/content-bu  
  ild/.git/objects/pack/tmp_pack_TuqUk8: No such file or directory             
    fatal: unable to rename temporary pack file: No such file or directory     
    fatal: cannot repack to clean up                                           
                                                                               
  - git@github.com:department-of-veterans-affairs/content-build.git            
    Cloning into '/var/lib/tugboat/docroot/vendor/va-gov/content-build'...     
    done.                                                                      
    fatal: remote composer already exists.     
```                                
                                                  
It might be due to the mirror being old.     I am trying one more time.

**Comment by swirtSJW** [comment]
Build is proceeeding now.   I confirmed the commit pinning is working as intended.
image

**Review by swirtSJW — APPROVED** [review]
QA pass all  checks out good and code as well.  Well done.

## Note to our future selves:
If you are here in our future it is because you are wondering why we pinned to a forked copy of the change_labels module.  
[Drupal Issue](https://www.drupal.org/project/change_labels/issues/3326097)
[fork](https://git.drupalcode.org/issue/change_labels-3326097/-/compare/1.0.x...3326097-remove-dependency-on-drupal-autoservices) 
[VA Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1670440937230289)

### FAQ's

**Why didn't we custom code it?**  The change_labels module really has a great implementation  that we would have just been copying into our local codebase in order to remove the questionable / risky use of the autoservices module which re-wires how Drupal's implementation of symfony works.

**Why didn't we use https://www.drupal.org/project/custom_add_another** It was not well maintained and had a lot of outstanding issues that had not been resolved including rector updates.  It had more baggage then we needed.

**Why didn't we just patch the module to remove the dependencies and such** Removing composer dependencies in a patch would only happen after composer had already run with the existing dependencies.  Chicken and egg problem.

**When should this atypical pinning to a commit be undone?** When  change_labels removes its dependency on the goofy autoservices module, or autoservices become a core approach.

**Why did we pin to a specific commit hash of that fork?**  Mainly security reasons so that our use of that fork did not float with whatever the most recent commit to that fork is.   This way we lock in exactly the code we are expecting.

**Pull request merged**
