### PR TITLE
VACMS-16732: Removes border color related to text-counter

### PR DESCRIPTION
**Pull request by omahane**
## Description

Relates to #16732

## Testing done
Manually

_Note on implementation: I added the body class to the CSS selectors to increase the specificity of the definitions, so that the styles set by the module itself would not override them._

### Before running out of characters
Screenshot 2024-03-08 at 4 17 12 PM

### After running out of characters
Screenshot 2024-03-08 at 4 17 29 PM

### Set up test user
- [x] Log in as an admin and set QA Content Publisher to the following:
  - [x] Roles:
    - [x] Content publisher
    - [x] Content creator - VAMC
    - [x] Content creator - VBA
    - [x] Content creation - Vet Center
  - [x] Sections:
    - [x] VA Boston health care
    - [x] VA Illiana health care

### Edit a Story as an Editor
- [x] Login as QA Content Publisher
- [x] Edit a [story](https://pr17449-thiq7crhhoxyfrukcqryypxntgvtzlyb.ci.cms.va.gov/node/66321/edit)
- [x] Add characters to the **First sentence (lede)** field
- [x] Confirm that no border changes occur during editing
- [x] Confirm that the text changes happen when the remaining characters are < 0.
- [x] Confirm the color (dark red) and style (bold) are desired
- [x] Edit **Caption** similarly
- [x] Confirm similar results

### Edit a News Release as an Editor
- [x] Edit a [news release](https://pr17449-thiq7crhhoxyfrukcqryypxntgvtzlyb.ci.cms.va.gov/node/66364/edit)
- [x] Edit the **Press Release Title** similarly, adding characters until they exceed allowed characters
- [x] Confirm that the behavior is desired

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.
- [ ] If there are field changes, front end output has been thoroughly checked.

### Select Team for PR review

- [x] `CMS Team`
- [ ] `Public websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### CODE REVIEW

**Comment by Becapa** [comment]
I'm not sure if this is in the scope of this ticket or not, but on the News Release portion of the QA, the `Characters Used:` behaves differently than the `Characters Remaining:`. For instance, the `Characters Used` number turns yellow(ish) when the count is 145 and turns a different shade of red (not the dark red) than everything else when the count gets above 150, whereas the `Characters Remaining` stays dark gray at 5 remaining and turns to the expected dark red at < 0.

**Comment by omahane** [comment]
> I'm not sure if this is in the scope of this ticket or not, but on the News Release portion of the QA, the `Characters Used:` behaves differently than the `Characters Remaining:`. For instance, the `Characters Used` number turns yellow(ish) when the count is 145 and turns a different shade of red (not the dark red) than everything else when the count gets above 150, whereas the `Characters Remaining` stays dark gray at 5 remaining and turns to the expected dark red at < 0.

That's a great observation, but it *is* outside the scope of the ACs on this issue, and is directly related to how we are not communicating the textfield counter consistently across widgets.

**Review by Becapa — DISMISSED** [review]

**Comment by Becapa** [comment]
> > I'm not sure if this is in the scope of this ticket or not, but on the News Release portion of the QA, the `Characters Used:` behaves differently than the `Characters Remaining:`. For instance, the `Characters Used` number turns yellow(ish) when the count is 145 and turns a different shade of red (not the dark red) than everything else when the count gets above 150, whereas the `Characters Remaining` stays dark gray at 5 remaining and turns to the expected dark red at < 0.
> 
> That's a great observation, but it **is** outside the scope of the ACs on this issue, and is directly related to how we are not communicating the textfield counter consistently across widgets.

In that case, this looks good to me! 😁

**Comment by davidmpickett** [comment]
> I'm not sure if this is in the scope of this ticket or not, but on the News Release portion of the QA, the `Characters Used:` behaves differently than the `Characters Remaining:`. For instance, the `Characters Used` number turns yellow(ish) when the count is 145 and turns a different shade of red (not the dark red) than everything else when the count gets above 150, whereas the `Characters Remaining` stays dark gray at 5 remaining and turns to the expected dark red at < 0.

Spun that off into a new ticket https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17477

**Review by davidmpickett — DISMISSED** [review]
Looks good!

**Review by laflannery — DISMISSED** [review]

**Review by srancour — APPROVED** [review]
From an accessibility perspective, I’m not seeing anything that worries me and I’m good with these changes. I will let @MDomngz chime in from the UX perspective.

**Comment by thejordanwood** [comment]
This looks good to me!

**Review by thejordanwood — DISMISSED** [review]

**Comment by MDomngz** [comment]
Approved by CMS UX/A11y - Steve and I both are signing off

I'm signing off on this ticket as the UX Designer of the CMS/Drupal team based on the previous designer's participation in this ticket. Blake worked with Jordan on a final solution that took into account the USWDS. I will meet with Jordan to get a better understanding of their decisions. My main concern is tracking user data for this release to understand if this is a successful change or if it will require additional discovery/sprint work.

**Review by MDomngz — DISMISSED** [review]

**Comment by omahane** [comment]
It appears that `textfield-counter-element.error` is a valid select when this has been submitted. I can address [Steve's comment](https://dsva.slack.com/archives/CT4GZBM8F/p1710258989552939?thread_ts=1710184228.463289&cid=CT4GZBM8F) using this.

**Comment by srancour** [comment]
Another issue that now exists: When the user enters and then exits the input box with the error state like previous, the input no longer is marked in error even with no changes. This can be become very confusing for any user, but especially screen reader users as the aria-invalid is being set to false on leaving the field. See video for interaction of leaving the field when the error is still exists and note the aria-invalid changing from true to false.

https://github.com/department-of-veterans-affairs/va.gov-cms/assets/18683379/2c183374-5a4c-46e8-bd7c-84e8d58f3628

**Comment by omahane** [comment]
> Another issue that now exists: When the user enters and then exits the input box with the error state like previous, the input no longer is marked in error even with no changes. This can be become very confusing for any user, but especially screen reader users as the aria-invalid is being set to false on leaving the field. See video for interaction of leaving the field when the error still exists and note the aria-invalid changing from true to false.
> 

Got it. I found an error class that persists during editing:

Screenshot 2024-03-14 at 5 14 59 PM

**Comment by srancour** [comment]
@omahane Checked the ticket again and the visual mark is staying, but the aria-invalid is still changing to false in the code when you set focus and take away focus.

**Review by srancour — APPROVED** [review]
@omahane When I started reviewing this ticket's build to prod, prod did not have the issue of the aria-invalid state changing. That has changed and that issue is now in prod as well. Because of the issue not being in prod and it being present within these builds it looked like, to me, that the changes here were causing a downstream effect that caused the change of the aria-invalid state, thus would be in scope for this ticket to fix. I will retract what I said about needing to fix the aria-invalid issue for this ticket and this can move forward as is. 

I will also create a ticket for the aria-invalid issue for the CMS team to look into what happened and has caused this issue so we can remediate the issue so it won't be lost.

**Comment by omahane** [comment]
> I will retract what I said about needing to fix the aria-invalid issue for this ticket and this can move forward as is.
> 
> I will also create a ticket for the aria-invalid issue for the CMS team to look into what happened and has caused this issue so we can remediate the issue so it won't be lost.

@srancour OK, that sounds good. I couldn't figure out what I might have done by changing CSS to trip the aria error.

**Pull request merged**
