### PR TITLE
VACMS-3036: add LC permissions + tests for content editor/publisher/reviewer roles

### PR DESCRIPTION
**Pull request by acrollet**
## Description

See #3036  

## Testing done

* Logged in as each role and confirmed that the appropriate actions were available 
* Updated and ran phpunit permissions test

## QA steps

As a user with the content editor role:
- [x] Can create new LC content
- [x] Can edit LC nodes
- [x] Can view LC node revisions

As a user with the content reviewer role:
- [x] Can edit LC nodes
- [x] Can view LC node revisions

As a user with the content publisher role:
- [x] Can edit LC nodes
- [x] Can revert LC node revisions

Then validate Acceptance Criteria from issue
- [x] permissions are updated appropriately
- [x] tests are updated appropriately

## Definition of Done
- [ ] Product release are written (or in progress), if required.
- [ ] Documentation has been updated, if applicable.

### CODE REVIEW

**Review by swirtSJW — APPROVED** [review]

**Comment by swirtSJW** [comment]
This behat failure looks more like a flicker than an actual issue.  I am retriggering the test run on devshop

**Review by oksana-c — COMMENTED** [review]
@acrollet, one late addition to the ACs -  let's add same permissions for "Learning Center Detail Page" content type. thank you

**Comment by swirtSJW** [comment]
@oksana-c  ok  holding on this until new AC met.

**Comment by acrollet** [comment]
@oksana-c @swirtSJW done, ready for review.

**Review by swirtSJW — APPROVED** [review]

**Pull request merged**
