### PR TITLE
VAGOV-838 Xdebug Support for Sandboxes

### PR DESCRIPTION
**Pull request by ElijahLynn**
I had CLI debugging working but didn't write it down when I did. Will need to make another documentation PR when I get it working again.

### CODE REVIEW

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-61<br><br> [button_visit-site](http://pr-61.va.agile6.com)

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-61<br><br> [button_visit-site](http://pr-61.va.agile6.com)

**Comment by ElijahLynn** [comment]
rebuild

**Comment by ElijahLynn** [comment]
rebuild

**Comment by ElijahLynn** [comment]
build

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-61<br><br> [button_visit-site](http://pr-61.va.agile6.com)

**Pull request merged**
