### PR TITLE
Revert "VACMS-11506: updated outdated content report (#11899)"

### LINKED ISSUE #11924: Admin/content displays "Outdated Content" h1 and breadcrumb
## Describe the defect
[This PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11899) introduced a defect where our base view for admin/content got renamed to Outdated content.

image

Outdated Content title also appears in admin breadcrumbs:
image

Raised here https://dsva.slack.com/archives/CT4GZBM8F/p1670949597270179?thread_ts=1670947468.896719&cid=CT4GZBM8F
Discussed here https://dsva.slack.com/archives/CT4GZBM8F/p1670956124650709

## To Reproduce
1. Go to https://prod.cms.va.gov/admin/content
2. See "Outdated content" h1
3. Go to https://prod.cms.va.gov/admin/content/facilities/addresses 
4. See "Outdated content" in the breadcrumb

## AC / Expected behavior
- [ ] H1 and breadcrumb should only display "Outdated content" on the outdated content view. 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [X] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by swirtSJW**
This reverts commit 3da852ba4d14a5b0a1e70e8129a7c508170b1d84.

## Description

closes #11924

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As admin
1. visit https://pr11926-mwg37zdwtjkzkxqqgui6vlw5gpdc6jtz.ci.cms.va.gov/admin/content
   - [ ] Validate that the tile of the page is "Content"
2. Visit a sub level view like https://pr11926-mwg37zdwtjkzkxqqgui6vlw5gpdc6jtz.ci.cms.va.gov/admin/content/facilities
   - [ ] Validate that the breadcrumbs are "Home  > Administration  > **Content**"

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by ndouglas — APPROVED** [review]
Looks right.

**Review by edmund-dunn — APPROVED** [review]
looks good to me.

**Comment by swirtSJW** [comment]
Running the cypress test again.

**Comment by swirtSJW** [comment]
Cypress error is unrelated 
```
  1 failing

  1) Google Tag Manager dataLayer values are correct
       Google Tag Manager should be provided with an appropriate list of roles for the current user. (example #1):
     TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.

  > Cannot read property 'forEach' of undefined

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application
      at https://pr11926-mwg37zdwtjkzkxqqgui6vlw5gpdc6jtz.ci.cms.va.gov/modules/contrib/sitewide_alert/js/init.js?v=9.4.7:104:14
```

**Pull request merged**
