### PR TITLE
VACMS-1025 Uninstall health_check module.

### PR DESCRIPTION
**Pull request by swirtSJW**
## Description

See #1025 
## QA steps

1. As admin enable maintenance mode at /admin/config/development/maintenance
1. In an incognito window with your browser network inspector open, visit /health
1. Then validate Acceptance Criteria from issue
- [ ] The network response code is 200
- [ ] The page shows only a unix timestamp

## Definition of Done
- [-] Product release notes 
- [-] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

### CODE REVIEW

**Comment by ElijahLynn** [comment]
What is providing /health with this uninstalled?

**Comment by ElijahLynn** [comment]
> What is providing the `/health` route with this module uninstalled?
> Then we need a follow up story as an AC to remove from codebase, correct?

I see in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1025 now.

**Comment by swirtSJW** [comment]
> What is providing the `/health` route with this module uninstalled?
> Then we need a follow up story as an AC to remove from codebase, correct?

@ElijahLynn The other module, health_check_url provides that route.   
Yes we need another pr to remove this module from the codebase after this roles out.   It is specified in the issue.

**Comment by ElijahLynn** [comment]
Thank you! Verified it works 
image

**Pull request merged**
