### PR TITLE
VACMS-11149: Remove field_benefits from publication content type.

### LINKED ISSUE #11149: CMS Delete field_benefits from Publication content type
In #11147 we will add/have added a new field (field_lc_categories, a tax ref field) for defining outreach topics, designed to supplant the existing field_benefits select list. Therefore, after #11147 lands, we can delete the field_benefits field.

AC
- [ ] field_benefits is removed from the Publication content type.

### PR DESCRIPTION
**Pull request by dsasser**
## Description
Do not merge until [FE Make outreach material topic filters use field_lc_categories](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11153) lands in production.

Closes #11149

## QA steps
- [ ] field_benefits is not present on Publication content type (outreach_asset)

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?
Yes: [FE Make outreach material topic filters use field_lc_categories](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11153)

- [x] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by dsasser** [comment]
```
va/tests/content-build-gql — Failed
```
Note that this test will continue to fail until we merge in #11153, where the graphQL queries are updated to no longer pull from the removed field_benefits field.

**Comment by jilladams** [comment]
Front end changes have merged and are verified in prod. Updated branch from main / tests rerunning, and this is ready for code review.

**Review by swirtSJW — APPROVED** [review]
The FE counterpart was merged.  So it seems like this is ready for release.

**Comment by swirtSJW** [comment]
This ought to be clear for a go, but tests are not happy.

**Comment by jilladams** [comment]
> This ought to be clear for a go, but tests are not happy.

In [slack](https://dsva.slack.com/archives/C52CL1PKQ/p1668638244433889?thread_ts=1668638218.782569&cid=C52CL1PKQ), Daniel thought another rebase might do it. I've updated branch again to see. 

If that doesn't work, may need Drupal help to troubleshoot since this is a sprint goal. Will wait to chase that til we see if this works.

**Comment by chri5tia** [comment]
I can't find the details of the content build graphQL failure, but it would seem that these changes warrant a new GraphQL query to be used to revise FE components. I think that's why that test if failing.

**Comment by ElijahLynn** [comment]
```
Error with GetOutreachAssets. Scroll up for the GraphQL query that has an error:

[
  {
    "message": "Cannot query field \"fieldBenefits\" on type \"NodeOutreachAsset\". Did you mean \"fieldMetaTags\", \"fieldMedia\", or \"fieldDescription\"?",
    "category": "graphql",
    "locations": [
      {
        "line": 15,
        "column": 9
      }
    ]
  }
]
    at parallelQuery (/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/drupal/api.js:191:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async Object.getAllPagesViaIndividualGraphQlQueries (/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/drupal/api.js:245:7)
    at async getContentViaGraphQL (/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/drupal/metalsmith-drupal.js:249:19)
    at async loadDrupal (/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/drupal/metalsmith-drupal.js:294:23)
    at async Ware.<anonymous> (/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/drupal/metalsmith-drupal.js:349:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/ru
```

**Comment by swirtSJW** [comment]
I double checked the codebase 
https://github.com/department-of-veterans-affairs/content-build/search?q=fieldBenefits

THis field is still in the GraohQL queries

**Comment by swirtSJW** [comment]
This issue was blocked by https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11153 but the PR that closed that issue did not remove the field from the graphQL, it only removed it from the template.

**Comment by swirtSJW** [comment]
This was just merged https://github.com/department-of-veterans-affairs/content-build/pull/1366

The release should make its way to the CMS tomorrow and unblock this PR.

**Comment by swirtSJW** [comment]
This was merged, https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11661
so this should get passing tests now.  I am rebuilding it.

**Comment by swirtSJW** [comment]
image

**Pull request merged**
