### PR TITLE
VACMS-000: small adjustments for m1 macs / ddev 1.9.

### PR DESCRIPTION
**Pull request by timcosgrove**
## Description

* forces the web service to AMD architecture; this change only applies to m1 macs (or other arm machines)
* adds a network stanza to the memached service; this is required by ddev 1.9

### CODE REVIEW

**Review by indytechcook — APPROVED** [review]

**Comment by swirtSJW** [comment]
@timcosgrove @ndouglas  Should this be merged or closed?   I can't test it as I am not on a mac and don't have any testing steps to follow.

**Comment by ndouglas** [comment]
I'll test this now and see if it works cleanly (on an x86 Mac; I don't have an M1 Mac).

**Comment by ndouglas** [comment]
I get an error locally:

```
Network ddev-va-gov-cms_default  Created 
"specify container image platform" requires API version 1.41, but the Docker daemon API version is 1.40 
```

That's with a fully updated DDEV as of this morning and with the supported version of Docker for Mac installed (the latest 2.x release, I think).  I switched to Colima and the error goes away.  That said, I'm not sure if this is safe to merge for non-M1 Mac users.

**Comment by cweagans** [comment]
@timcosgrove can this be closed in light of https://github.com/department-of-veterans-affairs/va.gov-cms/pull/8590 ?

**Pull request closed without merging**
