### PR TITLE
VAGOV-3079 Fix sync-db, sync-files to use private bucket.

### PR DESCRIPTION
**Pull request by ElijahLynn**
Corresponds to https://github.com/department-of-veterans-affairs/va.gov-cms-devops/pull/58

### CODE REVIEW

**Comment by ElijahLynn** [comment]
rebuild

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by mbenziane** [comment]
Created an environment devops-vagovcms#pr-287<br><br> [button_visit-site](http://internal-devops-vagovcms-3373-1841818087.us-gov-west-1.elb.amazonaws.com)

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
rebuild

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
This is passing and ready for review and merge now. The reason that I ran a second build was to test colored output, which is also working!

**Comment by ElijahLynn** [comment]
rebuild

**Comment by ElijahLynn** [comment]
This is passing now with the test passing now @andyhawks and can be merged.

**Comment by ElijahLynn** [comment]
Commit 19eee87460d6d3b5f3035681ca244da23cbea08b is same as #288, which won't pass until we merge this.

**Pull request merged**
