### PR TITLE
VACMS-4919: Check for deprecated code. [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

See #4919.  Did the simplest possible thing, let's see if it works.

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [x] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by swirtSJW** [comment]
I like this Nate.   I think we could get around the current failures by assigning the variable and then adding an inline docblock just ahead of the variable.   (Indy taught me that trick).
example 
```
$node = $form_state->getFormObject()->getEntity();
```

would become

```
/** /Drupal/blah/blah/formstateinferface */
$form_object = $form_state->getFormObject();
$node = $form_object->getEntity();
```

That way phpstan will know that ->getEntity() exists.

**Comment by indytechcook** [comment]
@ndouglas is there a way for the results to show up in a github comment?  Does using review dog help here?

**Comment by ndouglas** [comment]
I think that should happen normally _provided_ that the annotation refers to a line of code (or file?) modified by the PR.  Let's find out together!

**Comment by ndouglas** [comment]
Well, guess not.  I'm sure that could be accomplished with tweaking, though.  I like the line annotations but it'd be good to have a summary comment posted as well.  Should discuss in our spike ( #5880 ).

**Pull request closed without merging**
