### PR TITLE
VACMS-18019: Updates Expirable Content which includes updated help text.

### PR DESCRIPTION
**Pull request by dsasser**
## Description

Relates to #18019

## Testing done
Module updates correctly and displays expected help text.

## Screenshots
Screenshot 2024-07-08 at 12 17 06 PM

## QA steps
As an administrator
1. Visit https://pr18350-ivgcaxjauw1z8tu58iclz9r7ir1m1v7e.ci.cms.va.gov/admin/structure/expirable_content_types/manage/node.banner and validate the text below:
   - [ ] Validate Entity type: Text = Select the entity type to add content that can expire
   - [ ]  Entity bundle: Text = Select the bundle of the entity type.
   - [ ] Last updated field: Text = Select the name of the field that will calculate when the entity was last updated.
   - [ ] Days before expiration: Text = Enter the number of days before the entity will expire. This will be the number of days after the entity was created or last updated.
   - [ ] Days to notify before expiration: Text = Enter the number of days to notify an editor before an entity expires.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.
- [ ] If there are field changes, front end output has been thoroughly checked.

### Select Team for PR review

- [ ] `CMS Team`
- [x] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### CODE REVIEW

**Comment by anantais** [comment]
@dsasser - Hey. I just wanted to check the status if this ticket. I am trying to update another module and this ticket is causing a conflict. Is there anything I can do to help with this?

**Comment by dsasser** [comment]
> @dsasser - Hey. I just wanted to check the status of this ticket. I am trying to update another module and this ticket is causing a conflict. Is there anything I can do to help with this?

@anantais that is odd since this PR is not yet merged. Perhaps you are experiencing a the composer [issue](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/18339) related to updating modules with .git subtree folders?

**Comment by anantais** [comment]
> issue

I am experiencing this on my local build. It is odd but it tells me I need to upgrade this module before I can make changes to the other module (which I need to apply a patch to). This was after I had pulled down the latest code. This is also a Dependabot PR that I am fixing so that may be an issue. I was hoping this was ready to go which would solve my problem. But I guess I will check with Tim. Thanks!

**Comment by dsasser** [comment]
This work was merged in previously. During development of the Aging Content tests, #18005, I encountered an error when trying to use Composer to update the Expirable Content module to Alpha 3. This led me to open a [ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18257) to resolve the issue I was experiencing. While that issue was being worked by Platform CMS, I pivoted to work on this PR, which also caused a version bump in Expirable Content to Alpha 4. At some point in the #18005 branch I performed a Composer update for Expirable Content, which pulled in the Alpha 4 version.

**Pull request closed without merging**
