### PR TITLE
Get Jenkins API Token from SSM

### PR DESCRIPTION
**Pull request by tskinn**
## Description

Use AWS SSM Parameter Store as the source of Jenkins API tokens. This will allow Jenkins to be deployed and loss of api tokens will be tolerable as we can create a new token and populate the parameter store with the current api token.

See _issueid_. 

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

## Definition of Done
- [ ] Documentation has been updated, if applicable.

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by indytechcook** [comment]
I created an issue so we can get this work done: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3955

**Comment by ndouglas** [comment]
Let's see if I screwed that up!

`master` had some substantial changes (a major refactoring of the frontend build process) since the branches diverged, so I tried to update this PR as best I could.  Think I mighta done the wrong thing with a file, lemme check.

**Comment by indytechcook** [comment]
might be easier to do this on a new PR?

**Comment by ndouglas** [comment]
it was just a duplicated test file, but since the branch name doesn't match standards I'll create a new PR just for cleanliness

**Comment by ndouglas** [comment]
Closed in favor of #4149 .

**Pull request closed without merging**
