### PR TITLE
FE Build - vets-website #573e830

### PR DESCRIPTION
**Pull request by ElijahLynn**
`lando composer require va-gov/web:dev-master#573e830`

### CODE REVIEW

**Comment by ElijahLynn** [comment]
@kfrz This is building now, it will be at http://pr775.ci.cms.va.gov and the FE web build of `573e830` will be at http://pr775.web.ci.cms.va.gov. It should be ready around 9:35PT. 

Then, to trigger new Preview builds, go to http://pr775.ci.cms.va.gov/admin/content/deploy.

**Comment by ElijahLynn** [comment]
Hrm, was there anything new with dependencies in https://github.com/department-of-veterans-affairs/vets-website/pull/11109?

> ERROR: Failed to download Chromium r594312! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
> { [Error: ENOENT: no such file or directory, open '/var/aegir/projects/cms/pr776/docroot/vendor/va-gov/web/node_modules/puppeteer/.local-chromium/download-linux-594312.zip']
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'open',
>   path:
>    '/var/aegir/projects/cms/pr776/docroot/vendor/va-gov/web/node_modules/puppeteer/.local-chromium/download-linux-594312.zip' }

**Comment by kfrz** [comment]
@ElijahLynn the PR does add a dependency `bin/vale` to the `Dockerfile`

**Comment by ElijahLynn** [comment]
Closing as we don't actually need this, as far as I know. If wrong, reopen and the ENVs will be recreated.

**Pull request closed without merging**
