### PR TITLE
VAGOV-6276 Image Style Warmer & disable `itok` DDoS prevention.

### PR DESCRIPTION
**Pull request by ElijahLynn**
VAGOV-6276

- Adds Image Style Warmer module
- Disables `itok` DDoS prevention. 
- Adds VBO View for Image Style Warmer operation to process existing images (initial PROD deployment step needed)

image

image

image

image-style-warmup-vbo

### CODE REVIEW

**Comment by kevwalsh** [comment]
@ElijahLynn looks like you need to add views.view.image_style_warmer_warmup_files view and view display(s) to Drupal spec tool, and then update tests/behat/drupal-spec-tool/views.feature . Let me know if you need help with that.

**Comment by ElijahLynn** [comment]
> @ElijahLynn looks like you need to add views.view.image_style_warmer_warmup_files view and view display(s) to Drupal spec tool, and then update tests/behat/drupal-spec-tool/views.feature . Let me know if you need help with that.

Thanks, yes, I need help with this part.

**Comment by ElijahLynn** [comment]
> Looks good. @ElijahLynn are you taking on the post deployment step?

Yes, let's coordinate that and I will do that on the deploy.

**Comment by ElijahLynn** [comment]
> > Looks good. @ElijahLynn are you taking on the post deployment step?
> 
> Yes, let's coordinate that and I will do that on the deploy.

Just did this today!
Peek 2020-02-14 15-52

**Pull request merged**
