### PR TITLE
VACMS-8135: Flag theming breaks some views config

### LINKED ISSUE #8135: Flag theming breaks some views config
## To Reproduce
1. Edit any view based on nodes (eg /admin/content)
2. Click the relationships tab
3. See that the table is out of whack
4. See that the `tr.flag` is the one that is breaking the layout

My guess is that this may be affecting other Config UI. 

## Expected behavior
View UI isn't 
## Screenshots 

Cursor_and_Top_task_pages__Content____VA_gov_CMS

 ## Additional context

Seems like we need to be a bit more specific about theming the flags on the /admin/content/flagged view
 

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by netboss**
- Updated _views.scss and added CSS specificity to override default "flag" CSS in Views.

## Description

closes #8135 

## Testing done
Passes all tests

## Screenshots
VACMS-8135-flag-row

VACMS-8135-flag-row-hover

VACMS-8135-flagged-content

## QA steps

As user administrator
1. Go to `/admin/structure/views/view/content` (or any node related view):
    - [x] In the right column under "Advanced" click the "Add" button next to "Relationships" and scroll down until you find the "Content flag" and visually inspect to verify and confirm that the table row ins't broken any more and that the hover and focus effects works the same as other table rows
2. Go to `/admin/content/flagged` (or in `/admin/content` click on the "Flagged" tab):
    - [x] Verify and confirm that the "flags" CSS styling isn't broken or odd looking

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by swirtSJW — CHANGES_REQUESTED** [review]
I don't think this is the right approach.   We have formatting that should only be impacting the flagged view, but it is not properly limited and is leaking out and affecting other places.  I think it would be better to prevent it leaking out, than to create special cases of overriding it at other places.   

Kev offered this in the ticket which pointed at a better solution 
"Seems like we need to be a bit more specific about theming the flags on the /admin/content/flagged view"

**Comment by netboss** [comment]
> I don't think this is the right approach. We have formatting that should only be impacting the flagged view, but it is not properly limited and is leaking out and affecting other places. I think it would be better to prevent it leaking out, than to create special cases of overriding it at other places.
> 
> Kev offered this in the ticket which pointed at a better solution "Seems like we need to be a bit more specific about theming the flags on the /admin/content/flagged view"

@swirtSJW 
This is ready for review when you have a chance.

**Comment by swirtSJW** [comment]
The code looks good.   Let's consider the QA steps to not only include checking the previously broken views admin, but it should also check the view that may have been changed.

**Comment by netboss** [comment]
> The code looks good. Let's consider the QA steps to not only include checking the previously broken views admin, but it should also check the view that may have been changed.

@swirtSJW 
Updated QA steps to include the "Flagged" content and added screen shot of it showing the "flags" correctly styled.

**Review by swirtSJW — APPROVED** [review]
QA tests out good.  Nice work.

**Pull request merged**
