### PR TITLE
VACMS-4728: Restore url perm.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #4728

## QA steps
@kevwalsh to review

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by acrollet — APPROVED** [review]
lgtm, approved pending tests - should we consider adding a behavioral test that verifies that content admins can actually create an alias?

**Review by kevwalsh — APPROVED** [review]
Thanks @ethanteague!

**Comment by kevwalsh** [comment]
This reverts a small part of work done in #4713 yesterday, so i'm going to go ahead in merge ahead of today's deployment.

**Comment by kevwalsh** [comment]
> lgtm, approved - should we consider adding a behavioral test that verifies that content admins can actually create an alias?

Just saw this after i hit merge. i'll create an issue for this.

**Pull request merged**
