### PR TITLE
VACMS 4133: Update help text for link-to-file-or-video

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

See #4133. 

## Testing done
Manual testing.  This is a straight config read/write, not handled or altered in code.

## Screenshots
Screen Shot 2021-02-03 at 10 39 24 AM
Screen Shot 2021-02-03 at 10 41 17 AM

## QA steps
As a user with permission to edit CMS Help Page content:
1. Add a main content block
2. Verify the ACs from #4133 
    - [ ] paragraph title, thumbnail and description are updated per spec above
    - [ ] linked text field description in the paragraph is updated per spec bove

Note that while there's an additional description removed from the config, the relevant instruction re: file types is still present in the UI.  That description was apparently cruft.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by rachel-kauff** [comment]
@ndouglas I adjusted the SVG file for the paragraphs browser to remove the outlines. 

Here it is:
- SVG: https://drive.google.com/file/d/194HCkZVziiAfxWzdo0Wn0RwF_F0AOJWC/view?usp=sharing
- PNG: https://drive.google.com/file/d/1IYseZiKBjDM3txhzqMndLcblM7Tt06is/view?usp=sharing

Last thing, could we adjust the label of the paragraph to match this:
Screen Shot 2021-02-04 at 8 46 33 AM

**Comment by ndouglas** [comment]
Screen Shot 2021-02-04 at 11 57 27 AM

the new hotness

**Comment by ndouglas** [comment]
I'm gonna add some tests to this after #4187 is merged since I couldn't figure out how to do it with Behat.

**Review by acrollet — APPROVED** [review]
Reviewed on the PR env, meets ACs, config/file changes only.

**Pull request merged**
