### PR TITLE
VACMS-6950: Remove "Page last built" field from 3 content types

### LINKED ISSUE #6950: Remove "Page last built" field from 3 content types
## Description

See [Slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1636552285074500)

> Many moons ago, when VA.gov CMS first went decoupled and we only had two content types, a “Page last built” field was added to the landing_page content type.  I don’t have much context or memory about the intent or functionality here. I don’t know how accurate it is. It looks editable, but shouldn’t. It looks somewhat accurate. This health care landing page (see screenshot) shows 4:02pm yesterday. The disability page shows 3:08pm yesterday.
> The user story roughly corresponds, i think, to the one that drove the little calendar icon checkbox in the toolbar menu … “As a CMS user i want to know when content on www.va.gov was last built, so that i can know if my last content management action was made it to www.va.gov or not”.
> i think it’s tech debt that should be removed, but just wanted to mention it for awareness. Can anyone think of a reason to keep this? I assume there’s some custom code somewhere that populates that field.

@ndouglas wrote

> I believe that timestamp might be added when the build request is dispatched from the backend.  I've done some work with the code, lemme call it up quick and take a gander at it.
> I wanted to double-check specifically that it worked this way, but the last-build time is updated immediately after the request is dispatched, if that does not throw an exception.
> So it's not remotely accurate and will show false times in many content build failures. (edited) 

<details><summary>Screenshot</summary>

Edit_Benefits_Hub_Landing_Page_VA_health_care___VA_gov_CMS

</details>

## Acceptance Criteria

- [x] `field_page_last_built` is removed from `page`, `landing_page`, and `support_service`
- [x] Any deprecated code that populates that field is removed

## Implementation Notes
Because the code exists in plugins that execute in different environments, it could be easy for _some_ code to be removed, for the PR to pass tests, but for this to cause problems in staging post-deploy tests or in production.

See:
- `Drupal\va_gov_build_trigger\Service\BuildTimeRecorderInterface`
- `Drupal\va_gov_build_trigger\Service\BuildTimeRecorder`
- `Drupal\va_gov_build_trigger\Plugin\VAGov\Environment\*`

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

### PR DESCRIPTION
**Pull request by netboss**
- Configuration changes: Removed the "field_page_last_built" field from the "page", "landing_page", and "support_service" content types. Deleted "field_page_last_built" field config files.
- Code changes: Scanned the "va_gov_build_trigger" custom module and removed references to the "field_page_last_built" field and its dependencies.
- Behat: Updated "content_model_benefits_hubs_content_type_fields.feature" behat test and removed all "field_page_last_built" field references.

- Blocked by content-build PR, waiting for merge and release to prod: https://github.com/department-of-veterans-affairs/content-build/pull/819

## Description

closes #6950

## Testing done

All build test passed.

## QA steps

As user administrator

1. Go to `/admin/structure/types/manage/page/fields`
    - [x] Verify and confirm that the `field_page_last_built` have been removed from the "page" content type
    - [x] Create a "page" node (`node/add/page`) and verify and confirm there are no errors and all worked as expected
    - [x] Edit an existing "page" node and verify and confirm there are no errors and all worked as expected
    - [x] Check and confirm there are no errors: Go to `/admin/reports/dblog` and take a look at the latest reports

2. Go to `/admin/structure/types/manage/landing_page/fields`
    - [x] Verify and confirm that the `field_page_last_built` have been removed from the "landing_page" content type
    - [x] Create a "landing_page" node (`node/add/landing_page`) and verify and confirm there are no errors and all worked as expected
    - [x] Edit an existing "landing_page" node and verify and confirm there are no errors and all worked as expected
    - [x] Check and confirm there are no errors: Go to `/admin/reports/dblog` and take a look at the latest reports

3. Go to `/admin/structure/types/manage/support_service/fields`
    - [x] Verify and confirm that the `field_page_last_built` have been removed from the "support_service" content type
    - [x] Create a "support_service" node (`node/add/support_service`) and verify and confirm there are no errors and all worked as expected
    - [x] Edit an existing "support_service" node and verify and confirm there are no errors and all worked as expected
    - [x] Check and confirm there are no errors: Go to `/admin/reports/dblog` and take a look at the latest reports

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [ ] `Sitewide CMS Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by swirtSJW — COMMENTED** [review]
Code changes look good, but the tests are not happy.

**Comment by netboss** [comment]
@swirtSJW 
I think the failing tests (`va/tests/behat — Failed`) in this build might be because in the spec tool the `field_page_last_built` field is still there, correct? Can (should) I remove that field from the spec tool?

**Review by swirtSJW — APPROVED** [review]
ALL tests out ok.  Thank you @netboss 
image

**Comment by swirtSJW** [comment]
image

**Pull request merged**
