### PR TITLE
VACMS 2899 Prevent Duplicate Reference

### PR DESCRIPTION
**Pull request by kaise-lafrai**
## Description

See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/2899

## QA steps

As and editor
1. Login
2. Create new content items for the following and confirm that the VA Benefits Hub section is required and will not allow duplicated references on save:
- [ ] Q&A, FAQ - multiple Q&As, Checklist, Step-by-Step, Media list - Images, Media list - Videos.

## Definition of Done
- [ ] Product release are written (or in progress), if required.
- [ ] Documentation has been updated, if applicable.

### CODE REVIEW

**Comment by kaise-lafrai** [comment]
Ready for QA

**Comment by swirtSJW** [comment]
This has a conflict that needs resolving.

**Comment by kaise-lafrai** [comment]
> This has a conflict that needs resolving.

Thanks, I’ll check it out.

**Comment by kaise-lafrai** [comment]
@swirtSJW Conflict has been resolved. Thank you

**Comment by indytechcook** [comment]
temporary closing to trigger a devshop delete.

**Comment by indytechcook** [comment]
Reopen to trigger devshop

**Comment by oksana-c** [comment]
@kaise-lafrai , devshop is not building this branch. Please open a new PR w/ this work. thank you

**Comment by kaise-lafrai** [comment]
Closing PR and creating a new PR.

**Pull request closed without merging**
