### PR TITLE
VACMS-8046: add patch to stop graphql throwing notices.

### PR DESCRIPTION
**Pull request by timcosgrove**
## Description

Relates to #8046. See that issue for tests, screenshots, etc.

### CODE REVIEW

**Comment by ndouglas** [comment]
```
-    // By default we assume a 'single' request. This is going to fail in the
-    // graphql processor due to a missing query string but at least provides
-    // the right format for the client to act upon.
```

**Review by ndouglas — DISMISSED** [review]
GraphQL's definitely much, much quieter, and tests passed.  LGTM.

Screen Shot 2022-02-16 at 7 09 22 AM

**Review by ndouglas — APPROVED** [review]

**Comment by amponce** [comment]
Do we know what the original intention of using _controller for single requests was supposed to be?

**Comment by ndouglas** [comment]
@amponce It seems pointless to me:

Use this request controller: https://github.com/drupal-graphql/graphql/blob/8.x-3.x/src/Routing/QueryRoutes.php#L57-L58

which handles single or multiple requests:
https://github.com/drupal-graphql/graphql/blob/8418bb7f6a869d0482eb45bfe22efa2f817d7efd/src/Controller/RequestController.php#L65

Maybe that line was vestigial from some prior implementation of the request controller.

**Pull request merged**
