### PR TITLE
VACMS-6771: update migration CSV files to include data for Lovell

### LINKED ISSUE #6771: Migrate facility health service data for Lovell
## Acceptance Criteria
- [ ] Lovell health service data is on prod

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

### PR DESCRIPTION
**Pull request by JayDarnell**
## Description

Closes #6771

## Testing done

Manual/Visual testing

## Screenshots

Migration CSVs for `regional_health_care_service_region_keyed_3` and `facility_health_are_service_final_6visns` updated with Lovell data:
Screen Shot 2021-11-10 at 5 57 28 PM

Before running the migrations with the new Lovell data:
Screen Shot 2021-11-10 at 6 44 24 PM

Migrate run results:
Screen Shot 2021-11-10 at 6 44 44 PM

Results of the completed migrations:
Screen Shot 2021-11-10 at 6 44 58 PM

## QA steps

As an admin user
- [ ] Visit `admin/content` and search for nodes with Lovell in the title (note the total number of items found)

As a user with terminal access
- [ ] Run `drush ms` and check the status for the `regional_health_care_service_region_keyed_3` and `facility_health_are_service_final_6visns` migrations (note the number of unprocessed items)
- [ ] Run `lando drush migrate:import regional_health_care_service_region_keyed_3` and note the number of items processed
- [ ] Run `lando drush migrate:import facility_health_care_service_final_6visns` and note the number of items processed

As an admin user
- [ ] Visit `admin/content` and search for nodes with Lovell in the title (note the total number of items found - should equal the sum of the previous count and the number of items processed by the two migrations above)

### Select Team for PR review

- [ ] `Platform CMS team`
- [x] `Sitewide CMS Team`

### CODE REVIEW

**Comment by JayDarnell** [comment]
If you have questions about the changes to `regional-health-care-service-keyed-3.csv` (because it shows some lines removed) you can check out this branch and run `git diff upstream/main..HEAD`. Most of the changes were made by LibreOffice automatically where the body cell contained a link (notice the change to quotes for encapsulating those cells). LibreOffice also tried to append a `;` to the end of every line but I removed those with `sed`. Lastly, after all was said and done I noticed 3-5 instances where the last cell was duplicated and removed those. I think this was also caused by improperly placed single quotes as the cells before these duplicates had two leading single quotes.

Examples below:
Screen Shot 2021-11-11 at 9 38 41 AM

**Comment by swirtSJW** [comment]
I am a bit concerned about those row changes @JayDarnell A change of row will cause a change of the migrate hash that gets created for each row.   This should just be an addition of rows, not touching of rows that have already been migrated.
image

**Comment by JayDarnell** [comment]
@swirtSJW I can fix this. I didn't consider changes to previous rows modifying those hashes. Updated PR coming shortly.

**Comment by JayDarnell** [comment]
@swirtSJW please give this another look as time allows.

**Review by swirtSJW — APPROVED** [review]
Nice work @JayDarnell   If you can, after make a mental note to run these after they land on prod tomorrow.

**Pull request merged**
