### PR TITLE
VACMS-10739: Cache preventing options from showing

### LINKED ISSUE #10739: CMS: Account blocked from selecting site section on VAMC Detail Pages unless cache is cleared
## Describe the defect
As a VA Drupal CMS Helpdesk admin, I am often editing and updating VAMC Detail Pages -- such as when broken links have been added to the site.

However, every couple of days or so, I am blocked from being able to edit rich text fields or save changes to VAMC Detail Pages because the “Related office or health care system” field is missing, as shown in the screenshots attached below.

When I try to fill in this field, the dropdown is completely grayed out, and I cannot proceed. This happens across multiple sections when attempting to edit existing VAMC Detail Pages, until I flush the site cache.

Flushing the site cache allows me to edit VAMC Detail Pages once more. 

**Slack thread:** https://dsva.slack.com/archives/CT4GZBM8F/p1662054884604009

## To Reproduce
1. Log into https://prod.cms.va.gov/ as stefanie.gray
2. Go through your usual workday until you suddenly and randomly cannot edit a VAMC Detail Page or any rich text fields contained within it, due to the lack of a site section shown in the above screenshots.
3. Observe the Datadog error message displayed in #cms-notifications on the DSVA Slack
4. Flush the site cache in order to be able to edit the VAMC Detail Page.

**Datadog error message displayed in #cms-notifications whenever this happens:** https://dsva.slack.com/archives/CJT90C0UT/p1663263300628259

## AC / Expected behavior
- [ ] I should be able to edit VAMC Detail Pages without running into this issue.

## Screenshots
**Grayed out 'section' field on VAMC Detail Page when this issue occurs:**

image

**Drupal error message:**
image

**Screenshot of Datadog error message displayed in #cms-notifications when this happens:** 
Screen Shot 2022-09-15 at 11 45 01 AM

 ## Additional context
See the following Slack threads (also linked above):
- https://dsva.slack.com/archives/CT4GZBM8F/p1662054884604009
- https://dsva.slack.com/archives/CJT90C0UT/p1663263300628259

## Desktop (please complete the following information if relevant, or delete)
 - OS: MacOS Big Sur 11.6.8
 - Browser: Chrome
 - Version: 104

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by omahane**
## Description

Closes #10739.

## Testing done
Manually.

## Screenshots
Screen Shot 2022-11-03 at 12 04 39 AM

## QA steps
Because the fix to this bug is to create more specific caches, the only way to test it (especially with memcache running), is to simply edit content types as the user. Even though we never determined a replicable set of steps to trigger the error, a tester should still no longer see the following on the VAMC Facility Detail Page:
Error

As stefanie.gray, edit a [Vet Center Facility Service](https://pr11412-50kwcdiqgmlwz7pgfz485okslscdo6mn.ci.cms.va.gov/node/41100/edit).
- [x] Validate that you can successfully edit the page.
- [x] _Note: there's no need to save it_

As stefanie.gray, start the process to create a new [Vet Center Service](https://pr11412-50kwcdiqgmlwz7pgfz485okslscdo6mn.ci.cms.va.gov/node/add/vet_center_facility_health_servi).
- [x] Validate that you select from the following dropdowns:
  - [x] Section
  - [x] Facility name
  - [x] Service 
- [x] _Note: there's no need to save it_

As stefanie.gray, edit a [VAMC Detail Page](https://pr11412-50kwcdiqgmlwz7pgfz485okslscdo6mn.ci.cms.va.gov/node/35189/edit).
- [x] Validate that the "Related Office or Health Care System" dropdown has "VA Milwaukee Health Care" selected
- [x] Try to edit a Rich Text paragraph under "Main Content"
- [x] Validate that it throws no error
- [x] _Note: there's no need to save it_

As stefanie.gray, start the process to create a new [VAMC Detail Page](https://pr11412-50kwcdiqgmlwz7pgfz485okslscdo6mn.ci.cms.va.gov/node/add/health_care_region_detail_page)
- [x] Select a "Section" of your choosing
- [x] Select a "Related Office or Health Care System" of your choosing
- [x] Validate that the "Related Office or Health Care System" field is populated
- [x] _Note: there's no need to save it_

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by JayDarnell — APPROVED** [review]
@omahane I'm really impressed by this. All the QA steps worked out great.

**Comment by swirtSJW** [comment]
QA steps were good at covering Stefanies use case.  It is important to consider the normal editors use case and make sure we did not break that in the process

- Log in as RyanStub_____ (vmac editor for both pittsburgh and lebannon)
-  [x] validate his choices are still appropriate on a [detail page](https://pr11412-50kwcdiqgmlwz7pgfz485okslscdo6mn.ci.cms.va.gov/node/5442/edit) 
image

- [x] edit and event listing page https://pr11412-50kwcdiqgmlwz7pgfz485okslscdo6mn.ci.cms.va.gov/node/3034/edit  validate that the choices are filtered to pittsburg and lebanon
image

- Login as MARK.PARKER@va.gov Vet center Temecula and Corona
- [-] visit  a vet center service https://pr11412-50kwcdiqgmlwz7pgfz485okslscdo6mn.ci.cms.va.gov/node/34210/edit   This is interesting.  field_office is not limited to just his choices. But it should be... it is one of the field targets.  HOWEVER.  I confirmed this is also the case on prod, so it is not a regression..but is a mystery in need of a ticket.  The risk is low however because most editors do not get to services directly, they go through he dashboard which is an inline entity form, not node edit.
image

**Comment by swirtSJW** [comment]
Another test not working, but also not working on prod
https://main-ersyymdhh8rrzxlevrh1xsmeyx7pzcpv.demo.cms.va.gov/node/27746/edit?
image
This could use a ticket

**Review by swirtSJW — APPROVED** [review]
This is working.  The places where it is not, are pre exisitng conditions on prod and are not in scope for this ticket.

Nice work on this @christianmburk

**Comment by swirtSJW** [comment]
image

**Pull request merged**
