### PR TITLE
VACMS-0000: Ignores complaints about module and core updates on status-error check.

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

The status-error check can fail because of components that are outdated on `main`.  This doesn't really help anything and instead just delays code approval and deployment, results in more resource use on Tugboat, etc.

This PR ignores certain classes of status error explicitly -- outdated core, outdated modules, and security updates -- on the assumption that these are already present on `main` and being handled in other PRs.

The punctuation in the change is intentional -- Drush reads the option as CSV, then transforms it into an array.  Apparently it's maddeningly particular about quotation marks.

```
root@php:/var/lib/tugboat# drush $DRUSH_ALIAS core-requirements --ignore=35 --format=list --severity=2
35
root@php:/var/lib/tugboat# drush $DRUSH_ALIAS core-requirements --ignore='35' --format=list --severity=2
35
root@php:/var/lib/tugboat# drush $DRUSH_ALIAS core-requirements --ignore='"35"' --format=list --severity=2
35
root@php:/var/lib/tugboat# drush $DRUSH_ALIAS core-requirements --ignore='"35","Module and theme update status"' --format=list --severity=2
35
root@php:/var/lib/tugboat# drush $DRUSH_ALIAS core-requirements --ignore='"update status"' --format=list --severity=2
35
root@php:/var/lib/tugboat# drush $DRUSH_ALIAS core-requirements --ignore='"update_core","update_contrib"' --format=list --severity=2
35
root@php:/var/lib/tugboat# drush $DRUSH_ALIAS core-requirements --ignore='"update_core","update_contrib","update status"' --format=list --severity=2
35
root@php:/var/lib/tugboat# drush $DRUSH_ALIAS core-requirements --ignore='"update_core","update_contrib","update status",35' --format=list --severity=2
35
root@php:/var/lib/tugboat# drush $DRUSH_ALIAS core-requirements --ignore='"update_core","update_contrib","update status","Module and theme update status",35' --format=list --severity=2
35
root@php:/var/lib/tugboat# drush $DRUSH_ALIAS core-requirements --ignore='update status' --format=list --severity=2
34
root@php:/var/lib/tugboat# drush $DRUSH_ALIAS core-requirements --ignore='update_core,update_contrib,"update status"' --format=list --severity=2

root@php:/var/lib/tugboat# 
```

## Testing done
Typing variations of the same infernal command repeatedly until one of them did the thing, and then putting my head down on my desk for a little bit.

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by acrollet** [comment]
> Typing variations of the same infernal command repeatedly until one of them did the thing, and then putting my head down on my desk for a little bit.

**Comment by ndouglas** [comment]
MFW: Screen Shot 2021-09-30 at 10 18 12 AM

**Comment by acrollet** [comment]
> MFW: Screen Shot 2021-09-30 at 10 18 12 AM

appropriate that Dory is a Drupal blue...

**Review by acrollet — APPROVED** [review]
This makes sense to me, I don't see any advantage in blocking PRs because an unrelated module is out of date.

**Comment by ndouglas** [comment]
yeah, I think we discussed the idea before in scrum a few weeks back when we had a similar issue.  I didn't know Drush had this handy-dandy mechanism for ignoring certain requirements.  Which, obviously, turned out to not be so handy-dandy after all, but whatever.

**Pull request merged**
