### PR TITLE
Update Frontend Build command for tugboat

### PR DESCRIPTION
**Pull request by indytechcook**
## Description

Update Frontend Build command for tugboat.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

---
This change is [Reviewable](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/3734)

### CODE REVIEW

**Comment by ElijahLynn** [comment]
There is one more change, missing semi-colon here: 
image

**Comment by ElijahLynn** [comment]
> There is one more change, missing semi-colon here:
> image

I do wonder why we are sending this to /static, and think we should probably send it to the new web* alias so relative URLs work. Because if I click on a URL I get this: 
image

**Comment by ElijahLynn** [comment]
> Error when running "composer va:web:build": [RuntimeException] The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly

image

**Comment by indytechcook** [comment]
This really wasn't ready for testing yet

**Comment by ElijahLynn** [comment]
> This really wasn't ready for testing yet

Oh, I thought you meant tests needed to finish running.

**Comment by indytechcook** [comment]
This was totally my terrible communication skills...

**Comment by indytechcook** [comment]
I finally got the build to work.  There were several permissions issues

**Pull request merged**
