### PR TITLE
VACMS-5436: Restrict field_media to field_administration value context on node forms.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #5436

## Testing done
Visual

## QA steps
- As a non administrator, go to `node/3731/edit` and click the `Add media` button - visually verify Section select in modal only contains values available to user from options selected in user profile workbench access sections.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by swirtSJW — CHANGES_REQUESTED** [review]
The code looks good.  
The title on this PR is confusing because it says it is specific to vetcenter, but 
a) it does not match the original issue.
b) it does not contain logic to limit to vetcenter

So the title... which becomes the commit message when this gets merged is misleading.

Also Is this supposed to operate on paragraphs that use media?  It seems like it would not.

**Comment by ethanteague** [comment]
> The code looks good.
> The title on this PR is confusing because it says it is specific to vetcenter, but
> a) it does not match the original issue.
> b) it does not contain logic to limit to vetcenter
> 
> So the title... which becomes the commit message when this gets merged is misleading.
> 
> Also Is this supposed to operate on paragraphs that use media? It seems like it would not.

It doesn't target paragraphs, @swirtSJW ......should it? Maybe more of a @kevwalsh q?

**Comment by swirtSJW** [comment]
> The logic I have in place targets all instances of field_media on node forms (even if the field is in a paragraph on a node form), so this should cover all use cases for said field, @swirtSJW.

I don't think that is true.   The JS would find it regardless of paragraph or not, but because of this bit
```
if (!empty($form['field_media']) &amp;&amp; !empty($form['field_administration'])) {    $form['#attached']['library'][] = 'va_gov_backend/limit_modal_services_to_user_sections';  }
```
The JS would not be attached unless there was media specifically on the node.

**Comment by ethanteague** [comment]
> > The logic I have in place targets all instances of field_media on node forms (even if the field is in a paragraph on a node form), so this should cover all use cases for said field, @swirtSJW.
> 
> I don't think that is true. The JS would find it regardless of paragraph or not, but because of this bit
> 
> ```
> if (!empty($form['field_media']) &amp;&amp; !empty($form['field_administration'])) {    $form['#attached']['library'][] = 'va_gov_backend/limit_modal_services_to_user_sections';  }
> ```
> 
> The JS would not be attached unless there was media specifically on the node.

Yeah, you are right - I was thinking field_media would be the thing that would act as the entity ref to a paragraph (got it twisted). That said......do we have media browsers in paragraphs? Sorry for what's probably a dumb q, just not aware of where (or if) this is an issue. Can you weigh in, @kevwalsh ?

**Pull request closed without merging**
