### PR TITLE
VACMS-4822 Update drupal entity_fetch_field module.

### PR DESCRIPTION
**Pull request by swirtSJW**
## Description

See _issueid_. 

## QA steps

As user _uid_ with _user_role_
1. Go to https://pr4984-tx33nf8f48ochoo6kad1e0jlqsashwbu.ci.cms.va.gov/graphql/explorer
2. enter the following in the query window
```
query {
  nodeById(id: "16141") {
    uuid,
    entityType,
    entityBundle,
    entityLabel,
    title,
    status,
    entityMetatags {
      key
      value
    }
    ... on NodeVamcSystemPoliciesPage {
      fieldCcBottomOfPageContent{
        targetType,
        targetId,
        targetField,
        fetchedBundle
        fetched,
      }
      fieldCcTopOfPageContent {
        targetType,
        targetId,
        targetField,
        fetchedBundle
        fetched,
      }
    }
    
  }
}
```

- [x] validate that you see fetch wyswig data
image

- [x] validate that you see  'processed' html that is proper html without line \r other invalid html.
image

1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### CODE REVIEW

**Review by mpelzsherman — APPROVED** [review]

**Comment by kaise-lafrai** [comment]
@swirtSJW QA steps pass.

**Review by kaise-lafrai — COMMENTED** [review]
QA Pass

**Comment by swirtSJW** [comment]
Looks like there is a mysql schema error that is not causing a functional issue, but is creating a field mismatch error that is failing tests and needs to be resolved with an update hook.

**Comment by swirtSJW** [comment]
@mpelzsherman  This PR is blocked while I work out a related sql error, however to unblock you , you could simply pull content from here  https://pr4984-tx33nf8f48ochoo6kad1e0jlqsashwbu.ci.cms.va.gov during your development.

cc: @kevwalsh @cmaeng

**Comment by swirtSJW** [comment]
image

**Pull request merged**
