### PR TITLE
VACMS-9520: Add system menu reference field to VAMC Systems.

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

See #9520.

This adds a new field group to the sidebar of VAMC System nodes.  That field group contains a single field, "System Menu", which is a reference to a menu config entity.  

- The field and field group are hidden for users without the `administrator` role. 
- The field is auto-populated with an appropriate menu entity, if one exists, when the system is edited.

Note that the field _value_ isn't set by this PR; I'll be doing that manually once this is merged and deployed.

## Testing done
Manual testing.

## Screenshots
Screen Shot 2022-07-06 at 11 43 17 AM
Screen Shot 2022-07-06 at 11 47 46 AM

## QA steps

**What needs to be checked to prove this works?**

- The field should be visible in the node edit form for users with the administrator role.
- The field should not be visible in the node edit form for users without the administrator role.
- The field should appear in a field group in the sidebar in the node edit form.
- The field should not appear outside of the node edit form.
- The field can be included in a JSON:API query.

**What needs to be checked to prove it didn't break any related things?**

Pretty innocuous change; it doesn't change any existing data.  The modifications to the node edit form are tightly scoped.

**What variations of circumstances (users, actions, values) need to be checked?**

As a user with the `administrator` role:
1. Before the node is updated...
   - [x] Validate that https://cms-vvwmz6oytla09236a0pygzgusx7z9dwj.ci.cms.va.gov/fayetteville-arkansas-health-care does not display a "System Menu" field.
   - [x] Validate that https://cms-vvwmz6oytla09236a0pygzgusx7z9dwj.ci.cms.va.gov/node/7209/edit displays a "System Menu" field in the "System Menu" field group and has a value of "VA Fayetteville Arkansas health care".
   - [x] Validate that https://cms-vvwmz6oytla09236a0pygzgusx7z9dwj.ci.cms.va.gov/jsonapi/node/health_care_region_page/b78d9e9f-6111-4da1-9256-fde753154dda?include=field_system_menu 
     - [x] does not result in an error.
     - [x] contains `"field_system_menu": { "data": null ... }`
     - [x] does not contain `included: [ { "type": "menu--menu" ... } ... ]`
2. Update the node by saving a new published revision.
   - [x] Validate that https://cms-vvwmz6oytla09236a0pygzgusx7z9dwj.ci.cms.va.gov/fayetteville-arkansas-health-care does not display a "System Menu" field.
   - [x] Validate that https://cms-vvwmz6oytla09236a0pygzgusx7z9dwj.ci.cms.va.gov/node/7209/edit displays a "System Menu" field in the "System Menu" field group and has a value of "VA Fayetteville Arkansas health care".
   - [x] Validate that https://cms-vvwmz6oytla09236a0pygzgusx7z9dwj.ci.cms.va.gov/jsonapi/node/health_care_region_page/b78d9e9f-6111-4da1-9256-fde753154dda?include=field_system_menu 
     - [x] does not result in an error.
     - [x] contains `"field_system_menu": { "data": { "type": "menu--menu", "id": "518f..." ... } ... }`
     - [x] contains `included: [ { "type": "menu--menu" ... } ... ]`

As a user without the `administrator` role...
1. Whether the node has been updated or not...
   - [x] Validate that https://cms-vvwmz6oytla09236a0pygzgusx7z9dwj.ci.cms.va.gov/fayetteville-arkansas-health-care does not display a "System Menu" field.
   - [x] Validate that https://cms-vvwmz6oytla09236a0pygzgusx7z9dwj.ci.cms.va.gov/node/7209/edit does not display a "System Menu" field.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by tjheffner — COMMENTED** [review]
The code LGTM, but the jsonapi doesn't appear to populate correctly for me after saving new published revision of a node.

**Comment by ndouglas** [comment]
Weird!  Thanks, @tjheffner, I'll figure that out.

**Comment by ndouglas** [comment]
@tjheffner Turns out I'm a big dumb idiot.  I posted the links to retrieve the JSON:API for Alexandria, not Fayetteville, so of course those weren't updated and won't show the data.

Thanks again, Tanner, I really appreciate the review.

**Review by tjheffner — APPROVED** [review]
@ndouglas you're not a big dumb idiot at all, i should have realized when i was qa'ing that it wasn't the json for the same node, call it a wash :heart: 🤦 

I see the correct stuff in the jsonapi response after saving the revision, now that i'm looking at the right json 🤝 

Screen Shot 2022-07-15 at 7 51 12 AM

**Pull request merged**
