### PR TITLE
VAGOV-949: Administration vocabulary configuration

### PR DESCRIPTION
**Pull request by kevwalsh**

### CODE REVIEW

**Comment by mbenziane** [comment]
build

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-75<br><br> [button_visit-site](http://pr-75.va.agile6.com)

**Comment by andyhawks** [comment]
@kevwalsh composer conflict here

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-75<br><br> [button_visit-site](http://pr-75.va.agile6.com)

**Pull request merged**
