### PR TITLE
VACMS-3916: CLP-Form-Field-Updates

### PR DESCRIPTION
**Pull request by kaise-lafrai**
## Description

See _issueid_. 

https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3916

https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/4007

## QA steps

- Login to preview environment.
- Navigate here: `/node/add/campaign_landing_page`

### Submission guidelines
- Confirm the following:
- [x] The following text appears at the very top of the page: `Campaign landing page are made up of a series of page segments. Each serves a specific purpose in explaining the campaign's message. Segments marked with an asterisk (*) are required. You can enable up to seven more segments to be included on your page.`

### Hero banner
- Confirm the following:
- [x] Field labels and help texts look like the following:
image

### Why this matters
- Confirm the following:
- [x] Field labels and help texts look like the following:
image

### What you can do
- Confirm the following:
- [x] Field labels and help texts look like the following:
image

### Video
- Confirm the following:
- [x] Field labels and help texts look like the following:
image

### Spotlight
- Confirm the following:
- [x] Field labels and help texts look like the following:
image

### Stories
- Confirm the following:
- [x] Field labels and help texts look like the following:
image

### Downloadable resources
- Confirm the following:
- [x] Field labels and help texts look like the following:
image

### Events
- Confirm the following:
- [x] Field labels and help texts look like the following:
image

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by swirtSJW — DISMISSED** [review]
Looks good Kaise.  Thank you.

**Comment by swirtSJW** [comment]
@kaise it looks like this has some conflicts that need resolving.

**Comment by kaise-lafrai** [comment]
@swirtSJW Thank you, taking a look now.

**Review by swirtSJW — DISMISSED** [review]

**Comment by kaise-lafrai** [comment]
@kevwalsh Ready for review

**Comment by swirtSJW** [comment]
Looks like that accessibility test fail was not really a fail.  Just the test timed out.

**Review by swirtSJW — APPROVED** [review]

**Comment by swirtSJW** [comment]
Another round of different fails.   rebuilding again.

**Review by kevwalsh — APPROVED** [review]
Nice @kaise-lafrai!

**Comment by swirtSJW** [comment]
image

**Pull request merged**
