### PR TITLE
VACMS-6646 - fix known issues with og:image and description metatags

### LINKED ISSUE #6646: Fix known issues with og:image and description metatags
ACs
- [x] Remove the metatag config at Content that makes too many assumptions about fields that don't exist.
- [x] Every content type that has a `field_media` image has a definition at the content type level
- [x] Remove "Global" metatag config, and possibly move some of it to Content
- [x] Update drupal spec tool with latest 
- [ ] Visual audit and meeting (@kevwalsh and possibly @msbtterswrth) prep for the presentations to PW and Facilities teams along with drupal spec tool.

Public Websites
* Fallback scenarios sitewide
* PW product content types 

Facilities
* Vet Center and VAMC content types

### PR DESCRIPTION
**Pull request by JayDarnell**
## Description

Closes #6646 

This PR changes the values the metatag module provides our front end in some cases but I'm unsure how we could actually test this due to the decoupled nature of the site.

The following items were used to guide the changes I made:

- if a field_intro_text field is present and required on a given content type, update the metatag definition for that type to utilize this field as the basis of the description and og:description fields instead of using field_description
- if a field_intro_text field is present on a content type and not required but the field_description field is missing, update the metatag definition for that type to utilize this field as the basis of the description and og:description fields instead of using field_description
- if both fields are present but the field_intro_text field isn't required then continue using field_description
- if a given content type has the field_media field present, update the metatag definition for the content type to use this field for og:image
- update the metatag definition for all nodes (fallback) to use https://www.va.gov/img/design/logo/va-og-image.png for og:image instead of field_media

## QA steps

The following example items can be manually checked to verify description, og:description, and og:image tags have been supplied:

- [x] **Benefits Detail Page**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/health-care/covid-19-vaccine/about-covid-19-vaccine

- [x] **Benefits Hub Landing Page**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/disability

- [x] **Events List**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/birmingham-health-care/events

- [x] **FAQ - multiple Q&As**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/resources/waivers-for-va-benefit-debt

- [x] **Health Services List**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/loma-linda-health-care/health-services

- [x] **Landing Page**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/resources

- [x] **Leadership List**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/montana-health-care/about-us/leadership

- [x] **News Release**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/montana-health-care/news-releases/montana-va-health-care-system-launches-its-2021-flu-shot-season-with-statewide-clinics

- [x] **News Releases List**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/birmingham-health-care/news-releases

- [x] **Office**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/outreach-and-events

- [x] **Publication Listing Page**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/outreach-and-events/outreach-materials

- [x] **Resources and support Detail Page**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/resources/va-covid-19-debt-relief-options-for-veterans-and-dependents

- [x] **Staff Profile**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/tuscaloosa-health-care/staff-profiles/john-f-merkle

- [x] **Step-by-Step**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/resources/how-to-change-direct-deposit-information-for-va-benefits

- [x] **Stories List**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/birmingham-health-care/stories

- [x] **Story**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/asheville-health-care/stories/what-is-peer-support-celebration-day

- [x] **VAMC Detail Page**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/montana-health-care/about-us

- [x] **VAMC Facility**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/sierra-nevada-health-care/locations/lahontan-valley-va-clinic

- [x] **VAMC System**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/fayetteville-coastal-health-care

- [x] **VAMC System Locations List**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/bedford-health-care/locations

- [x] **VAMC System Operating Status**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/salt-lake-city-health-care/operating-status

- [x] **Vet Center**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/east-los-angeles-vet-center

- [x] **Vet Center - Locations List**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/tucson-vet-center/locations

The following example items can be checked to verify og:image but the description field is not fixed yet:

- [x] **Campaign Landing Page**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/initiatives/veteran-trust-in-va

- [x] **Event**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/erie-health-care/events/drive-thru-flu-clinic-0

- [x] **VA Form**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/find-forms/about-form-21p-0513-1

- [x] **VAMC System Policies Page**
https://pr6788-4d4cytycoml2sj4tenvuom3esdwc5lvi.ci.cms.va.gov/loma-linda-health-care/policies

### CODE REVIEW

**Review by kevwalsh — CHANGES_REQUESTED** [review]
This is awesome Jay. 

I agree that QA for this is hard. And I hate to expand scope, but i think the best way to QA this is to create a visual audit tool, which would launch us into the next phase of this epic, because it would provide a means for product teams to always be able to access examples, now and in the future. 

You could and probably should create this as another display of one of the existing /admin/content/audit views, but just be careful not to update the Default (aka master) view. 

- [ ] Path: admin/content/audit/seo-metatags
- [ ] Menu link: Administration menu. 
- [ ] Permissions: Content admin or Admin
- [ ] Fields
  - [ ] Title (that's linked to the node)
  - [ ] www.va.gov URL (a "Link to Content" field that's been rewritten to use www.va.gov version, so, say, www.va.gov/health-care instead of prod.cms.va.gov/health-care... this will let editors see it in action on VA.gov too)
  - [ ] <title>
  - [ ] <description>
  - [ ] <og:image> displayed as an image (I wonder if it should have some hacky inline css so that it doesn't blow up the page... like max 150px width or something)
  - [ ] Any others you can think of? 
- [ ] Set pagination small, like 5 or 10 nodes by default, because og:image will be heavy. I suppose we could expose the pagination?  
- [ ] Filters
  - [ ] Remove the default Published filter. 
  - [x] Add an exposed Content type filter with multiple select, and expose the operators. 
- [ ] Header: Results counter.

**Review by swirtSJW — APPROVED** [review]

**Review by swirtSJW — CHANGES_REQUESTED** [review]
On QA I found this one has no descriptions
image

If this reflects one of the ones with "issues" noted in the spec tool, lets surface it in the QA steps.   Reviewers should not have to chase details down.

**Comment by JayDarnell** [comment]
> On QA I found this one has no descriptions image
> 
> If this reflects one of the ones with "issues" noted in the spec tool, lets surface it in the QA steps. Reviewers should not have to chase details down.

Yes, for this item the Description is still broken because I'm unclear on which tag we could substitute for field_description. This is tricky to QA because most of the items I could "fix" as a new baseline but not all of them and since those were already specified in the spec tool I avoided duplicating that information here.

**Comment by JayDarnell** [comment]
For QA, since we still expect some errors, I think it may be sufficient to just note the items where description, og:description, or og:image are missing. I can cross reference with the spec tool at that point to see if we successfully moved the baseline as far as we can.

**Comment by JayDarnell** [comment]
I've added another commit to address a failing phpunit test. When the global metatag defaults were combined with the node metatag defaults I inadvertently omitted the twitter image alt tag which was causing the MetaTagTest phpunit test to fail on line 43. 

I updated the default node metatag settings to include an alt tag for the twitter image and then updated any individual content type defaults where og:image was set directly such that the twitter image would match and the twitter image alt tag would be pulled from that image.

**Review by swirtSJW — APPROVED** [review]
NIce work Jay.

**Pull request merged**
