### PR TITLE
VACMS-4451: Remove unused modules and packages.

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

See #4451.  Probably should wait until we're sure we've caught all of the modules/packages that will be removed as part of the D9 upgrade.  Not a huge issue if it goes out "early," though, all else being equal.

Current list: 
- `drupal/computed_field`
- `drupal/field_formatter`
- `drupal/markdown`
- `drupal/mass_pwreset`
- `drupal/openapi`
- `drupal/openapi_ui`
- `drupal/openapi_ui_redoc`
- `drupal/openapi_ui_swagger`
- `drupal/rest_menu_tree`
- `drupal/schemata`
- `drupal/simple_oauth`
- `drupal/views_infinite_scroll`
- `drupal/views_tree`
- `michelf/php-markdown`

## Testing done
I'm gonna look through the codebase casually to see if we have any hidden/undeclared dependencies on any of this code.

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by ndouglas** [comment]
Gonna take another look at the failed tests.

**Comment by ndouglas** [comment]
>┃ ┌─ @BeforeFeature @mock_va_gov_urls #                                                                                 ┃ CustomDrupal\ContentModelContextCustom::enableVaGovBackendHttpClient()                                               
 ┃ ╳  The module menu_normalizer does not exist. (Drupal\Core\Extension\Exception\UnknownExtensionException)    
 
 Weird.  This was removed and I don't really understand why.  Gonna poke around and see what happened and what else might've been affected.

**Comment by ndouglas** [comment]
That package was not explicitly required, so I required it.  I looked through the composer.lock changes and didn't see any other Drupal module packages that were removed inadvertently, so I figure this might just be a weird case.  I'm not sure how this hasn't been removed before... 🤔

**Comment by ndouglas** [comment]
>┃ ┌─ @BeforeFeature @mock_va_gov_urls #                                                                                 ┃ CustomDrupal\ContentModelContextCustom::enableVaGovBackendHttpClient()                                               
 ┃ │                                                                                                                    
 ┃ ╳  The module schemata does not exist. (Drupal\Core\Extension\Exception\UnknownExtensionException)                   
 ┃ │                                                                                                                    

Oh.  Schemata also shows this issue, but I missed it because I saw that it was to be explicitly removed in #4292 and mistakenly thought it was already done.

**Comment by ndouglas** [comment]
I can roll the composer changes for #4292 (modules disabled in #4859) into this PR as well, since they've already irritated me once...

**Comment by ndouglas** [comment]
Per #4718 Adding `drupal/views_infinite_scroll` to this.

**Review by acrollet — APPROVED** [review]
lgtm. I'm in favor of getting this out even if we have to remove a couple more later.

**Pull request merged**
