### PR TITLE
VACMS-18281 Added character counters & help text to phone paragraph type

### PR DESCRIPTION
**Pull request by davidmpickett**
## Description

Relates to #18281 & #15803

## Testing done

Using the [entity relationship diagram](https://pr18542-bqc641quszrp87hs4gatpmdax0eaaubv.ci.cms.va.gov/admin/reports/content-model/entity-diagram/paragraph/phone_number?max_depth=1), I identified 4 different Drupal entities that currently use the Phone Paragraph type

Screenshot 2024-07-17 at 12 23 03 PM

- VAMC System VA police Page -> Tested directly
- Service Location paragraph -> Tested via VAMC Facility Health Service
- Contact Information paragraph -> Tested via Resources and Support Detail Page
- VAMC Facility Health Service node -> (A legacy field which is hidden in the UI, [but hasn't been deleted yet](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17137))

## Screenshots

<details><summary>Character counts updates without help text changes</summary>

Screenshot 2024-07-17 at 12 38 10 PM

Screenshot 2024-07-17 at 12 38 17 PM

</details>
<details><summary>  Help Text changes without character count update</summary>

Screenshot 2024-07-17 at 2 22 21 PM

</details>

<details><summary>All together now</summary>

Screenshot 2024-07-17 at 2 36 09 PM

</details>

## QA steps

What needs to be checked to prove this works?
What needs to be checked to prove it didn't break any related things?
What variations of circumstances (users, actions, values) need to be checked?

1. [Log in to tugboat](https://pr18542-bqc641quszrp87hs4gatpmdax0eaaubv.ci.cms.va.gov/) as an Admin (e.g. christian.burk@va.gov)
2. Add a [new VAMC Facility Health Service](https://pr18542-bqc641quszrp87hs4gatpmdax0eaaubv.ci.cms.va.gov/node/add/health_care_local_health_service)
   - [x] Under Service Location go to Appointments > Phone number for appointments > Add a phone number
   - [x] Under Service Location go to Contact Info > Phone  > Add a phone number
   - [x] Validate that character counters behave as expected
   - [x] Validate that help text shows up as expected
3. Add a [new VAMC System VA police Page](https://pr18542-bqc641quszrp87hs4gatpmdax0eaaubv.ci.cms.va.gov/node/add/vamc_system_va_police)
   - [x] Under Contact phone number
   - [x] Validate that character counters behave as expected
   - [x] Validate that help text shows up as expected
4. Add a [new Resources & and Support detail page](https://pr18542-bqc641quszrp87hs4gatpmdax0eaaubv.ci.cms.va.gov/node/add/support_resources_detail_page)
   - [x] Under Contact information > Add a phone number
   - [x] Validate that character counters behave as expected
   - [x] Validate that help text shows up as expected

### Definition of Done

- [ ] Automated tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### CODE REVIEW

**Comment by davidmpickett** [comment]
Updated so this will close two related issues instead of just 1

**Review by thejordanwood — APPROVED** [review]
Looks great!

**Comment by laflannery** [comment]
The help text does not appear to match what's in Figma:
image

**Comment by davidmpickett** [comment]
> The help text does not appear to match what's in Figma: image

Gah, I was bamboozled by a comment preview

Screenshot 2024-07-18 at 10 59 16 AM

Foolishly, I took it at it's word and did not dive deeper

Screenshot 2024-07-18 at 11 02 14 AM

I'll go fix that now

**Comment by laflannery** [comment]
If Jordan approves the change that works for me!

**Review by laflannery — APPROVED** [review]

**Review by omahane — APPROVED** [review]
Everything checks out and looks good. Nice work.

**Pull request merged**
