### PR TITLE
VACMS-10667 show additional vet centers

### LINKED ISSUE #10667: CMS: Vet Center Locations pages do not show mobile on node:view.
## Describe the defect
When I look at node:view on a Vet Center location page, I can see the "Main and satelite locations" but I can not see "Display additional mobile vet centers"
image

Surfaced in [this slack thread](https://dsva.slack.com/archives/C02730UEZPS/p1662667671380849)
## To Reproduce
1. Go to '/node/28131/edit'
2. Notice that it has an entry for a mobile vet center
3. Click on the "View" tab and notice that the mobile vet center does not show.
4. It does show correctly on https://www.va.gov/dundalk-vet-center/locations and the preview server http://preview-prod.vfs.va.gov/preview?nodeId=28131

## AC / Expected behavior
- [ ] When on node view, the field and any entries for it are shown in a similar fashion as "Main and satelite locations"

## Screenshots
image

 ## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### LINKED ISSUE #11162: CMS: Vet Center - Locations list table is missing caption
## Description
In the CMS, the Vet Center - Locations list displays "Main and Satellite Locations" in a table on the View screen.  However, this table uses a basic <div> element as a header for the table rather than a programmatic table caption, making it difficult for screen reader user to fully understand the exact purpose of the table date.

This View has also recently been update to include a second table displaying "Additional Mobile Vet Center Locations".  This table uses the same table as above, therefore it also is missing the associated table caption.

### Screenshot
image

## Accessibility Criteria
[WCAG 1.3.1 A](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html) 

## Acceptance Criteria
- [ ] Update existing "Main and Satellite Locations" table to use caption instead of div
- [ ] Update new "Additional Mobile Vet Center Locations" table to use caption instead of div

### PR DESCRIPTION
**Pull request by omahane**
## Description

Closes #10667 
Closes #11162 

## Testing done

Manually

## Screenshots
Screen Shot 2022-10-06 at 7 08 11 AM

## QA steps
As an admin, go to the Dundalk Vet Center listing:https://pr11111-8gjyhiorwsy2rxvysrsxdokv26fmbrr5.ci.cms.va.gov/dundalk-vet-center/locations
- [x] Validate that the node:view shows the table of additional vet centers
- [x] Go to node:edit
- [x] Validate that the same set of additional vet centers shows (Baltimore Mobile)

As an admin, go to the Clearwater Vet Center listing (clearwater-vet-center/locations):
- [x] Validate that the node:view shows the table of additional vet centers
- [x] Go to node:edit
- [x] Validate that the same set of additional vet centers shows (Clearwater Mobile)

As an admin, go to the St. Petersburg Vet Center listing (st-petersburg-vet-center/locations):
- [x] Validate that the node:view shows no additional vet centers
- [x] Go to node:edit
- [x] Validate no additional vet centers are listed

As an admin, go to the Houston West Vet Center listing (houston-west-vet-center/locations):
- [x] Validate that the node:view shows no additional vet centers
- [x] Go to node:edit
- [x] Validate no additional vet centers are listed

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [x] Tests have been added if necessary.
- [x] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by laflannery** [comment]
1. Remove the labels and replace with table captions instead
2. Will also look at removing the unintended addition of "additional mobile vet centers" on the edit screen

**Review by swirtSJW — COMMENTED** [review]
Code looks good and functionally it is all good. 
image

image



Can we get these to visually flow better?
image

**Comment by JayDarnell** [comment]
@omahane I saw you pushed new commits after Steve and Laura's comments above. Is this ready for another review pass?

**Comment by omahane** [comment]
Screen Shot 2022-10-07 at 3 24 17 PM
Screen Shot 2022-10-07 at 3 24 01 PM

Programmatically attaching MVC view to the footer of the VC view, but only on node:view.

I also made the text above the MVC view the table caption, so it doesn't match the other one. I'll change that subsequently, in a different commit.

**Comment by omahane** [comment]
Screen Shot 2022-10-07 at 3 34 19 PM
Replaced the field_label with a table caption.

**Review by laflannery — APPROVED** [review]
508 approved.  Table captions look good on both view and edit

**Comment by swirtSJW** [comment]
Looks like the column aligments are totally at the whim of the length of the title.  

It would be nice to fix those with percentages so that the two tables don't look so ragged.
image


image



Lets have @BlakeOrgan  decide whether alignment is something worth worrying about or if it just my issue.

**Review by swirtSJW — DISMISSED** [review]
Code all tests out fine.  If Blake approves as-is, I am fine with merging.

**Comment by BlakeOrgan** [comment]
Yeah, these should probably line up with one another.

**Comment by omahane** [comment]
Screen Shot 2022-10-10 at 11 20 55 AM

**Comment by BlakeOrgan** [comment]
Looks good! ✅

**Review by swirtSJW — APPROVED** [review]
Nice work @christianmburk 

Looks as good as it performs ;) 
image

**Comment by swirtSJW** [comment]
image

**Pull request merged**
