### PR TITLE
15308 Update color variables in CSS

### PR DESCRIPTION
**Pull request by edmund-dunn**
## Description

Relates to #15308

## QA steps

What needs to be checked to prove this works?
What needs to be checked to prove it didn't break any related things?
What variations of circumstances (users, actions, values) need to be checked?

Review colors and a11y per #15309

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by laflannery — APPROVED** [review]
I'm tested quite a few pages and no color contrast issues are being flagged so this looks good to me.

**Comment by ndouglas** [comment]
@edmund-dunn Any particular reason this hasn't been merged yet? 🤔

**Comment by gracekretschmer-metrostar** [comment]
Pull up for sprint 22 and bring in Amanda and Marisa.

**Comment by JakeBapple** [comment]
Strategy:
new branch from main using 15308 naming
merge in 15308 and then 14753
run the storybook styles and then the theme command to check for errors
tag edmund, steve, and marissa for review
can close those two after we merge in the new one

**Comment by JakeBapple** [comment]
closing this pr as it was consolidated in this: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/19520

**Pull request closed without merging**
