### PR TITLE
VAGOV-982: Region content structure.

### PR DESCRIPTION
**Pull request by kevwalsh**

### CODE REVIEW

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-148<br><br> [button_visit-site](http://pr-148.va.agile6.com)

**Comment by andyhawks** [comment]
rebuild

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
The reason that this is failing is because it needs #137 merged/rebased.

> stderr": "unable to prepare context: path \"./docker/images/va-socks-proxy\" not found

That path needs to be there with its files from #137.

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-148<br><br> [button_visit-site](http://pr-148.va.agile6.com)

**Pull request merged**
