### PR TITLE
VACMS-11397: fix for help text color and size

### LINKED ISSUE #10299: Update the color of description text on Vet Center Cards
## Description
On the Vet Center Dashboard in the CMS, the description help text on the cards (HEX 757576) does not pass WCAG 2.0 AA color contrast requirements against the light gray background

### Changes:

 - This description text will be updated to be the same color as the standard text color. `#212121`
 - Increase size of description text from 13px to 14px.

## Screenshot
image

## Accessibility Standard

WCAG version 2.0 AAA, [Criterion 1.4.6](https://www.w3.org/WAI/WCAG21/Understanding/contrast-enhanced)

## Acceptance Criteria
- [ ] Update text color to `#212121`
- [ ] Update text size to 14px
- [ ] Accessibility Review
- [ ] Design Review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### LINKED ISSUE #11397: Update the color of help text within CMS
## Description
Blake has [provided design direction](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10070#issuecomment-1287087253) to update the help text within the CMS to align with the Design System and accessibility guidelines.

Suggested edits and a link to the [Figma file](https://www.figma.com/file/ZENA4mBp6DPyCtvj3NlBRn/Help-Text?node-id=16%3A563) for reference.

### Changes:

 - Help text will **always** be the same color as the Input label. `#212121`
    - This includes disabled help text text (If an input field is disabled, the input help text should still be `#212121`)
 - Increase size of help text from 13px to 14px.

## Acceptance Criteria

- [ ] Update help text color to `#212121` across the CMS
- [ ] Update help text size to 14px across the CMS
- [ ] Accessibility Review
- [ ] Design Review

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by edmund-dunn**
## Description

Closes #11397 
Closes #10299

## Testing done
Tested locally. Verified changes on the forms for a Vet Center, a Vet Center -Facility Services, VAMC Detail page and Full Width Alert. 

## Screenshots
CleanShot2023-01-04at09 29 44
CleanShot2023-01-04at11 00 25

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

- [ ] Update help text color to `#212121` across the CMS
- [ ] Update help text size to 14px across the CMS
- [ ] Accessibility Review
- [ ] Design Review

### Accessibility QA

- [x] Run axe on Vet center dashboard
- [x] Run axe on an edit page with help text and disabled text, like a Facility edit view: https://pr12168-cpswdwlxamabhzzatft6uwyawm2oeptu.ci.cms.va.gov/node/1081/edit
- [x] Confirm that no color contrast errors are flagged

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by laflannery — CHANGES_REQUESTED** [review]
The only update I do not see is the disabled text:
- On this page for example: https://pr12168-cpswdwlxamabhzzatft6uwyawm2oeptu.ci.cms.va.gov/node/1820/edit There are 2 disabled fields
  - Facility Locator API ID (in the main form section)
  - Create new revision Revisions are required. (right column section)

We would like all disabled text to be updated to the standard color as well

**Comment by BlakeOrgan** [comment]
Also, on the link that Laura posted above, there are places where the help text contains a link. The color of the link text should be `#004795`

**Comment by laflannery** [comment]
@BlakeOrgan I confirmed the links all remained the correct link color

**Review by laflannery — APPROVED** [review]
Looks good!

**Review by EWashb — APPROVED** [review]
I see no issues.

**Review by BlakeOrgan — APPROVED** [review]
Looks good!

**Review by JayDarnell — APPROVED** [review]
Looks good to me.

**Comment by JayDarnell** [comment]
Screenshot 2023-01-05 at 2 29 44 PM

**Pull request merged**
