### PR TITLE
[WIP] VACMS 8299 + 8300 site alert improvements

### LINKED ISSUE #8299: [Implement] first site alert improvement

### PR DESCRIPTION
**Pull request by tjheffner**
## Description
Closes #8299 and #8300. Contributes & uses a patch for adding dismissible behaviors to site alert. Creates site alert component in design system, used in Drupal.

All site alert forms now have a "dismissible" checkbox that allows them to be dismissed. This is set to false by default.
Dismissed alerts are remembered in sessionstorage, so it will not re-appear for a user on any page once dismissed. If the dismissed site alert is saved again as no longer dismissible, it will re-appear as expected.

Some minor styling work needed still, dependent on #8994 to clean up some SB structure so I will revisit this later this sprint. 

## Testing done
added multiple alerts,  some dismissible and not, dismissed alerts, checked different pages and verified alerts still disappeared (and did not re-appear on the ajax refreshes)

## QA steps
- as admin, log in and navigate to `/admin/config/system/site-alerts`
- enable any alert
  - check the schedule to make sure it will actually appear while you're testing
  - warning that any "High" status alerts will block the full screen unless they are marked dismissible! Need to delete the html element if you accidentally lock yourself out
  - save the alert
- create another alert that is dismissible, save it
- see alerts show on next page, see that one can be dismissed and one cannot.
- dismiss the dismissible alert
- navigate to a new page (or refresh), see that the dismissed alert does not reappear

- log out, log in as any editor (kitty.walsh@va.gov)
- see the alerts behave as expected.... you may need to delete the cookie in session storage labeled "siteAlertsVisibility" to reset all alert status for your browser, or use an incognito window

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [x] `DO NOT MERGE`

### CODE REVIEW

**Comment by swirtSJW** [comment]
@tjheffner and @rachel-kauff   I don't think this site alert dismissability is working for the way we use site alert.   
example:  
1. I put up a "content  release flowing again" message and make it dismissible 
2. The alert appears   as dimissable, 
image
3.  I dismiss it and it goes away.
4. I refresh the page I am on and it comes back.  Then the next time the ajax runs, it hides itself... so it shows for about 10-30 sec then goes away.
5. I go to any other page and it still shows and never goes away, unless I dismiss it on that page.

The dismissal is showing in the sessionstorage but is not be respected on the subsequent pages nor the initial page load.
image


Also if it was listening to its session storage and working as directed, it would prevent us from having a re-useable dismissable alert.  As the next time we re-activate it, it would not show itself again.    So we would have to be careful not to have the combination of re-useable and dismissable.


Separately, is this styling what we are after? Seems ragged like this
image

**Comment by tjheffner** [comment]
Ah, the styling is definitely not ready yet, I should not have marked this out of WIP-- wasn't thinking this morning. i apologize for that. Appreciate the QA sanity check, I will double check the patch... it appeared to have the desired behavior locally

**Comment by swirtSJW** [comment]
Summarizing call from earlier today with @rachel-kauff and @tjheffner 

- Explore hashing the content of the message field and using the hash (included in the ajax endpoint) to allow for detecting if the message changed and needing to resurface a dismissed alert.

**Comment by tjheffner** [comment]
Dug into this a little bit - difference in behavior between my local and tugboat/higher environments is due to different values in `drupalSettings.siteAlert.workaround_needed`. This is set to `true` on my local, but false on the higher environments. `true` forces the javascript to load and run immediately, `false` waits until the first timeout trigger, about 10s after page load. yikes.

Need to dig into the caching mechanism of the module itself and find out why this behavior is changing / how to set it correctly for higher environments.

**Comment by tjheffner** [comment]
Closing this in favor of #9723 which uses the new sitewide alert module that includes dismissibility as a feature ootb.

**Pull request closed without merging**
