### PR TITLE
[DO NOT MERGE][OLD] VAGOV-3930: SimpleSAMLPHP Configuration. 

### PR DESCRIPTION
**Pull request by andyhawks**
QA instructions are at https://va-gov.atlassian.net/browse/VAGOV-4201.

In reviewing you can ignore everything under /simplesamlphp-1.17.2 and /saml2, those are third-party library files unchanged except for /simplesamlphp-1.1.7.2/config/config.php. 

SimpleSAMLPHP 1.17.2 is installed manually outside of composer at project root because: a) our Vendor dir being under docroot is problematic (simplesamlphp needs to be outside of docroot), b) should not be installed via composer because we need symlinks, so the directory needs to be permanent in the codebase and not an artifact.

### CODE REVIEW

**Comment by ElijahLynn** [comment]
Are the main files to review here:
1. docroot/.htacces
1. docroot/simplesaml
1. composer.json

**Comment by andyhawks** [comment]
> Are the main files to review here:
> 
> 1. docroot/.htacces
> 2. docroot/simplesaml
> 3. composer.json

For code review look at .htaccess and composer.json and confirm the code organization with simplesamlphp-1.17.2 at project root, and then QA and follow the QA instructions at https://va-gov.atlassian.net/browse/VAGOV-4201. Thx!

**Comment by ElijahLynn** [comment]
K, thanks, both PR ENVs are failing at /simplesaml with:
> Fatal error: Uncaught Exception: Unable to load Composer autoloader in /app/simplesamlphp-1.17.2/lib/_autoload.php on line 19 Exception: Unable to load Composer autoloader in /app/simplesamlphp-1.17.2/lib/_autoload.php on line 19 Call Stack: 0.0000 396912 1. {main}() /app/simplesamlphp-1.17.2/www/index.php:0 0.0000 397304 2. require_once('/app/simplesamlphp-1.17.2/www/_include.php') /app/simplesamlphp-1.17.2/www/index.php:3 0.0000 397552 3. require_once('/app/simplesamlphp-1.17.2/lib/_autoload.php') /app/simplesamlphp-1.17.2/www/_include.php:4

**Comment by andyhawks** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/pull/401

**Pull request closed without merging**
