### PR TITLE
VACMS-17969: Update hours to midnight

### PR DESCRIPTION
**Pull request by omahane**
## Description

Relates to #17969 
Relates to #18393

## Testing done
Manually

### Changed hours in test processor script
Screenshot 2024-06-14 at 10 51 23 PM

## QA steps
- [x] Run the following script in the Tugboat terminal: `drush scr scripts/content/vacms-17969/VACMS-17969-vba-test-data-processor.php`
- [ ] As an admin, go to [Philadelphia VA Regional Benefit Office - Grief and bereavement counseling](https://pr18328-8xlwvjaivaajom82pgmuy8h3n3fzt65g.ci.cms.va.gov/node/70318), which has "hours_12a_12a" in the spreadsheet for the service location.
- [ ] Confirm that it hours are listed as "All day open" in the node:view
- [ ] Click **Edit**
- [ ] Confirm that the hours in Drupal are shown correctly (i.e., 12 am - 12 am)

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### CODE REVIEW

**Comment by omahane** [comment]
@laflannery Noting that I don't see any hours, even though I fixed both Grief and have other facilities with with hours, such as Disability compensation: 

Screenshot 2024-06-14 at 10 51 59 PM

Screenshot 2024-06-14 at 10 51 23 PM

At least the Drupal hours look right.

**Comment by jilladams** [comment]
@laflannery @omahane what's left to get this PR over the line? Happy to help, if I can.

**Comment by laflannery** [comment]
@jilladams I think it could be closed? There's definitely something funky going on with the hours and I ended up making [a separate ticket for it](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18393) but I think it's unrelated to this script. I'm not totally clear on what this PR is for exactly so I'll let @omahane speak to if this PR specifically can be closed

**Comment by jilladams** [comment]
OK noted. I linked this PR to #18393 and commented there. We don't have to close the PR if it seems useful, but I _am_ going to close the test script ticket.

**Review by timcosgrove — APPROVED** [review]

**Pull request merged**
