### PR TITLE
VACMS-3910: Update formatter to use unmanaged files.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #3910 

## Testing done
Visual / Behat

## Screenshots
image

## QA steps
- As an administrator, go to `/node/15068/edit` and visually verify that each panel has an svg, and alt text.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by kevwalsh — CHANGES_REQUESTED** [review]
@ethanteague Minor responsiveness issue at certain screensizes.  

Create_Campaign_Landing_Page___VA_gov_CMS

**Review by swirtSJW — DISMISSED** [review]
Code looks good to me.

**Review by swirtSJW — APPROVED** [review]

**Comment by swirtSJW** [comment]
Just waiting on tests to finish

**Comment by ethanteague** [comment]
> Just waiting on tests to finish

ty, sir

**Comment by swirtSJW** [comment]
image

**Pull request merged**
