### PR TITLE
VACMS-10649: Disables Update Manager module.

### LINKED ISSUE #10649: Disable Update Manager.
## Description
Isn't useful, may freak out people.

## Acceptance Criteria
- [ ] Update Manager module is disabled completely.

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

Closes #10649.

The Update Manager functionality is considered [distracting and possibly alarming](https://dsva.slack.com/archives/CT4GZBM8F/p1662582777954349) on production.  So the thought was to disable it there.  If it's not a good thing on production, then it's not a good thing on staging either.  And if it's not good on production or staging, and barely anyone uses dev unless staging is tied up, then it's hard to see how it could be a good thing on dev.  If it's not a good thing in any BRD environment, we have to ask what possible purpose it could serve on Tugboat or local dev environments.

So I'm just killing it everywhere.

## Testing done

Tested config import/export to verify that removing it does not impact other configuration.  Verified that the module is actually disabled and that the appropriate warning appears in the status report.  Running normal automated tests to verify that no other meaningful functionality is impacted.

## QA Steps
1. Go here: https://cms-jzzjmpuihwhn0qghbeohar1em8l2vd57.ci.cms.va.gov/admin/reports/status
  - [ ] Confirm that you see the message: 
Screen Shot 2022-09-08 at 8 13 38 AM

### CODE REVIEW

**Review by swirtSJW — CHANGES_REQUESTED** [review]
This has an uninstall hook that needs to be run before disabling it
image

It needs one of these in va_gov_db.install

```
/**
 * Uninstall Entity Embed module.
 */
function va_gov_db_update_9010(&$sandbox) {
  $messages = _va_gov_db_uninstall_modules(['update']);

  return $messages;
}
```

**Comment by ndouglas** [comment]
I'm having trouble understanding why that would be required.  

The `update_uninstall()` function should be called when the module is uninstalled.  There shouldn't be any need to run the uninstall hook _before_ the module is uninstalled.  I read the [documentation](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/workflow.md) and existing uses and can't figure out why it would be a good idea to do this.

I logged into CMS-Test staging to verify manually:

```
[cms@ip-redacted cms]$ drush state:get update.last_check
1661889142
[cms@ip-redacted cms]$ drush state:get update.last_email_notification
1661150216

MariaDB [dsva_cms_staging]> SELECT * FROM queue WHERE name="update_fetch_tasks";
...
68 rows in set (0.00 sec)

[cms@ip-redacted cms]$ nano -w ./config/sync/core.extension.yml 
... removed update module ...
[cms@ip-redacted cms]$ rm config/sync/update.settings.yml 

[cms@ip-redacted cms]$ drush cim -y
... 
 [notice] Synchronized extensions: uninstall update.
...
[cms@ip-redacted cms]$ drush state:get update.last_email_notification

[cms@ip-redacted cms]$ drush state:get update.last_check

MariaDB [dsva_cms_staging]> SELECT * FROM queue WHERE name="update_fetch_tasks";
Empty set (0.00 sec)
```

I also deployed this commit to CMS-Test staging.

The deployment [succeeded without issue](http://jenkins.vfs.va.gov/job/deploys/job/cms-test-vagov-staging/279/console):

```
10:29:33  ok: [ip-10-247-34-146.us-gov-west-1.compute.internal] => 
10:29:33    drushdeploy.stdout_lines:
10:29:33    - ' [notice] Database updates start.'
10:29:33    - '>  [success] No pending updates.'
10:29:33    - ' [success] Cache rebuild start.'
10:29:33    - '>  [success] Cache rebuild complete.'
10:29:33    - ' [success] Config import start.'
10:29:33    - +------------+----------------------------------------------------------------+-----------+
10:29:33    - '| Collection | Config                                                         | Operation |'
10:29:33    - +------------+----------------------------------------------------------------+-----------+
10:29:33    - '|            | field.field.node.vba_facility.field_address                    | Create    |'
10:29:33    - '|            | field.field.node.vba_facility.field_office_hours               | Create    |'
10:29:33    - '|            | field.storage.node.field_facility_vba_classificatio            | Create    |'
10:29:33    - '|            | field.field.node.vba_facility.field_facility_vba_classificatio | Create    |'
10:29:33    - '|            | field.field.node.vba_facility.field_phone_number               | Create    |'
10:29:33    - '|            | core.entity_view_display.node.vba_facility.ief_table           | Create    |'
10:29:33    - '|            | core.entity_view_display.node.vba_facility.external_content    | Create    |'
10:29:33    - '|            | core.extension                                                 | Update    |'
10:29:33    - '|            | password_policy.password_policy.va_gov_cms                     | Update    |'
10:29:33    - '|            | core.entity_view_display.node.vba_facility.teaser              | Update    |'
10:29:33    - '|            | core.entity_view_display.node.vba_facility.default             | Update    |'
10:29:33    - '|            | core.entity_form_display.node.vba_facility.default             | Update    |'
10:29:33    - '|            | raven.settings                                                 | Update    |'
10:29:33    - '|            | simplesamlphp_auth.settings                                    | Update    |'
10:29:33    - '|            | syslog.settings                                                | Update    |'
10:29:33    - '|            | update.settings                                                | Delete    |'
10:29:33    - +------------+----------------------------------------------------------------+-----------+
10:29:33    - ''
10:29:33    - ' // Import the listed configuration changes?: yes.                              '
10:29:33    - ''
10:29:33    - '>  [warning] Invalid argument supplied for foreach() ConfigImportSubscriber.php:177'
10:29:33    - '>  [notice] Synchronized extensions: uninstall update.'
10:29:33    - '>  [notice] Synchronized configuration: create field.field.node.vba_facility.field_address.'
10:29:33    - '>  [notice] Synchronized configuration: create field.field.node.vba_facility.field_office_hours.'
10:29:33    - '>  [notice] Synchronized configuration: create field.storage.node.field_facility_vba_classificatio.'
10:29:33    - '>  [notice] Synchronized configuration: create field.field.node.vba_facility.field_facility_vba_classificatio.'
10:29:33    - '>  [notice] Synchronized configuration: create field.field.node.vba_facility.field_phone_number.'
10:29:33    - '>  [notice] Synchronized configuration: create core.entity_view_display.node.vba_facility.ief_table.'
10:29:33    - '>  [notice] Synchronized configuration: create core.entity_view_display.node.vba_facility.external_content.'
10:29:33    - '>  [notice] Synchronized configuration: update password_policy.password_policy.va_gov_cms.'
10:29:33    - '>  [notice] Synchronized configuration: update prometheus_exporter.settings.'
10:29:33    - '>  [notice] Synchronized configuration: update core.entity_view_display.node.vba_facility.teaser.'
10:29:33    - '>  [notice] Synchronized configuration: update core.entity_view_display.node.vba_facility.default.'
10:29:33    - '>  [notice] Synchronized configuration: update core.entity_form_display.node.vba_facility.default.'
10:29:33    - '>  [notice] Synchronized configuration: update raven.settings.'
10:29:33    - '>  [notice] Synchronized configuration: update simplesamlphp_auth.settings.'
10:29:33    - '>  [notice] Synchronized configuration: update syslog.settings.'
10:29:33    - '>  [notice] Finalizing configuration synchronization.'
10:29:33    - '>  [success] The configuration was imported successfully.'
10:29:33    - ' [success] Cache rebuild start.'
10:29:33    - '>  [success] Cache rebuild complete.'
10:29:33    - ' [success] Deploy hook start.'
10:29:33    - '>  [success] No pending deploy hooks.'
```

And once again I verified that the hook was run as expected and had the desired effects:

```
[cms@ip-10-247-34-146 cms]$ drush sql-cli
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 57803
Server version: 10.5.13-MariaDB-log managed by https://aws.amazon.com/rds/

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [dsva_cms_staging]> SELECT * FROM queue WHERE name="update_fetch_tasks";
Empty set (0.00 sec)

MariaDB [dsva_cms_staging]> quit
Bye
[cms@ip-redacted cms]$ drush state:get update.last_check

[cms@ip-redacted cms]$ drush state:get update.last_email_notification

```

Can you help me understand in which circumstances we might encounter issues from not calling `_va_gov_db_uninstall_modules()`?

**Comment by swirtSJW** [comment]
That is an interesting proof that this method is no longer needed.  It use to be that if you disable a module with config, it would still show as needing an uninstall here
image

But it looks like that issue is no longer a thing.  I'll  make a note to mark that function as depricated and update our documentation on it.   Good find Nate.

**Comment by ndouglas** [comment]
Maybe a core bug that got fixed 🎉

**Review by swirtSJW — APPROVED** [review]

**Comment by swirtSJW** [comment]
image

**Comment by swirtSJW** [comment]
Resulted in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10657

**Pull request merged**
