### PR TITLE
VACMS-6317: Enable style guide for auth and anon users.

### LINKED ISSUE #6317: Enable styleguide module and page for vagovadmin theme
## User Story or Problem Statement

As a designer, i can see the vagovadmin theme's default styles all in one place.

## Acceptance Criteria
- [ ] Styleguide is visible at /admin/appearance/styleguide/vagovadmin to anon users

## Implementation steps
- [ ] install enable styleguide module
- [ ] Set permissions to anon

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

### PR DESCRIPTION
**Pull request by kevwalsh**
## Description

Resolves #6317. 

## Testing done

phpunit, manual.

## Screenshots

VA_gov_Admin_Theme___Veterans_Affairs

## QA steps

As anon verify that you can go to admin/appearance/styleguide/vagovadmin

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by ethanteague — DISMISSED** [review]
Niiiiiiiicccccceeee.
:+1:

**Review by swirtSJW — APPROVED** [review]

**Comment by swirtSJW** [comment]
Composer conflict.   Will need a `lando composer update --lock`

**Comment by swirtSJW** [comment]
I just resolved the conflict.   Waiting on tests to run.

**Review by swirtSJW — DISMISSED** [review]

**Comment by swirtSJW** [comment]
Tests seem to be stuck.  They have been running for 3 hrs now.

**Comment by swirtSJW** [comment]
Looks like an odd but related failure  Looking into this now.
```
                                                                              
  In ConfigImportCommands.php line 359:                                        
                                                                               
                                                                               
    The import failed due to the following reasons:                            
                                                                               
    Unable to install the <em class="placeholder">styleguide</em> module sinc  
  e                                                                            
    it does not exist.                
```

**Comment by swirtSJW** [comment]
Looks like my conflict resolution was bad.  I just fixed it.   Waiting on tests to run.

**Review by swirtSJW — APPROVED** [review]

**Pull request merged**
