### PR TITLE
VACMS-12630: Test READ-COMMITTED database setting.

### LINKED ISSUE #12630: Test READ-COMMITTED database transaction isolation level.
## Description
Edmund found [this article](https://www.drupal.org/docs/system-requirements/setting-the-mysql-transaction-isolation-level), Daniel vouched for its efficacy, it sounds like it'd prevent some test failures, let's check it out 😎 

## Acceptance Criteria
- [ ] READ-COMMITTED transaction isolation setting has been tested in a PR, perhaps by looping over the test suite 20-50 times or something.
- [ ] Either it gets approved and committed or rejected.

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

Closes #12630.

```
$ tugboat shell 63efae3b63b3e8775eb89002
root@php:/var/lib/tugboat# query="show variables WHERE Variable_name LIKE '%_isolation'";drush eval "print_r(\Drupal::database()->query(\"$query\")->fetchAll());"
Array
(
    [0] => stdClass Object
        (
            [Variable_name] => tx_isolation
            [Value] => READ-COMMITTED
        )

)
```

Note that using `drush sqlq` to query the variable directly gives a misleading answer.

Gotta run tests again.

### CODE REVIEW

**Comment by ndouglas** [comment]
This actually isn't having an effect -- this needs to be done from the DevOps side, I believe.  Closing.

**Comment by ndouglas** [comment]
Gonna play with this a little more.

**Comment by ndouglas** [comment]
No test failures are resulting from deadlocks; they all are due to random test failures, issues with tests not being idempotent, etc.

**Review by edmund-dunn — APPROVED** [review]
Nicely done!

**Pull request merged**
