### PR TITLE
VACMS-4823 Update vet center migration to lookup parent by id.

### PR DESCRIPTION
**Pull request by swirtSJW**
## Description

See _issueid_. 

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by swirtSJW** [comment]
The issue was that the parent value on the entity generate accepts a term id not a term name.  190 should have been the value.  Not the term name.  Fixing this was stymied by this little bit of annoying magic here in migrate_plus 's entity generate  process plugin 
image
It makes it impossible to pass in '190' directly.  You can only pass it in via a constant or row field.

**Comment by swirtSJW** [comment]
This PR fixes it and will require a manual process that I will repair all the issues that were created on prod today.
1. delete all existing terms by deleting their  temporary parent containers.
2. roll back the mobile vet center migration
3. run the vet center migration with an update flag.  (this will recreate all the sections terms under "Vet Centers")
4. run the mobile vet center migration
5. delete the mobiles hiding in vet centers
5. run the outstation migration
6. delete the oustations hiding in vet centers as you copy their status to the new outstation.

@kevwalsh @kaise-lafrai

**Comment by mchelen-gov** [comment]
@swirtSJW ty for the amazing work tracking this down! what an "interesting" result :sweat_smile: 

any idea why it behaved differently on staging, or how we can catch this kind of problem in lower envs?

**Comment by swirtSJW** [comment]
@mchelen  It was totally on me.  I had caught it on QA in the lower environments  more than a sprint ago and it was then fixed and  working at that point.   Somewhere along the line we had a regression and I did not re-QA that particular aspect.  In the final QA.

**Pull request merged**
