### PR TITLE
VACMS-3923: Limit qa's in FAQ panel to 10.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #3923 

## Testing done
Visual / behat

## Screenshots
image

## QA steps
- As an administrator, go to `/node/15051/edit` and open the FAQs panel.
- Visually verify that the `Add Q&A` button does not appear.
- Remove one Q&A paragraph, and visually verify that the `Add Q&A` button does appear.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by indytechcook** [comment]
Could this be done as a field config?

Hi ethan!

**Comment by ethanteague** [comment]
> Could this be done as a field config?
> 
> Hi ethan!
Howdy @indytechcook ! Sadly, trying to do this with config results in a really gnarly layout - whenever you set a limit to a certain number, you end up with an initial display of the max number.

**Comment by acrollet** [comment]
@kevwalsh @indytechcook @ethanteague Since this is a pattern for us, should we look at whether [Field Limiter](https://www.drupal.org/project/field_limiter) would meet our use case? The module is simple, has clean code and would reduce our tech debt. (assuming it works the way we need)

**Comment by indytechcook** [comment]
I do like the approach of using field formatted as it's much more Drupal.  The downside is that it adds 2 dependant modules in Field Limiter and Field Formatter. But I think it will give us more flexibility going forward.

**Comment by acrollet** [comment]
The other advantage is less custom js functionality to re-validate as we're looking to change themes in the relatively near future.

**Review by swirtSJW — DISMISSED** [review]

**Comment by swirtSJW** [comment]
@ethanteague  can you rework this with method @indytechcook  and @acrollet are suggesting.

**Comment by ethanteague** [comment]
> @ethanteague can you rework this with method @indytechcook and @acrollet are suggesting.

:+1:

**Comment by ethanteague** [comment]
@indytechcook @acrollet @swirtSJW field_limiter only works for node display output (module doesn't have logic for form mode). Unless we patch it, it won't meet our use case.

**Comment by acrollet** [comment]
@ethanteague oh shoot, sorry for the rabbit trail :-\ I did just find this module which might do what we actually want, although I don't like the code quite as well: https://www.drupal.org/project/limited_field_widgets

Probably for expediency we should go with the js solution and create a follow-on to have a unified long-term solution for this use case.

**Comment by ethanteague** [comment]
> @ethanteague oh shoot, sorry for the rabbit trail :-\ I did just find this module which might do what we actually want, although I don't like the code quite as well: https://www.drupal.org/project/limited_field_widgets
> 
> Probably for expediency we should go with the js solution and create a follow-on to have a unified long-term solution for this use case.

@acrollet limited_field_widget seems pretty legit to me - I just pushed a new commit that uses it / updated config in place of my previous js commit, as well as the other instance in clp where we were using js to limit adding more than 3 paragraphs in the spotlight panel.
cc: @indytechcook @swirtSJW

**Review by indytechcook — APPROVED** [review]
Looks Good.  I went to the node in question and wasn't able to add any more.  I remove one and the new button appeared and worked as expected.

**Review by swirtSJW — APPROVED** [review]
Nice pivot @ethanteague

**Pull request merged**
