### PR TITLE
VACMS-12664: invalid html when adding benefit hub contacts v2

### PR DESCRIPTION
**Pull request by dsasser**
## Description

Relates to #12664

## Testing done
Tested various entity types using the affected paragraph including checklists and R&S pages.

## Screenshots
Screenshot 2024-02-01 at 1 17 45 PM
Screenshot 2024-02-01 at 1 17 22 PM

## QA steps
As a content admin
1. Visit /resources/test-registry-exam-checklist
   - [ ] Under 'Contact Information', validate the label 'VA health care' is not wrapped in a `<ul>`
2. Visit /resources/getting-a-gi-bill-extension
   - [ ] Under 'Contact Information', validate the label 'VA health care' is not wrapped in a `<ul>`

### Definition of Done

- [x] Documentation has been updated, if applicable.
- [x] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [x] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.
- [x] If there are field changes, front end output has been thoroughly checked.

### Select Team for PR review

- [ ] `CMS Team`
- [x] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### CODE REVIEW

**Comment by dsasser** [comment]
@laflannery I had to open a new PR for this, and it is ready to QA. Thank you!

**Comment by laflannery** [comment]
@dsasser I validated the 2 QA items above and those look good, however there was a second part of the original ticket not mentioned in the QA steps, I'm not sure if that was addressed?

Ideally the bullets should also be a valid list and while the markup has changed a bit, they are now 5 individual divs with a `<ul>` inside that div, are we able to make this 1 list element?
image

**Comment by dsasser** [comment]
> @dsasser I validated the 2 QA items above and those look good, however there was a second part of the original ticket not mentioned in the QA steps, I'm not sure if that was addressed?
> 
> Ideally the bullets should also be a valid list and while the markup has changed a bit, they are now 5 individual divs with a `<ul>` inside that div, are we able to make this 1 list element? image

@laflannery yes we can do that!

**Comment by dsasser** [comment]
> > @dsasser I validated the 2 QA items above and those look good, however there was a second part of the original ticket not mentioned in the QA steps, I'm not sure if that was addressed?
> > Ideally the bullets should also be a valid list and while the markup has changed a bit, they are now 5 individual divs with a `<ul>` inside that div, are we able to make this 1 list element? image
> 
> @laflannery yes we can do that!

@laflannery these changes have been made and are ready for re-testing. Thanks!

**Review by laflannery — APPROVED** [review]
This looks great! Thank you @dsasser

**Pull request merged**
