### PR TITLE
VAGOV-2022 Update build trigger to use new job & internal VAEC IP for DEV box.

### PR DESCRIPTION
**Pull request by ElijahLynn**

### CODE REVIEW

**Comment by ElijahLynn** [comment]
still testing this, something is wrong with it, don't merge

**Comment by ElijahLynn** [comment]
rebuild

**Comment by mbenziane** [comment]
Created an environment devops-vagovcms#pr-271<br><br> [button_visit-site](http://internal-devops-vagovcms-3737-289452545.us-gov-west-1.elb.amazonaws.com)

**Comment by mbenziane** [comment]
Created an environment devops-vagovcms#pr-271<br><br> [button_visit-site](http://internal-devops-vagovcms-3354-674950611.us-gov-west-1.elb.amazonaws.com)

**Comment by mbenziane** [comment]
Created an environment devops-vagovcms#pr-271<br><br> [button_visit-site](http://internal-devops-vagovcms-3588-976382172.us-gov-west-1.elb.amazonaws.com)

**Comment by ElijahLynn** [comment]
rebuild

**Comment by mbenziane** [comment]
Created an environment devops-vagovcms#pr-271<br><br> [button_visit-site](http://internal-devops-vagovcms-3564-2113382758.us-gov-west-1.elb.amazonaws.com)

**Comment by ElijahLynn** [comment]
The config for permissions didn't get imported, I think I need to merge in latest develop with a previous revert in it.

**Comment by mbenziane** [comment]
rebuild

**Comment by mbenziane** [comment]
Created an environment devops-vagovcms#pr-271<br><br> [button_visit-site](http://internal-devops-vagovcms-3792-489000360.us-gov-west-1.elb.amazonaws.com)

**Comment by mbenziane** [comment]
Created an environment devops-vagovcms#pr-271<br><br> [button_visit-site](http://internal-devops-vagovcms-3728-1600423974.us-gov-west-1.elb.amazonaws.com)

**Comment by mbenziane** [comment]
Created an environment devops-vagovcms#pr-271<br><br> [button_visit-site](http://internal-devops-vagovcms-3202-396790422.us-gov-west-1.elb.amazonaws.com)

**Comment by ElijahLynn** [comment]
rebuild

**Comment by ElijahLynn** [comment]
I manually changed:
* ENVIRONMENT_TYPE=dev,stg,prod
* JENKINS_BUILD_ENV=dev,staging,prod

To test this for each ENV, I killed the apache process (underneath PID 1) and ran `sh -c a2enmod rewrite && apache2-foreground` and it runs just long enough I can test the build trigger. Before it gets a SIGWINCH.

**Comment by mbenziane** [comment]
Created an environment devops-vagovcms#pr-271<br><br> [button_visit-site](http://internal-devops-vagovcms-3883-345153809.us-gov-west-1.elb.amazonaws.com)

**Comment by ElijahLynn** [comment]
DEV and STAGING needed `cmsEnvBuildOverride`, tested with new param for DEV. 

image

**Pull request merged**
