### PR TITLE
VAGOV-000: Speed up composer with zaporylie/composer-drupal-optimizat…

### PR DESCRIPTION
**Pull request by kevwalsh**
…ions.

### CODE REVIEW

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-139<br><br> [button_visit-site](http://pr-139.va.agile6.com)

**Comment by andyhawks** [comment]
rebuild

**Comment by andyhawks** [comment]
rebuild

**Comment by ElijahLynn** [comment]
rebuild

**Comment by ElijahLynn** [comment]
build

**Comment by mbenziane** [comment]
build

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-139<br><br> [button_visit-site](http://pr-139.va.agile6.com)

**Pull request merged**
