### PR TITLE
VACMS-13768: Updates method name after namespace change

### LINKED ISSUE #13768: Force queue of VetCenter Facilities does not include all Outstations, mobiles or CAPS.
## Describe the defect
When we force queue VetCetner facilities for a bulk push to lighthouse, it is only doing VetCenters and is not doing outstations, mobiles or CAPs (should not be pushing caps now, but once CAPS are in Facility API we neeed to).
image

All the logic lives here modules/custom/va_gov_post_api/src/Form/VaGovFacilityForceQueueForm.php

## To Reproduce
1. visit https://prod.cms.va.gov/admin/config/va-gov-post-api/facility-force-queue
2. Notice that only Vet Cetnters are counted here.  (code was not updated when we split vet centers into 3 types)

## AC / Expected behavior
- [ ] I expect that when I visit the force queue page, there are options for Outstations, VC mobile ~, and CAPs~
- [ ] I expect that the Outstation and mobile options force queue nodes in all states except archived.
- [ ] ~I expect that the CAPs option  only force queuing PUBLISHED CAPs.  (node status = 1) Because they do not exist in the facility API until they are published in the CMS.~ CAPs need to wait for #13777, per @swirtSJW on [Slack](https://dsva.slack.com/archives/C0FQSS30V/p1687893324053059?thread_ts=1687886741.775019&cid=C0FQSS30V).
- [ ] ~I expect that the CAPs option clearly indicates that it is only force queuing PUBLISHED CAPs.~ 

## Screenshots
image

### PR DESCRIPTION
**Pull request by omahane**
## Description

Relates to #13768 

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by omahane** [comment]
@swirtSJW Just making that namespace change resulted in some warnings. I committed anyway with `-n` just to get this up to show you.
Screen Shot 2023-06-16 at 10 52 51 AM

I think the solution for entityQuery is to create a custom service, but I'm not sure if that's overkill to avoid the warning. Maybe not. We do have 21 uses of `\Drupal::entityQuery` throughout several modules. I assume these were used before the use of static Drupal functions was discouraged. 

Screen Shot 2023-06-16 at 10 57 26 AM

**Review by swirtSJW — APPROVED** [review]

**Comment by swirtSJW** [comment]
@omahane The issue you raise is a bit of overkill .   We can ignore those for now.

**Comment by swirtSJW** [comment]
@omahane I am going to merge this because I need to be able to force push.  I know it is incomplete as to the other tasks in the issue so I will not let it close the issue.

**Review by swirtSJW — APPROVED** [review]
Approving this as we need the fix.  It is incomplete as to the other items in the issue, but it solves our current bug.

**Comment by swirtSJW** [comment]
image

**Pull request merged**
