### PR TITLE
VACMS-1797 Security update SA-CORE-2020-002

### PR DESCRIPTION
**Pull request by swirtSJW**
## Description

See #1797  

## QA steps

As admin
1. Login and visit /admin/reports/status
- [ ] Validate that site is running 8.8.6
2. Bounce around on the site to several content pages then visit /admin/reports/dblog
- [ ] Validate that there are not a bunch of new errors or notices tied to the update.
3. Edit a node with a WYSWIG: visit /node/2450/edit
4.  Edit one of the WYSIWYG paragraphs in the main content section. then save the node.
5 Validate that the change worked.
6. Edit a node with draggable paragrapsh: visit /node/2450/edit
7. Drag the the bottom paragraph in the main content section to the top of the section and save the node.  
- [ ] validate that the bottom content now appears as the top of the section.
9. Create a site_alert here /admin/config/system/site-alerts and set an expiry time a minute or two in the future
- [ ] validate that the alert appears. 
- [ ] stay on the page and validate that the alert disappears when the time has past. (polls every 30 seconds)
10. Visit a node edit page /node/716/edit
- [ ] Open your browser console and validate there are no js errors.

### CODE REVIEW

**Comment by indytechcook** [comment]
@swirtSJW do we want to create a follow up issue to create these tests?

**Comment by indytechcook** [comment]
I got the following when running `composer install`.  I'm going to try `composer nuke` then run it again

```
  - Applying patches for drupal/core
    https://www.drupal.org/files/issues/drupal-core-allow-menu-items-to-link-to-unpublished-2807629-7-8.3.x.patch (2807629 - Allow menu items which link to unpublished nodes to be selected in the parent item selector)
    https://www.drupal.org/files/issues/2020-01-07/2893933-34.patch (2893933 - claimItem in the database and memory queues does not use expire correctly)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2020-01-07/2893933-34.patch
    https://www.drupal.org/files/issues/2019-09-11/3057267-maintenance-forced-logout-experimental.patch (3057267 - User logout during maintenance mode)
    https://www.drupal.org/files/issues/2869592-remove-update-warning-7.patch (2869592 - Disabled update module shouldn't produce a status report warning)
    https://www.drupal.org/files/issues/2019-11-27/2815221-125.patch (2815221 - Add quickedit to the latest-revision route)
    https://www.drupal.org/files/issues/2019-11-05/1356276-531-8.8.x-4.patch (1356276 - Allow profiles to define a base/parent profile and load them in the correct order)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2019-11-05/1356276-531-8.8.x-4.patch
    https://www.drupal.org/files/issues/2018-07-09/2914389-8-do-not-test.patch (2914389 - Allow profiles to exclude dependencies of their parent)
```

**Comment by indytechcook** [comment]
I looked in devshop and it does not show the logs for composer:

http://devshop.cms.va.gov/node/31996

```
cd /var/aegir/projects/cms/pr1804 && composer install --no-interaction --no-progress --no-dev --ansi
```

**Comment by indytechcook** [comment]
Odd lando behavior on this branch:

```
~/code/va/va.gov-cms VACMS-1797-drupal-SA-CORE-2020-002* 5m 1s
❯ composer nuke
> rm -rf bin node_modules docroot/libraries docroot/core docroot/modules/contrib docroot/themes/contrib docroot/profiles/contrib/ docroot/vendor /var/www/.cache/yarn
> composer clear-cache
Clearing cache (cache-vcs-dir): /Users/neil.hastings-a/.composer/cache/vcs
Clearing cache (cache-repo-dir): /Users/neil.hastings-a/.composer/cache/repo
Clearing cache (cache-files-dir): /Users/neil.hastings-a/.composer/cache/files
Clearing cache (cache-dir): /Users/neil.hastings-a/.composer/cache
All caches cleared.

~/code/va/va.gov-cms VACMS-1797-drupal-SA-CORE-2020-002* 18s
❯ lando composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 320 installs, 0 updates, 0 removals


  [RuntimeException]
  /app/docroot/vendor does not exist and could not be created.
```

**Comment by indytechcook** [comment]
After upgrade lando and rebuiliding everything works fine, including patching drupal.

**Comment by indytechcook** [comment]
@swirtSJW 

All of the tests pass as you stated.

Got the following errors when updating the content of a paragraph on the following steps:

> Edit a node with a WYSWIG: visit /node/2450/edit
> Edit one of the WYSIWYG paragraphs in the main content section. then save the node.
> 5 Validate that the change worked.
> Edit a node with draggable paragrapsh: visit /node/2450/edit
> Drag the the bottom paragraph in the main content section to the top of the section and save the node.

```
Warning: Creating default object from empty value in Drupal\menu_link_content\Plugin\Menu\MenuLinkContent->updateLink() (line 237 of core/modules/menu_link_content/src/Plugin/Menu/MenuLinkContent.php).
Warning: Creating default object from empty value in Drupal\menu_link_content\Plugin\Menu\MenuLinkContent->updateLink() (line 237 of core/modules/menu_link_content/src/Plugin/Menu/MenuLinkContent.php).
Warning: Creating default object from empty value in Drupal\menu_link_content\Plugin\Menu\MenuLinkContent->updateLink() (line 237 of core/modules/menu_link_content/src/Plugin/Menu/MenuLinkContent.php).
Warning: Creating default object from empty value in Drupal\menu_link_content\Plugin\Menu\MenuLinkContent->updateLink() (line 237 of core/modules/menu_link_content/src/Plugin/Menu/MenuLinkContent.php).
```

I'm not sure these are related, I know @oksana-c fixed this at one time.

**Comment by swirtSJW** [comment]
@indytechcook I am seeing those same warnings on prod currently so I do not think they are related to this update.
image

**Comment by indytechcook** [comment]
I think #1645 is related to fix this message.

**Pull request merged**
