### PR TITLE
VAGOV-000: Adding file download field to staff profile content type.

### PR DESCRIPTION
**Pull request by ethanteague**
**ABOUT**
Relates to https://va-gov.atlassian.net/browse/VAGOV-5022
I thought I could fake the bio by grabbing text and generating pdf with js library. Decided too many unknowns. This approach allows for a user to upload a pdf to drupal file system, which we can path to on frontend with graphql.

### CODE REVIEW

**Comment by kevwalsh** [comment]
Yeah this definitely needs to be boring download PDF field.

**Comment by kevwalsh** [comment]
rebuild

**Comment by andyhawks** [comment]
rebuild

**Comment by kevwalsh** [comment]
Looks great to me! Thanks for taking the time to configure the form.

**Pull request merged**
