### PR TITLE
VACMS-15901: Removes facilities not in user sections

### PR DESCRIPTION
**Pull request by omahane**
## Description

Relates to #15901
Relates to #15391
Relates to #7538
Relates to #12737
Relates to #15906

## Testing done
Manually
Cypress

### VBA Facility Service (intended content type)
Screenshot 2024-01-08 at 1 12 43 PM

### Events (an affected content type)
Screenshot 2024-01-05 at 3 34 57 PM

### What needs to be checked to prove this works?

- [x] Create facility service as editor in Cheyenne VA Regional Benefit Office
  - [x] Log in as "test_Chanelle18"
  - [x] Create a [VBA Facility service](https://pr16663-qymzgx6nhcrlbdd8ahjuxg5xqw6l4sff.ci.cms.va.gov/node/add/vba_facility_service) 
  - [x] Confirm that the **Facility** dropdown only shows facilities in the "Cheyenne VA Regional Benefit Office" section
  - [x] Choose "VA Regional Benefit Satellite Office at Sheridan VA Medical Center" from the **Facility** dropdown
  - [x] Choose "Home Loans" from the **Service name** dropdown
  - [x] Save the node
  - [x] Log out
- [x] Edit facility as editor in Cheyenne and Columbia sections
  - [x] Log in as "test_Lucy.Abernathy30" 
  - [x] Edit the "Home loans" service you just created
  - [x] Confirm that the **Facility** dropdown only shows facilities in the Cheyenne and Columbia sections

### What needs to be checked to prove it didn't break any related things?

- [x] Spot-check one content type for each of the winnowed fields
  - [x] Create an Event (to check `field_listing`)
    - [x] Log in as "QA Content Publisher," an editor in only one section
      - [x] Create an [event](https://pr16663-qymzgx6nhcrlbdd8ahjuxg5xqw6l4sff.ci.cms.va.gov/node/add/event)
      - [x] Confirm that you can only choose a facility in the user's section from the **Where should the event be listed?** dropdown.
    - [x] Log in as "Victor.A.MCtest," an editor in the "Outreach hub" and other sections
    - [x] Create an [event](https://pr16663-qymzgx6nhcrlbdd8ahjuxg5xqw6l4sff.ci.cms.va.gov/node/add/event)
      - [x] Confirm that you can only choose a facility in the user's sections or "Outreach and events: outreach events" from the **Where should the event be listed?** dropdown.
  - [x] Create a VAMC Facility Health Service (to check `field_facility_location`)
    - [x] As Victor.A.MCtest, create a [VAMC Facility health service](https://pr16663-qymzgx6nhcrlbdd8ahjuxg5xqw6l4sff.ci.cms.va.gov/node/add/health_care_local_health_service)
    - [x] Confirm that you can only choose a facility in one of the user's sections from the **Facility** dropdown.
  - [x] Create a VAMC Detail Page (to check `field_office`)
    - [x]  As Victor.A.MCtest, create a [VAMC Detail Page](https://pr16663-qymzgx6nhcrlbdd8ahjuxg5xqw6l4sff.ci.cms.va.gov/node/add/health_care_region_detail_page).
    - [x] Confirm that you can only choose a VAMC system in one of the user's sections from the **Related office or health care system** dropdown.

Testing Google spreadsheet:
https://docs.google.com/spreadsheets/d/17WXvo_QAPvB02Xlm0_np1uQWy83u3dbfJnRxAQdG_h0/edit#gid=0

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.
- [ ] If there are field changes, front end output has been thoroughly checked.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [x] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### CODE REVIEW

**Comment by jilladams** [comment]
Tested as 3 different editors who have multiple section permissions: 2 that have 1 VAMC + Outreach Hub, and 1 that has 2 VAMC sections. In all 3 cases, the Section options match the Event listing options, and Event saved correctly. Just requested a content release for kicks, but the FE shouldn't have anything to do with the change here. So: LGTM.

The events I made: 

https://pr16663-qymzgx6nhcrlbdd8ahjuxg5xqw6l4sff.ci.cms.va.gov/northeast-ohio-health-care/events/64718
Screenshot 2024-01-08 at 2 56 59 PM
* VA NE Ohio & Outreach Hub Sections
* Published to Outreach Hub also

https://pr16663-qymzgx6nhcrlbdd8ahjuxg5xqw6l4sff.ci.cms.va.gov/northern-arizona-health-care/events/64719
Screenshot 2024-01-08 at 3 08 10 PM
* VA Northern Arizona & Outreach Hub Sections

https://pr16663-qymzgx6nhcrlbdd8ahjuxg5xqw6l4sff.ci.cms.va.gov/bedford-health-care/events/64720
* VA Bedford & VA Boston Sections

**Comment by jilladams** [comment]
Added "Relates to" in ticket body to all the tickets we think we might be solving here. Each'll need to be verified by the relevant team, but this'll help with paper trail.

**Review by swirtSJW — APPROVED** [review]
This tests out flawlessly and code is precise.  Great work @omahane 
image

**Comment by swirtSJW** [comment]
image

**Pull request merged**
