### PR TITLE
[docs] VACMS-9084: Created content-audit.md issue template for PW team

### PR DESCRIPTION
**Pull request by allisonlu**
## Description

Relates to #9084: [Content Support](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9084)

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by allisonlu** [comment]
cc: @jilladams @wesrowe

**Comment by wesrowe** [comment]
This looks good to me, except "assignees" is blank – I'm guessing that this should notify someone (Wes or Jill) when an issue is created. Otherwise it could very easily fall through the cracks.

**Comment by jilladams** [comment]
@wesrowe I checked across templates and in most cases, assignee is blank. The instructions note to ping you and me in slack when the issue is created, and that seemed like a useful paradigm to keep, since we may not be the ones actively processing the issue. But I could be persuaded either direction.

**Comment by jilladams** [comment]
Oh! Except the instructions were on a different PW template, and I didn't add them here. Will find that language and get to Allison to add.

**Comment by jilladams** [comment]
Ok. For context, that instruction to ping in Slack is in the PW intake issue template in the Team repo ([PR](https://github.com/department-of-veterans-affairs/va.gov-team/pull/41742/files?short_path=f8c6a88#diff-f8c6a88c9822227b8d6596a03c402c7aa4e573ddc1cc60cfec2f1eda59197420)).

Looking at that though, I think Wes is right. @allisonlu could you update line 6: 
`assignees: jilladams, wesrowe`

**Review by jilladams — APPROVED** [review]
Not sure who needs to approve for merge purposes, but this is good from my perspective!

**Review by swirtSJW — APPROVED** [review]

**Pull request merged**
