### PR TITLE
VACMS-1500: Post API Cron killswitch.

### PR DESCRIPTION
**Pull request by oksana-c**
## Description

See #1500. 

Adds "Pause processing on Cron" configuration option to Post API

## QA steps

- [x] as an admin, visit /admin/config/post-api/config and confirm "Pause processing on Cron" configuration option is available in a form of a checkbox
- [x] leave checkbox unchecked; add item to queue; remove sandbox creds if you have them locally; clear cache; run cron `lando drush cron`, confirm the queue is being processed and you get log messages from post api
- [x] check the checkbox to pause processing on Cron; run cron; confirm the queue is not processed by verifying that there are no new log messages in dblog 
- [x] process queue manually. Confirm manual queue processing is not affected by the new config option.

## Definition of Done
- [ ] Product release notes 
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

### CODE REVIEW

**Comment by swirtSJW** [comment]
Manual QA passes 
image

**Comment by swirtSJW** [comment]
Behat and phpunit tests are unrelated.

**Comment by swirtSJW** [comment]
Pulls in this issue from contrib https://www.drupal.org/project/post_api/issues/3127328

**Comment by ElijahLynn** [comment]
Worth noting this was hit by the deadlock issue:
> Caused by
PDOException: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction

**Comment by swirtSJW** [comment]
Closing this as the kill switch version was brought in with this pr that was just merged https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1638

**Pull request closed without merging**
