### PR TITLE
VACMS-8956: Add new covid status taxonomy.

### LINKED ISSUE #8956: Add covid status vocabulary
To maintain the source of truth for the covid status IDs and description we need a covid status vocabulary created

## ACs
- Vocabulary "Facility Supplemental Status" (facility_supplemental_status)
   - [x]  Description "Supplemental statuses to be used with facilities."
   - Fields
      - [x] term title   "Visible title of the status ie: Covid-Red"
      - [x] field_description  "Veteran facing text to use when a this status appears." full html  - no length limit
      - [x] field_guidance "Editor facing guidance on when to use this status." limited html  - some length limit  (talk to Kauff)
      - [x] field_status_id "Identifier for this status that will never change.  ie. covid_red"  This will eventually be locked to all but true admins. 
      - [x] field_administration entity reference for section ownership.
    - Perms
       - [ ]  Should respect workbench moderation section ownership 
       - [ ] identical to health_care_service_taxonomy

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
closes #8956

## Testing done
Visual / behat

## Screenshots
Vocabulary listing view
image

Form view
image

Node view
image

## QA steps
 - [x] As an administrator, go to `/admin/people/pfm-permissions` and select Taxonomy from modules, and all roles. Search page for `Facility Supplemental ` and visually verify only administrator can perform any operations (matches health_care_service_taxonomy perm scheme)
 - [x] As an administrator, go to https://pr8963-5dpcxs15ghurgq2tqdxjf19lclvte3h7.ci.cms.va.gov/admin/structure/taxonomy/manage/facility_supplemental_status/add and add a term
 - [x] Visually verify form matches screenshot, above
 - [x] Fill in all fields, and visually verify node view experience is in line with screenshot, above
 -  Go to https://pr8963-5dpcxs15ghurgq2tqdxjf19lclvte3h7.ci.cms.va.gov/admin/structure/taxonomy/manage/facility_supplemental_status/add

 and add a new term but use the same status ID you used in the first term. 
- [x] Validate that a validation error warns of a repeated id and prevents save
 image

### CODE REVIEW

**Review by swirtSJW — APPROVED** [review]
This all looks good Ethan.  Thank you.

Did this size come from Kauff?
image

If the limit is approved we probably want a counter, but we can switch widgets later.

**Comment by swirtSJW** [comment]
Just double checking the size limit on the guidance field.

**Comment by ethanteague** [comment]
Apologies, @swirtSJW , I didn't reach out to @rachel-kauff for guidance. My work was suffering today.

**Comment by swirtSJW** [comment]
No worries man.  I reached out to [Kauff here](https://dsva.slack.com/archives/C0FQSS30V/p1651790689321969) will discuss more an finalize in the AM

**Comment by swirtSJW** [comment]
I just rewired a couple fields and updated behat to come from spec.   Spec has been updated.

**Review by swirtSJW — APPROVED** [review]
QA steps all pass.

**Pull request merged**
