### PR TITLE
VACMS-7551: permissions updates for non-clinical services and top tas…

### LINKED ISSUE #7551: VAMC content creators should be able to create VAMC facility non-clinical services
## User Story or Problem Statement

As a VAMC editor, i should be able to create VAMC facility non-clinical services

## Acceptance Criteria
- [x] As  james.hoehn2@va.gov, i can go to /node/add/ and i see VAMC facility non-clnicial service as an option. 
- [x] Automated tests pass
- [ ] PR is merged close to the day we roll out the new top task pages

## Implementation steps
- [ ] Update permissions and automated tests

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected.
- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by JayDarnell**
…k pages

## Description

Closes #7551 

## Testing done

Manual/Visual testing

## Screenshots

Screen Shot 2022-01-21 at 1 57 19 PM

Screen Shot 2022-01-21 at 1 57 49 PM

Screen Shot 2022-01-21 at 1 58 34 PM

Screen Shot 2022-01-21 at 1 58 50 PM

## QA steps

As user james.hoehn2@va.gov with role: **Content creator - VAMC**

- [x] Visit /node/add/ and see VAMC facility non-clinical service as an option
- [x] Visit /node/42275/edit and click on the **Add location (opens in a new window)** link - verify the page loads and you are able to add a new non-clinical service
- [x] Visit /node/42275/edit and click on the **Edit location (opens in a new window)** link - verify that you are able to modify and save changes to the existing non-clinical service

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [x] `DO NOT MERGE`

### CODE REVIEW

**Comment by kevwalsh** [comment]
in slack, @swirtSJW said these are too broad, but i'm not sure what he meant. 

here are the issues i see. 
<details><summary>Screenshot</summary>

VACMS-7551__permissions_updates_for_non-clinical_services_and_top_tas…_by_JayDarnell_·_Pull_Request__7705_·_department-of-veterans-affairs_va_gov-cms


</details>

**Comment by JayDarnell** [comment]
Updated to remove the redundancies above. Also, it appears I accidentally included an extra screenshot which showed the status of the edit permissions before I changed them. I removed that screenshot. Now the screenshots above are accurate with the exception of the three redundant checkboxes for the content admin role. Those have been removed in my most recent commit.

**Review by swirtSJW — DISMISSED** [review]
This looks good.  Is it still a draft, or is it good to go?

**Comment by swirtSJW** [comment]
Closing this as it was cherry-picked into https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7421

**Comment by kevwalsh** [comment]
@swirtSJW we can go ahead and merge this now, we need to expose this permission for a beta tester next week.

**Comment by JayDarnell** [comment]
Rebased and good to go

**Review by swirtSJW — APPROVED** [review]
Looks good Jay

**Pull request merged**
