### PR TITLE
VACMS-5596: Enable media standalone URL so that viewing/editing/locking work as expected.

### LINKED ISSUE #5596: Unlocking when editing an image doesn't unlock
**Describe the defect**
When editing an image and going through the unlock process, it takes you back in to editing the image.

**To Reproduce**
1. Go to 'https://prod.cms.va.gov/media/image/4165'
2. Click on 'the unlock button at the bottom of the screen'
3. Click on `Confirm break lock`
4. See that it confirms the lock break but puts you back into the edit screen for the image, which effectively locks it again

**Expected behavior**
Unlocking when editing an image takes you somewhere else, maybe to the media library?

**Screenshots**
image

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

Closes #5596.

Media is currently "edit-only".  You can't just look at an image -- you have to edit it.

Viewing media without editing it can be enabled by checking this checkbox:

Screen Shot 2022-09-08 at 7 57 14 AM

If it's checked, then you can view media.  And, consequently, when you unlock the content that you're editing, you will be redirected to a normal view of the media item.

I think this is the best approach to solving the aggravating problem with content lock on media items.  It doesn't involve any custom code or otherwise add technical debt, and makes handling media more consistent with how we handle nodes.

## Testing done

Verified that I could view media without editing it, and that unlocking a media item I was editing redirected me to the view page for the media item, rather than back to the edit page.

## QA steps

As a user who can edit media items:

1. Visit this page: https://cms-9x4r85kz3xkp6gem8b8wjarqvtiow7lu.ci.cms.va.gov/media/image/4165
  - [ ] Confirm that this is an "Edit" form for the media in question
  - [ ] Confirm that the media is locked: 
Screen Shot 2022-09-08 at 8 07 23 AM
2. Click the "Unlock" button.
3. Click the "Confirm break lock" button.
  - [ ] Confirm that you are at this URL: https://cms-9x4r85kz3xkp6gem8b8wjarqvtiow7lu.ci.cms.va.gov/media/4165
  - [ ] Confirm that you see the media item, but are not _editing_ it.
4. Click the "Edit" button.
  - [ ] Confirm that this is an "Edit" form for the media in question
  - [ ] Confirm that the media is locked: 
Screen Shot 2022-09-08 at 8 07 23 AM

### CODE REVIEW

**Comment by swirtSJW** [comment]
I think preventing viewing media directly was intentional.  If editors could see media entities, they could link to them and in the cms the links would work fine, but would break on the FE.  We might want to revisit this.

**Comment by ndouglas** [comment]
I could add a filter to prevent linking to media view pages, if that's the issue.  It's a simple pattern to catch.

**Comment by ndouglas** [comment]
I went to https://dev.cms.va.gov/ and enabled this option:

Screen Shot 2022-09-12 at 8 49 10 AM

and edited some content to reference an absolute URL to a media page, and received this error:

Screen Shot 2022-09-12 at 8 47 35 AM

As media is not content and excluded from the Linkit matcher, Linkit does not suggest media either based on title terms 

Screen Shot 2022-09-12 at 8 53 25 AM

or the media path

Screen Shot 2022-09-12 at 8 53 40 AM

But I opened #10691 to deal with the possibility that an editor might someday just copy in the path to a media view page.

**Comment by swirtSJW** [comment]
I like how you are thinking Nate.  


i think someone pasting in a /media/123 for a link is definitely something we want to fail on.

**Review by edmund-dunn — APPROVED** [review]
Worked as expected of course!

**Pull request merged**
