### PR TITLE
VAGOV-3157-SMTP-INTEGRATION

### PR DESCRIPTION
**Pull request by mbenziane**
https://github.com/department-of-veterans-affairs/va.gov-cms-devops/pull/75

### CODE REVIEW

**Comment by mbenziane** [comment]
rebuild

**Comment by ElijahLynn** [comment]
Nice, it is working for me! 

Can you make another devops PR to revert the `cms.va.gov` FROM, as it was only set on the devops ENV anyways. And can we set the `www-data` part of it to va-cms-admin@va.gov

**Comment by ElijahLynn** [comment]
Follow up to #357.

**Comment by mbenziane** [comment]
rebuild

**Comment by ElijahLynn** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms-devops/pull/78

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Pull request merged**
