### PR TITLE
VACMS-3263-5040-5041: Improve /admin/people page for user admin.

### PR DESCRIPTION
**Pull request by kevwalsh**
## Description

See #3263 #5040 #5041. (epic #5039)

## Testing done

Manual.

## Screenshots
People___VA_gov_CMS

## QA steps

Helpdesk should perform this QA. 

As an admin

* go to https://pr5212-qn03aywof9kg7zylcur4nyqpt9kuk3xn.ci.cms.va.gov/admin/people
* Filter by various sections. The filter should work as expected (filtering by VISN 4 should show all users with associations to child sections
* Click edit on the Roles column. this should take you to the Roles tab instead of the full user form, which is easier to use.
* Click CSV to export to CSV. it should respect the filters. 

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by swirtSJW — COMMENTED** [review]
The View looks good  and functions perfectly.

I found three issues with the CSV:
1. minor: Edit as a column.
image

2. moderate: roles are joined without delimiter
3. minor: Download has no file extension (.txt or .csv).
image

**Comment by kevwalsh** [comment]
Good catch, thanks @swirtSJW. Latest commit fixes these issues.

**Review by swirtSJW — APPROVED** [review]
Looks great.

**Comment by swirtSJW** [comment]
I just triggered a rebuild in tugboat as it looks like the tests on this stalled out.

**Pull request merged**
