### PR TITLE
VACMS-4871: Switch from Yaml-Tasks to Task (Test PR)

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

See #4871 and #4880.  This branch exists to provide a place to actually test the functionality of Task and Reviewdog as it is implemented.  All of the actual work is gonna get pushed upstream and be merged from #4880, so this specific PR will at some point be closed without merging.

Assuming I know what's going on, which is always up for debate (scholarly and otherwise).

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] P=NP
- [ ] P≠NP
- [ ] etc

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [x] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by ndouglas** [comment]
Screen Shot 2021-03-31 at 4 19 08 PM

f75

**Comment by ndouglas** [comment]
test

**Comment by acrollet** [comment]
> test

**Comment by ndouglas** [comment]
That last comment was posted by `github-commenter` -- it looks like Reviewdog just fails silently if the GH token doesn't have adequate permissions or something along those lines 😭 .  Switched out the GH token in the Tugboat env and it posted that comment successfully.  However, Reviewdog's still failing.

**Comment by ndouglas** [comment]
TEST 2

**Comment by acrollet** [comment]
I couldn't help myself and played with this a bit more. For posterity, the command that worked from tugboat to post these messages was:

```
./bin/phpcs docroot/modules/custom/ --report-checkstyle | ./bin/reviewdog -f="checkstyle" -reporter=github-pr-review -level=warning -fail-on-error=true -filter-mode=nofilter
```

**Comment by ndouglas** [comment]
I feel like I tried all of those in various combinations except `-fail-on-error=true`.

 `-fail-on-error` is not sufficient but `-fail-on-error=true` works?

Ugh.

**Comment by ndouglas** [comment]
I don't think I have a good mental model of under what conditions `reviewdog` will succeed and under which it will fail silently.

But good job!  And thanks again!

**Comment by ndouglas** [comment]
Screen Shot 2021-04-02 at 9 33 02 AM

🎉

**Comment by acrollet** [comment]
> I feel like I tried all of those in various combinations except `-fail-on-error=true`.
> 
> `-fail-on-error` is not sufficient but `-fail-on-error=true` works?
> 
> Ugh.

yeah they definitely don't follow convention for arguments :-\

**Comment by ndouglas** [comment]
Screen Shot 2021-04-02 at 10 13 25 AM

smh

**Comment by ndouglas** [comment]
omg it works

**Comment by ndouglas** [comment]
```
> cd web && NODE_ENV=production yarn build:content --pull-drupal --no-drupal-proxy --buildtype=vagovdev --api=https://dev-api.va.gov --asset-source=$(git rev-parse --verify HEAD)
/var/lib/tugboat/docroot/vendor/va-gov/web/src/site/stages/build/index.js:285
    if (err) throw err;
             ^

Error: HTTP error: 502: Bad Gateway
    at Object.query (/var/lib/tugboat/docroot/vendor/va-gov/web/src/site/stages/build/drupal/api.js:123:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async parallelQuery (/var/lib/tugboat/docroot/vendor/va-gov/web/src/site/stages/build/drupal/api.js:225:22)
    at async Promise.all (index 10)
    at async Object.getAllPagesViaIndividualGraphQlQueries (/var/lib/tugboat/docroot/vendor/va-gov/web/src/site/stages/build/drupal/api.js:284:7)
    at async getContentViaGraphQL (/var/lib/tugboat/docroot/vendor/va-gov/web/src/site/stages/build/drupal/metalsmith-drupal.js:162:19)
    at async loadDrupal (/var/lib/tugboat/docroot/vendor/va-gov/web/src/site/stages/build/drupal/metalsmith-drupal.js:231:7)
    at async Ware.<anonymous> (/var/lib/tugboat/docroot/vendor/va-gov/web/src/site/stages/build/drupal/metalsmith-drupal.js:275:20)
error Command failed with exit code 1.
```

That's the Behat thing, assuming this is a flicker.

**Pull request closed without merging**
