### PR TITLE
VACMS-9483-Adds-Vet-Centers-to-VA-Locator

### LINKED ISSUE #9483: Backend: Vet Centers are not listed as "VA facilities" when adding an Event location
## Describe the defect
As a VAMC Editor, I would like to add an Event to my site that is hosted at a local Vet Center. (Real life example: VA Bedford is hosting an Event at the Lowell Vet Center.)

When adding the Event location and selecting "At a VA Facility," I expect to see Vet Centers listed within the VA facility location dropdown menu. 

However, there are none listed. This does not make any sense, because Vet Centers are clearly VA facilities.

## To Reproduce

1. While adding or editing a VAMC Event page, select **Location type = At a VA facility**
Link: https://prod.cms.va.gov/node/add/event

2. If you start typing a sample word such as “North” within the “Facility Location” field (see screenshot below), the names of various VAMCs will appear within the dropdown menu that follows.

3. However, if you start typing “Vet Center,” there are zero Vet Centers listed. (See screenshot below.)

## Expected behavior
Vet Centers are VA facilities and should therefore be included within the list of possible VA facility locations for Events.

### **Here is what this menu looks like under normal circumstances after typing the word "North":**

Screen Shot 2022-06-15 at 8 42 43 PM

### **However, if you type "Vet Center," there are no Vet Centers listed within this menu:**

Screen Shot 2022-06-15 at 12 57 56 PM

## Tasks
Expose Vet Centers (content type) in the "Where should the event be listed?" field

## Assumptions
1. Events at a Vet Center location must publish to an existing Event list, e.g. for the greater VAMC. Vet Center pages do not show Event lists.
2. Mobile Vet Centers move location, so events related to a Mobile Vet Center should be listed as "At a non-VA location" and address listed where the Mobile Vet Center will be for the event.
3. FE will adapt seamlessly.

## Tasks
- catch up on the how
- confirm assumptions above
- update View
- QA in tugboat
- code review (1 person)
- FE investigation will be handled in another ticket (if needed)

## Acceptance criteria
- [ ] Only Facilities with published nodes are included in Facility Location list
- [x] Vet Center - Mobile Vet Center is **not** included in Facility location list 
- All other facility types in the CMS should be available in the Facility Location select list, including:
  - [x] Vet Center
  - [x] Vet Center - Community Access Point
  - [x] Vet Center - Outstation
  - [ ] NCA Facility
  - [x] VAMC Facility
  - [ ] VBA Facility
- [ ] Include @swirtSJW as code reviewer on your PR
- [ ] Test the FE against the BE changes (consultation with FE engineer baked-in)
 

 ## Additional context
Original Jira ticket: https://va-gov.atlassian.net/browse/VAHELP-4350
Slack thread: https://dsva.slack.com/archives/C0FQSS30V/p1655320252428059

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by chri5tia**
## Description

Closes #9483

## Testing done

- [x] Manual functional testing via local and review instance
- [x] Automated testing via draft PR creation 

## Screenshots

Screen Shot 2022-08-19 at 2 06 16 AM

## QA steps

What needs to be checked to prove this works?  

- [x] Following the steps outlined in #9483 below/check if the front-end works:

Screen Shot 2022-08-19 at 4 17 12 PM

- [x] The event location autocomplete field should include vet center locations.

- [x] Choose a vet center, outstation or cap and validate that each are rendered as something useful on the FE.

Screen Shot 2022-09-01 at 11 18 44 AM

What needs to be checked to prove it didn't break any related things?  

- [x] Check an existing event (I used https://cms-n3knkfbyfpdm6vnolxuf8qpaluwmfz6h.ci.cms.va.gov/node/48830/latest) and see that the Facility Location is still populated. You can select a new one from the content list filtered by events: https://cms-n3knkfbyfpdm6vnolxuf8qpaluwmfz6h.ci.cms.va.gov/admin/content?title=&type=event&moderation_state=All&owner=All
- [x] Change the Facility location to a related Vet Center (In my example I changed from Bangor VA Clinic to Bangor Vet Center), select "Save as Published" and then click Save. Ensure that there are not weird errors and that this event switches cleanly. Then trigger a content release (Content > release content) and find the even on the Front end via https://web-n3knkfbyfpdm6vnolxuf8qpaluwmfz6h.ci.cms.va.gov/

- [x] Create a new event: Content > Add content > Event. Default/NY timezone. "Where should the event be listed: VA Albany health care: Events", Location: At a VA Facility, Facility Location: Albany Vet Center, save as a draft. Then save as published. Ensure there are no Drupal errors or any problems. Ensure that Albany Vet Center is listed as the Facility Location when published.
Screen Shot 2022-08-25 at 12 17 15 PM

Screen Shot 2022-08-25 at 12 17 15 PM

What variations of circumstances (users, actions, values) need to be checked?  

- [x] Different users only control different regional sections. The above test was done under my account. Researching what users are best to use for this and how. [jonathan.barczyk@va.gov](https://cms-n3knkfbyfpdm6vnolxuf8qpaluwmfz6h.ci.cms.va.gov/user/2924) can be used to test Maine region such as the Bangor one above.

- [x]  Plug in the following GraphQL query into the graphQL explorer to make sure that Bangor Vet Center is populated per the node 48830 that I switched locations for:

```
query GetNodeEvents($onlyPublishedContent: Boolean!) {
  nodeQuery(
    limit: 1
    filter: 
    	{conditions: 
        	[
            {field: "status", value: ["1"], enabled: $onlyPublishedContent}, 
      			{field: "type", value: ["event"]}, 
            {field: "nid", value: ["48830"]}
            ]}
  ) {
    entities {
      ... on NodeEvent {
        fieldFacilityLocation {
          entity {
            entityBundle
            entityId
            entityLabel
          }
        }
      }
    }
  }
}
```

Note: I do not see the "Where" being populated for vet centers and believe there is some FE work for this.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.
- [ ] Front-End considerations have been discussed.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [x] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [x] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [x] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by swirtSJW — CHANGES_REQUESTED** [review]
I think this has some issues.   We are letting editors specify facilities like vetcenters which is good, as long as they are published,  However we are also letting them specify VBA and NCA locations that have no FE presence.   So if they choose a cemetery for an event like this
image


The FE builds with no information so the veteran is lost about where to attend the event.
image

This is likely a FE defect, but it needs to be worked out and released in the right order.

**Comment by swirtSJW** [comment]
This PR needs to add a QA step to actually check choosing one of the new facility types and verify that the FE works.

**Comment by chri5tia** [comment]
@swirtSJW I'm concerned that building out the FE part of the VBA and NCA locations may be something that would cause this work to cross over the sprint, however, since adding VBA and NCA seems to have been an after thought for the original work to add vet centers, I could run this by @jilladams for us to cut that as a separate/additional body of work. 

I propose only adding vet centers for this PR, testing that and creating a new ticket for the VBA and NCA, since there isn't (likely) an FE piece to it.

As far as what happens if they add a location that has a node that isn't published, I'll take a look at the view to ensure that only published locations show up in the list. This could have ramifications for existing functionality that I will need to test for e.g. I need to find out where and how this view list is used in any other places.

Thoughts?

**Comment by chri5tia** [comment]
I amended the commit so that it only includes vet centers for now.

**Comment by swirtSJW** [comment]
>  I'm concerned that building out the FE part of the VBA and NCA locations may be something that would cause this work to cross over the sprint, however, since adding VBA and NCA seems to have been an after thought for the original work to add vet centers, I could run this by @jilladams for us to cut that as a separate/additional body of work.

I think that sounds like a good plan if @jilladams is ok with it.

I think limiting the list to only allow published facilities makes sense.  We had it allow draft back when most of the facilities were not published as a way to stage content.  We have moved past that model so I think it makes sense to restrict to only published.


Please add a QA step to choose a vet center, outstation and cap and validate that they get rendered as something useful on the FE.   They should, but our QA culture should not leave it to chance.

Also on these QA steps:

```
What needs to be checked to prove it didn't break any related things?

 See if there is anything else that uses this location autocomplete field that should not include vet centers
What variations of circumstances (users, actions, values) need to be checked?

 That any user with editor privileges can add a vet center as the location of an event.
```

Can you make them less hypothetical and actually be the steps to prove that they don't break anything?  The idea is that anybody on the team should be able to grab a pr and run through the qa steps and get the same results as anyone else.

**Comment by jilladams** [comment]
Cosign - ok to split NCA/VBA into a sep ticket, and merge this. @chri5tia and I will sync about cutting that ticket.

**Comment by chri5tia** [comment]
https://web-n3knkfbyfpdm6vnolxuf8qpaluwmfz6h.ci.cms.va.gov/maine-health-care/events/48830/
Not showing location after changing Bangor VA Clinic to Bangor Vet Center in the content build.

Screen Shot 2022-08-25 at 1 04 06 PM

**Comment by chri5tia** [comment]
Working with Bryan to test our PRs together, we have confirmed that the "where" field now displays the vet centers and this is ready for a review.

Screen Shot 2022-09-01 at 11 18 44 AM

**Review by dsasser — APPROVED** [review]

**Comment by jilladams** [comment]
Front-end PR merged. https://github.com/department-of-veterans-affairs/content-build/pull/1289

**Review by swirtSJW — APPROVED** [review]
Tests out good from FE 
image

**Pull request merged**
