### PR TITLE
VACMS-11495: added content search for content audit

### PR DESCRIPTION
**Pull request by edmund-dunn**
## Description

Relates to #11495.
Relates to #11208.
Relates to #11647.

## QA steps
~Go to Content, and in the content navigation go to Content Audit Tools. Under that you should find a Content Search tab. You can search by keywords like VRRAP, ID.me and Air Force. You can also filter by content type depending on the nature of the audit. ~

- Go to https://pr11706-vs5cfdcsh2vti4crwdkxp7t14onom0hv.ci.cms.va.gov/admin/content/audit/search
- [x] validate that the tab is in the right order (alph order) under Content Audit Tools
- go to [this link](https://pr11706-vs5cfdcsh2vti4crwdkxp7t14onom0hv.ci.cms.va.gov/admin/content/audit/search?keywords=VRRAP&label=&type%5B%5D=banner&type%5B%5D=basic_landing_page&type%5B%5D=campaign_landing_page&type%5B%5D=centralized_content&type%5B%5D=checklist&type%5B%5D=documentation_page&type%5B%5D=event&type%5B%5D=event_listing&type%5B%5D=faq_multiple_q_a&type%5B%5D=full_width_banner_alert&type%5B%5D=health_care_local_facility&type%5B%5D=health_care_local_health_service&type%5B%5D=health_care_region_detail_page&type%5B%5D=health_care_region_page&type%5B%5D=health_services_listing&type%5B%5D=landing_page&type%5B%5D=leadership_listing&type%5B%5D=locations_listing&type%5B%5D=media_list_images&type%5B%5D=media_list_videos&type%5B%5D=nca_facility&type%5B%5D=news_story&type%5B%5D=office&type%5B%5D=outreach_asset&type%5B%5D=page&type%5B%5D=person_profile&type%5B%5D=press_release&type%5B%5D=press_releases_listing&type%5B%5D=promo_banner&type%5B%5D=publication_listing&type%5B%5D=q_a&type%5B%5D=regional_health_care_service_des&type%5B%5D=step_by_step&type%5B%5D=story_listing&type%5B%5D=support_resources_detail_page&type%5B%5D=support_service&type%5B%5D=vamc_operating_status_and_alerts&type%5B%5D=vamc_system_billing_insurance&type%5B%5D=vamc_system_medical_records_offi&type%5B%5D=vamc_system_policies_page&type%5B%5D=vamc_system_register_for_care&type%5B%5D=va_form&type%5B%5D=vba_facility&type%5B%5D=vba_facility_service&type%5B%5D=vet_center&type%5B%5D=vet_center_cap&type%5B%5D=vet_center_facility_health_servi&type%5B%5D=vet_center_locations_list&type%5B%5D=vet_center_mobile_vet_center&type%5B%5D=vet_center_outstation&type%5B%5D=vha_facility_nonclinical_service)
- [x] validate that there are  nodes that show up in the report.
- validate that the View meets the apprproprate ACs from our [Views Style Guide](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1740472321/CMS+Views+Style+Guide).
- [x] Display machinename, not `default` or 'page'
- [x] URL [`/admin/content/{{parent-view-name}}/name-of-view`] /admin/content/audit/content-search
- [x] Menu item setting: Is it where it belongs?
- [x] Limit to 100 per page, paginated
- [x] Show result count in header. (`<p>Displaying @start - @end of @total</p>`)
- [x] Has table caption describing the table
- [ ] Columns
  - [x] Title (sortable) 
  - [x] Edit button (not operations, no heading) 
  - [x] Content type ~(sortable) (if applicable)~
  - [x] Moderation State
  - [x] Section (field_administration) ~(sortable)~
  - [ ] ~Is Locked (optional)~
  - [ ] Last updated (date time and by user) (sortable, default sort, DESC)
  - [ ] [Other content fields as needed] (sortable)
- [ ] Filters
  - [ ] Exposed
    - [x] "Title contains" (text search of title field)
    - [x] "Content type" (single value drop down or multivalue? should options be limited) 
    - [x] "Moderation state"  (single value drop down or multivalue?)
    - [ x] "Section" ~(workbench access section; single select, show children)~ Added:  due to the nature of search api, this is not attainable as a select list./
    - [x] Order of filters matches order of columns
    - [x] Reset button exists
    - [x] Apply button says 'Filter' 
- [x] Tab navigation is alpha sorted or intentionally grouped
- [ ] Not exposed
    - [x] only by relevance

**Added 12/12**
- [ ] vist https://pr11706-vs5cfdcsh2vti4crwdkxp7t14onom0hv.ci.cms.va.gov/admin/content/audit/rich-text-field-audit  validated you are directed from the old view to the new
- [x] validate old "rich text" tab no longer appears under audit.
- [x] visit search for [diabetic care in terms](https://pr11706-vs5cfdcsh2vti4crwdkxp7t14onom0hv.ci.cms.va.gov/admin/content/audit/search?search=diabetic+care&title=&etype_op=or&etype=entity%3Ataxonomy_term&ms=All&published=All&section=)  validate  several terms show up.
   - [x] Click the download csv button validate that it saves a file to your machine.
   - [x] Open it in excell or libreoffice or other spreadsheet.  validate there are the same number of result as the visible view.
   - [x] validate that the edit column contains full urls to prod.
   - [x] validate that the url collumn contains full urls to prod
   - [x] validate that the rows all line up like they are supposed to (no data escaped its colunm)
- [x] Do a [media search for "verterans day"](https://pr11706-vs5cfdcsh2vti4crwdkxp7t14onom0hv.ci.cms.va.gov/admin/content/audit/search?search=veterans+day&title=&etype_op=or&etype=entity%3Amedia&ms=All&published=All&section=)
   - [x] validate that media shows up whose contents contain the search term.
   - [x] validate the edit button takes you to the media edit
   - [x] validate the search excerpt shows up
   - [x] validate the content type column identifies it as media.

added 12/13
- Login as kitty.walsh  
   - [x] Validate that you can see the  https://pr11706-vs5cfdcsh2vti4crwdkxp7t14onom0hv.ci.cms.va.gov/admin/content/audit/search

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by EWashb** [comment]
@edmund-dunn I couldn't get the search to return any results when I searched for VRRAP or ID.me

**Comment by swirtSJW** [comment]
@edmund-dunn can we get the qa steps to be actual steps (like in the template sample)   so that they are  specific enough  to follow and check off.  These should be the same steps you are following before asking others to QA. 

> Go to Content, and in the content navigation go to Content Audit Tools. Under that you should find a Content Search tab. You can search by keywords like VRRAP, ID.me and Air Force. You can also filter by content type depending on the nature of the audit.

Should be more like this

- Go to https://pr11706-vs5cfdcsh2vti4crwdkxp7t14onom0hv.ci.cms.va.gov/admin/content/audit/search
- [ ] validate that the tab is in the right order (alph order) under Content Audit Tools
- go to [this link](https://pr11706-vs5cfdcsh2vti4crwdkxp7t14onom0hv.ci.cms.va.gov/admin/content/audit/search?keywords=VRRAP&label=&type%5B%5D=banner&type%5B%5D=basic_landing_page&type%5B%5D=campaign_landing_page&type%5B%5D=centralized_content&type%5B%5D=checklist&type%5B%5D=documentation_page&type%5B%5D=event&type%5B%5D=event_listing&type%5B%5D=faq_multiple_q_a&type%5B%5D=full_width_banner_alert&type%5B%5D=health_care_local_facility&type%5B%5D=health_care_local_health_service&type%5B%5D=health_care_region_detail_page&type%5B%5D=health_care_region_page&type%5B%5D=health_services_listing&type%5B%5D=landing_page&type%5B%5D=leadership_listing&type%5B%5D=locations_listing&type%5B%5D=media_list_images&type%5B%5D=media_list_videos&type%5B%5D=nca_facility&type%5B%5D=news_story&type%5B%5D=office&type%5B%5D=outreach_asset&type%5B%5D=page&type%5B%5D=person_profile&type%5B%5D=press_release&type%5B%5D=press_releases_listing&type%5B%5D=promo_banner&type%5B%5D=publication_listing&type%5B%5D=q_a&type%5B%5D=regional_health_care_service_des&type%5B%5D=step_by_step&type%5B%5D=story_listing&type%5B%5D=support_resources_detail_page&type%5B%5D=support_service&type%5B%5D=vamc_operating_status_and_alerts&type%5B%5D=vamc_system_billing_insurance&type%5B%5D=vamc_system_medical_records_offi&type%5B%5D=vamc_system_policies_page&type%5B%5D=vamc_system_register_for_care&type%5B%5D=va_form&type%5B%5D=vba_facility&type%5B%5D=vba_facility_service&type%5B%5D=vet_center&type%5B%5D=vet_center_cap&type%5B%5D=vet_center_facility_health_servi&type%5B%5D=vet_center_locations_list&type%5B%5D=vet_center_mobile_vet_center&type%5B%5D=vet_center_outstation&type%5B%5D=vha_facility_nonclinical_service)
- [ ] validate that there are  nodes that show up in the report.
- [ ] validate that the View meets the apprproprate ACs from our [Views Style Guide](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1740472321/CMS+Views+Style+Guide).
- [ ] - [ ] Display machinename, not `default`
- [ ] URL [`/admin/content/{{parent-view-name}}/name-of-view`]
- [ ] Menu item setting: Is it where it belongs?
- [ ] Limit to 100 per page, paginated
- [ ] Show result count in header below any exposed filters. (`<p>Displaying @start - @end of @total</p>`)
- [ ] Has table caption describing the table
- [ ] Columns
  - [ ] Title (sortable) 
  - [ ] Edit button (not operations, no heading) 
  - [ ] Content type (sortable) (if applicable)
  - [ ] Moderation State
  - [ ] Section (field_administration) (sortable)
  - [ ] Is Locked (optional)
  - [ ] Last updated (date time and by user) (sortable, default sort, DESC)
  - [ ] [Other content fields as needed] (sortable)
- [ ] Filters
  - [ ] Exposed
    - [ ] "Title contains" (text search of title field)
    - [ ] "Content type" (single value drop down or multivalue? should options be limited) (if applicable)
    - [ ] "Moderation state"  (single value drop down or multivalue?)
    - [ ] "Section" (workbench access section; single select, show children)
    - [ ] Order of filters matches order of columns
    - [ ] Reset button exists
    - [ ] Apply button says 'Filter' 
- [ ] Tab navigation is alpha sorted or intentionally grouped
- [ ] Not exposed
    - [ ] [Any not exposed filters, as needed]

**Comment by swirtSJW** [comment]
Generally, I don't think this is working correctly.   Across all contetnt types I would expect there to be more than 4 instances of "benefits"
image

My hunch is that it is because the search index is not being generated for old items, so the test nodes are the only ones to show.

**Comment by edmund-dunn** [comment]
> @edmund-dunn I couldn't get the search to return any results when I searched for VRRAP or ID.me

This is because it didn't index the sight.

**Comment by edmund-dunn** [comment]
> @edmund-dunn can we get the qa steps to be actual steps (like in the template sample) so that they are specific enough to follow and check off. These should be the same steps you are following before asking others to QA.
> 
> > Go to Content, and in the content navigation go to Content Audit Tools. Under that you should find a Content Search tab. You can search by keywords like VRRAP, ID.me and Air Force. You can also filter by content type depending on the nature of the audit.
> 
> Should be more like this
> 
> * Go to https://pr11706-vs5cfdcsh2vti4crwdkxp7t14onom0hv.ci.cms.va.gov/admin/content/audit/search
> * [ ]  validate that the tab is in the right order (alph order) under Content Audit Tools
> * go to [this link](https://pr11706-vs5cfdcsh2vti4crwdkxp7t14onom0hv.ci.cms.va.gov/admin/content/audit/search?keywords=VRRAP&label=&type%5B%5D=banner&type%5B%5D=basic_landing_page&type%5B%5D=campaign_landing_page&type%5B%5D=centralized_content&type%5B%5D=checklist&type%5B%5D=documentation_page&type%5B%5D=event&type%5B%5D=event_listing&type%5B%5D=faq_multiple_q_a&type%5B%5D=full_width_banner_alert&type%5B%5D=health_care_local_facility&type%5B%5D=health_care_local_health_service&type%5B%5D=health_care_region_detail_page&type%5B%5D=health_care_region_page&type%5B%5D=health_services_listing&type%5B%5D=landing_page&type%5B%5D=leadership_listing&type%5B%5D=locations_listing&type%5B%5D=media_list_images&type%5B%5D=media_list_videos&type%5B%5D=nca_facility&type%5B%5D=news_story&type%5B%5D=office&type%5B%5D=outreach_asset&type%5B%5D=page&type%5B%5D=person_profile&type%5B%5D=press_release&type%5B%5D=press_releases_listing&type%5B%5D=promo_banner&type%5B%5D=publication_listing&type%5B%5D=q_a&type%5B%5D=regional_health_care_service_des&type%5B%5D=step_by_step&type%5B%5D=story_listing&type%5B%5D=support_resources_detail_page&type%5B%5D=support_service&type%5B%5D=vamc_operating_status_and_alerts&type%5B%5D=vamc_system_billing_insurance&type%5B%5D=vamc_system_medical_records_offi&type%5B%5D=vamc_system_policies_page&type%5B%5D=vamc_system_register_for_care&type%5B%5D=va_form&type%5B%5D=vba_facility&type%5B%5D=vba_facility_service&type%5B%5D=vet_center&type%5B%5D=vet_center_cap&type%5B%5D=vet_center_facility_health_servi&type%5B%5D=vet_center_locations_list&type%5B%5D=vet_center_mobile_vet_center&type%5B%5D=vet_center_outstation&type%5B%5D=vha_facility_nonclinical_service)
> * [ ]  validate that there are  nodes that show up in the report.
> * [ ]  validate that the View meets the apprproprate ACs from our [Views Style Guide](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1740472321/CMS+Views+Style+Guide).
> * [ ]  - [ ] Display machinename, not `default`
> * [ ]  URL [`/admin/content/{{parent-view-name}}/name-of-view`]
> * [ ]  Menu item setting: Is it where it belongs?
> * [ ]  Limit to 100 per page, paginated
> * [ ]  Show result count in header below any exposed filters. (`<p>Displaying @start - @end of @total</p>`)
> * [ ]  Has table caption describing the table
> * [ ]  Columns
>   
>   * [ ]  Title (sortable)
>   * [ ]  Edit button (not operations, no heading)
>   * [ ]  Content type (sortable) (if applicable)
>   * [ ]  Moderation State
>   * [ ]  Section (field_administration) (sortable)
>   * [ ]  Is Locked (optional)
>   * [ ]  Last updated (date time and by user) (sortable, default sort, DESC)
>   * [ ]  [Other content fields as needed] (sortable)
> * [ ]  Filters
>   
>   * [ ]  Exposed
>     
>     * [ ]  "Title contains" (text search of title field)
>     * [ ]  "Content type" (single value drop down or multivalue? should options be limited) (if applicable)
>     * [ ]  "Moderation state"  (single value drop down or multivalue?)
>     * [ ]  "Section" (workbench access section; single select, show children)
>     * [ ]  Order of filters matches order of columns
>     * [ ]  Reset button exists
>     * [ ]  Apply button says 'Filter'
> * [ ]  Tab navigation is alpha sorted or intentionally grouped
> * [ ]  Not exposed
>   
>   * [ ]  [Any not exposed filters, as needed]

@swirtSJW In the future, for general feedback not specific to the PR please set up a zoom call where I can ask clarifying questions.

**Review by EWashb — COMMENTED** [review]
This seems to be working as expected now from my end. @swirtSJW can make the final approval before merging, but standard QA looks good to me.

**Comment by swirtSJW** [comment]
In looking at this and discussing with Erika and Dawn,  this is removing a formerly released tool "Rich Text Audit"  with a search that works but it not as robust.  We have lost the fine grained search and the ability to export the results.
None of the tickets that his is identified as being related to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11495,  https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11208, https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11647 address removing existing functionality.  

This also has not been communicated to the audiences that may be using the Rich Text Audit.  We can't just rip out tools that have already been released without some level of change management.

I understand the old tool had some limitations/faults but we need to replicate as much of it as we can, if we are going to remove the original.

**Comment by swirtSJW** [comment]
I am also concerned that this search is too broad and returns hits that do not match   A search for a specific string returns 46 hits, but only 2 actually contains that string.
image

The old tool shows the count more correctly
image

**Comment by EWashb** [comment]
@swirtSJW would you say there is some level where the new tool is too broad and the old tool isn't broad enough?

**Comment by swirtSJW** [comment]
> @swirtSJW would you say there is some level where the new tool is too broad and the old tool isn't broad enough?

Yes.  I agree with that.  The two do different things. So at the moment we should not be removing the original unless we can get them to have more similar features (which may not be possible).  

The other issue is that the new does not meet most of our Views Style guide standards.

**Comment by EWashb** [comment]
Ok- so my vote is to then keep both for the time being. I do think there is value in the new search, though, and would like to see how we can get the new search to be the preferred method of searching. There has to be some happy medium.

**Comment by EWashb** [comment]
@swirtSJW OK, so we are going to keep the rich text and add as much as possible with the style guide. After consulting with @edmund-dunn, the search API will not allow for sort. For CSV at this point, it is not launch blocking IMO to leave it out. We can definitely iterate on it after user feedback. I will be creating a KB on how to use this new content search tool and share it with Sitewide Content and others. I'm ok with iterating on this as needed once we get more feedback.

**Comment by EWashb** [comment]
@swirtSJW can we all hop on a zoom call to get this worked out? The Sitewide Content team needs the VRRAP audit by 12/11 so I would like to get this moving if we can. Thank you!

**Comment by swirtSJW** [comment]
> After consulting with @edmund-dunn, the search API will not allow for sort.

We have to escape the habit of whenever 2 or more of the Views Style guide AC template items can not apply, of throwing out the whole thing.  There are lots of items on the style guide AC's that can and should apply to this View, they just have not been followed.  I can call them out item by item if it makes it easier.

I've got some fixes to make this View a bit more reliable I can handle addressing the missing style guide items too.

**Comment by swirtSJW** [comment]
Pushing/pushed an update that made the following items inline with our Views Style Guide
- [x] Display machinename, not `default` or 'page'  I changed from 'page' to 'content_search'
- [x] Limit to 100 per page, paginated  I changed from 20 to 100
- [ ] Columns
  - [ ] Title (sortable) 
  - [ ] Edit button (not operations, no heading) 
  - [ ] Content type (sortable) (if applicable)
  - [ ] Moderation State
  - [ ] Section (field_administration) (sortable)
  - [ ] Is Locked (optional)
  - [ ] Last updated (date time and by user) (sortable, default sort, DESC)
  - [ ] [Other content fields as needed] (sortable)
- [ ] Filters
  - [ ] Exposed
    - [x] "Title contains" (text search of title field)  Changed from "Title"
    - [ ] "Content type" (single value drop down or multivalue? should options be limited) (if applicable)
    - [ ] "Moderation state"  (single value drop down or multivalue?)
    - [ ] "Section" (workbench access section; single select, show children)
    - [ ] Order of filters matches order of columns
    - [ ] Reset button exists
    - [ ] Apply button says 'Filter' 
- [x] Tab navigation is alpha sorted or intentionally grouped
- [ ] Not exposed
    - [ ] [Any not exposed filters, as needed]

**Comment by swirtSJW** [comment]
Interesting / concerning to note that generating this index locally crashes my containers locally.
This is a very large index to add, without stress testing it on our system and looking for performance declines.

**Comment by EWashb** [comment]
@swirtSJW thank you for this feedback! I'll keep an eye on this thread to see how we can improve

**Comment by swirtSJW** [comment]
This capabilities of this new search view are nearly in competition with the features  of the original rick text view.
Some of the filters are not an exact match, but they are pretty close.  And in many cases better
image


I think now it makes sense to remove the old.

**Comment by swirtSJW** [comment]
I just added redirects from the retired rich text search to the new.  
image

**Comment by swirtSJW** [comment]
I'll update the QA steps monday morning so we can get this tested and in.

**Comment by EWashb** [comment]
@swirtSJW I tried to download the CSV and I'm getting this error:
Screen Shot 2022-12-12 at 11 41 45 AM

When I click that link it shows this:

Screen Shot 2022-12-12 at 11 41 52 AM

**Comment by swirtSJW** [comment]
Interesting error.  I will take a look.

**Comment by swirtSJW** [comment]
@EWashb Can you try  that csv download again?
It worked fine for me on a couple of differnet trials on tugboat

image

image


I wonder if that 504 was just a transient tugboat thing.

**Comment by swirtSJW** [comment]
@laflannery If you want to use this PR env to update the KB from.  You should be set.   If not you can wait until it is merged.

**Comment by EWashb** [comment]
Yep...still getting the same error :( @swirtSJW

**Comment by swirtSJW** [comment]
I have not been able to reproduce this error, but I do have a fix in progress for the recursive rendering error.  That is a pretty minor one and will actually lead to better results too.

**Comment by laflannery** [comment]
@swirtSJW Question regarding permissions, currently this looks like it is only accessible to super admins (folks like us).  Can we make this available to content admins (the Sitewide content team)? I believe the intention was for them to be able to self-serve for their content audits in the future using this tool. 

CC: @EWashb

**Comment by swirtSJW** [comment]
I pushed up a change to open the perms a little on the parents of content_search so that anyone can drill down to it.
There is no risk to opening this as workbench menu access will prevent anyone from getting to edit pages if they are outside of their section or editorial role.

**Comment by swirtSJW** [comment]
Confirmed LARGE csv export is working now that batching was set to 500 node batches.

Confirmed recursive rendering errors are gone now that recursive fields are removed from render index.  (simplifies results too)

Confirmed that logged in as kitty.walsh with no  extra perms or sections now has an entrance path to this view and a few key others  
image

Important to note. We can send people an export link to the csv and they don't have to even be logged in to download it (intentionl)

**Review by swirtSJW — APPROVED** [review]

**Review by swirtSJW — APPROVED** [review]

**Pull request merged**
