### PR TITLE
VACMS-5785: Add confirm step to vbo.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #5785

## Testing done
Visual / behat

## QA steps
- As an administrator, go to `admin/content/bulk` , select a few items, and perform various vbo ops.
- Visually verify a confirmation step.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by kevwalsh — APPROVED** [review]
Everything works as expected but i'm confused by the PR, why it looks like the field wasn't there before at all. Did you override the master Fields display on the Bulk Edit Content display and then make a change? 

It makes me wonder why we have this field on Master, which is a bit dangerous if we only want to use it on this one view.  We may want to remove it from the Master display now.

**Comment by ethanteague** [comment]
> Everything works as expected but i'm confused by the PR, why it looks like the field wasn't there before at all. Did you override the master Fields display on the Bulk Edit Content display and then make a change?
> 
> It makes me wonder why we have this field on Master, which is a bit dangerous if we only want to use it on this one view. We may want to remove it from the Master display now.

Nah @kevwalsh, all I did was toggle on the confirm options on steps in the vbo field that offered it in the bulk display for the view, here: `admin/structure/views/view/content/edit/page_2` 
image

but not in the master display, here: `admin/structure/views/view/content/edit/default` 
image

**Comment by kevwalsh** [comment]
i think it's fine and QA passes, i was just surprised by the config diff.  it makes it look like a new field entirely, when the field was already there.

**Review by swirtSJW — APPROVED** [review]

**Comment by swirtSJW** [comment]
image

**Pull request merged**
