### PR TITLE
VACMS-7163: Delete the "VA Lovell Federal health care" menu

### LINKED ISSUE #7163: H1 and breadcrumb is wrong for Lovell Federal health care
## To Reproduce
1. Go to https://va.gov/lovell-federal-health-care
2. Note that it reads VA Lovell Federal health care for the h1, and Lovell FHCC for the breadcrumb

## Expected behavior
- [ ] It should read Lovell Federal health care in both places

## Screenshots 
<details><summary>FE</summary>

VA_Lovell_Federal_Health_Care___Veterans_Affairs

</details>

<details><summary>CMS</summary>

These all need to read "Lovell Federal health care
VA_Lovell_Federal_health_care___Veterans_Affairs

</details>

 ## Additional context

There may need to be a change on the FE `va-lovell-federal-health-care',`  may need to be `lovell-federal-health-care` in order to change the h1 / VAMC system name [in this file](https://github.com/department-of-veterans-affairs/content-build/blob/32b4170dffa06c4b4cf95d044ca390072e97e273/src/site/stages/build/drupal/graphql/navigation-fragments/facilitySidebar.nav.graphql.js#L90).

This may require a new menu in drupal too, with that machine name, and which will need to be enabled for all VAMC content types. 

This may require some careful change management. 

I did some digging but i could not figure out where the "FHCC" is coming from in the Drupal breadcrumb.

### PR DESCRIPTION
**Pull request by netboss**
- Created ".install" with update hook to delete the "VA Lovell Federal health care" menu.

## Description

closes #7163 

## Testing done
Passes all tests

## QA steps

As user administrator
1. [x] Go to `/admin/structure/menu?page=1` to verify and confirm that the "VA Lovell Federal health care" menu have been removed
2. [x] Go to the "Lovell Federal health care" page and enter node/edit mode `/node/15007/edit` to verify and check that the new "Lovell Federal health care" menu is still there

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by swirtSJW — COMMENTED** [review]
Nice work on the hook_update_n  @netboss  It deleted the menu... but then config sync brought it back.  You need to run this locally and then config export after running it.
image

**Review by swirtSJW — COMMENTED** [review]
I was expecting to see this go away too 
https://github.com/department-of-veterans-affairs/va.gov-cms/blob/3731c4ee11ec3ceb018b5e36db4cb81734977342/config/sync/menu_breadcrumb.settings.yml#L157-L161

**Comment by netboss** [comment]
> I was expecting to see this go away too
> 
> https://github.com/department-of-veterans-affairs/va.gov-cms/blob/3731c4ee11ec3ceb018b5e36db4cb81734977342/config/sync/menu_breadcrumb.settings.yml#L157-L161

@swirtSJW 
I can't see the "VA Lovell Federal health care" menu in the [menu breadcrumb settings via the admin UI](/admin/config/user-interface/menu-breadcrumb) but I can see it in my local `config/sync/menu_breadcrumb.settings.yml`. I guess I'll need to manually remove it from the config file, correct?

VACMS-7163_menu-breadcrumb

**Review by swirtSJW — APPROVED** [review]
Nice work @netboss

**Pull request merged**
