### PR TITLE
VACMS-4204: Add patch to prevent deletion of fetched entities.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #4204 

## Testing done
Visual

## QA steps
As an administrator, go to `node/15588/delete` (an entity whose content has been fetched) and visually verify `Access denied` message.

## Screenshots
image

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by ethanteague** [comment]
Current pr approach is flawed (querying for entity ref's instead of eff's). Working on new solution.

**Comment by swirtSJW** [comment]
I'm going to close this for 2 reasons:
1. The patch is not complete (does not account for paragraph deletion)
2. We won't apply the patch... once I merge the patch upstream, we will just bump to the newer module release.

**Comment by swirtSJW** [comment]
Looks like this got re-opened when the issue did,  converted to draft to avoid confusion.

**Comment by swirtSJW** [comment]
In testing this patch out for node deletion.  It is only preventing deletion on the node delete form.   If does not prevent deletion by bulk operation.
image

image

image

**Comment by swirtSJW** [comment]
I think access is still the right control, but it has to be on an operation, not a form.

**Comment by swirtSJW** [comment]
I am going to putter with this a bit.

**Comment by swirtSJW** [comment]
I worked on this quite a bit.  There just is no way to prevent deletions that are performed using the API which is what the bulk operation uses other than throwing an exception that would cause a whitescreen.

@ethanteague  I commited your patch but then followed it up with some changes to account for taxonomy terms and some other refinements.  Here are the changes I made if you want to see them. 
 https://git.drupalcode.org/project/entity_field_fetch/commit/eded92c

**Comment by ethanteague** [comment]
> I worked on this quite a bit. There just is no way to prevent deletions that are performed using the API which is what the bulk operation uses other than throwing an exception that would cause a whitescreen.
> 
> @ethanteague I commited your patch but then followed it up with some changes to account for taxonomy terms and some other refinements. Here are the changes I made if you want to see them.
> https://git.drupalcode.org/project/entity_field_fetch/commit/eded92c

Really appreciate your time and hard work on this, @swirtSJW . Ty, buddy.

**Comment by swirtSJW** [comment]
This is replaced by https://github.com/department-of-veterans-affairs/va.gov-cms/pull/6053

**Pull request closed without merging**
