### PR TITLE
VACMS-4753: Standalone-Page-Required-Hidden-Field

### PR DESCRIPTION
**Pull request by kaise-lafrai**
…made both the uri and title of the field_related_information optional in code

## Description

See _issueid_. #4753 

## QA steps

- Navigate to PR env.
- Navigate here: '/node/15603/edit'
- [x] Confirm you can save the node with the "Enable standalone Resources and support page for this Q&A." unchecked.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by swirtSJW** [comment]
Looks like we have a failing test.

**Comment by acrollet** [comment]
@ndouglas is there a way to see the output from the behavioral test?

**Comment by ndouglas** [comment]
D'oh, no, I think that's just being captured and not echoed.  🤦

**Comment by acrollet** [comment]
@ndouglas whoops! In the meantime it looks like the test can be run on the tugboat terminal with `./scripts/tests/cypress.sh behavioral`

**Comment by acrollet** [comment]
@ndouglas so the behavioral tests are failing when run manually bc they're hitting the lando site url, is there an environment variable that needs to be set?

**Comment by ndouglas** [comment]
See #5100 to echo the output.

**Comment by ndouglas** [comment]
`CYPRESS_BASE_URL` might be what we're looking for.  `set -o allexport && source .env && set +o allexport` if my memory is correct to get that env var set in the current terminal

**Comment by kaise-lafrai** [comment]
@acrollet @ndouglas Are we waiting for https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5100 to resolve this tickets failed test?

**Comment by ndouglas** [comment]
you should be able to run it in Tugboat with the commands I listed above to set the environment variables correctly, if you're in a hurry, but I think #5100 should be done soon.

**Comment by kaise-lafrai** [comment]
@swirtSJW @ndouglas @acrollet Finally got cypress interactive to work locally. Running that now and should hopefully be able to resolve this.

**Comment by kaise-lafrai** [comment]
Behavioral test passed locally. Rebuilding the PR.

**Comment by kaise-lafrai** [comment]
@swirtSJW Looks like it was just a glitch. Tests have passed here. Thanks

**Review by swirtSJW — APPROVED** [review]
QA passes.   Nice work.

**Comment by swirtSJW** [comment]
image

**Pull request merged**
