### PR TITLE
VACMS-8424 reduce content builds in tests

### LINKED ISSUE #8424: Remove duplicate content build during test run
## User Story or Problem Statement

As a CMS developer I would like to reduce the number of content builds in the testing stack so that tests will run more quickly, with no loss of test coverage.

## Acceptance Criteria
- [x] Minimal loss of test coverage
- [x] Only one content build in testing stack

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [x] `Platform CMS Team`
- [x] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by swirtSJW**
## Description

Closes #8424
This PR does the following

- Removes the redundant content build
- Moves the behat decoupled tests that relied on the previously existing content built to AFTER the content build is called by the behat test.  
- Removes some related documentation and some documentation of a [PR that never landed](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/547). 

The only decouple test that was removed was connected to the existing state of content before a save.  It did not test anything explicitly and offered no additional test coverage.  It is fully covered by the remaining tests.

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

This PR is completely covered by its own tests.
- [ ] Validate all tests pass

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by swirtSJW** [comment]
In order for this to pass it will need the requirement of 
image
to be removed from github.

**Comment by cweagans** [comment]
If you'd like, I can turn off the va/web/build requirement now.

**Comment by swirtSJW** [comment]
> If you'd like, I can turn off the va/web/build requirement now.

@cweagans I can't really think of any downside to turning it off "early".  If the content build fails on other PRs, it will still fail a second time on the behat decoupled.feature.  I don't think turning it off increases our risk (please double check my logic on that).

**Comment by cweagans** [comment]
I agree. It's also easily reversible. va/web/build has been disabled as a requirement.

**Review by cweagans — APPROVED** [review]

**Pull request merged**
