### PR TITLE
VACMS-3167: Add clp content type.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #3167 
Implements 
 - Hero panel
 - Why this matters
 - What you can do
 - VA Benefits panel

_Does not update spec tool (will wait until we have solid mvp to prevent friction for other devs using spec tool)_

## Testing done
Visual / Manual

## Screenshots
See Video: https://www.loom.com/share/338fb19c2a32468196be59a8695fd980

## QA steps
This is an mvp, and will be iterative. Implements the 4 panels we agreed we are safe to make assumptions about. @kevwalsh to review / provide feedback.

### CODE REVIEW

**Comment by kevwalsh** [comment]
@ethanteague Awesome, i think this is actually pretty close to mergeable, so why not drupal spec'ify it? 

A few things. 

- [ ] Remove the authoring info and promotion options from node form
Create_Campaign_Landing_Page___VA_gov_CMS

- [ ] Move revision log message box into the Editorial Workflow fieldgroup, and update automated test that checks for that (not sure where that lives)

Create_Campaign_Landing_Page___VA_gov_CMS

- [ ] Change all character count syntax to "100 characters remaining" instead of "Characters remaining: 100" 

Create_Campaign_Landing_Page___VA_gov_CMS

- [ ] Add help text to VA Benefits fieldgroup: "Select one or two benefits that are related to this campaign"

Create_Campaign_Landing_Page___VA_gov_CMS

- [ ] Change the Related benefits to use this look without the "VA " prefix. 

Create_VA_Form___VA_gov_CMS

- [ ] Allow content admins to create these nodes (permissions)
- [ ] Change the weight of the "Campaign Landing Page" /node/add menu link to be alphabetical (after Benefits Hub Landing Page, before Checklist") 

Create_Campaign_Landing_Page___VA_gov_CMS

**Review by kevwalsh — CHANGES_REQUESTED** [review]
@ethanteague 

Nice. One last detail i forgot...  

- [x] Add the Owner field for CLP to `/admin/config/workflow/workbench_access/access_scheme/section/edit`

**Comment by ethanteague** [comment]
> @ethanteague
> 
> Nice. One last detail i forgot...
> 
> * [x]  Add the Owner field for CLP to `/admin/config/workflow/workbench_access/access_scheme/section/edit`

Added, @kevwalsh :+1:

**Review by kevwalsh — APPROVED** [review]
Nice!

**Review by swirtSJW — APPROVED** [review]

**Comment by swirtSJW** [comment]
image

**Pull request merged**
