### PR TITLE
VACMS-4446: Update vc cap address and hours fields.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #4446

## Testing done
Visual / behat

## Screenshots
image

## QA steps
- As an administrator, go to `node/add/vet_center_cap` and visually verify that the changes reflected in the screenshot appear on the page.

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by kevwalsh — CHANGES_REQUESTED** [review]
nice work hiding the Table Caption field. @swirtSJW any concerns with that? i think we may want to reuse this on Service location within Facility health service. 

One more thing i missed (sorry): removing this misleading help text on the hours field. 

109577675-00c4ac80-7ac4-11eb-8385-a0a4571a9d2b_png__1471×1006_

**Comment by kevwalsh** [comment]
@swirtSJW @ethanteague See #4508 for a possible followup to work done here.

**Comment by ethanteague** [comment]
> nice work hiding the Table Caption field. @swirtSJW any concerns with that? i think we may want to reuse this on Service location within Facility health service.
> 
> One more thing i missed (sorry): removing this misleading help text on the hours field.
> 
> 109577675-00c4ac80-7ac4-11eb-8385-a0a4571a9d2b_png__1471×1006_

I think the primary concern is that hiding a piece of a field (via an unset) could break the frontend build. But va web build test passed, so I think we are good.

**Comment by ethanteague** [comment]
> nice work hiding the Table Caption field. @swirtSJW any concerns with that? i think we may want to reuse this on Service location within Facility health service.
> 
> One more thing i missed (sorry): removing this misleading help text on the hours field.
> 
> 109577675-00c4ac80-7ac4-11eb-8385-a0a4571a9d2b_png__1471×1006_

Np a'tall, @kevwalsh - updated :+1:

**Comment by ethanteague** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4511

**Pull request closed without merging**
