### PR TITLE
[WIP] VACMS-2763: create new video entities from Media list - Videos component

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #2763 

## Testing done
Visual / Behat

## Screenshots
image
image

## QA steps
- As an admin go to `/node/add/media_list_videos` and visually verify that you see a video upload option. (Will require @oksana-c 's feedback)
- Add a youtube url and confirm save is successful

### CODE REVIEW

**Comment by ethanteague** [comment]
@oksana-c will need to iterate on the upload experience. E.g., do we wanna add thumbnails to the fieldset, or do we wanna get even fancier and add it to the Media library field above, etc. Can be a big thing, or a small thing.

**Comment by swirtSJW** [comment]
This seems to not agree with the AC from 2717

> Video media entities only allow YouTube as video provider. Vimeo and YouTube Playlist are removed from allowed options.

image

**Review by swirtSJW — CHANGES_REQUESTED** [review]
Code looks fine.  Seems to be missing some of the AC on 2717

**Comment by ethanteague** [comment]
> Code looks fine. Seems to be missing some of the AC on 2717

Thanks for catching that, @swirtSJW - updated.

**Comment by swirtSJW** [comment]
image
 The language seems confusing to me even knowing the difference.
Suggesting we run this by UX team.
perhaps "Add media" button becomes "Choose from existing media"

**Review by swirtSJW — COMMENTED** [review]
Code is all good.  But I think it should wait based on the language in the UX being confusing.

**Comment by ethanteague** [comment]
@oksana-c I've created a separate pr to address the quick config stuff in 2717 (https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2869) so that we can devote this pr to the heavy / deep-dive stuff in 2763.

**Pull request closed without merging**
