### PR TITLE
VACMS-4773: Update pathauto for detail page, and audit URLs.

### PR DESCRIPTION
**Pull request by kevwalsh**
## Description

See #4773 for discussion. 

## ACs

- [x] [node:menu-link:parents:join-path] should be updated to meet two needs
  - [x] 1. parent menu items with `<nolink>`are ignored 
  - [x] 2. parent menu items that have path aliases set manually (in this case, all VAMC systems, which have `va-` stripped from their first URL path... like `VA Altoona health care` becomes `altoona-health-care). 
- [x] this pattern should be applied to all VAMC Detail Pages

## Testing done

Manual, behat, Airtable review. See QA steps.

## Screenshots

Detail_page_URL_audit_and_bulk_udpate___VA_gov_CMS

## QA steps

- [x] Go to https://pr5329-hlvekp16ivk1elzkftnv0vc65wvkaizj.ci.cms.va.gov/admin/content/audit/detail-pages-urls
- [x] Note 2594 results (as of May 24)
- [x] Filter by "is none of" "VA Pittsburgh health care" (since we will be doing those manually".
- [x] You should see ~50 less results, representing Pittsburghs filtered out.
- [x] Select Run "Update URL alias" on all nodes
- [x] Clear all caches 
- [x] CSV   
- [x] URLs should match the spec from #4773  (some analysis done in airtable)

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by swirtSJW — APPROVED** [review]
Code looks good.

**Comment by swirtSJW** [comment]
I believe this is blocked for two reasons:

1. The view is just for QA purposes and will not go into the final PR.
2. Redirects from the old location to the new location need to be added immediately after this change goes out and is implemented on the CMS.

**Comment by kevwalsh** [comment]
I've confirmed that Ethan's patch (from https://www.drupal.org/node/3214658 ​fixes the `<nolink>` items being included. But there's another issue that i hadn't noticed... `[node:menu-link:parents:join-path]` is not using the _path_ from the menu item hierarchy... it's using the menu item titles. So the desired `/altoona-health-care` at the root level is being rewritten to `/va-altoona-health-care`, because the menu item title for the VAMC system homepage is "VA Altoona health care". See results here https://pr5329-hlvekp16ivk1elzkftnv0vc65wvkaizj.ci.cms.va.gov/admin/content/audit/detail-pages-urls

​If i understand correctly, it may be because the "Generate automatic URL alias" has been _unchecked_ for the VAMC system node that lies at the root of each tree. 

I found a couple of issues that relate to this. 

https://www.drupal.org/project/token/issues/1829268
https://www.drupal.org/project/pathauto/issues/1496582
https://stackoverflow.com/questions/4683610/menu-path-in-pathauto
​

**Comment by kevwalsh** [comment]
@ethanteague this is a QA pass, great work!  I updated the PR description with ACs and my manual QA, and did some analysis in [this airtable](https://airtable.com/invite/l?inviteId=invhNrpkHCczagIfH&inviteToken=0cedb6a08339f0f5f53ff78dcdfa7e95749e75b38ea53227aac418e52fcc2d9c), which i passed on to VAMC upgrade team. i also updated the behat test.

@swirtSJW I think this might be OK to merge pending your code review of course. It's an improvement on the existing system. We'll want to communicate with VAMC upgrade team that detail pages will get the right URL now, and they should stop overriding them.

**Comment by ethanteague** [comment]
> @ethanteague this is a QA pass, great work! I updated the PR description with ACs and my manual QA, and did some analysis in [this airtable](https://airtable.com/invite/l?inviteId=invhNrpkHCczagIfH&inviteToken=0cedb6a08339f0f5f53ff78dcdfa7e95749e75b38ea53227aac418e52fcc2d9c), which i passed on to VAMC upgrade team. i also updated the behat test.
> 
> @swirtSJW I think this might be OK to merge pending your code review of course. It's an improvement on the existing system. We'll want to communicate with VAMC upgrade team that detail pages will get the right URL now, and they should stop overriding them.

Thanks for updating that behat test, @kevwalsh ! I forget to do that.

**Pull request closed without merging**
