### PR TITLE
Vagov 5038 migration anomaly fix

### PR DESCRIPTION
**Pull request by beeyayjay**
nothing really to test, mostly yaml updates, a few code changes.

### CODE REVIEW

**Comment by ElijahLynn** [comment]
rebuild

**Comment by ElijahLynn** [comment]
This needs latest develop to pass.

**Comment by ElijahLynn** [comment]
failed due to Jenkins CA issue, fixing.

**Comment by ElijahLynn** [comment]
rebuild

**Comment by jonpugh** [comment]
force push and failing reinstall has been fixed. 
After this install, I'll re-trigger the environment detel as well.

**Pull request merged**
