### PR TITLE
[WIP] VAGOV-6425: Require vets-website branch not listed in devshop.

### PR DESCRIPTION
**Pull request by kevwalsh**
## Description

Trying to require a vets-website branch in a PR enviornment, for E2E testing. 

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

## Definition of Done
- [ ] Product release notes 
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

### CODE REVIEW

**Comment by ElijahLynn** [comment]
Can you post branch here? Need to see if it here https://packagist.org/packages/va-gov/web.

**Comment by ethanteague** [comment]
> Can you post branch here? Need to see if it here https://packagist.org/packages/va-gov/web.

@ElijahLynn https://github.com/department-of-veterans-affairs/vets-website/tree/VAGOV-6425-refactor-listings-et

**Comment by ElijahLynn** [comment]
> > Can you post branch here? Need to see if it here https://packagist.org/packages/va-gov/web.
> 
> @ElijahLynn https://github.com/department-of-veterans-affairs/vets-website/tree/VAGOV-6425-refactor-listings-et

Thank you, until DevShop pulls in all the branches I manually set it here using these steps:
`hub pr checkout 1185`
`git reset --hard 6d1246^` (revert this PRs composer changes)
`lando composer nuke`
`lando composer install` (installs composer and npm packages)
`lando composer require va-gov/web:dev-VAGOV-6425-refactor-listings-et` (right way to pull in the upstream branch)
`git push --force` (wiped your composer change)
`./scripts/sync-db.sh` (runs cache:rebuild, config:import and updatedb too)
`lando composer yaml-tests` (getting failures, but it is on the correct branch now)

**Comment by ElijahLynn** [comment]
This is closable now yah?

**Pull request closed without merging**
