### PR TITLE
Fix .env file on Tugboat clone.

### PR DESCRIPTION
**Pull request by ElijahLynn**
## Description

#4069

## Screenshots

### CODE REVIEW

**Review by acrollet — DISMISSED** [review]
Looks reasonable to me! Nice work figuring this out 🙂

**Review by oksana-c — COMMENTED** [review]
thanks for catching this @ElijahLynn .

We have ~30 cloned environments in demo project. They all currently show web URL from the base preview. It looks like we will need to delete/recreate them all once this PR is merged in. Correct?

**Comment by ElijahLynn** [comment]
Yes, either recloned or run the one clone step, ,`j2 ...`, manually on each one in a terminal.

**Review by indytechcook — APPROVED** [review]

**Comment by indytechcook** [comment]
@ElijahLynn if the `.env` file is generated on the base preview, would it be cloned?

**Comment by ElijahLynn** [comment]
> @ElijahLynn if the `.env` file is generated on the base preview, would it be cloned?

Yes

**Review by indytechcook — APPROVED** [review]

**Comment by indytechcook** [comment]
I confirmed a refresh of a clone has the latest commit from the branch:

```
commit aa545215255bf1cc041bac31c8d4e095847eff6f (HEAD -> neil-demo, origin/neil-demo)
Author: Neil Hastings <neil.hastings@agile6.com>
Date:   Mon Jan 25 12:43:02 2021 -0500

    Update README.md
```

https://github.com/department-of-veterans-affairs/va.gov-cms/commits/neil-demo

**Pull request merged**
