### PR TITLE
VACMS-1948: Experimental Drupal 9 [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

See #1948.  This is a somewhat-improvised ad-hoc upgrade and shouldn't be merged.  Mostly just opening this to get the automated tests to run and see what other issues pop up. 

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [x] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by ndouglas** [comment]
Screen Shot 2021-05-05 at 9 37 08 AM

ap_090911089838_sq-3271237f28995f6530d9634ff27228cae88e3440

**Comment by acrollet** [comment]
tenor-2

**Comment by ndouglas** [comment]
Pseudo-script for replicating this:

Update Composer requirements but don't actually update:
```bash
lando composer require \
  drupal/core-recommended:^9.0.0 \
  drupal/core-composer-scaffold:^9.0.0 \
  drupal/core-project-message:^9.0.0 \
  symfony/config:^4.0 \
  symfony/routing:^4.0 \
  --update-with-dependencies \
  --no-update;
```

Update dev-dependencies separately.
```bash
lando composer require --dev \
  acquia/drupal-spec-tool:^4.0.0 \
  --no-update;  
```

Alter drupal/core patches to match the following:
```json
                "2807629 - Allow menu items which link to unpublished nodes to be selected in the parent item selector": "https://www.drupal.org/files/issues/2021-04-19/2807629-35.patch",
                "2894449 - Indirect modification of overloaded element with Views responsive table": "https://www.drupal.org/files/issues/2018-10-05/core-indirect-modification-of-overloaded-element-2894449-18.patch",
                "3057267 - User logout during maintenance mode": "https://www.drupal.org/files/issues/2019-09-11/3057267-maintenance-forced-logout-experimental.patch",
                "1091852 - Display Bug when using #states (Forms API) with Ajax Request": "https://www.drupal.org/files/issues/2021-02-19/1091852-128.patch",
                "2859042 - Entity original revision": "https://www.drupal.org/files/issues/2018-07-30/entity_original_revision-2859042-26.patch",
                "2930508 - Seven inactive tabs do not meet WCAG AA 1.4.3 for contrast": "https://www.drupal.org/files/issues/2020-10-15/drupal-seven_inactive_tabs_do_not_meet_wcag_aa-2930508-36.patch",
                "2632750 - Interface previews/skeleton screens through optional preview or placeholder templates": "https://www.drupal.org/files/issues/2020-11-18/2632750-76-do-not-test_0.patch",
                "2911932 - Correct vertical tab does not focus on form validation": "https://www.drupal.org/files/issues/2020-12-12/vertical-tabs--focus-on-onvalid-7b.patch",
                "2893933 - claimItem in the database and memory queues does not use expire correctly": "https://www.drupal.org/files/issues/2021-01-14/2893933-40.patch",
                "3198608 - Migrate does not set set track_lst_updated from config": "https://www.drupal.org/files/issues/2021-02-15/3198608-track-last-updated-6.patch",
                "3205691 - Disallow aria-required on fieldsets": "https://www.drupal.org/files/issues/2021-03-25/disallow-aria-required-fieldsets.patch"
```

In composer.json, change dropzone's source -- otherwise, it won't install correctly and D9 will complain because `core-requirement`:
```json
        "bower-asset/dropzone": "^5.5" -> "npm-asset/dropzone": "^5.5",
```

Then:
```bash
lando composer install
```

And, obv:
```bash
lando drush updb
```

**Comment by ndouglas** [comment]
Managed to zig when I should've zagged in a composer.lock merge and broke PHPunit tests, so I'll fix that later.

**Comment by ElijahLynn** [comment]
Slack thread for our mob testing session > https://dsva.slack.com/archives/CT4GZBM8F/p1621278991119700

**Pull request closed without merging**
