### PR TITLE
VACMS-5101: Echo task output to stdout.

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

Test output wasn't being output to the log, which was problematic when tests failed 🤦 

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by acrollet — APPROVED** [review]
Approved pending tests

**Comment by acrollet** [comment]
@ndouglas hmm, I'm not seeing the task output in the tugboat log. Is go-task swallowing it perhaps?

**Comment by ndouglas** [comment]
Yeah, lemme look and see if there's some better way to capture/control the output of those command substitutions.  Especially in these long tasks...

**Comment by acrollet** [comment]
> Especially in these long tasks...

yeah, it would be ideal if it could get printed out in real time...

**Comment by ndouglas** [comment]
Switched to `tee`'ing, which was the first thing I thought of but thought it might get screwed up by Lando.  But it seems to work okay -- let's see if it gets screwed up by Tugboat.  I think there're some cross-platform issues with ttys, ptys, etc but since everything involved here is a pretty mainstream Linux I'm hoping that'll be moot.

**Review by indytechcook — APPROVED** [review]

**Pull request merged**
