### PR TITLE
VACMS-14268: Adds design system color edits as specified by the UX Team.

### PR DESCRIPTION
**Pull request by tonytaylor**
## Description

Updates design system color specifications in accord with the [VA.gov Design System Documentation](https://design.va.gov/). 

Storybook changelog story has also been updated to reflect changes made.

Relates to #14268 

### Select Team for PR review

- [x] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### CMS user-facing announcement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [x] No announcement is needed for this code change.
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by laflannery** [comment]
I did not see any accessibility issues but I did see some QA items that I wanted to point out and I think warrants a more thorough QA of the CMS. Some issues I noticed:

- The alert that used to be green is now black/dark gray
image
- The red alert is also black/dark gray
image
- Buttons at the bottom of the edit view are not styled correctly any more:
image

**Comment by tonytaylor** [comment]
Thanks @laflannery for catching that. I've updated the components that were in need of a lil love.

**Comment by BlakeOrgan** [comment]
Continuing to look at this, but I do notice that in Storybook the sky, sand, blush, and mint colors should be deprecated and any instances of those colors should be changed to their lightest blue, gold, red, and green colors.

**Review by BlakeOrgan — APPROVED** [review]
Storybook looks good and is approved, however, I am still seeing old colors in the pr environment that aren't in Storybook so I'm not sure where those are coming in from. I will create a list of things that we can address as a follow up, but I'm going to approve this since Storybook looks as expected. Requesting a review from @edmund-dunn as well so we can get another set of eyes on this from a dev perspective.

**Comment by gracekretschmer-metrostar** [comment]
Pull up for sprint 22 and bring in Amanda and Marisa.

**Comment by JakeBapple** [comment]
Strategy:
new branch from main using 15308 naming
merge in 15308 and then 14753
run the storybook styles and then the theme command to check for errors
tag edmund, steve, and marissa for review
can close those two after we merge in the new one

**Comment by JakeBapple** [comment]
Closing this PR as it was consolidated in this: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/19520

**Pull request closed without merging**
