### PR TITLE
VACMS-3347: run phpcs on tests dir

### PR DESCRIPTION
**Pull request by acrollet**
## Description

See #3347 

## Testing done

Ran phpunit, behat and axe tests locally.

## QA steps

- [x] Confirm that phpcs is automatically run on the tests directory
- [x] Confirm that tests function as before

### CMS user-facing release note

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication.
- [ ] Yes, but it hasn't yet been written (this code is not ready to merge!).
- [x] No announcement is needed for this code change.

### CODE REVIEW

**Review by ndouglas — APPROVED** [review]
96a054c518571eb2a87e1f6c9bd480c4_crop_north

**Comment by ndouglas** [comment]
whoop whoop, wait, didn't look at everything, just the first commit.

**Comment by ndouglas** [comment]
Okay, stand by my original approval 😎

**Comment by acrollet** [comment]
> Okay, stand by my original approval 😎

tenor

**Review by swirtSJW — APPROVED** [review]

**Comment by swirtSJW** [comment]
image
merging based on

**Pull request merged**
