### PR TITLE
VAGOV-000: Adding xdebug to lando.

### PR DESCRIPTION
**Pull request by ethanteague**
# About
We need to have xdebug available - this pr does this.
See screenshot for demo / config setup (launch.json) in VScode

# Screenshot
setup

### CODE REVIEW

**Comment by ElijahLynn** [comment]
I use Lando regularly with xdebug without the new settings. All that is required is to uncomment the `xdebug: true` line in .lando.yml and `lando rebuild`. Are you sure you want to enable this for everyone?

**Comment by ElijahLynn** [comment]
> I use Lando on this project regularly with xdebug without the new settings. All that is required is to uncomment the `xdebug: true` line in .lando.yml and `lando rebuild`. Are you sure you want to enable this for everyone?

If you do, please also update the xdebug docs in the main README.md.

**Comment by ethanteague** [comment]
> I use Lando on this project regularly with xdebug without the new settings. All that is required is to uncomment the `xdebug: true` line in .lando.yml and `lando rebuild`. Are you sure you want to enable this for everyone?

How does it work without the changes to php.ini?

**Comment by ElijahLynn** [comment]
> > I use Lando on this project regularly with xdebug without the new settings. All that is required is to uncomment the `xdebug: true` line in .lando.yml and `lando rebuild`. Are you sure you want to enable this for everyone?
> 
> How does it work without the changes to php.ini?



> > I use Lando on this project regularly with xdebug without the new settings. All that is required is to uncomment the `xdebug: true` line in .lando.yml and `lando rebuild`. Are you sure you want to enable this for everyone?
> 
> How does it work without the changes to php.ini?

I just hit the listen icon in my IDE and it comes in fine. Lando has the support for that key so I think they must take care of that include behind the scenes. I am thinking when that key is set they include a xdebug.ini file in the rebuild of the container, so it is abstracted away.

**Comment by ethanteague** [comment]
> > > I use Lando on this project regularly with xdebug without the new settings. All that is required is to uncomment the `xdebug: true` line in .lando.yml and `lando rebuild`. Are you sure you want to enable this for everyone?
> > 
> > 
> > How does it work without the changes to php.ini?
> 
> I just hit the listen icon in my IDE and it comes in fine. Lando has the support for that key so I think they must take care of that include behind the scenes. I am thinking when that key is set they include a xdebug.ini file in the rebuild of the container, so it is abstracted away.

Awesome. I'll close this.

**Pull request closed without merging**
