### PR TITLE
VACMS-19481: enable family member menu on Benefit detail pages

### PR DESCRIPTION
**Pull request by davidmpickett**
## Description

Relates to #19481.

## Testing done

Manual in Tugboat

## Screenshots

Screenshot 2024-10-28 at 3 35 16 PM
Screenshot 2024-10-28 at 3 34 19 PM

## QA steps

What needs to be checked to prove this works?
What needs to be checked to prove it didn't break any related things?
What variations of circumstances (users, actions, values) need to be checked?

As user [4488](https://staging.cms.va.gov/user/4488) or a Content Admin 
1. [Login to the tugboat](https://pr19629-n55abtnmka82hdzehxwby3vswcrvznhq.ci.cms.va.gov/)
2. Then go to Content and [filter by Benefit Detail Pages](https://pr19629-n55abtnmka82hdzehxwby3vswcrvznhq.ci.cms.va.gov/admin/content?title=&type=page&moderation_state=All&owner=All)
   - [ ] Edit any existing Benefit Detail Page
   - [ ] In the sidebar go to menu settings / Parent link
   - [ ] Select <Family and caregiver benefits hub>
   - [ ] Add a revision message and save as draft
3. Then go to Content > Add Content > [Benefit Detail Page](https://pr19629-n55abtnmka82hdzehxwby3vswcrvznhq.ci.cms.va.gov/node/add/page)
   - [ ] Fill out required fields
   - [ ] In the sidebar go to menu settings and check Provide a menu link
   - [ ] Under parent Link select <Family and caregiver benefits hub>
   - [ ] Add a revision message and save as draft

### Definition of Done

- [x] Automated tests have passed.
- [x] Code Quality Tests have passed.
- [x] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### CODE REVIEW

**Comment by jilladams** [comment]
Verified: 
* Logged in as 4488 in PR env
* Edit https://pr19629-n55abtnmka82hdzehxwby3vswcrvznhq.ci.cms.va.gov/node/68096/edit
* Can select the Family & Caregiver benefit hub menu
* Create new BDP, can assign that menu

Go team.

**Comment by jilladams** [comment]
Ready for code review, I think.

**Comment by dsasser** [comment]
I'm trying to get the phpunit tests to pass, but It seems tugboat is sporadically returning 502 errors today, causing the tests  to fail with errors similar to:

```
uzzleHttp\Exception\ServerException: Server error: `GET https://pr19629-n55abtnmka82hdzehxwby3vswcrvznhq.ci.cms.va.gov//jsonapi/node/news_story?page%5Blimit%5D=5` resulted in a `502 Bad Gateway` response:
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html> (truncated...)

```

**Review by dsasser — APPROVED** [review]
LGTM!

**Pull request merged**
