### PR TITLE
VACMS-3449: Forces paragraphs to clone and hides their checkboxes on the clone form.

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

See #3449. 

## Testing done
Attempted to clone a node with paragraphs and noted that the form no longer contains checkboxes for the paragraph children of the original node.  Clone completed successfully and verified in Views that this created new paragraphs whose parents were the newly cloned node.

## Screenshots
Screen Shot 2020-11-13 at 8 17 47 AM

## QA steps
As any user with the permission to clone a node:
1. Clone [a node with paragraphs](http://va-gov-cms.lndo.site/entity_clone/node/2768)
1. Verify that:
  - [ ] the clone form does not give the option to avoid cloning the paragraphs
  - [ ] the clone operation succeeds and the new node has paragraphs that are distinct from the paragraphs of the original node

## Definition of Done
It's just a config update.

### CMS user-facing announcement
Is an announcement needed to let editors know of this change? 
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by ndouglas** [comment]
@indytechcook Turns out this is already a thing, see http://va-gov-cms.lndo.site/admin/config/system/entity-clone .  Hey, at least it's done, right?  I just went ahead and hid the paragraph elements of the form too since it's wonky and unnecessary if we're always cloning them, but that can be undone obv.

**Comment by indytechcook** [comment]
this is great!

**Comment by indytechcook** [comment]
Config looks good

Entity clone settings | VA gov CMS 2020-11-13 10-14-45
Clone Content | VA gov CMS 2020-11-13 10-14-31

**Review by indytechcook — APPROVED** [review]

**Comment by indytechcook** [comment]
Adding a note that the UX change of removing the options was reviewed with @kevwalsh

**Pull request merged**
