### PR TITLE
VACMS-2955: Refactor Field Related Links

### PR DESCRIPTION
**Pull request by kaise-lafrai**
## Description

See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/2955

## QA steps

As an editor
- [ ] Log into preview environment. (This can be found in devshop) 

- Navigate to the following content types to confirm the addition of a new _entity reference revisions_ field called `Related Information | field_related_information.`

## checklist

- [ ] Navigate to `/admin/structure/types/manage/checklist/fields`
   - [ ] New field `Related Information | field_related_information.` exists.
   - Select **Edit** under the Operations column for the **Related Information** field and confirm the following:
      - [ ] Label: Related Information
      - [ ] Help text: Add up to 5 link teasers.
      - [ ] Paragraph Type: Link teaser
   - Select **Field Settings** tab and confirm the following:
      - [ ] Allowed number of values: Limited: 5
- Navigate back to the **Manage Fields** tab and select the **Manage form display** tab.
   - [ ] Confirm Related Links field is disabled
   - [ ] Confirm Related Information field is below the VA Benefit Hubs field
   - [ ] Confirm widget is Paragraphs EXPERIMENTAL
   - Select Gear icon associated with the **Related Information** field and confirm the following:
      - [ ] Paragraph Title: Link teaser
      - [ ] Plural Paragraph Title: Link teaser
      - [ ] Enable widget features: Only Collapse/Edit all is selected
- Select the **Manage display** tab.
   - [ ] Confirm Related Links field is disabled
   - [ ] Confirm Related Information field is below the VA Benefit Hubs field

## faq_multiple_q_a

- [ ] Navigate to `/admin/structure/types/manage/faq_multiple_q_a/fields`
   - [ ] New field `Related Information | field_related_information.` exists.
   - Select **Edit** under the Operations column for the **Related Information** field and confirm the following:
      - [ ] Label: Related Information
      - [ ] Help text: Add up to 5 link teasers.
      - [ ] Paragraph Type: Link teaser
   - Select **Field Settings** tab and confirm the following:
      - [ ] Allowed number of values: Limited: 5
- Navigate back to the **Manage Fields** tab and select the **Manage form display** tab.
   - [ ] Confirm Related Links field is disabled
   - [ ] Confirm Related Information field is below the VA Benefit Hubs field
   - [ ] Confirm widget is Paragraphs EXPERIMENTAL
   - Select Gear icon associated with the **Related Information** field and confirm the following:
      - [ ] Paragraph Title: Link teaser
      - [ ] Plural Paragraph Title: Link teaser
      - [ ] Enable widget features: Only Collapse/Edit all is selected
- Select the **Manage display** tab.
   - [ ] Confirm Related Links field is disabled
   - [ ] Confirm Related Information field is below the VA Benefit Hubs field

## step_by_step

- [ ] Navigate to `/admin/structure/types/manage/step_by_step/fields`
   - [ ] New field `Related Information | field_related_information.` exists.
   - Select **Edit** under the Operations column for the **Related Information** field and confirm the following:
      - [ ] Label: Related Information
      - [ ] Help text: Add up to 5 link teasers.
      - [ ] Paragraph Type: Link teaser
   - Select **Field Settings** tab and confirm the following:
      - [ ] Allowed number of values: Limited: 5
- Navigate back to the **Manage Fields** tab and select the **Manage form display** tab.
   - [ ] Confirm Related Links field is disabled
   - [ ] Confirm Related Information field is below the VA Benefit Hubs field
   - [ ] Confirm widget is Paragraphs EXPERIMENTAL
   - Select Gear icon associated with the **Related Information** field and confirm the following:
      - [ ] Paragraph Title: Link teaser
      - [ ] Plural Paragraph Title: Link teaser
      - [ ] Enable widget features: Only Collapse/Edit all is selected
- Select the **Manage display** tab.
   - [ ] Confirm Related Links field is disabled
   - [ ] Confirm Related Information field is below the VA Benefit Hubs field

## media_list_images

- [ ] Navigate to `/admin/structure/types/manage/media_list_images/fields`
   - [ ] New field `Related Information | field_related_information.` exists.
   - Select **Edit** under the Operations column for the **Related Information** field and confirm the following:
      - [ ] Label: Related Information
      - [ ] Help text: Add up to 5 link teasers.
      - [ ] Paragraph Type: Link teaser
   - Select **Field Settings** tab and confirm the following:
      - [ ] Allowed number of values: Limited: 5
- Navigate back to the **Manage Fields** tab and select the **Manage form display** tab.
   - [ ] Confirm Related Links field is disabled
   - [ ] Confirm Related Information field is below the VA Benefit Hubs field
   - [ ] Confirm widget is Paragraphs EXPERIMENTAL
   - Select Gear icon associated with the **Related Information** field and confirm the following:
      - [ ] Paragraph Title: Link teaser
      - [ ] Plural Paragraph Title: Link teaser
      - [ ] Enable widget features: Only Collapse/Edit all is selected
- Select the **Manage display** tab.
   - [ ] Confirm Related Links field is disabled
   - [ ] Confirm Related Information field is below the VA Benefit Hubs field

## media_list_videos

- [ ] Navigate to `/admin/structure/types/manage/media_list_videos/fields`
   - [ ] New field `Related Information | field_related_information.` exists.
   - Select **Edit** under the Operations column for the **Related Information** field and confirm the following:
      - [ ] Label: Related Information
      - [ ] Help text: Add up to 5 link teasers.
      - [ ] Paragraph Type: Link teaser
   - Select **Field Settings** tab and confirm the following:
      - [ ] Allowed number of values: Limited: 5
- Navigate back to the **Manage Fields** tab and select the **Manage form display** tab.
   - [ ] Confirm Related Links field is disabled
   - [ ] Confirm Related Information field is below the VA Benefit Hubs field
   - [ ] Confirm widget is Paragraphs EXPERIMENTAL
   - Select Gear icon associated with the **Related Information** field and confirm the following:
      - [ ] Paragraph Title: Link teaser
      - [ ] Plural Paragraph Title: Link teaser
      - [ ] Enable widget features: Only Collapse/Edit all is selected
- Select the **Manage display** tab.
   - [ ] Confirm Related Links field is disabled
   - [ ] Confirm Related Information field is below the VA Benefit Hubs field

## q_a

- [ ] Navigate to `/admin/structure/types/manage/q_a/fields`
   - [ ] New field `Related Information | field_related_information.` exists.
   - Select **Edit** under the Operations column for the **Related Information** field and confirm the following:
      - [ ] Label: Related Information
      - [ ] Help text: Add up to 5 link teasers.
      - [ ] Paragraph Type: Link teaser
   - Select **Field Settings** tab and confirm the following:
      - [ ] Allowed number of values: Limited: 5
- Navigate back to the **Manage Fields** tab and select the **Manage form display** tab.
   - [ ] Confirm Related Links field is disabled
   - [ ] Confirm Related Information field is below the VA Benefit Hubs field
   - [ ] Confirm widget is Paragraphs EXPERIMENTAL
   - Select Gear icon associated with the **Related Information** field and confirm the following:
      - [ ] Paragraph Title: Link teaser
      - [ ] Plural Paragraph Title: Link teaser
      - [ ] Enable widget features: Only Collapse/Edit all is selected
- Select the **Manage display** tab.
   - [ ] Confirm Related Links field is disabled
   - [ ] Confirm Related Information field is below the VA Benefit Hubs field

## Spec Tool
- [ ] spec tool is updated

## Definition of Done
- [ ] Product release are written (or in progress), if required.
- [ ] Documentation has been updated, if applicable.

### CODE REVIEW

**Comment by swirtSJW** [comment]
@kaise-lafrai  Can you make the QA steps more granular?  Example, If there are three content types to check, there should be a validation step with a path to visit for each one.   Generally we want the steps to be able to be performed by someone who is not a developer.

**Comment by kaise-lafrai** [comment]
> @kaise-lafrai Can you make the QA steps more granular? Example, If there are three content types to check, there should be a validation step with a path to visit for each one. Generally we want the steps to be able to be performed by someone who is not a developer.

Absolutely!

**Review by oksana-c — COMMENTED** [review]
noting that we need to bring `field_related_links` back and have it disabled in "Form display" config before this is ready to go to prod.

[updated] P.S. just noticed WIP tag, duh 👍

**Comment by oksana-c** [comment]
also noting that new `field_related_information` is configured per spec on all requested content types - ✅  checked on devshop.

**Review by oksana-c — DISMISSED** [review]
needs behat conflict resolution, but otherwise good to go 👍

**Comment by kelsonic** [comment]
What time will this be deployed today? 🙂

**Comment by oksana-c** [comment]
@kelsonic , just seeing this message. This is already on prod. Deployed happened Friday 3:30pm.

**Comment by kelsonic** [comment]
Perfect, thanks for the update! 🙂

**Pull request merged**
