### PR TITLE
VACMS-9696: Create phone number audit.

### PR DESCRIPTION
**Pull request by msbtterswrth**
## Description

Relates to #9696. 

## Testing done
manual, behat

## Screenshots
image

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As CMS admin
1. Visit the new phone audit `admin/content/audit/phone-numbers`
   - [x] Validate that phone numbers are able to be searched via string
   - [x] Validate that phone numbers appear as columns in the view
   - [ ] Validate that the report can be exported

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by swirtSJW — COMMENTED** [review]
Facility Title?
image



Can we sort on the various phone columns to make it easier to bubble things in one column to the top?

image

**Comment by swirtSJW** [comment]
Minor:  Consistent tab casing would make this more polished too   
image

**Comment by swirtSJW** [comment]
Does this close #9696  I see a reference in the issue to search rich text, but this doesn't do that.

**Comment by msbtterswrth** [comment]
@swirtSJW This does not close 9696, but it does relate to it. I used the HTML entity usage module to complete the rich text search for that portion.

**Comment by swirtSJW** [comment]
Trying to download the csv after filtering fails
image

**Comment by swirtSJW** [comment]
> As for the columns. I could TOTALLY combine them into one...
@msbtterswrth  I was not suggesting making them into one.  Just making each one sortable individually.

**Comment by swirtSJW** [comment]
> I also updated the casing.
@msbtterswrth It didn't stick
image

**Comment by msbtterswrth** [comment]
Updated: 
image

**Comment by msbtterswrth** [comment]
ahhhhh @swirtSJW can you help me figure out what's going on with it? i don't see anything out of place, and I copied one of the other exports to make it...

**Comment by swirtSJW** [comment]
@msbtterswrth I poked at this a bit more.  It is not the view itself, it is the preview.   being unlimited rows  and multi field... it is just choking trying to display the preview.
Part of it is resolve by 
image


This is problematic too.  Is there a reason all the data export displays are named the same?
image

I am going to tweak these while I am in here and add them to your PR.

**Comment by swirtSJW** [comment]
I adjusted the names and order of the displays.
image

**Review by swirtSJW — DISMISSED** [review]
Checks out good now.

Noting that the last column is missing because it is an entity ref and will not show up in string search.  https://dsva.slack.com/archives/CT4GZBM8F/p1657205887326079?thread_ts=1657204621.166169&cid=CT4GZBM8F

image

**Review by swirtSJW — APPROVED** [review]

**Comment by swirtSJW** [comment]
This is good and set to auto merge if tests pass.

**Review by ndouglas — APPROVED** [review]

**Pull request merged**
