### PR TITLE
VACMS-7009: Video link text label is not making it to the FE

### LINKED ISSUE #7009: Video link text label is not making it to the FE
## Describe the defect

Editors are asked to enter Link text for videos, but the FE is not using it, it just says "Go to video". The node view (proofing) experience in Drupal is the same. 

This was reported by Nikki @ VA Houston in [Jira issue 2647](https://va-gov.atlassian.net/browse/VAHELP-2647)

## To Reproduce
1. [Edit node 23174](https://prod.cms.va.gov/node/23174/edit) and see the link text for the video was entered as "Find out more about Pharmacy Residency programs at VA Houston."
2. [View node 23174](https://prod.cms.va.gov/houston-health-care/work-with-us/internships-and-fellowships/pharmacy-residencies) and see that the link text is "Go to video"
3. Go to [the FE page](https://www.va.gov/houston-health-care/work-with-us/internships-and-fellowships/pharmacy-residencies)

It should say "Find out more about Pharmacy Residency programs at VA Houston."

## Expected behavior

The FE should show the link text "Find out more about Pharmacy Residency programs at VA Houston." not "Go to video"

## Screenshots 

<details><summary>Screenshot</summary>

Edit

Node view

FE

</details>

 ## Additional context

This is probably two different defects, one in the CMS and one in the FE

* Looks like this was added to [the node view experience here](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/b098ef0be3a3300053683e5b050c8062828093c9/docroot/themes/custom/vagovadmin/templates/paragraph/paragraph--downloadable-file.html.twig#L48) as part of some work to improve the KB experience
* It seems like the link text is not being used in Drupal twig for the CMS experience (based on the history of the above code change)
* [The FE is hardcoded to use "Go to video".](https://github.com/department-of-veterans-affairs/content-build/blob/79033e6d54d3e46bde08bc9adcd41d9480a3198f/src/site/paragraphs/downloadable_file.drupal.liquid#L55) We'll want to confirm with VAMC product owners that we want that to respect the link text managed in the CMS. 
 

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

### PR DESCRIPTION
**Pull request by netboss**
- Updated video link text in paragraph twig template.
- FE PR: https://github.com/department-of-veterans-affairs/content-build/pull/803
## Description

closes #7009 

## Screenshots
VACMS-7009-video-link-text-fixed

## QA steps

As user editor
- [x] Go to `/houston-health-care/work-with-us/internships-and-fellowships/pharmacy-residencies/` (node 23174) to verify and confirm that the link text for the video is "_**Find out more about Pharmacy Residency programs at VA Houston.**_" and not "_**Go to video**_".

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [ ] `Sitewide CMS Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by swirtSJW — APPROVED** [review]
This looks good Ivan.  We will wait to merge this until the front-end fix has been merged in so that there is parity.

**Comment by swirtSJW** [comment]
When you create the front end PR please reference it here.

**Comment by swirtSJW** [comment]
Also this needs some QA steps.

**Comment by netboss** [comment]
@swirtSJW 
Front-end changes PR: https://github.com/department-of-veterans-affairs/content-build/pull/803

**Comment by netboss** [comment]
Rebased

**Review by swirtSJW — APPROVED** [review]
Nice work with your first coordination with the FE.

**Pull request merged**
