### PR TITLE
VACMS-0000: Fixes issue with va/tests/status-error task.

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

This line in the task file is problematic:

```bash
line_count=\$(grep -c "^.+$" <<< \$lines)
```

Grep uses basic regular expressions by default.  In basic regular expressions, the `+` has no special meaning and needs to be escaped to function as expected here.

The current version of Drush evaluates the previous line as follows:

Screen Shot 2021-05-04 at 12 58 09 PM

This is almost useless, and I'm sure there's an upstream issue for this somewhere in the drush-ops repo, but at the moment tests can pass that should be failing, and that's my primary concern.  Anyway, it outputs _something_, and that's sufficient for our needs.

However, if we test the `grep` expression above against that string, we don't get a hit:

```bash
www-data@30b6e1a82854:/app$ lines=7
www-data@30b6e1a82854:/app$ grep -c "^.+$" <<< $lines
0
```

but do with the `+` escaped:

```bash
www-data@30b6e1a82854:/app$ grep -c "^.\+$" <<< $lines
1
```

Unfortunately, I don't think the replacement is all that great either because of the likelihood of false positives:

```bash
www-data@30b6e1a82854:/app$ grep -c "^.+$" <<< $(echo "")
0
www-data@30b6e1a82854:/app$ grep -c "^.\+$" <<< $(echo "")
0
www-data@30b6e1a82854:/app$ grep -c "^.+$" <<< $(echo " ")
0
www-data@30b6e1a82854:/app$ grep -c "^.\+$" <<< $(echo " ")
1
www-data@30b6e1a82854:/app$ grep -c "^.+$" <<< $(echo "\n")
0
www-data@30b6e1a82854:/app$ grep -c "^.\+$" <<< $(echo "\n")
1
www-data@30b6e1a82854:/app$ grep -c "^.+$" <<< $(echo "\n\n")
0
www-data@30b6e1a82854:/app$ grep -c "^.\+$" <<< $(echo "\n\n")
1
```

I suggest replacing this with `grep -c "\S"`, which will count only lines with non-whitespace characters.

```bash
www-data@30b6e1a82854:/app$ grep -c "\S" <<< ""     
0
www-data@30b6e1a82854:/app$ grep -c "\S" <<< $(echo "")
0
www-data@30b6e1a82854:/app$ grep -c "\S" <<< $(echo -e "")
0
www-data@30b6e1a82854:/app$ grep -c "\S" <<< $(echo -e "\n")
0
www-data@30b6e1a82854:/app$ grep -c "\S" <<< $(echo -e "\n\n")
0
www-data@30b6e1a82854:/app$ grep -c "\S" <<< $(echo -e "\n7\n")
1
```

## QA steps

As user _uid_ with _user_role_
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue
- [ ] This
- [ ] That
- [ ] The other thing

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by indytechcook** [comment]
@ndouglas can you create a broken PR off this one to prove it catches it ok?

**Comment by ndouglas** [comment]
Sure.

**Comment by ndouglas** [comment]
@indytechcook See #5240

**Comment by ndouglas** [comment]
Actually, didn't realize that Drush's `--format=list` is a generic option and not specific to this -- I'm just going to extend this  PR further to add a non-stupid comment.

**Comment by ndouglas** [comment]
These tests that aren't running appear to be an issue with Tugboat's deployment of the PR env and not the PR itself.

**Pull request closed without merging**
