### PR TITLE
VACMS-13613 Add VetCenter CAP data push.

### PR DESCRIPTION
**Pull request by swirtSJW**
## Descriptio
Relates to #13613

## Blocked
This is currently blocked by Lighthouse not having an endpoint that we can push this data to.   We currently have no  place to push this data to.  Once Lighthouse builds and endpoint to receive this data, which hopefully will be the same endpoint we need to push VBA data, then we can proceed with test pushes to make sure they receive it.

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

As user _uid_ with _user_role_
1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue
   - [ ] a
   - [ ] b
   - [ ] c

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `CMS Team`
- [ ] `Public websites`
- [ ] `Facilities`
- [ ] `User support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping the UX writer so they are ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping the UX writer to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by jilladams** [comment]
@swirtSJW can you update this PR with what the steps are to unblock merging it?

Removing sprint.

**Comment by mmiddaugh** [comment]
@swirtSJW is this work dependent on [#14083 Upgrade Address module to version 2](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/14083)?

**Comment by swirtSJW** [comment]
> @swirtSJW is this work dependent on [#14083 Upgrade Address module to version 2](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/14083)?

@mmiddaugh It is no dependent on 14083, however if 14083 were to land first, this code would likely need to be adjusted in the same way our other code needs adjusting.

**Comment by swirtSJW** [comment]
> @swirtSJW can you update this PR with what the steps are to unblock merging it?

@jilladams  Sorry I missed this.  I added a "blocked" section to the description

**Comment by swirtSJW** [comment]
@jilladams I need to recreate this PR because currently it is from my fork which will likely disappear in a puff of smoke when they remove me from the repo in Feb.

**Comment by swirtSJW** [comment]
Closing this in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16837 (same code just deconflicted and moved to branch in the primary repository.

**Pull request closed without merging**
