### PR TITLE
VACMS-2312: User guides content model part 2, and theming.

### PR DESCRIPTION
**Pull request by kevwalsh**
## Description

See #2312 and #2438 

## Testing done
Manual

User_guide_strategy_•_Agile_Six_Workspace

## QA steps

As admin 

1. Edit /node/6501/edit, a Detail page
1. Add a content block
  - [x] In the paragraphs browser, you SHOULD NOT see "Lists of links"
1. Edit /node/6454/edit, a CMS user guide page
1. Add content block
  - [x] In the paragraphs browser note the new content block type "Lists of links"
 a section header for each list of links
  - [x] Add a "list of link teasers" and 6 link teasers. Add an optional section header. 
  - [x] Add a "Lists of links" and add 4 lists of links
     - [ ] Add a "final link" for 2 of these 4.
     - [ ] Add an optional section header
1. Add two "Related user guides"

1. Save

Review ACs from #2312 
  - [x] Add H1 to top of proofing block (done previously)
  - [x] Remove irrelevant blocks: Recent changes, Preview button, Owner (done previously)
  - [x] Remove broken links report from documentation content type (done previously)
  - [x] Fix breadcrumb bug (breadcrumbs not showing past first level) (done previously)
  - [ ] Adjust font size for headings (headings are now smaller)
  - [ ] Implement lite CSS adjustments(line spacing btwn headings, padding btwn text and tables)
  - [ ] Limit body column width to ~95 characters for readability

New ACs based on #2438 content model updates
- [ ] List of links should have an h3 section header

### CODE REVIEW

**Comment by kevwalsh** [comment]
This PR eclipses #2439

**Comment by rachel-kauff** [comment]
@kevwalsh It's starting to look really good! Here's a few adjustments I can see that would help make it even better:

1.  A few adjustments to the size of the border/margin around the paragraphs to better group visual grouping
  - Currently you can add headings to individual columns, but not the 3 column layout element as a whole. Adding a wysiwyg is a good workaround, but doing it that way adds too much space btwn the bottom of the wysiwyg and the top of the 3 column layout.
  - Same thing goes for the space at the bottom of the 3 column layout and the top of the next heading/wysiwyg. (see attached screenshot.
  - Not sure what the solution is here, and what the implications would be for view experience elsewhere, but it would be great if we could adjust the border sizes for these paragraphs.

CMS-help-center-Veterans-Affairs

2. 3 column layout paragraph is a little too responsive. (see screenshot)
Screen Shot 2020-07-28 at 9 00 31 AM

3. Is it possible to add the "See more guides on login and account" link to the bottom of a column so that users can get to the associated landing page for that topic, similar to the pattern you showed me for learning center?
Screen Shot 2020-07-28 at 9 36 42 AM

**Comment by rachel-kauff** [comment]
@kevwalsh Another spacing note for the teasers
Screen Shot 2020-07-28 at 9 50 14 AM

**Comment by rachel-kauff** [comment]
One more thing: 
Screen Shot 2020-07-28 at 9 56 28 AM

**Comment by rachel-kauff** [comment]
@kevwalsh Also also:

Screen Shot 2020-07-28 at 4 03 18 PM

**Comment by kevwalsh** [comment]
@rachel-kauff i've made a number of changes:

1. Got rid of 3 column layout, and replaced with with a new paragraph type called "Lists of links" (multiple lists of multiple links) in which you can add as many "List of links" (singular list, multiple links) as you like.  Lists of links has an optional section header. 

2. Added a new, optional "final link" field to the "List of links" content block. I don't love the editorial experience or the field name, but that can be updated later. It appears bolded but you'll have to put in your own ">" for now. 

3. Updated CSS 
* so that both Lists of links OR Lists of link teasers appear in a grid, with the same vertical height. You still might want to aim for sets of 3s, but the CSS doesn't care anymore. 
* Updated some h2 and h3 and link spacing, although i'm sure there's still lots that could be improved.
* Made the whole page 1280px maximum. i don't love this yet, but it's better than before. 

CMS_Help___Veterans_Affairs

**Comment by kevwalsh** [comment]
@swirtSJW this is ready for code review now.

**Pull request merged**
