### PR TITLE
DNM: VACMS-15385: Event Email CTA

### PR DESCRIPTION
**Pull request by dsasser**
# Do not merge until the FE work is ready.

## Description
This PR adds the ability to define an Email address for an Event CTA. In order to allow the editor to specify URL or Email, an additional field, 'How to apply', controls the visibility of the URL and Email fields based on its value.

The flow of setting a CTA has changed, such that once a user chooses any 'Call to Action' value other than 'none', the new 'how to apply' field is revealed and requires a user to set either an Email or URL value.

Summary of changes
- Adds a new 'How to apply' field to the Event content type
- Adds a new 'Email" field to the Event content type
- New constraint to prevent setting a mailto: in the URL field
- New constraint to prevent setting the Email to any address outside of va.gov
- Updates existing Event client-side javascript to control visibility for the new fields.
- Updates/add cypress tests

Relates to #15385

### Before
Before - Event registration URL

### After
After - Event registration no CTA
After - Event registration Email
After - Event registration URL
After - Event registration How to Sign Up

## QA steps
[TBD]
What needs to be checked to prove this works?
What needs to be checked to prove it didn't break any related things?
What variations of circumstances (users, actions, values) need to be checked?

### Test existing Event with URL

As a content admin

1. visit https://cms-fwlvssypud9glye0p1gfv4hmamkufgpi.ci.cms.va.gov/node/44574/edit
2. Scroll to the 'Registration' fieldset
   - [x] Validate that 'Call to Action' is set to 'Register'
   - [x] Validate that 'How to Sign Up' is set to 'URL'
   - [x] Validate that 'URL' is set to 'https://dashboard.teletownhall.us/registration/CP4BJYA9XFM2'

### Test field conditional display

As a content admin

3. Visit https://cms-fwlvssypud9glye0p1gfv4hmamkufgpi.ci.cms.va.gov/node/add/event
4. Select the 'Include registration information' checkbox
   - [x] Validate the 'Call to action' field is set to "- None - "
5. Select 'Register'
   - [x] Validate the 'How to apply' field appears.
6. Select 'URL' in the 'How to apply' field.
   - [x] Validate the 'URL' field appears.
7. Select 'Email' in the 'How to apply' field.
   - [x] Validate the 'Email' field appears.

### Test validations

As a content admin

8. Visit https://cms-fwlvssypud9glye0p1gfv4hmamkufgpi.ci.cms.va.gov/node/add/event
10. Select the 'Include registration information' checkbox
11. Select the 'Apply' value in the 'Call to action' field
12. Select the 'URL' option in the 'How to apply' field
13. Enter "mailto:test@example.com" in the 'URL' field.
14. Fill other required fields for the Event, and save.
   - [x] Validate you receive an error on the 'URL' field: "Links to email addresses are not allowed."
15. Change the 'How to apply' option to 'Email'
16. Enter "test@example.com" in the Email field, and save the node.
   - [x] Validate you receive the error message: "The email must be a VA.gov email address."

### Definition of Done

- [x] Documentation has been updated, if applicable.
- [x] Tests have been added if necessary.
- [x] Automated tests have passed.
- [x] Code Quality Tests have passed.
- [x] Acceptance Criteria in related issue are met.
- [x] Manual Code Review Approved.
- [x] If there are field changes, front end output has been thoroughly checked.

### Select Team for PR review

- [ ] `CMS Team`
- [x] `Public websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

### CODE REVIEW

**Comment by dsasser** [comment]
@laflannery This needs an a11y review
@thejordanwood this needs a design review
@jilladams && @FranECross this needs a PM review

**Review by ndouglas — APPROVED** [review]
All QA steps passed 🙂 

I appreciate the work done in tests too ❤️

**Comment by laflannery** [comment]
A couple comments:
- We should do our best to help users make successful form inputs and avoid errors whenever possible. This means that we should put all requirements in the help text/instructions. This wasn't done for the "va.gov" requirement (I think this was mostly because it was a late addition)
  - Can we change the help text to "Add a VA.gov email address that people can contact to sign up for this event. Use a general VA email address whenever possible. Example: contact@va.gov."
- For the error message itself, there is italic font. We should never use italics because it goes against the VA content guidelines and it's not ideal for readability. I have 2 suggestions for changing this (but open to others):
  - Remove italics completely so everything is just standard text but this might not be preferred by design because there would be no distinction between the field value and the other text.
  - Change the error message entirely to be more generic and don't include the field value - "The email must be a VA.gov email address."

**Comment by dsasser** [comment]
@thejordanwood && @laflannery I made the changes requested above. Could you please take another look? Thank you!

**Comment by thejordanwood** [comment]
@dsasser Thanks for making those changes! This looks good to me.

**Comment by laflannery** [comment]
@dsasser Looks good, thanks!

**Comment by FranECross** [comment]
@dsasser PM review done and looks great! Thanks.

**Pull request merged**
