### PR TITLE
PR-348 Added Behat tests to tests.yml.

### PR DESCRIPTION
**Pull request by schiavo**
Testing integration.

### CODE REVIEW

**Comment by jonpugh** [comment]
@schiavo Can you open a new PR on this branch so we have a cleaner looking PR for demo?

**Comment by jonpugh** [comment]
ohh wait I see,.... the comments will always be there :)

**Comment by ElijahLynn** [comment]
This was just for demo right? Closing for now.

**Comment by jonpugh** [comment]
Nah, @ElijahLynn we need a PR for behat, might as well be this one, yeah?

**Comment by ElijahLynn** [comment]
K, I didn't see anything added for behat and usually the branch is named after the story so let's open a new one with the right branch name.

**Pull request closed without merging**
