### PR TITLE
WIP: VAGOV-000 `develop` Test 

### PR DESCRIPTION
**Pull request by ElijahLynn**

### CODE REVIEW

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-166<br><br> [button_visit-site](http://pr-166.va.agile6.com)

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-166<br><br> [button_visit-site](http://pr-166.va.agile6.com)

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
Above BUILD is VAEC only, accessible only through SOCKS proxy.

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-166<br><br> [button_visit-site](http://pr-166.va.agile6.com)

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-166<br><br> [button_visit-site](http://pr-166.va.agile6.com)

**Comment by ElijahLynn** [comment]
build

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-166<br><br> [button_visit-site](http://pr-166.va.agile6.com)

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-166<br><br> [button_visit-site](http://pr-166.va.agile6.com)

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by ElijahLynn** [comment]
build

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-166<br><br> [button_visit-site](http://pr-166.va.agile6.com)

**Comment by ElijahLynn** [comment]
build

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-166<br><br> [button_visit-site](http://pr-166.va.agile6.com)

**Comment by ElijahLynn** [comment]
build

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-166<br><br> [button_visit-site](http://pr-166.va.agile6.com)

**Comment by ElijahLynn** [comment]
build

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-166<br><br> [button_visit-site](http://pr-166.va.agile6.com)

**Pull request merged**
