### PR TITLE
VAGOV-1759: Add seckit, password_policy, config_split, env_indicator. 

### PR DESCRIPTION
**Pull request by andyhawks**
https://va-gov.atlassian.net/browse/VAGOV-1759

### CODE REVIEW

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-177<br><br> [button_visit-site](http://pr-177.va.agile6.com)

**Comment by andyhawks** [comment]
rebuild

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-177<br><br> [button_visit-site](http://pr-177.va.agile6.com)

**Comment by ElijahLynn** [comment]
This appears to be failing because the containers keep restarting because of:

wait-for-it.sh: waiting 120 seconds for database:3306
wait-for-it.sh: database:3306 is available after 29 seconds
[success] Cache rebuild complete.
[warning] The following profile is missing from the file system: headless_lightning bootstrap.inc:276
[warning] The following profile is missing from the file system: headless_lightning bootstrap.inc:276
[success] No database updates required.
+------------+------------------------------------------------------+-----------+
| Collection | Config | Operation |
+------------+------------------------------------------------------+-----------+
| | password_policy.password_policy.va_gov_cms | Create |
| | password_policy.settings | Create |
| | field.storage.user.field_password_expiration | Create |
| | field.storage.user.field_last_password_reset | Create |
| | field.field.user.user.field_password_expiration | Create |
| | field.field.user.user.field_last_password_reset | Create |
| | core.entity_form_display.user.user.default | Create |
| | environment_indicator.settings | Create |
| | environment_indicator.switcher.agile_six_dev | Create |
| | environment_indicator.switcher.agile_six_stg | Create |
| | environment_indicator.switcher.local | Create |
| | environment_indicator.switcher.local2 | Create |
| | environment_indicator.switcher.local3 | Create |
| | environment_indicator.switcher.local4 | Create |
| | environment_indicator.switcher.vaec_dev | Create |
| | environment_indicator.switcher.vaec_production | Create |
| | environment_indicator.switcher.vaec_production_alias | Create |
| | environment_indicator.switcher.vaec_staging | Create |
| | seckit.settings | Create |
| | core.extension | Update |
| | lightning_core.versions | Update |
+------------+------------------------------------------------------+-----------+
// Import the listed configuration changes?: yes.
[notice] Synchronized extensions: install color.
[notice] Synchronized extensions: install config_filter.
[notice] Synchronized extensions: install seckit.
[notice] Synchronized extensions: install config_split.
[notice] Synchronized extensions: install environment_indicator.
In ContentEntityBase.php line 586:
Field field_last_password_reset is unknown.
config:import [--preview [PREVIEW]] [--source SOURCE] [--partial] [--diff] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--druplicon] [--xh-link XH-LINK] [--notify [NOTIFY]] [--] <command> [<label>]

**Comment by ElijahLynn** [comment]
Here are the errors I received locally after checking out this PR and then `lando db-sync-stg`:

> 
>  // Import the listed configuration changes?: yes.                                                                                                                                                                  
> 
>  [error]  Drupal\Core\Config\ConfigImporterException: There were errors validating the config synchronization.                                                                                                      
> Unable to install the <em class="placeholder">config_filter</em> module since it does not exist.          
> Unable to install the <em class="placeholder">config_split</em> module since it does not exist.           
> Unable to install the <em class="placeholder">environment_indicator</em> module since it does not exist.  
> Unable to install the <em class="placeholder">password_policy</em> module since it does not exist.        
> Unable to install the <em class="placeholder">password_policy_character_types</em> module since it does not exist.                                                                                                  
> Unable to install the <em class="placeholder">password_policy_characters</em> module since it does not exist.                                                                                                       
> Unable to install the <em class="placeholder">password_policy_length</em> module since it does not exist. 
> Unable to install the <em class="placeholder">password_policy_username</em> module since it does not exist.                                                                                                         
> Unable to install the <em class="placeholder">seckit</em> module since it does not exist. in Drupal\Core\Config\ConfigImporter->validate() (line 737 of /app/docroot/core/lib/Drupal/Core/Config/ConfigImporter.php).
>  
> 
> In ConfigImportCommands.php line 259:
>                                                                                                                                                                                                                     
>   The import failed due to the following reasons:                                                                                                                                                                   
>   Unable to install the <em class="placeholder">config_filter</em> module since it does not exist.                                                                                                                  
>   Unable to install the <em class="placeholder">config_split</em> module since it does not exist.                                                                                                                   
>   Unable to install the <em class="placeholder">environment_indicator</em> module since it does not exist.                                                                                                          
>   Unable to install the <em class="placeholder">password_policy</em> module since it does not exist.                                                                                                                
>   Unable to install the <em class="placeholder">password_policy_character_types</em> module since it does not exist.                                                                                                
>   Unable to install the <em class="placeholder">password_policy_characters</em> module since it does not exist.                                                                                                     
>   Unable to install the <em class="placeholder">password_policy_length</em> module since it does not exist.                                                                                                         
>   Unable to install the <em class="placeholder">password_policy_username</em> module since it does not exist.                                                                                                       
>   Unable to install the <em class="placeholder">seckit</em> module since it does not exist.                                                                                                                         
>                                                                                                                                                                                                                     
>

**Comment by ElijahLynn** [comment]
The build job needs to fail on these.

**Comment by ElijahLynn** [comment]
Oh, didn't run composer install first, which build job does. Local error is same as PR:

> In ContentEntityBase.php line 586:
> Field field_last_password_reset is unknown.

**Comment by andyhawks** [comment]
thx for the debug @ElijahLynn , much appreciated.

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-177<br><br> [button_visit-site](http://pr-177.va.agile6.com)

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-177<br><br> [button_visit-site](http://pr-177.va.agile6.com)

**Pull request merged**
