### PR TITLE
VACMS-4077 Hide field labels and source data for entity field fetch fields.

### PR DESCRIPTION
**Pull request by swirtSJW**
## Description

See #4077 and #4138.

## QA steps

As user _uid_ with _user_role_
1. As an admin go to https://pr4224-0d61wv7bdc2wtwjdqvqwb9r4mdg3qbrt.ci.cms.va.gov/node/add/vamc_system_policies_page
- [x] Validate the field labels are NOT showing  on the entity_field_fetch fields.
image
- [x] validate that the source data is not showing.
image

- [x] Validate that the updated date is showing.
image

- [ ] Go to node view for the sample you created in prior steps.  Validate that the field labels for centralized content are not present.
image

### Definition of Done

- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by kaise-lafrai** [comment]
Thanks Steve.

**Comment by kaise-lafrai** [comment]
@swirtSJW This looks great! I'll go ahead and approve/merge this so I can update the labels to visually-hidden under manage display. 
d

**Comment by kaise-lafrai** [comment]
@swirtSJW On second thought. Do we want to make that update in this PR? Update the labels of the entity fetch fields to visually-hidden under manage display?

**Comment by swirtSJW** [comment]
> @swirtSJW On second thought. Do we want to make that update in this PR? Update the labels of the entity fetch fields to visually-hidden under manage display?
Good catch.  I forgot about the node view.   I'll update this PR

**Comment by swirtSJW** [comment]
@kaise-lafrai  I cherry-picked in your behat changes and updated field labels on node view to be hidden.

**Comment by kaise-lafrai** [comment]
@swirtSJW 

I think we need to add the labels back into the behat test. Right now they are empty for those for EFFF fields. 

I am not able to see the developer data under inspect element: AC: Dev data should only be shown upon inspection of source code.

**Comment by kaise-lafrai** [comment]
Thanks for combining all this work into a single ticket @swirtSJW !

**Pull request merged**
