### PR TITLE
1543 basic page ax improvements

### PR DESCRIPTION
**Pull request by kevwalsh**

### CODE REVIEW

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-123<br><br> [button_visit-site](http://pr-123.va.agile6.com)

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-123<br><br> [button_visit-site](http://pr-123.va.agile6.com)

**Comment by andyhawks** [comment]
rebuild

**Comment by mbenziane** [comment]
Created an environment test-vagovcms#pr-123<br><br> [button_visit-site](http://pr-123.va.agile6.com)

**Pull request merged**
