### PR TITLE
VACMS-12108: lovell federal list pages should show urls with links

### LINKED ISSUE #12108: Lovell Federal list pages (stories, events, news)  should show appropriate va.gov urls with links
List pages set to section Lovell Federal Health care have a FE urls that are always show as "pending".  Its list items are harvested and copied to Lovell VA and Lovell Tricare.  It correctly shows those as the urls, but shows them as pending.  But if you copy and paste them, they do resolve correctly.
~Therefore, either of two things should happen~
~A) The va.gov url should not be displayed, because there is none.~
~B) the dual links for the Lovell VA and Lovell Tricare variants should be shown.~ 

~Recommendation:  **Option A** is not only the easier choice, it is the least confusing for editors, and less likely to break as otherwise we have to hard code in the alternate listing pages.~

## ACs
- [x] on Lovell Federal Events list  node https://prod.cms.va.gov/lovell-federal-health-care/events the va.gov url should display 2 useable links in the right sidebar
- [ ]  on Lovell Federal news release list node https://prod.cms.va.gov/lovell-federal-health-care/news-releases the va.gov url should display 2 useable links in the right sidebar
- [ ] on Lovell Federal stories list node https://prod.cms.va.gov/lovell-federal-health-care/stories the va.gov url should display 2 useable links in the right sidebar
- [ ] separate curls should be made for each link showing in the right sidebar.

### PR DESCRIPTION
**Pull request by JayDarnell**
## Description

Closes #12108 

## Testing done

Manual testing

## Screenshots

Events list page (for umbrella system)
Screenshot 2023-01-05 at 4 33 31 PM

Stories list page (for umbrella system)
Screenshot 2023-01-05 at 4 34 16 PM

News release list page (for umbrella system)
Screenshot 2023-01-05 at 4 35 02 PM

## QA steps

- [x] https://cms-vhijhwrq9t4gdmtjpx2b3ywasvito9ez.ci.cms.va.gov/lovell-federal-health-care/events the va.gov url should display 2 useable links in the right sidebar
- [x] https://cms-vhijhwrq9t4gdmtjpx2b3ywasvito9ez.ci.cms.va.gov/lovell-federal-health-care/news-releases the va.gov url should display 2 useable links in the right sidebar
- [x] https://cms-vhijhwrq9t4gdmtjpx2b3ywasvito9ez.ci.cms.va.gov/lovell-federal-health-care/stories the va.gov url should display 2 useable links in the right sidebar
- [ ] Separate curls should be made for each link showing in the right sidebar.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

### CODE REVIEW

**Review by swirtSJW — APPROVED** [review]
Nice refactor of the code.

- [x] https://cms-vhijhwrq9t4gdmtjpx2b3ywasvito9ez.ci.cms.va.gov/lovell-federal-health-care/events the va.gov url should display 2 useable links in the right sidebar
image

- [x] https://cms-vhijhwrq9t4gdmtjpx2b3ywasvito9ez.ci.cms.va.gov/lovell-federal-health-care/news-releases the va.gov url should display 2 useable links in the right sidebar
image

- [ ] https://cms-vhijhwrq9t4gdmtjpx2b3ywasvito9ez.ci.cms.va.gov/lovell-federal-health-care/stories the va.gov url should display 2 useable links in the right sidebar
image


- [ ] Separate curls should be made for each link showing in the right sidebar.
Not sure how to prove this, but it seems to be working and the order of ops int he code seems to support that.

Added:  

- [x] Confirm Tricare variant works https://cms-vhijhwrq9t4gdmtjpx2b3ywasvito9ez.ci.cms.va.gov/lovell-federal-tricare-health-care/stories
image

- [ ] Confirm VA variant works https://cms-vhijhwrq9t4gdmtjpx2b3ywasvito9ez.ci.cms.va.gov/lovell-federal-va-health-care/stories
image


- [ ] Confirm non-lovell works https://cms-vhijhwrq9t4gdmtjpx2b3ywasvito9ez.ci.cms.va.gov/pittsburgh-health-care/stories
image

- [ ] confirm non-ha variant works https://cms-vhijhwrq9t4gdmtjpx2b3ywasvito9ez.ci.cms.va.gov/pension
image


Nice work @JayDarnell

**Comment by swirtSJW** [comment]
Updated QA.

Christian and I logged in to web and deleted the index file for Tricare evetns then flushed cache and reloaded the CMS page
image

**Review by omahane — APPROVED** [review]
Followed the QA without issue.

**Comment by swirtSJW** [comment]
image

**Pull request merged**
