### PR TITLE
VACMS-1534: Project-specific post_api tests.

### PR DESCRIPTION
**Pull request by oksana-c**
## Description

See #1534 . 

- added phpunit tests for Post API that are project-specific. Test verifies item expiration logic, for which we have applied a core patch. It is important, because it will notify us immediately if the core patch no longer applies
- added php unit tests to DO contrib post_api that verify basic queue functionality, dedupe logic and expiration logic. NOTE: expiration logic test is reversed see [comments in code](https://git.drupalcode.org/project/post_api/-/blob/2.x/tests/src/Kernel/PostApiQueueTest.php#L59). 

P.S. this PR is constantly getting out of date, so I'll rebase again once reviewed.

## QA steps

- [ ] review added project-specific phpunit tests. Confirm they are passing within our build
- [ ] [review added drupal/post_api phpunit tests](https://www.drupal.org/project/post_api) . confirm they passing.

## Definition of Done
- [ ] Product release notes 
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

### CODE REVIEW

**Comment by swirtSJW** [comment]
This one needs a rebase and conflict resolution.

**Comment by oksana-c** [comment]
looks like one of the added phpunit tests is not picking up api host url, although it is set in env variables. Looking into this.

**Comment by oksana-c** [comment]
*-api.va.gov certificates have expired on devshop, which is causing one of the Post API tests to fail. See [Slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1591204886435000) for more context.

It appears that added Post API tests help us identify multiple issues in one swoop :)

Once cert issue is resolved, this PR can be merged and likely will need to be rebased again.

**Comment by swirtSJW** [comment]
The good news is, it passed.   The bad news is, composer lock conflict.

**Comment by oksana-c** [comment]
issue w/ failing cert verification that was blocking this PR was resolved in #1922 . Thanks @ElijahLynn @indytechcook !

**Pull request merged**
