### PR TITLE
VACMS-8274 clean up media menu

### LINKED ISSUE #8274: Clean up media menu items
## Describe the defect

We have two menu items under the the Content menu that go to the same place: Media and Media Library

We have two menu items under the Content menu with the same label "Media Library", which go to differnet places.

The Files menu item lost its home under Media

## To Reproduce
1. Click on the 3 menu items under Content with the word "media" in them. 

## Expected behavior

We should have only one menu item under Content with the word "media"

Other items should be children of Media. 

Ideally, this is the IA

```
Media
* Add media (with all its children)
* Images
* PDFs
* Files
* Bulk media edit
```

If we can emulate Jay's menu item approach to Facilities, that would be ideal. One differences is that a number of these menu items are defined by Drupal Core (Media, Add media and its children, and Files). 

## Screenshots 

Cursor_and_Media_-_images___VA_gov_CMS

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by msbtterswrth**
## Description
Small note: the default media tab says 'table' and neither @JayDarnell nor I could figure out why. I also combined the media - images view with the main media view.

Closes #8274 .

## Testing done
Logged in and confirmed only one media link exists in admin menu and related views are nested under it as either links or tabs. 

## Screenshots
image

image

## QA steps

As a cms user I can
1. open the 'content' menu and hover over the media item
2. click on `Media` and see the new tabs
3. Then validate Acceptance Criteria from issue
- [ ] We should have only one menu item under Content with the word "media"
- [ ] Add media links and Files link should be children of the media menu
- [ ] Media Images, Media PDFs, Bulk Edit should be tabs on the media view

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by swirtSJW** [comment]
Thanks @msbtterswrth   It seems like there are a lot of changes here that are not just related to menus.  I'll look at this after it has some detailed QA steps that you have run through first.

**Review by kevwalsh — CHANGES_REQUESTED** [review]
This is great. 

A few things, not all are necessarily blockers, we can discuss.
- [ ] Can we add menu items to the admin menu for each of the tabs as children of the Media menu item?  So that the tabs would appear both as secondary tabs AND in the admin menu. and the admin menu would be: 
```
Media
* Add media (with all its children)
* Images
* PDFs
* Files
* Bulk media edit
 ```

looks like you had this in an[ earlier iteration](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8274#issuecomment-1060934991)

<details><summary>Screenshot</summary>

Clean_up_media_menu_items_·_Issue__8274_·_department-of-veterans-affairs_va_gov-cms


</details>

- [ ] Streamline the tab labels 
  - [ ] "All media" (not "Table") should appear first
  - [ ] "Images" (not Media Images")
  - [ ] "PDFs" (not Media PDFs")
  - [ ] "Bulk edit" last

<details><summary>Screenshot</summary>

Media___VA_gov_CMS


</details>

- [ ] "Media bulk edit" parent should not exist / should not appear when Bulk edit is active

<details><summary>Screenshot</summary>
Cursor_and_Media___VA_gov_CMS



</details>

**Comment by msbtterswrth** [comment]
Added the menu items in addition to the tabs: 
image

Updated the tab titles and removed the extra bulk edit tab: 
image


I will create a follow up for the 'table' label for the main view.

**Review by kevwalsh — APPROVED** [review]
QA pass!

**Pull request merged**
