### PR TITLE
VACMS-7154 Expand url audit view.

### LINKED ISSUE #7154: Modify url alias audit tool
## User Story or Problem Statement

As someone who needs to audit links and titles I need a report that allows sufficient filtering, searching, and export abilities
to give me data I can operate with.

## Acceptance Criteria
Broaden the scope of https://prod.cms.va.gov/admin/content/audit/detail-pages-urls
- [ ] change path to /admin/content/audit/page-urls
- [ ] Change title to `URL audit and bulk update`
- [ ] add search for url path (might not be possible in Views)
- [ ] 

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

### PR DESCRIPTION
**Pull request by swirtSJW**
## Description

closes #7154

## QA steps

As admin
1. Visit https://pr7155-qajgjssxdhvojjnkgk8kd71dnlgpsijt.ci.cms.va.gov/admin/content/audit   
2. Filter section to VISN 1.
   - [x] validate there are well more than just two items showing (~1600).
3. Filter section to "VA bedford health care"
   - [x] validate that there are around  175 items
 4. Scroll to the bottom of the page and click the  orange "CSV button"
 5. The batch should run and then return this status message 
image
6.  Clicking that link may not work.  If not copy and past the url for that link into a new tab.  It should kick off the download
7. Save the file and import it into a spreadsheet.
   - [x] Validate that the number of rows matches the number from step 3 +1 row for the header

1  Visit https://pr7155-qajgjssxdhvojjnkgk8kd71dnlgpsijt.ci.cms.va.gov/admin/content/audit/vamc-detail-pages
- [x] validate this url works
- [x] Filter by Visn 11.  Validate that roughly 280 items show up.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS team`
- [x] `Sitewide CMS Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [ ] Yes, and it's written in issue ____ and queued for publication.
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change.
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by netboss — APPROVED** [review]
@swirtSJW Looks good!

**Comment by swirtSJW** [comment]
@netboss If you ran through the QA steps can you check them off.   Otherwise I don't know what you did.

**Comment by netboss** [comment]
@swirtSJW Sorry, I thought this was only a code review and didn't went through the QA steps at first.

Followed the QA steps and all steps worked fine:

1. Visit https://pr7155-qajgjssxdhvojjnkgk8kd71dnlgpsijt.ci.cms.va.gov/admin/content/audit   
2. Filter section to VISN 1.
   - [x] validate there are well more than just two items showing (~1600).
VACMS-7154-filter-section-VISN-1

3. Filter section to "VA bedford health care"
   - [x] validate that there are around  175 items
VACMS-7154-filter-va-bedford-health-care

 4. Scroll to the bottom of the page and click the  orange "CSV button"
 5. The batch should run and then return this status message 
VACMS-7154-click-orange-csv-button

6.  Clicking that link may not work.  If not copy and past the url for that link into a new tab.  It should kick off the download
VACMS-7154-click-orange-csv-button-download-in-new-tab

7. Save the file and import it into a spreadsheet.
   - [x] Validate that the number of rows matches the number from step 3 +1 row for the header
VACMS-7154-open-csv-spreadsheet-validate

1  Visit https://pr7155-qajgjssxdhvojjnkgk8kd71dnlgpsijt.ci.cms.va.gov/admin/content/audit/vamc-detail-pages
- [x] validate this url works
- [x] Filter by Visn 11.  Validate that roughly 280 items show up.
NOTE: There is no VISN 11 option so I filtered by VISN 1 instead. See screen shot.
VACMS-7154-no-visn-11-option

**Comment by swirtSJW** [comment]
Thanks @netboss   that was a perfect QA.  
Generally you should not approve a PR for just code alone.  It is expected that if you "approve" it that you have looked at the code for weaknesses and run the QA steps.   Othewise if you approved only part, someone might merge an un-QA's PR.

**Comment by swirtSJW** [comment]
image

**Pull request merged**
