### PR TITLE
VACMS-8861: display error message if office hours comment contains ti…

### LINKED ISSUE #8861: Standardize comment variants for time zone, closed and 24/7
## User Story or Problem Statement

We recently replaced migrated our office hours data from the old table field format to the new office hours format. The new office hours field stores three items for each day: start time, end time, and a comment. As part of that migration we cleaned up some key items that could end up in the comments field such as:

- Closed
- 24/7
- ET, CT, MT, PT (time zones)

The new office hours comment field is wide open in terms of what editors could enter. As we move forward, on node save, we should inspect the contents of the comments fields and when the contents is a variant of the above make sure the input is standardized.

Examples: 

- CLOSED, closed, Closed, Closed. - should all result in Closed
- EST, est, ET, et - should all result in ET

## Implementation steps

We can repurpose some of the code used in the office hours migration script to check comment field data on node save (with a node hook) and replace (standardize) these variants.

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

### PR DESCRIPTION
**Pull request by JayDarnell**
…me zone

## Description

Closes #8861 

## Testing done

Visual Testing

## Screenshots

Strings containing time zones as substrings are allowed (Example: the word established contains est)
Screen Shot 2022-05-20 at 2 34 13 PM

Actual time zones are not allowed
Screen Shot 2022-05-20 at 2 41 26 PM

## QA steps

As an admin user or content editor
1. Edit a VAMC Facility Non-clinical Service (in this example a register for care node) /node/46300/edit
2. Expand the service location hours field and try adding some time zones into the comments (EST, ET, CST, CT, MST, MT, PST, PT) case does not matter
3. An error should be displayed and the office hours field(s) should be highlighted in red.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

## Deployment

Once this code has been merged and deployed we will want to run the following script on production: `drush scr ./scripts/content/VACMS-8935-scrub-tz-in-hours-field-comment.php`

### CODE REVIEW

**Comment by JayDarnell** [comment]
I'll adjust the regular expression to fix that @swirtSJW

**Comment by kevwalsh** [comment]
Let's wait for #8935 to be done befor merging.

**Review by ethanteague — COMMENTED** [review]
Passes QA, but still concerned about breaking this out into a new module as opposed to using va_gov_vamc. I defer to you all. @JayDarnell @swirtSJW

**Review by ethanteague — APPROVED** [review]

**Comment by ElijahLynn** [comment]
This is a year old, closing for now, reopen if necessary.

**Pull request closed without merging**
