### PR TITLE
Remove # from standbox drush update

### PR DESCRIPTION
**Pull request by indytechcook**
This change is [Reviewable](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/1445)

### CODE REVIEW

**Comment by ElijahLynn** [comment]
Confirmed this is updating the schema now. 
> drush sql:query "select name,value from key_value where name = 'va_gov_db'"

Might be related to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1441.

**Comment by indytechcook** [comment]
Also see: https://api.drupal.org/api/examples/batch_example%21batch_example.module/8.x-1.x

**Comment by ElijahLynn** [comment]
And here is with this PR:
image

And current master shows like this, repeating the update hook name 10 times:
image

**Comment by indytechcook** [comment]
I'm merging this even with the deadlock issue so we can get this deployed since is it causing updb to break.

**Comment by ElijahLynn** [comment]
Caught this error before it was destroyed, just putting it here for now:

> [4/4] Building fresh packages...
> 
> error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/var/aegir/projects/cms/pr1445/docroot/vendor/va-gov/web/node_modules/global-agent/node_modules/core-js/es/array/virtual/join.js'".
> 
> info If you think this is a bug, please open a bug report with the information provided in "/var/aegir/projects/cms/pr1445/docroot/vendor/va-gov/web/yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> 
> Script export NODE_EXTRA_CA_CERTS=/etc/pki/tls/certs/ca-bundle.crt PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=TRUE; cd web && yarn install handling the va:web:install event returned with error code 1
> 
> Script @va:web:install was called via post-install-cmd

http://devshop.cms.va.gov/node/19482

**Pull request merged**
