### PR TITLE
VACM-9512 sitewide alert types

### LINKED ISSUE #9512: Create shield like alert types

### PR DESCRIPTION
**Pull request by tjheffner**
## Description

Closes #9512, #8299, #8300. Styles the sitewide alerts based on the figma designs seen in 9512/8299. This module has dismissible behavior included. Adds these different alerts as a component to storybook, uses that in the drupal theme.

## Testing done
- Verified that site alerts rendered with proper styles in the 3 alert types.
- Verified that dismissed alerts stay dismissed and can be un-dismissed with appropriate fields checked on form updates.
- Verified that the site shield alert blocks the full page.

## Screenshots
storybook:
Screen Shot 2022-07-06 at 4 42 34 PM

informational, dismissible:
Screen Shot 2022-07-06 at 4 41 05 PM

warning, dismissible:
Screen Shot 2022-07-06 at 4 41 34 PM

site shield, non-dismissible:
Screen Shot 2022-07-06 at 4 41 52 PM

## QA steps
- In the storybook link generated below, see that the "Sitewide Alert" component exists in the list with variations.

- Then on the environment generated below, log in as an admin user and navigate to `/admin/content/sitewide_alert`. Create a new alert.
- Start with "Informational" style, and check the box to make it dismissible. Alert Title is optional. Save your alert and see it appear on the page.
- Dismiss the alert, then edit it.
- Change the style to "Warning", and check the box to ignore previous dismissals. Save the alert.
- See that the alert has changed to yellow, and is dismissible again.
- Dismiss the alert, then edit it.
- Change the style to "Site Shield" and uncheck it as dismissible. Save the alert.
- See that the "Site Shield" style functions in the same manner as our existing site shields (full page, can scroll behind but can't click anything).
- optional: inspect and delete the site alert container so that you can edit it again and switch it off of site shield / make it inactive.

### Definition of Done

- [x] Documentation has been updated, if applicable.
- [x] Tests have been added if necessary.
- [x] Automated tests have passed.
- [x] Code Quality Tests have passed.
- [x] Acceptance Criteria in related issue are met.
- [x] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change?
- [x] No announcement is needed for this code change.
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by swirtSJW — DISMISSED** [review]
Really nice work on this @tjheffner

**Comment by swirtSJW** [comment]
Tests are all recorded a passing, so if @rachel-kauff  approves, then it is good to merge.
image

**Comment by tjheffner** [comment]
Icons updated, spacing re-aligned, alert style names updated to match.

Screen Shot 2022-07-12 at 1 22 43 PM

**Review by rachel-kauff — APPROVED** [review]
Looks great. Thank you Tanner!

**Comment by tjheffner** [comment]
Screen Shot 2022-07-13 at 1 18 46 PM, will merge after tests pass

**Pull request merged**
