### PR TITLE
VACMS-6176: Remove banner fields from alert block.

### LINKED ISSUE #6176: Remove all the banner-specific fields from alert block type
## User Story or Problem Statement

The banner node type will deprecate certain fields. 

This is blocked by PW va.gov-team issue [forthcoming] to remove dependency on FE.

## Acceptance Criteria
The following fields have been purged from alert block. 
- [ ] field_is_this_a_header_alert_
- [ ] field_alert_dismissable
- [ ] field_alert_frequency
- [ ] field_node_reference

Add_Alert_custom_block___VA_gov_CMS

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
Closes #6176

## Testing done
Behat

## Screenshots
image

## QA steps
 - [ ] As an administrator, go to `admin/structure/block/block-content/manage/alert/form-display` and visually verify page matches above screenshot.

### CODE REVIEW

**Comment by kevwalsh** [comment]
this can't be merged until FE removes dependencies on these fields.

**Comment by ethanteague** [comment]
> this can't be merged until FE removes dependencies on these fields.

Thanks for adding the tag / comment, @kevwalsh ! Apologies for not doing that.

**Comment by swirtSJW** [comment]
Updated this as it should run now that Kelsons work has been merged.

**Review by swirtSJW — APPROVED** [review]
Approved, just waiting on tests to pass.

**Comment by swirtSJW** [comment]
Looks like these fields are still in the FE query 
```
Error with GetAlerts. Scroll up for the GraphQL query that has errors:
      │ 
      │ [
      │   {
      │     "message": "Cannot query field \"fieldAlertDismissable\" on type \"BlockContentAlert\". Did you mean \"fieldAlertTitle\" or \"fieldAlertType\"?",
      │     "category": "graphql",
      │     "locations": [
      │       {
      │         "line": 11,
      │         "column": 9
      │       }
      │     ]
      │   },
      │   {
      │     "message": "Cannot query field \"fieldAlertFrequency\" on type \"BlockContentAlert\". Did you mean \"fieldAlertContent\", \"fieldAlertTitle\", or \"fieldAlertType\"?",
      │     "category": "graphql",
      │     "locations": [
      │       {
      │         "line": 12,
      │         "column": 9
      │       }
      │     ]
      │   },
      │   {
      │     "message": "Cannot query field \"fieldNodeReference\" on type \"BlockContentAlert\".",
      │     "category": "graphql",
      │     "locations": [
      │       {
      │         "line": 13,
      │         "column": 9
      │       }
      │     ]
      │   },
      │   {
      │     "message": "Cannot query field \"fieldIsThisAHeaderAlert\" on type \"BlockContentAlert\".",
      │     "category": "graphql",
      │     "locations": [
      │       {
      │         "line": 16,
      │         "column": 9
      │       }
      │     ]
      │   }
      │ ]
```

**Comment by ethanteague** [comment]
This should be ready to go, @swirtSJW

**Pull request merged**
