### PR TITLE
VACMS-4844: Fix broken events view.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #4844 

## Testing done
Visual

## Screenshots
image

## QA steps
As an administrator, go to `/admin/config/system/taxonomy-entity-index/reindex` and reindex content
Once complete, visit `/admin/content/events` and verify view is working as expected.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by kevwalsh — COMMENTED** [review]
@ethanteague this filter is not working for me. i tried "less than" "+0 day".  Am i doing something wrong? If so (actually either way) i wonder if we can improve the UI a bit.

**Comment by ethanteague** [comment]
> @ethanteague this filter is not working for me. i tried "less than" "+0 day". Am i doing something wrong? If so (actually either way) i wonder if we can improve the UI a bit.

My bad, @kevwalsh - had the wrong option checked in the offset filter. This should be fixed, but glad to change ui up however you see fit.

**Comment by kevwalsh** [comment]
LGTM. Let's worry about UI later, this is just for admins right now.

**Review by kevwalsh — APPROVED** [review]
QA pass.  UI is not ideal but i think this can wait, wasn't in scope of this defect issue.

**Review by swirtSJW — APPROVED** [review]

**Comment by swirtSJW** [comment]
image

**Pull request merged**
