### PR TITLE
VACMS-4385: Add featured content to vc.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #4385

## Testing done
Visual / behat

## Screenshots
image

## QA steps
- As an administrator, go to `/node/add/vet_center`
- Visually verify that the new featured content paragraph button appears.
- Add two, and confirm the add more button no longer appears
- Confirm both instances have a call to action button, that when clicked brings up a call to action paragraph within the parent.

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by kevwalsh — CHANGES_REQUESTED** [review]
109706422-edb6e880-7b66-11eb-9faf-a99577e862f7_png__1773×1053_

can you change this from placeholder text to textcounter widget with a soft limit?

**Comment by ethanteague** [comment]
> 109706422-edb6e880-7b66-11eb-9faf-a99577e862f7_png__1773×1053_
> 
> can you change this from placeholder text to textcounter widget with a soft limit?

My bad, @kevwalsh - updated :+1:

**Comment by indytechcook** [comment]
Is feature content something that is re-usable outside of the vets-center content type?

**Review by swirtSJW — APPROVED** [review]
Tests out ok for me.

**Comment by swirtSJW** [comment]
> Is feature content something that is re-usable outside of the vets-center content type?

It is available in some places as a paragraph to choose from 
image

But at the moment I don't think there is a request/plan for it to be used other places.

**Comment by kevwalsh** [comment]
@indytechcook @swirtSJW I'd say there's a decentt chance it will get used elsewhere at some point. [i did an audit](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1612232782625/4ab5b2335b8c53b6451f10e43e88eba800028071) and it's pretty similar to some other needs out there, particularly the featured forms on the /find-forms landing page. But also the "spotlight" on Health Services page, which should probably use this instead to get away from hard-coded "Read more" CTAs.

**Comment by indytechcook** [comment]
Thanks @kevwalsh !  In determining reusability, I also think of it from a field/content/paragraph/us case structure perspecitrve.  I'd like to keep an eye focused on building our paragraph library in a way that is reusable across products.  "Featured" is a very generic concept that would add a lot of value throughout the platform.  Have different "featured" paragraphs for different content types is going to lead to tons of duplicate code from a workflow and CMS Editorior UI perspective. 

For this PR, just renaming the paragraph to something not specific to `vets-center` is all that's really needed.

As I type this and think about it, it's featured just a boolean field on a paragraph?  Should we be able to make anything paragraphs "featured"?  My concern is focused on using the word "featured" and what it means to editors and consumers of the API.

**Comment by swirtSJW** [comment]
> Thanks @kevwalsh ! In determining reusability, I also think of it from a field/content/paragraph/us case structure perspecitrve. I'd like to keep an eye focused on building our paragraph library in a way that is reusable across products. "Featured" is a very generic concept that would add a lot of value throughout the platform. Have different "featured" paragraphs for different content types is going to lead to tons of duplicate code from a workflow and CMS Editorior UI perspective.
> 
> For this PR, just renaming the paragraph to something not specific to `vets-center` is all that's really needed.
> 
> As I type this and think about it, it's featured just a boolean field on a paragraph? Should we be able to make anything paragraphs "featured"? My concern is focused on using the word "featured" and what it means to editors and consumers of the API.

Featured in this case is not like "sticky" where it is just a flag to set for any paragraph.  It is pretty specific to this field not so much the paragraph.

I think the paragraph is already re-useable and is not specific to vetcenters.     The field however  that allows the use of the paragraph is specific to vetcenter and maybe it shouldn't be.    However it may have business logic beyond UI config  that are specific to vetcenters in which case it  is cleaner to target if it is named specific to vetcenters.

@indytechcook  are you asking that the field name be more generic?

**Comment by swirtSJW** [comment]
Approved and just resolved some conflicts so just waiting on tests to pass.  When they pass, this can be merged.

**Comment by ethanteague** [comment]
> Approved and just resolved some conflicts so just waiting on tests to pass. When they pass, this can be merged.

Thanks for doing that, buddy.

**Comment by kevwalsh** [comment]
@indytechcook wrote

> Is feature content something that is re-usable outside of the vets-center content type?

per slack, but to close the loop here (i wish i had seen my github notifications earlier) 

[this audit](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1612232782625/4ab5b2335b8c53b6451f10e43e88eba800028071) shows opportunities across products for this component. two products in particular could leverage this, beyond Vet Center: www.va.gov/find-forms and VAMC system on [the health services page](https://www.va.gov/pittsburgh-health-care/health-services/).

**Review by swirtSJW — APPROVED** [review]

**Pull request merged**
