### PR TITLE
VACMS-6302: Add content audit view display for content admins.

### PR DESCRIPTION
**Pull request by kevwalsh**
## Description

Closes to #6302. 

## Testing done

Behat

## Screenshots

Content_audit_tools___VA_gov_CMS

### Scenario 1 

As a content admin, 
- [x] you can see four tabs that are not visible to non-content admins or admins
- [x] On the Content Audit tools tab at https://pr6303-vfzlqszzyequlhikkfixqksak2oltfae.ci.cms.va.gov/admin/content/audit:
  - [x] filters work as you might expect they would (two of them are multivalue here by design, where normally they are not) 
  - [x] Clicking CSV icon at the bottom work as you'd expect, and filters previously added are respected
 

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [ ] `Core Application Team`
- [x] `Product Support Team`

### Is this PR blocked by another PR?

- [ ] `DO NOT MERGE`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [ ] No announcement is needed for this code change. 
  - [ ] Merge & carry on unburdened by announcements

### CODE REVIEW

**Comment by kevwalsh** [comment]
This is working OK, except that CSV export doesn't work. I think this is because batch processing is enabled for the CSV export view display at /admin/structure/views/view/content/edit/content_audit_csv_export 

Content__Content____VA_gov_CMS

It works fine when batch Method is changed to Standard, but i think that's a bad idea for 25K+ nodes.

**Comment by kevwalsh** [comment]
> This is working OK, except that CSV export doesn't work. I think this is because batch processing is enabled for the CSV export view display at /admin/structure/views/view/content/edit/content_audit_csv_export
> 
> Content__Content____VA_gov_CMS
> 
> It works fine when batch Method is changed to Standard, but i think that's a bad idea for 25K+ nodes.

Upon further inspection, this _kind of_ works, if you copy/paste the download link into a new tab. @swirtSJW reproduced this on Chrome for linux. We decided that this is acceptable since this is not really user-facing for now.

**Review by swirtSJW — APPROVED** [review]
Looks good. 
CSV is fully formed 
image


Only weird issue is the download link which is strange.   Tried removing all parameters from link and it still is not clickable.    Copy and pasting works fine however.

**Comment by swirtSJW** [comment]
image

**Pull request merged**
