### PR TITLE
VAGOV-1884: More flexible field help text

### PR DESCRIPTION
**Pull request by acabouet**
Installs and enables better field descriptions to module to allow site builders to put help text above or below a field.

### CODE REVIEW

**Comment by mbenziane** [comment]
rebuild

**Comment by mbenziane** [comment]
rebuild

**Comment by ElijahLynn** [comment]
rebuild - argh, " 503  Service Unavailable [IP: 130.89.148.14 80]" when building database image.

**Comment by ElijahLynn** [comment]
IP Address Exhaustion on subnet discussing here https://dsva.slack.com/archives/CDJQ0JCE4/p1555712265306800

**Comment by acabouet** [comment]
rebuild

**Pull request merged**
