### PR TITLE
VACMS-3513: Update Drupal core to 8.8.11 for SA-CORE-2020-012

### PR DESCRIPTION
**Pull request by acrollet**
## Description

See #3513 

## Testing done

- reviewed diff between 8.8.10 and 8.8.11, seeing that the only differences are related to file upload functionality
- tested uploading images to the media image content type
- ran behat + phpunit tests locally
- searched current copy of files directory for suspicious files:
  - files with double extensions (only a few images were found, e.g. `2020-07/7_30 STD web v2-2x1.jpg.png`)
  - files with dangerous extensions:
    - php: only found under the php/twig dir
    - phar: none found
    - pl: none found
    - py: none found
    - cgi: none found
    - asp: none found
    - js: none found
    - html: none found
    - htm: none found

## Screenshots

Screen Shot 2020-11-18 at 3 59 08 PM

## QA steps

As a CMS developer
1. Review `testing done` steps
1. Then validate Acceptance Criteria from issue
- [ ] There is not other file upload functionality that CMS editors rely upon

### Definition of Done

- [x] Documentation has been updated, if applicable.
- [x] Tests have been added if necessary.
- [ ] Automated tests have passed.
- [ ] Code Quality Tests have passed.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Manual Code Review Approved.

### Select Team for PR review

- [x] `Core Application Team`
- [ ] `Product Support Team`

### Does this PR need review from a Product Owner

- [ ] `Needs PO review`

### CMS user-facing annoucement

Is an announcement needed to let editors know of this change? 
- [ ] Yes, and it's written in issue ____ and queued for publication. 
  - [ ] Merge and ping @ rachel-kauff so she's ready to publish after deployment
- [ ] Yes, but it hasn't yet been written 
  - [ ] Don't merge yet -- ping @ rachel-kauff to prompt her to write and queue content
- [x] No announcement is needed for this code change. 
  - [x] Merge & carry on unburdened by announcements

### CODE REVIEW

**Review by swirtSJW — DISMISSED** [review]

**Comment by swirtSJW** [comment]
Approved, just waiting on automated testing

**Comment by swirtSJW** [comment]
QA checks out great

Going in:
image


Actually saved
image



rendered:
image

**Comment by indytechcook** [comment]
@acrollet can you fix the merge conflict.

**Review by indytechcook — APPROVED** [review]

**Comment by acrollet** [comment]
@indytechcook should we wait for re-test or go ahead and merge?

**Pull request merged**
