### PR TITLE
VACMS-10502: Adds `composer validate` GitHub Action.

### LINKED ISSUE #10502: Add a GitHub Action for `composer validate`.
## Description
See #10341.

We have an issue (as it turns out, mostly because of me) with the `composer.lock` `content-hash` not accurately representing the contents of `composer.json`, and therefore introducing further complexity and unreliability into the general development workflow.

We can guard against this in an automated fashion by adding a simple GitHub Action that runs `composer validate` on the codebase and throws an error if there is an issue.

## Acceptance Criteria
- [x] A GitHub Action exists that runs `composer validate` and errors if the lockfile isn't correct.
- [ ] The above Action is required in branch protection rules.

### PR DESCRIPTION
**Pull request by ndouglas**
## Description

Closes #10502.

## QA steps

If this and current tests pass, this should be safe to merge.

## Notes

- [ ] After this is merged, it needs to be added to branch protection rules.

### CODE REVIEW

**Comment by ndouglas** [comment]
```
     | "health_care_local_facility"     | "health_care_local_facility page2"     |
        SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction: INSERT INTO "node_field_data" ("nid", "vid", "type", "langcode", "status", "title", "uid", "created", "changed", "promote", "sticky", "default_langcode", "revision_translation_affected") VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7, :db_insert_placeholder_8, :db_insert_placeholder_9, :db_insert_placeholder_10, :db_insert_placeholder_11, :db_insert_placeholder_12); Array
        (
            [:db_insert_placeholder_0] => 49153
            [:db_insert_placeholder_1] => 679900
            [:db_insert_placeholder_2] => health_care_local_facility
            [:db_insert_placeholder_3] => en
            [:db_insert_placeholder_4] => 0
            [:db_insert_placeholder_5] => health_care_local_facility page2
            [:db_insert_placeholder_6] => 4367
            [:db_insert_placeholder_7] => 1662130751
            [:db_insert_placeholder_8] => 1662130751
            [:db_insert_placeholder_9] => 0
            [:db_insert_placeholder_10] => 0
            [:db_insert_placeholder_11] => 1
            [:db_insert_placeholder_12] => 1
        )
         (Drupal\Core\Entity\EntityStorageException)
        │
        │   ----- -------------- ------- ---------- -------------------------------------- 
        │    ID    Date           Type    Severity   Message                               
        │   ----- -------------- ------- ---------- -------------------------------------- 
        │    243   02/Sep 15:04   node    Error      Drupal\Core\Database\DatabaseExcepti  
        │                                            onWrapper: SQLSTATE[40001]:           
        │                                            Serialization failure: 1213 Deadlock  
        │                                            found when trying to get lock; try    
        │                                            restarting transaction: INSERT INTO   
        │                                            "node_field_data                      
        │    242   02/Sep 15:04   user    Notice     Session opened for t0VGbLhS.          
        │    241   02/Sep 15:04   user    Notice     Session opened for dDL8bdQf.          
        │    240   02/Sep 15:04   user    Notice     Deleted user: rfLUtUNO .              
        │    239   02/Sep 15:04   image   Warning    Could not apply Large (480×480)       
        │                                            image style to                        
        │                                            public://63121a6a5ba7f/63121a6a5ba76  
        │                                            .txt because the style does not       
        │                                            support it.                           
        │    238   02/Sep 15:04   user    Notice     Session opened for vZkOfkdN.          
        │    237   02/Sep 15:04   user    Notice     Session opened for rfLUtUNO.          
        │    236   02/Sep 15:04   user    Notice     Deleted user: wfIhvdxU .              
        │    235   02/Sep 15:04   user    Notice     Session opened for                    
        │                                            test_Michel_Abshire7.                 
        │    234   02/Sep 15:04   user    Notice     Session opened for wfIhvdxU.          
        │   ----- -------------- ------- ---------- -------------------------------------- 
        │  
        │
        └─ @AfterStep # CustomDrupal\FeatureContext::printWatchdogLogAfterFailedStep()
        │
        │  
        │  Dumped HTML to behat_failures/2022-09-02--11-04-40-perms.feature.html
        │  Dumped Text to behat_failures/2022-09-02--11-04-40-perms.feature.txt
        │  
        │
        └─ @AfterStep # CustomDrupal\FeatureContext::printHtmlAfterFailedStep()
```

Not related, obviously 😩

**Review by cweagans — APPROVED** [review]
Not sure -- do we already run this elsewhere? Should we remove it from there so we're only running it once in GHA?

**Comment by ndouglas** [comment]
@cweagans We only run this here -- we frequently have unclean lock hashes, e.g. when I locally check out a Dependabot PR, add/update a patch, and then commit the changes without running `composer update --lock` because I'm a 🤡 .

**Comment by ndouglas** [comment]
It doesn't need to be a separate action, but I'm hoping to refactor a lot of these soon to share common steps, etc.

**Pull request merged**
