### PR TITLE
VACMS-7217: Fix duplicate help text below textarea fields.

### PR DESCRIPTION
**Pull request by ethanteague**
## Description
See #7217

## Testing done
Visual / behat

## Screenshots
image

## QA steps
 - [ ] As an administrator, go to `/node/3597/edit` and open up multiple existing services via the edit button.
 - [ ] Visually verify help text appears below title, and is not duplicated.

### CODE REVIEW

**Comment by swirtSJW** [comment]
@ethanteague Is there  a future use/need  for themable_forms?

If No, is there another solution that does not involve adding a new module?

**Comment by ethanteague** [comment]
> @ethanteague Is there a future use/need for themable_forms?
> 
> If No, is there another solution that does not involve adding a new module?

Asked myself the same question, and realistically, I think the answer is no. To do it without this module requires me adding some custom code, ala: a theme suggestions hook and then passing some variables to the template in a theme function. I can do this, but was thinking that adding a contrib module was kind of the harm reduction approach. I could be persuaded otherwise - just lemme know if you want me to go the other way, @swirtSJW

**Comment by suzanne-gray** [comment]
Looks good to me @ethanteague ! Thank you!!

**Comment by swirtSJW** [comment]
@ethanteague  That's a tough call.  It's a single use module AND it has no full release (security coverage).  And its requiring a local template.   We have other JS coming in as part of #7243   Can we just add to that JS to just eat the duplicate?


current PR is conflicted.

**Comment by ethanteague** [comment]
> @ethanteague That's a tough call. It's a single use module AND it has no full release (security coverage). And its requiring a local template. We have other JS coming in as part of #7243 Can we just add to that JS to just eat the duplicate?
> 
> current PR is conflicted.

Yeah, I'll kill this one, @swirtSJW, and I'll get rid of this module / go the other way. Also agree with you about https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7243#discussion_r766832507 , so I can address it will I'm in there.

**Comment by ethanteague** [comment]
Closing in favor of resolution in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7243

**Pull request closed without merging**
